export function getData() {
    return [
        {
            year: new Date(2000, 0, 1),
            'Onshore wind': 81,
            'Offshore wind': 0,
            'Solar photovoltaics': 0,
            'Plant biomass': 11,
            'Landfill gas': 718,
        },
        {
            year: new Date(2001, 0, 1),
            'Onshore wind': 83,
            'Offshore wind': 0,
            'Solar photovoltaics': 0,
            'Plant biomass': 81,
            'Landfill gas': 822,
        },
        {
            year: new Date(2002, 0, 1),
            'Onshore wind': 108,
            'Offshore wind': 0,
            'Solar photovoltaics': 0,
            'Plant biomass': 92,
            'Landfill gas': 879,
        },
        {
            year: new Date(2003, 0, 1),
            'Onshore wind': 110,
            'Offshore wind': 1,
            'Solar photovoltaics': 0,
            'Plant biomass': 137,
            'Landfill gas': 1075,
        },
        {
            year: new Date(2004, 0, 1),
            'Onshore wind': 149,
            'Offshore wind': 17,
            'Solar photovoltaics': 0,
            'Plant biomass': 123,
            'Landfill gas': 1313,
        },
        {
            year: new Date(2005, 0, 1),
            'Onshore wind': 215,
            'Offshore wind': 35,
            'Solar photovoltaics': 1,
            'Plant biomass': 129,
            'Landfill gas': 1407,
        },
        {
            year: new Date(2006, 0, 1),
            'Onshore wind': 307,
            'Offshore wind': 56,
            'Solar photovoltaics': 1,
            'Plant biomass': 123,
            'Landfill gas': 1451,
        },
        {
            year: new Date(2007, 0, 1),
            'Onshore wind': 386,
            'Offshore wind': 67,
            'Solar photovoltaics': 1,
            'Plant biomass': 138,
            'Landfill gas': 1534,
        },
        {
            year: new Date(2008, 0, 1),
            'Onshore wind': 498,
            'Offshore wind': 115,
            'Solar photovoltaics': 1,
            'Plant biomass': 242,
            'Landfill gas': 1540,
        },
        {
            year: new Date(2009, 0, 1),
            'Onshore wind': 647,
            'Offshore wind': 151,
            'Solar photovoltaics': 2,
            'Plant biomass': 387,
            'Landfill gas': 1613,
        },
        {
            year: new Date(2010, 0, 1),
            'Onshore wind': 621,
            'Offshore wind': 263,
            'Solar photovoltaics': 3,
            'Plant biomass': 461,
            'Landfill gas': 1711,
        },
        {
            year: new Date(2011, 0, 1),
            'Onshore wind': 930,
            'Offshore wind': 443,
            'Solar photovoltaics': 21,
            'Plant biomass': 554,
            'Landfill gas': 1744,
        },
        {
            year: new Date(2012, 0, 1),
            'Onshore wind': 1053,
            'Offshore wind': 654,
            'Solar photovoltaics': 116,
            'Plant biomass': 1062,
            'Landfill gas': 1708,
        },
        {
            year: new Date(2013, 0, 1),
            'Onshore wind': 1455,
            'Offshore wind': 986,
            'Solar photovoltaics': 173,
            'Plant biomass': 2008,
            'Landfill gas': 1697,
        },
        {
            year: new Date(2014, 0, 1),
            'Onshore wind': 1595,
            'Offshore wind': 1153,
            'Solar photovoltaics': 349,
            'Plant biomass': 2913,
            'Landfill gas': 1651,
        },
        {
            year: new Date(2015, 0, 1),
            'Onshore wind': 1965,
            'Offshore wind': 1498,
            'Solar photovoltaics': 648,
            'Plant biomass': 3850,
            'Landfill gas': 1598,
        },
        {
            year: new Date(2016, 0, 1),
            'Onshore wind': 1785,
            'Offshore wind': 1411,
            'Solar photovoltaics': 894,
            'Plant biomass': 3855,
            'Landfill gas': 1542,
        },
        {
            year: new Date(2017, 0, 1),
            'Onshore wind': 2470,
            'Offshore wind': 1798,
            'Solar photovoltaics': 985,
            'Plant biomass': 4206,
            'Landfill gas': 1405,
        },
        {
            year: new Date(2018, 0, 1),
            'Onshore wind': 2612,
            'Offshore wind': 2281,
            'Marine energy': 1,
            'Solar photovoltaics': 1089,
            'Plant biomass': 4898,
            'Landfill gas': 1284,
        },
        {
            year: new Date(2019, 0, 1),
            'Onshore wind': 2739,
            'Offshore wind': 2749,
            'Marine energy': 1,
            'Solar photovoltaics': 1068,
            'Plant biomass': 5400,
            'Landfill gas': 866,
        },
        {
            year: new Date(2020, 0, 1),
            'Onshore wind': 3004,
            'Offshore wind': 3498,
            'Marine energy': 1,
            'Solar photovoltaics': 1109,
            'Plant biomass': 5637,
            'Landfill gas': 835,
        },
        {
            year: new Date(2021, 0, 1),
            'Onshore wind': 2507,
            'Offshore wind': 3053,
            'Solar photovoltaics': 1044,
            'Plant biomass': 5990,
            'Landfill gas': 791,
        },
    ];
}
