export function getData() {
    return [
        {
            id: 'Ashley Rivers',
            parentId: null,
            name: 'Ashley Rivers',
            job: 'CEO',
            location: 'France',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/19.webp',
        },
        {
            id: 'Deborah Love',
            parentId: 'Ashley Rivers',
            name: 'Deborah Love',
            job: 'CTO',
            location: 'Spain',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/23.webp',
        },
        {
            id: 'Michael Allen',
            parentId: 'Deborah Love',
            name: 'Michael Allen',
            job: 'Legal',
            location: 'United Kingdom',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/17.webp',
        },
        {
            id: 'Peggy Williams',
            parentId: 'Michael Allen',
            name: 'Peggy Williams',
            job: 'Legal',
            location: 'Netherlands',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/28.webp',
        },
        {
            id: 'Kristy Zuniga',
            parentId: 'Michael Allen',
            name: 'Kristy Zuniga',
            job: 'Legal',
            location: 'Portugal',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/11.webp',
        },
        {
            id: 'Lori West',
            parentId: 'Deborah Love',
            name: 'Lori West',
            job: 'Legal',
            location: 'Netherlands',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/8.webp',
        },
        {
            id: 'Evelyn Jones',
            parentId: 'Lori West',
            name: 'Evelyn Jones',
            job: 'Legal',
            location: 'Italy',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/12.webp',
        },
        {
            id: 'Dawn Smith',
            parentId: 'Lori West',
            name: 'Dawn Smith',
            job: 'Legal',
            location: 'Portugal',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/15.webp',
        },
        {
            id: 'Jeffery Moore',
            parentId: 'Deborah Love',
            name: 'Jeffery Moore',
            job: 'Exec. Vice President',
            location: 'United Kingdom',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/13.webp',
        },
        {
            id: 'Christopher Carter',
            parentId: 'Jeffery Moore',
            name: 'Christopher Carter',
            job: 'Legal',
            location: 'Netherlands',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/5.webp',
        },
        {
            id: 'Jamie Stafford',
            parentId: 'Jeffery Moore',
            name: 'Jamie Stafford',
            job: 'Legal',
            location: 'Netherlands',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/18.webp',
        },
        {
            id: 'Joseph Howe',
            parentId: 'Ashley Rivers',
            name: 'Joseph Howe',
            job: 'CTO',
            location: 'United States',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/20.webp',
        },
        {
            id: 'Mr. Jeffrey Brown',
            parentId: 'Joseph Howe',
            name: 'Mr. Jeffrey Brown',
            job: 'Design',
            location: 'France',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/22.webp',
        },
        {
            id: 'Melissa Vazquez',
            parentId: 'Mr. Jeffrey Brown',
            name: 'Melissa Vazquez',
            job: 'Design',
            location: 'France',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/2.webp',
        },
        {
            id: 'John Thomas',
            parentId: 'Mr. Jeffrey Brown',
            name: 'John Thomas',
            job: 'Design',
            location: 'Netherlands',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/5.webp',
        },
        {
            id: 'Nicole Jones',
            parentId: 'Joseph Howe',
            name: 'Nicole Jones',
            job: 'Exec. Vice President',
            location: 'Portugal',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/29.webp',
        },
        {
            id: 'James Long',
            parentId: 'Nicole Jones',
            name: 'James Long',
            job: 'Design',
            location: 'Netherlands',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/25.webp',
        },
        {
            id: 'Susan Hernandez',
            parentId: 'Nicole Jones',
            name: 'Susan Hernandez',
            job: 'Design',
            location: 'Ireland',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/7.webp',
        },
        {
            id: 'Justin Contreras',
            parentId: 'Joseph Howe',
            name: 'Justin Contreras',
            job: 'Design',
            location: 'Italy',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/10.webp',
        },
        {
            id: 'Rachel Ibarra',
            parentId: 'Justin Contreras',
            name: 'Rachel Ibarra',
            job: 'Design',
            location: 'Italy',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/2.webp',
        },
        {
            id: 'John Gomez',
            parentId: 'Justin Contreras',
            name: 'John Gomez',
            job: 'Design',
            location: 'France',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/17.webp',
        },
        {
            id: 'Gary Garcia',
            parentId: 'Ashley Rivers',
            name: 'Gary Garcia',
            job: 'Head of Department',
            location: 'Netherlands',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/18.webp',
        },
        {
            id: 'Lawrence Martinez',
            parentId: 'Gary Garcia',
            name: 'Lawrence Martinez',
            job: 'Design',
            location: 'United States',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/33.webp',
        },
        {
            id: 'Devin Pittman',
            parentId: 'Lawrence Martinez',
            name: 'Devin Pittman',
            job: 'Design',
            location: 'United Kingdom',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/18.webp',
        },
        {
            id: 'Emily Barajas',
            parentId: 'Lawrence Martinez',
            name: 'Emily Barajas',
            job: 'Design',
            location: 'Italy',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/28.webp',
        },
        {
            id: 'Breanna Ward',
            parentId: 'Gary Garcia',
            name: 'Breanna Ward',
            job: 'Exec. Vice President',
            location: 'France',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/14.webp',
        },
        {
            id: 'Ronald Wright',
            parentId: 'Breanna Ward',
            name: 'Ronald Wright',
            job: 'Design',
            location: 'United States',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/9.webp',
        },
        {
            id: 'Kristin Thomas',
            parentId: 'Breanna Ward',
            name: 'Kristin Thomas',
            job: 'Design',
            location: 'United States',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/19.webp',
        },
        {
            id: 'Eric Jensen',
            parentId: 'Gary Garcia',
            name: 'Eric Jensen',
            job: 'Design',
            location: 'Spain',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/35.webp',
        },
        {
            id: 'Michael Morris',
            parentId: 'Eric Jensen',
            name: 'Michael Morris',
            job: 'Design',
            location: 'France',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/10.webp',
        },
        {
            id: 'Jodi Miller',
            parentId: 'Eric Jensen',
            name: 'Jodi Miller',
            job: 'Design',
            location: 'Italy',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/30.webp',
        },
        {
            id: 'Adrian Conner',
            parentId: 'Ashley Rivers',
            name: 'Adrian Conner',
            job: 'COO',
            location: 'Netherlands',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/17.webp',
        },
        {
            id: 'Steven Mann',
            parentId: 'Adrian Conner',
            name: 'Steven Mann',
            job: 'Head of Department',
            location: 'France',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/5.webp',
        },
        {
            id: 'Melinda Harrington',
            parentId: 'Steven Mann',
            name: 'Melinda Harrington',
            job: 'Exec. Vice President',
            location: 'Portugal',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/20.webp',
        },
        {
            id: 'Misty Graves',
            parentId: 'Melinda Harrington',
            name: 'Misty Graves',
            job: 'Product',
            location: 'Spain',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/4.webp',
        },
        {
            id: 'Jill Sullivan',
            parentId: 'Melinda Harrington',
            name: 'Jill Sullivan',
            job: 'Product',
            location: 'Netherlands',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/4.webp',
        },
        {
            id: 'Rebecca Butler',
            parentId: 'Steven Mann',
            name: 'Rebecca Butler',
            job: 'Product',
            location: 'Spain',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/7.webp',
        },
        {
            id: 'Jennifer Jones',
            parentId: 'Rebecca Butler',
            name: 'Jennifer Jones',
            job: 'Product',
            location: 'United States',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/11.webp',
        },
        {
            id: 'Alan Archer',
            parentId: 'Rebecca Butler',
            name: 'Alan Archer',
            job: 'Product',
            location: 'Spain',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/29.webp',
        },
        {
            id: 'Barbara Alexander',
            parentId: 'Steven Mann',
            name: 'Barbara Alexander',
            job: 'Exec. Vice President',
            location: 'Spain',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/20.webp',
        },
        {
            id: 'Andrew Sullivan',
            parentId: 'Barbara Alexander',
            name: 'Andrew Sullivan',
            job: 'Product',
            location: 'Ireland',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/26.webp',
        },
        {
            id: 'Christian Klein',
            parentId: 'Barbara Alexander',
            name: 'Christian Klein',
            job: 'Product',
            location: 'United Kingdom',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/28.webp',
        },
        {
            id: 'Cheryl Browning',
            parentId: 'Adrian Conner',
            name: 'Cheryl Browning',
            job: 'CTO',
            location: 'United States',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/1.webp',
        },
        {
            id: 'Deborah Morales',
            parentId: 'Cheryl Browning',
            name: 'Deborah Morales',
            job: 'Customer Support',
            location: 'Italy',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/24.webp',
        },
        {
            id: 'Ian Kramer',
            parentId: 'Deborah Morales',
            name: 'Ian Kramer',
            job: 'Customer Support',
            location: 'United Kingdom',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/33.webp',
        },
        {
            id: 'Amy Rojas',
            parentId: 'Deborah Morales',
            name: 'Amy Rojas',
            job: 'Customer Support',
            location: 'Netherlands',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/20.webp',
        },
        {
            id: 'Shawn Hendrix',
            parentId: 'Cheryl Browning',
            name: 'Shawn Hendrix',
            job: 'Exec. Vice President',
            location: 'France',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/35.webp',
        },
        {
            id: 'Aaron Hull',
            parentId: 'Shawn Hendrix',
            name: 'Aaron Hull',
            job: 'Customer Support',
            location: 'United Kingdom',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/22.webp',
        },
        {
            id: 'Dr. Janice Rice',
            parentId: 'Shawn Hendrix',
            name: 'Dr. Janice Rice',
            job: 'Customer Support',
            location: 'United Kingdom',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/24.webp',
        },
        {
            id: 'Bryan Hawkins',
            parentId: 'Cheryl Browning',
            name: 'Bryan Hawkins',
            job: 'Customer Support',
            location: 'Ireland',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/26.webp',
        },
        {
            id: 'Gregory Walker',
            parentId: 'Bryan Hawkins',
            name: 'Gregory Walker',
            job: 'Customer Support',
            location: 'Portugal',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/22.webp',
        },
        {
            id: 'Chris Bruce',
            parentId: 'Bryan Hawkins',
            name: 'Chris Bruce',
            job: 'Customer Support',
            location: 'France',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/5.webp',
        },
        {
            id: 'Clayton Conway',
            parentId: 'Adrian Conner',
            name: 'Clayton Conway',
            job: 'Head of Department',
            location: 'Spain',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/33.webp',
        },
        {
            id: 'Shelby Jenkins',
            parentId: 'Clayton Conway',
            name: 'Shelby Jenkins',
            job: 'Customer Support',
            location: 'United Kingdom',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/27.webp',
        },
        {
            id: 'Vincent Martin',
            parentId: 'Shelby Jenkins',
            name: 'Vincent Martin',
            job: 'Customer Support',
            location: 'United Kingdom',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/5.webp',
        },
        {
            id: 'Devon Bradley',
            parentId: 'Shelby Jenkins',
            name: 'Devon Bradley',
            job: 'Customer Support',
            location: 'United States',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/29.webp',
        },
        {
            id: 'Andrew Ford',
            parentId: 'Clayton Conway',
            name: 'Andrew Ford',
            job: 'Customer Support',
            location: 'Ireland',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/25.webp',
        },
        {
            id: 'Bradley Johnson',
            parentId: 'Andrew Ford',
            name: 'Bradley Johnson',
            job: 'Customer Support',
            location: 'United States',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/9.webp',
        },
        {
            id: 'Matthew Jones',
            parentId: 'Andrew Ford',
            name: 'Matthew Jones',
            job: 'Customer Support',
            location: 'Portugal',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/33.webp',
        },
        {
            id: 'Jonathan Green',
            parentId: 'Clayton Conway',
            name: 'Jonathan Green',
            job: 'Customer Support',
            location: 'Italy',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/35.webp',
        },
    ];
}
