export function getData() {
    return [
        {
            id: 'Ashley Rivers',
            parentId: null,
            name: 'Ashley Rivers',
            job: 'CEO',
            location: 'France',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/19.webp',
        },
        {
            id: 'Joseph Howe',
            parentId: 'Ashley Rivers',
            name: 'Joseph Howe',
            job: 'CTO',
            location: 'United States',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/20.webp',
        },
        {
            id: 'Mr. Jeffrey Brown',
            parentId: 'Joseph Howe',
            name: 'Mr. Jeffrey Brown',
            job: 'Design',
            location: 'France',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/22.webp',
        },
        {
            id: 'Melissa Vazquez',
            parentId: 'Mr. Jeffrey Brown',
            name: 'Melissa Vazquez',
            job: 'Design',
            location: 'France',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/2.webp',
        },
        {
            id: 'John Thomas',
            parentId: 'Mr. Jeffrey Brown',
            name: 'John Thomas',
            job: 'Design',
            location: 'Netherlands',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/5.webp',
        },
        {
            id: 'Nicole Jones',
            parentId: 'Joseph Howe',
            name: 'Nicole Jones',
            job: 'Exec. Vice President',
            location: 'Portugal',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/29.webp',
        },
        {
            id: 'James Long',
            parentId: 'Nicole Jones',
            name: 'James Long',
            job: 'Design',
            location: 'Netherlands',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/25.webp',
        },
        {
            id: 'Susan Hernandez',
            parentId: 'Nicole Jones',
            name: 'Susan Hernandez',
            job: 'Design',
            location: 'Ireland',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/7.webp',
        },
        {
            id: 'Justin Contreras',
            parentId: 'Joseph Howe',
            name: 'Justin Contreras',
            job: 'Design',
            location: 'Italy',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/10.webp',
        },
        {
            id: 'Rachel Ibarra',
            parentId: 'Justin Contreras',
            name: 'Rachel Ibarra',
            job: 'Design',
            location: 'Italy',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/2.webp',
        },
        {
            id: 'John Gomez',
            parentId: 'Justin Contreras',
            name: 'John Gomez',
            job: 'Design',
            location: 'France',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/17.webp',
        },
        {
            id: 'Gary Garcia',
            parentId: 'Ashley Rivers',
            name: 'Gary Garcia',
            job: 'Head of Department',
            location: 'Netherlands',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/18.webp',
        },
        {
            id: 'Lawrence Martinez',
            parentId: 'Gary Garcia',
            name: 'Lawrence Martinez',
            job: 'Design',
            location: 'United States',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/33.webp',
        },
        {
            id: 'Devin Pittman',
            parentId: 'Lawrence Martinez',
            name: 'Devin Pittman',
            job: 'Design',
            location: 'United Kingdom',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/18.webp',
        },
        {
            id: 'Emily Barajas',
            parentId: 'Lawrence Martinez',
            name: 'Emily Barajas',
            job: 'Design',
            location: 'Italy',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/28.webp',
        },
        {
            id: 'Eric Jensen',
            parentId: 'Gary Garcia',
            name: 'Eric Jensen',
            job: 'Design',
            location: 'Spain',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/35.webp',
        },
        {
            id: 'Michael Morris',
            parentId: 'Eric Jensen',
            name: 'Michael Morris',
            job: 'Design',
            location: 'France',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/10.webp',
        },
        {
            id: 'Jodi Miller',
            parentId: 'Eric Jensen',
            name: 'Jodi Miller',
            job: 'Design',
            location: 'Italy',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/30.webp',
        },
    ];
}
