import markdoc from '@astrojs/markdoc';
import react from '@astrojs/react';
import sitemap from '@astrojs/sitemap';
import { defineConfig } from 'astro/config';
import dotenvExpand from 'dotenv-expand';
import * as sass from 'sass';
import { loadEnv } from 'vite';
import mkcert from 'vite-plugin-mkcert';
import svgr from 'vite-plugin-svgr';

import agCacheSitemap from '../../external/ag-website-shared/plugins/agCacheSitemap';
import agLinkChecker from '../../external/ag-website-shared/plugins/agLinkChecker';
import agMkcertPreview from '../../external/ag-website-shared/plugins/agMkcertPreview';
import agSitemapFilterNoindex from '../../external/ag-website-shared/plugins/agSitemapFilterNoindex';
import agSitemapLastmod from '../../external/ag-website-shared/plugins/agSitemapLastmod';
import agSourcemapCors from '../../external/ag-website-shared/plugins/agSourcemapCors';
import { SITEMAP_CACHE_DIR } from '../../external/ag-website-shared/src/constants';
import agAutoRedirect from './plugins/agAutoRedirect';
import agCssAsString from './plugins/agCssAsString';
import agHotModuleReload from './plugins/agHotModuleReload';
import agHtaccessGen from './plugins/agHtaccessGen';
import agRedirectsChecker from './plugins/agRedirectsChecker';
import { getAstroRedirectRules } from './src/utils/htaccess/htaccessRules';
import { getSitemapConfig } from './src/utils/sitemap';
import { urlWithBaseUrl } from './src/utils/urlWithBaseUrl';

const { NODE_ENV } = process.env;

const DEFAULT_BASE_URL = '/';
const PRODUCTION_SITE_URLS = ['https://ag-grid.com', 'https://www.ag-grid.com'];
const dotenv = {
    parsed: loadEnv(NODE_ENV, process.cwd(), ''),
};
const {
    PORT,
    PUBLIC_SITE_URL,
    PUBLIC_BASE_URL = DEFAULT_BASE_URL,
    PUBLIC_GRID_VERSION,
    PUBLIC_HTTPS_SERVER = '1',
    PUBLIC_DEFAULT_FRAMEWORK,
    PUBLIC_GALLERY_IMAGE_DPR_ENHANCEMENT,
    HTACCESS = 'false',
    CHECK_LINKS = 'false',
    /**
     * Check all redirects have a valid page generated by the build
     *
     * Checks the `to` paths in `src/utils/htaccess/redirects.ts`
     */
    CHECK_REDIRECTS = 'false',
    PUBLIC_ENABLE_HOT_RELOAD,
} = dotenvExpand.expand(dotenv).parsed;

const httpsEnabled = !['0', 'false'].includes(PUBLIC_HTTPS_SERVER);

const OUTPUT_DIR = '../../dist/packages/ag-charts-website';

console.log(
    'Astro configuration',
    JSON.stringify(
        {
            NODE_ENV,
            PORT,
            PUBLIC_SITE_URL,
            PUBLIC_BASE_URL,
            PUBLIC_GRID_VERSION,
            OUTPUT_DIR,
            PUBLIC_DEFAULT_FRAMEWORK,
            PUBLIC_GALLERY_IMAGE_DPR_ENHANCEMENT,
            HTACCESS,
            CHECK_REDIRECTS,
            CHECK_LINKS,
            PUBLIC_ENABLE_HOT_RELOAD,
        },
        null,
        2
    )
);

const plugins = [
    agSourcemapCors(),
    svgr(),
    agCssAsString(),
    agHotModuleReload(),
    agAutoRedirect(['/javascript', '/react', '/vue', '/angular', '/gallery']),
];
if (NODE_ENV !== 'test') {
    plugins.push(mkcert()); // mkcert is not necessary for tests
}

// https://astro.build/config
export default defineConfig({
    site: PUBLIC_SITE_URL,
    base: PUBLIC_BASE_URL,
    outDir: OUTPUT_DIR,
    devToolbar: {
        enabled: false,
    },
    security: {
        /**
         * Astro 6's secFetchMiddleware 403s cross-origin subresource requests
         * unless the origin is in this allow-list. Needed for example embedders
         * (Plunkr, CodeSandbox) to load the dev-server UMD bundles.
         */
        allowedDomains: [
            { hostname: 'run.plnkr.co', protocol: 'https' },
            { hostname: '**.csb.app', protocol: 'https' },
        ],
    },
    vite: {
        plugins,
        optimizeDeps: {
            exclude: [
                'ag-charts-angular',
                'ag-charts-community',
                'ag-charts-enterprise',
                'ag-charts-types',
                'ag-charts-locale',
                'ag-charts-react',
                'ag-charts-vue3',
            ],
        },
        server: {
            https: httpsEnabled,
            cors: {
                /**
                 * CORS allow list for opening examples on external sites
                 */
                origin: [
                    // Plunkr
                    'https://run.plnkr.co',
                    // Codesandbox
                    /\.csb.app/,
                    // Github codespaces
                    /\.github.dev/,
                ],
            },
            allowedHosts: [new URL(PUBLIC_SITE_URL).hostname],
            headers: {
                'Content-Security-Policy': [
                    "default-src 'self'",
                    "script-src 'self' https://*.ag-grid.com https://localhost:4600 https://localhost:4601 https://www.googletagmanager.com https://cdn.jsdelivr.net 'unsafe-inline' 'unsafe-eval'",
                    "style-src 'self' https://fonts.googleapis.com 'unsafe-inline'",
                    "font-src 'self' https://fonts.gstatic.com data:",
                    "img-src 'self' data: blob: https:",
                    "connect-src 'self' https:",
                    "worker-src 'self' blob:",
                ].join('; '),
                'X-Content-Type-Options': 'nosniff',
            },
        },
        css: {
            preprocessorOptions: {
                scss: {
                    api: 'modern',
                    functions: {
                        'urlWithBaseUrl($url)': function (args) {
                            const sassUrl = args[0].assertString();
                            const url = sassUrl.toString().replaceAll(/['"]/g, '');
                            const urlWithBase = urlWithBaseUrl(url, PUBLIC_BASE_URL);

                            return new sass.SassString(urlWithBase);
                        },
                    },
                    loadPaths: ['../../external/ag-website-shared/src'],
                },
            },
        },
    },
    integrations: [
        react(),
        markdoc(),
        sitemap(getSitemapConfig()),
        agHtaccessGen({ htaccessEnv: HTACCESS }),
        agLinkChecker({ include: CHECK_LINKS === 'true', prefix: PUBLIC_BASE_URL }),
        agRedirectsChecker({
            skip: CHECK_REDIRECTS !== 'true',
        }),

        agSitemapFilterNoindex({ enabled: PRODUCTION_SITE_URLS.includes(PUBLIC_SITE_URL) }),
        agSitemapLastmod(),
        agCacheSitemap({
            cacheFolder: SITEMAP_CACHE_DIR,
        }),
        agMkcertPreview({ enabled: httpsEnabled }),
    ],
    redirects: getAstroRedirectRules(),
});
