import markdoc from '@astrojs/markdoc';
import react from '@astrojs/react';
import sitemap from '@astrojs/sitemap';
import { defineConfig } from 'astro/config';
import dotenvExpand from 'dotenv-expand';
import * as sass from 'sass';
import { loadEnv } from 'vite';
import mkcert from 'vite-plugin-mkcert';
import svgr from 'vite-plugin-svgr';

import agCacheSitemap from '../../external/ag-website-shared/plugins/agCacheSitemap';
import agLinkChecker from '../../external/ag-website-shared/plugins/agLinkChecker';
import { SITEMAP_CACHE_DIR } from '../../external/ag-website-shared/src/constants';
import agAutoRedirect from './plugins/agAutoRedirect';
import agHotModuleReload from './plugins/agHotModuleReload';
import agHtaccessGen from './plugins/agHtaccessGen';
import agRedirectsChecker from './plugins/agRedirectsChecker';
import { getAstroRedirectRules } from './src/utils/htaccess/htaccessRules';
import { getSitemapConfig } from './src/utils/sitemap';
import { urlWithBaseUrl } from './src/utils/urlWithBaseUrl';

const { NODE_ENV } = process.env;

const DEFAULT_BASE_URL = '/';
const dotenv = {
    parsed: loadEnv(NODE_ENV, process.cwd(), ''),
};
const {
    PORT,
    PUBLIC_SITE_URL,
    PUBLIC_BASE_URL = DEFAULT_BASE_URL,
    PUBLIC_GRID_VERSION,
    PUBLIC_HTTPS_SERVER = '1',
    PUBLIC_DEFAULT_FRAMEWORK,
    PUBLIC_GALLERY_IMAGE_DPR_ENHANCEMENT,
    HTACCESS = 'false',
    CHECK_LINKS = 'false',
    /**
     * Check all redirects have a valid page generated by the build
     *
     * Checks the `to` paths in `src/utils/htaccess/redirects.ts`
     */
    CHECK_REDIRECTS = 'false',
    PUBLIC_ENABLE_HOT_RELOAD,
} = dotenvExpand.expand(dotenv).parsed;

const OUTPUT_DIR = '../../dist/packages/ag-charts-website';

console.log(
    'Astro configuration',
    JSON.stringify(
        {
            NODE_ENV,
            PORT,
            PUBLIC_SITE_URL,
            PUBLIC_BASE_URL,
            PUBLIC_GRID_VERSION,
            OUTPUT_DIR,
            PUBLIC_DEFAULT_FRAMEWORK,
            PUBLIC_GALLERY_IMAGE_DPR_ENHANCEMENT,
            HTACCESS,
            CHECK_REDIRECTS,
            PUBLIC_ENABLE_HOT_RELOAD,
        },
        null,
        2
    )
);

const plugins = [
    svgr(),
    agHotModuleReload(),
    agAutoRedirect(['/javascript', '/react', '/vue', '/angular', '/gallery']),
];
if (NODE_ENV !== 'test') {
    plugins.push(mkcert()); // mkcert is not necessary for tests
}

// https://astro.build/config
export default defineConfig({
    site: PUBLIC_SITE_URL,
    base: PUBLIC_BASE_URL,
    outDir: OUTPUT_DIR,
    experimental: {
        // Prepare for Astro 6
        preserveScriptOrder: true,
    },
    devToolbar: {
        enabled: false,
    },
    vite: {
        plugins,
        optimizeDeps: {
            exclude: [
                'ag-charts-angular',
                'ag-charts-community',
                'ag-charts-enterprise',
                'ag-charts-types',
                'ag-charts-locale',
                'ag-charts-react',
                'ag-charts-vue3',
            ],
        },
        server: {
            https: !['0', 'false'].includes(PUBLIC_HTTPS_SERVER),
            cors: {
                /**
                 * CORS allow list for opening examples on external sites
                 */
                origin: [
                    // Plunkr
                    'https://run.plnkr.co',
                    // Codesandbox
                    /\.csb.app/,
                    // Github codespaces
                    /\.github.dev/,
                ],
            },
            allowedHosts: [new URL(PUBLIC_SITE_URL).hostname],
        },
        css: {
            preprocessorOptions: {
                scss: {
                    api: 'modern',
                    functions: {
                        'urlWithBaseUrl($url)': function (args) {
                            const sassUrl = args[0].assertString();
                            const url = sassUrl.toString().replaceAll(/['"]/g, '');
                            const urlWithBase = urlWithBaseUrl(url, PUBLIC_BASE_URL);

                            return new sass.SassString(urlWithBase);
                        },
                    },
                    loadPaths: ['../../external/ag-website-shared/src'],
                },
            },
        },
    },
    integrations: [
        react(),
        markdoc(),
        sitemap(getSitemapConfig()),
        agHtaccessGen({ include: HTACCESS === 'true' }),
        agLinkChecker({ include: CHECK_LINKS === 'true', prefix: PUBLIC_BASE_URL }),
        agRedirectsChecker({
            skip: CHECK_REDIRECTS !== 'true',
        }),

        agCacheSitemap({
            cacheFolder: SITEMAP_CACHE_DIR,
        }),
    ],
    redirects: getAstroRedirectRules(),
});
