export function getData() {
    return [
        { id: 'Ashley Rivers', parentId: null, name: 'Ashley Rivers', title: 'Chief Executive Officer' },

        { id: 'Joseph Howe', parentId: 'Ashley Rivers', name: 'Joseph Howe', title: 'Chief Technology Officer' },
        { id: 'Priya Nair', parentId: 'Joseph Howe', name: 'Priya Nair', title: 'VP, Platform Engineering' },
        { id: 'John Thomas', parentId: 'Priya Nair', name: 'John Thomas', title: 'Director of Core Services' },
        { id: 'Rachel Ibarra', parentId: 'John Thomas', name: 'Rachel Ibarra', title: 'Engineering Manager, Data' },
        { id: 'Susan Hernandez', parentId: 'Rachel Ibarra', name: 'Susan Hernandez', title: 'Staff Software Engineer' },
        { id: 'John Gomez', parentId: 'Rachel Ibarra', name: 'John Gomez', title: 'Senior Software Engineer' },
        { id: 'Olivia Bennett', parentId: 'Rachel Ibarra', name: 'Olivia Bennett', title: 'Software Engineer' },
        { id: 'Carlos Mendez', parentId: 'John Thomas', name: 'Carlos Mendez', title: 'Engineering Manager, APIs' },
        { id: 'Aisha Khan', parentId: 'Carlos Mendez', name: 'Aisha Khan', title: 'Staff Software Engineer' },
        { id: 'Robert Frank', parentId: 'Carlos Mendez', name: 'Robert Frank', title: 'Senior Software Engineer' },
        { id: 'Sofia Russo', parentId: 'Carlos Mendez', name: 'Sofia Russo', title: 'Software Engineer' },
        { id: 'Melissa Vazquez', parentId: 'Priya Nair', name: 'Melissa Vazquez', title: 'Director of Infrastructure' },
        { id: 'Grace Liu', parentId: 'Melissa Vazquez', name: 'Grace Liu', title: 'Engineering Manager, Cloud' },
        { id: 'Daniel Osei', parentId: 'Grace Liu', name: 'Daniel Osei', title: 'Senior Reliability Engineer' },
        { id: 'Ingrid Sorensen', parentId: 'Grace Liu', name: 'Ingrid Sorensen', title: 'Site Reliability Engineer' },
        { id: 'Pedro Alvarez', parentId: 'Grace Liu', name: 'Pedro Alvarez', title: 'Software Engineer' },
        { id: 'Yuki Tanaka', parentId: 'Melissa Vazquez', name: 'Yuki Tanaka', title: 'Engineering Manager, DevEx' },
        { id: 'Nina Petrova', parentId: 'Yuki Tanaka', name: 'Nina Petrova', title: 'Staff Software Engineer' },
        { id: 'George Hill', parentId: 'Yuki Tanaka', name: 'George Hill', title: 'Senior Software Engineer' },
        { id: 'Chloe Dubois', parentId: 'Yuki Tanaka', name: 'Chloe Dubois', title: 'Software Engineer' },
        { id: 'Noah Kim', parentId: 'Joseph Howe', name: 'Noah Kim', title: 'VP, Product Engineering' },
        { id: 'Eric Jensen', parentId: 'Noah Kim', name: 'Eric Jensen', title: 'Director of Web Engineering' },
        { id: 'Hannah Lee', parentId: 'Eric Jensen', name: 'Hannah Lee', title: 'Engineering Manager, Web Client' },
        { id: 'Lena Fischer', parentId: 'Hannah Lee', name: 'Lena Fischer', title: 'Staff Frontend Engineer' },
        { id: 'Gary Garcia', parentId: 'Hannah Lee', name: 'Gary Garcia', title: 'Senior Frontend Engineer' },
        { id: 'Emily Barajas', parentId: 'Hannah Lee', name: 'Emily Barajas', title: 'Frontend Engineer' },
        { id: 'Laura Bianchi', parentId: 'Eric Jensen', name: 'Laura Bianchi', title: 'Engineering Manager, Mobile' },
        { id: 'Omar Haddad', parentId: 'Laura Bianchi', name: 'Omar Haddad', title: 'Senior Mobile Engineer' },
        { id: 'Rebecca Stone', parentId: 'Laura Bianchi', name: 'Rebecca Stone', title: 'Mobile Engineer' },
        { id: 'Felix Wagner', parentId: 'Laura Bianchi', name: 'Felix Wagner', title: 'Mobile Engineer' },
        { id: 'Sam Carter', parentId: 'Noah Kim', name: 'Sam Carter', title: 'Director of Integrations' },
        { id: 'Fatima Zahra', parentId: 'Sam Carter', name: 'Fatima Zahra', title: 'Engineering Manager, Partners' },
        { id: 'Marcus Webb', parentId: 'Fatima Zahra', name: 'Marcus Webb', title: 'Senior Software Engineer' },
        { id: 'Catherine Wu', parentId: 'Fatima Zahra', name: 'Catherine Wu', title: 'Software Engineer' },
        { id: 'Daniel Kim', parentId: 'Fatima Zahra', name: 'Daniel Kim', title: 'Software Engineer' },
        { id: 'Lawrence Martinez', parentId: 'Sam Carter', name: 'Lawrence Martinez', title: 'QA Manager' },
        { id: 'Devin Pittman', parentId: 'Lawrence Martinez', name: 'Devin Pittman', title: 'Senior QA Engineer' },
        { id: 'Maya Roberts', parentId: 'Lawrence Martinez', name: 'Maya Roberts', title: 'QA Engineer' },
        { id: 'Ada Quinn', parentId: 'Joseph Howe', name: 'Ada Quinn', title: 'Director of Security Engineering' },
        { id: 'Ben Stout', parentId: 'Ada Quinn', name: 'Ben Stout', title: 'Security Engineering Manager' },
        { id: 'Cara Lin', parentId: 'Ben Stout', name: 'Cara Lin', title: 'Senior Security Engineer' },
        { id: 'Dev Rao', parentId: 'Ben Stout', name: 'Dev Rao', title: 'Security Engineer' },

        { id: 'Jeffrey Brown', parentId: 'Ashley Rivers', name: 'Jeffrey Brown', title: 'Chief Product Officer' },
        { id: 'Sara Lindqvist', parentId: 'Jeffrey Brown', name: 'Sara Lindqvist', title: 'VP, Product Management' },
        { id: 'Hiroshi Tanaka', parentId: 'Sara Lindqvist', name: 'Hiroshi Tanaka', title: 'Director of Product' },
        { id: 'Diego Morales', parentId: 'Hiroshi Tanaka', name: 'Diego Morales', title: 'Group Product Manager' },
        { id: 'Anna Schmidt', parentId: 'Diego Morales', name: 'Anna Schmidt', title: 'Senior Product Manager' },
        { id: 'Kevin Park', parentId: 'Diego Morales', name: 'Kevin Park', title: 'Product Manager' },
        { id: 'Ravi Patel', parentId: 'Diego Morales', name: 'Ravi Patel', title: 'Product Manager' },
        { id: 'Sophie Laurent', parentId: 'Hiroshi Tanaka', name: 'Sophie Laurent', title: 'Group Product Manager' },
        { id: 'Elena Costa', parentId: 'Sophie Laurent', name: 'Elena Costa', title: 'Product Manager' },
        { id: 'Ivan Petrov', parentId: 'Sophie Laurent', name: 'Ivan Petrov', title: 'Associate Product Manager' },
        { id: 'Zoe Lambert', parentId: 'Sara Lindqvist', name: 'Zoe Lambert', title: 'Director of Product Analytics' },
        { id: 'Hugo Marsh', parentId: 'Zoe Lambert', name: 'Hugo Marsh', title: 'Senior Product Analyst' },
        { id: 'Amara Okafor', parentId: 'Zoe Lambert', name: 'Amara Okafor', title: 'Product Analyst' },
        { id: 'Iris Vance', parentId: 'Jeffrey Brown', name: 'Iris Vance', title: 'VP, Design' },
        { id: 'Owen Mercer', parentId: 'Iris Vance', name: 'Owen Mercer', title: 'Director of Design' },
        { id: 'Tara Bose', parentId: 'Owen Mercer', name: 'Tara Bose', title: 'Design Manager' },
        { id: 'Leo Hartman', parentId: 'Tara Bose', name: 'Leo Hartman', title: 'Senior Product Designer' },
        { id: 'Mia Donovan', parentId: 'Tara Bose', name: 'Mia Donovan', title: 'Product Designer' },
        { id: 'Caleb Ford', parentId: 'Tara Bose', name: 'Caleb Ford', title: 'Product Designer' },
        { id: 'Nora Beck', parentId: 'Owen Mercer', name: 'Nora Beck', title: 'UX Research Manager' },
        { id: 'Julia Fernandez', parentId: 'Nora Beck', name: 'Julia Fernandez', title: 'Senior UX Researcher' },
        { id: 'Victor Nguyen', parentId: 'Nora Beck', name: 'Victor Nguyen', title: 'UX Researcher' },

        {
            id: 'Justin Contreras',
            parentId: 'Ashley Rivers',
            name: 'Justin Contreras',
            title: 'Chief Operating Officer',
        },
        { id: 'Elliot Shaw', parentId: 'Justin Contreras', name: 'Elliot Shaw', title: 'VP, Finance' },
        { id: 'Rosa Delgado', parentId: 'Elliot Shaw', name: 'Rosa Delgado', title: 'Director of Financial Planning' },
        { id: 'Wesley Boone', parentId: 'Rosa Delgado', name: 'Wesley Boone', title: 'Senior Financial Analyst' },
        { id: 'Ines Duarte', parentId: 'Rosa Delgado', name: 'Ines Duarte', title: 'Financial Analyst' },
        { id: 'Malik Hassan', parentId: 'Elliot Shaw', name: 'Malik Hassan', title: 'Director of Accounting' },
        { id: 'Greta Lund', parentId: 'Malik Hassan', name: 'Greta Lund', title: 'Accounting Manager' },
        { id: 'Sean Doyle', parentId: 'Malik Hassan', name: 'Sean Doyle', title: 'Accountant' },
        { id: 'Bianca Rossi', parentId: 'Justin Contreras', name: 'Bianca Rossi', title: 'VP, Business Operations' },
        { id: 'Anya Volkov', parentId: 'Bianca Rossi', name: 'Anya Volkov', title: 'Operations Manager' },
        { id: 'Jonas Weber', parentId: 'Anya Volkov', name: 'Jonas Weber', title: 'Operations Analyst' },
        { id: 'Finn Lowe', parentId: 'Justin Contreras', name: 'Finn Lowe', title: 'SVP, Revenue' },
        { id: 'Gita Sen', parentId: 'Finn Lowe', name: 'Gita Sen', title: 'VP, Sales' },
        { id: 'Hal Reed', parentId: 'Gita Sen', name: 'Hal Reed', title: 'Director of Enterprise Sales' },
        { id: 'Isla Dunn', parentId: 'Hal Reed', name: 'Isla Dunn', title: 'Enterprise Account Manager' },
        { id: 'Thomas Berg', parentId: 'Hal Reed', name: 'Thomas Berg', title: 'Enterprise Account Executive' },
        { id: 'Lucas Meyer', parentId: 'Hal Reed', name: 'Lucas Meyer', title: 'Account Executive' },
        { id: 'Patrick Reilly', parentId: 'Gita Sen', name: 'Patrick Reilly', title: 'Director of Customer Success' },
        { id: 'Henry Cole', parentId: 'Patrick Reilly', name: 'Henry Cole', title: 'Customer Success Manager' },
        { id: 'Nadia Petrov', parentId: 'Patrick Reilly', name: 'Nadia Petrov', title: 'Customer Success Manager' },
        { id: 'Esme Roy', parentId: 'Patrick Reilly', name: 'Esme Roy', title: 'Customer Success Associate' },
        { id: 'Marta Silva', parentId: 'Finn Lowe', name: 'Marta Silva', title: 'VP, Marketing' },
        { id: 'Simone Blake', parentId: 'Marta Silva', name: 'Simone Blake', title: 'Director of Demand Generation' },
        { id: 'Otis Grant', parentId: 'Simone Blake', name: 'Otis Grant', title: 'Marketing Manager' },
        { id: 'Priti Shah', parentId: 'Simone Blake', name: 'Priti Shah', title: 'Campaign Manager' },
        { id: 'Noel Adeyemi', parentId: 'Marta Silva', name: 'Noel Adeyemi', title: 'Director of Brand & Content' },
        { id: 'Clara Mendes', parentId: 'Noel Adeyemi', name: 'Clara Mendes', title: 'Content Lead' },
        { id: 'Tobias Frank', parentId: 'Noel Adeyemi', name: 'Tobias Frank', title: 'Content Strategist' },
        { id: 'Camille Okonkwo', parentId: 'Justin Contreras', name: 'Camille Okonkwo', title: 'VP, People' },
        {
            id: 'Derek Yates',
            parentId: 'Camille Okonkwo',
            name: 'Derek Yates',
            title: 'Director of Talent Acquisition',
        },
        { id: 'Lila Novak', parentId: 'Derek Yates', name: 'Lila Novak', title: 'Technical Recruiter' },
        { id: 'Umar Aziz', parentId: 'Derek Yates', name: 'Umar Aziz', title: 'Recruiter' },
        { id: 'Fiona Walsh', parentId: 'Camille Okonkwo', name: 'Fiona Walsh', title: 'Director of People Operations' },
        { id: 'Beatriz Alves', parentId: 'Fiona Walsh', name: 'Beatriz Alves', title: 'People Operations Manager' },
        { id: 'Theo Larsen', parentId: 'Fiona Walsh', name: 'Theo Larsen', title: 'People Operations Associate' },
    ];
}
