export function getData() {
    return [
        { id: 'Ashley Rivers', parentId: null, name: 'Ashley Rivers', title: 'Chief Executive Officer' },
        { id: 'Joseph Howe', parentId: 'Ashley Rivers', name: 'Joseph Howe', title: 'Chief Technology Officer' },
        { id: 'Jeffrey Brown', parentId: 'Ashley Rivers', name: 'Jeffrey Brown', title: 'Chief Product Officer' },
        { id: 'Justin Contreras', parentId: 'Ashley Rivers', name: 'Justin Contreras', title: 'Chief Risk Officer' },
        { id: 'Priya Nair', parentId: 'Joseph Howe', name: 'Priya Nair', title: 'SVP, Engineering' },
        { id: 'Melissa Vazquez', parentId: 'Priya Nair', name: 'Melissa Vazquez', title: 'VP, Platform Engineering' },
        { id: 'John Thomas', parentId: 'Melissa Vazquez', name: 'John Thomas', title: 'Director of Engineering' },
        { id: 'Rachel Ibarra', parentId: 'John Thomas', name: 'Rachel Ibarra', title: 'Engineering Manager' },
        { id: 'Susan Hernandez', parentId: 'Rachel Ibarra', name: 'Susan Hernandez', title: 'Staff Software Engineer' },
        { id: 'John Gomez', parentId: 'Susan Hernandez', name: 'John Gomez', title: 'Senior Software Engineer' },
        { id: 'Olivia Bennett', parentId: 'John Gomez', name: 'Olivia Bennett', title: 'Software Engineer' },
        { id: 'Sam Carter', parentId: 'Eric Jensen', name: 'Sam Carter', title: 'Director of Engineering' },
        { id: 'Lena Fischer', parentId: 'Sam Carter', name: 'Lena Fischer', title: 'Engineering Manager' },
        { id: 'Gary Garcia', parentId: 'Lena Fischer', name: 'Gary Garcia', title: 'Staff Software Engineer' },
        {
            id: 'Lawrence Martinez',
            parentId: 'Gary Garcia',
            name: 'Lawrence Martinez',
            title: 'Senior Software Engineer',
        },
        { id: 'Emily Barajas', parentId: 'Lawrence Martinez', name: 'Emily Barajas', title: 'Software Engineer' },
        { id: 'Tom Whitfield', parentId: 'Emily Barajas', name: 'Tom Whitfield', title: 'Associate Software Engineer' },
        { id: 'Devin Pittman', parentId: 'Tom Whitfield', name: 'Devin Pittman', title: 'Junior Software Engineer' },
        { id: 'Maya Roberts', parentId: 'Devin Pittman', name: 'Maya Roberts', title: 'Engineering Intern' },
        { id: 'Noah Kim', parentId: 'Joseph Howe', name: 'Noah Kim', title: 'SVP, Engineering' },
        { id: 'Eric Jensen', parentId: 'Noah Kim', name: 'Eric Jensen', title: 'VP, Platform Engineering' },
        { id: 'Hannah Lee', parentId: 'Eric Jensen', name: 'Hannah Lee', title: 'Director of Engineering' },
        { id: 'Carlos Mendez', parentId: 'John Thomas', name: 'Carlos Mendez', title: 'Engineering Manager' },
        { id: 'Aisha Khan', parentId: 'Carlos Mendez', name: 'Aisha Khan', title: 'Staff Software Engineer' },
        { id: 'Robert Frank', parentId: 'Aisha Khan', name: 'Robert Frank', title: 'Senior Software Engineer' },
        { id: 'Grace Liu', parentId: 'Rachel Ibarra', name: 'Grace Liu', title: 'Staff Software Engineer' },
        { id: 'Daniel Osei', parentId: 'Grace Liu', name: 'Daniel Osei', title: 'Senior Software Engineer' },
        { id: 'Sofia Russo', parentId: 'Daniel Osei', name: 'Sofia Russo', title: 'Software Engineer' },
        { id: 'Mark Daniels', parentId: 'Susan Hernandez', name: 'Mark Daniels', title: 'Senior Software Engineer' },
        { id: 'Ingrid Sorensen', parentId: 'Mark Daniels', name: 'Ingrid Sorensen', title: 'Software Engineer' },
        {
            id: 'Pedro Alvarez',
            parentId: 'Ingrid Sorensen',
            name: 'Pedro Alvarez',
            title: 'Associate Software Engineer',
        },
        { id: 'Chloe Dubois', parentId: 'Olivia Bennett', name: 'Chloe Dubois', title: 'Associate Software Engineer' },
        { id: 'Liam Murphy', parentId: 'Chloe Dubois', name: 'Liam Murphy', title: 'Junior Software Engineer' },
        { id: 'Yuki Tanaka', parentId: 'Sam Carter', name: 'Yuki Tanaka', title: 'Engineering Manager' },
        { id: 'Nina Petrova', parentId: 'Yuki Tanaka', name: 'Nina Petrova', title: 'Staff Software Engineer' },
        { id: 'George Hill', parentId: 'Nina Petrova', name: 'George Hill', title: 'Senior Software Engineer' },
        { id: 'Fatima Zahra', parentId: 'Lawrence Martinez', name: 'Fatima Zahra', title: 'Software Engineer' },
        { id: 'Marcus Webb', parentId: 'Fatima Zahra', name: 'Marcus Webb', title: 'Associate Software Engineer' },
        { id: 'Sara Lindqvist', parentId: 'Jeffrey Brown', name: 'Sara Lindqvist', title: 'VP, Product' },
        { id: 'Hiroshi Tanaka', parentId: 'Sara Lindqvist', name: 'Hiroshi Tanaka', title: 'Director of Product' },
        { id: 'Diego Morales', parentId: 'Hiroshi Tanaka', name: 'Diego Morales', title: 'Group Product Manager' },
        { id: 'Anna Schmidt', parentId: 'Diego Morales', name: 'Anna Schmidt', title: 'Senior Product Manager' },
        { id: 'Kevin Park', parentId: 'Anna Schmidt', name: 'Kevin Park', title: 'Product Manager' },
        { id: 'Laura Bianchi', parentId: 'Hannah Lee', name: 'Laura Bianchi', title: 'Engineering Manager' },
        { id: 'Omar Haddad', parentId: 'Laura Bianchi', name: 'Omar Haddad', title: 'Staff Software Engineer' },
        { id: 'Rebecca Stone', parentId: 'Omar Haddad', name: 'Rebecca Stone', title: 'Senior Software Engineer' },
        { id: 'Felix Wagner', parentId: 'Rebecca Stone', name: 'Felix Wagner', title: 'Software Engineer' },
        { id: 'Nadia Petrov', parentId: 'Gita Sen', name: 'Nadia Petrov', title: 'Risk & Compliance Manager' },
        { id: 'Julia Fernandez', parentId: 'Nadia Petrov', name: 'Julia Fernandez', title: 'Senior Risk Analyst' },
        { id: 'Victor Nguyen', parentId: 'Julia Fernandez', name: 'Victor Nguyen', title: 'Risk Analyst' },
        { id: 'Thomas Berg', parentId: 'Victor Nguyen', name: 'Thomas Berg', title: 'Compliance Analyst' },
        { id: 'Amara Okafor', parentId: 'Thomas Berg', name: 'Amara Okafor', title: 'Junior Risk Analyst' },
        { id: 'Lucas Meyer', parentId: 'Amara Okafor', name: 'Lucas Meyer', title: 'Risk Operations Associate' },
        { id: 'Sophie Laurent', parentId: 'Hiroshi Tanaka', name: 'Sophie Laurent', title: 'Group Product Manager' },
        { id: 'Ravi Patel', parentId: 'Anna Schmidt', name: 'Ravi Patel', title: 'Product Manager' },
        { id: 'Elena Costa', parentId: 'Kevin Park', name: 'Elena Costa', title: 'Associate Product Manager' },
        { id: 'Catherine Wu', parentId: 'Rebecca Stone', name: 'Catherine Wu', title: 'Software Engineer' },
        { id: 'Daniel Kim', parentId: 'Catherine Wu', name: 'Daniel Kim', title: 'Associate Software Engineer' },
        { id: 'Marta Silva', parentId: 'Daniel Kim', name: 'Marta Silva', title: 'Junior Software Engineer' },
        { id: 'Patrick Reilly', parentId: 'Victor Nguyen', name: 'Patrick Reilly', title: 'Compliance Analyst' },
        { id: 'Yara Haddad', parentId: 'Patrick Reilly', name: 'Yara Haddad', title: 'Junior Risk Analyst' },
        { id: 'Henry Cole', parentId: 'Yara Haddad', name: 'Henry Cole', title: 'Risk Operations Associate' },
        { id: 'Iris Vance', parentId: 'Justin Contreras', name: 'Iris Vance', title: 'VP, Risk & Compliance' },
        { id: 'Owen Mercer', parentId: 'Iris Vance', name: 'Owen Mercer', title: 'Director of Compliance' },
        { id: 'Tara Bose', parentId: 'Owen Mercer', name: 'Tara Bose', title: 'Risk & Compliance Manager' },
        { id: 'Leo Hartman', parentId: 'Tara Bose', name: 'Leo Hartman', title: 'Senior Risk Analyst' },
        { id: 'Mia Donovan', parentId: 'Leo Hartman', name: 'Mia Donovan', title: 'Risk Analyst' },
        { id: 'Caleb Ford', parentId: 'Mia Donovan', name: 'Caleb Ford', title: 'Compliance Analyst' },
        { id: 'Nora Beck', parentId: 'Caleb Ford', name: 'Nora Beck', title: 'Junior Risk Analyst' },
        { id: 'Ivan Petrov', parentId: 'Ravi Patel', name: 'Ivan Petrov', title: 'Associate Product Manager' },
        { id: 'Zoe Lambert', parentId: 'Ivan Petrov', name: 'Zoe Lambert', title: 'Product Analyst' },
        { id: 'Hugo Marsh', parentId: 'Zoe Lambert', name: 'Hugo Marsh', title: 'Product Operations Associate' },
        { id: 'Ada Quinn', parentId: 'Hal Reed', name: 'Ada Quinn', title: 'Senior Risk Analyst' },
        { id: 'Ben Stout', parentId: 'Ada Quinn', name: 'Ben Stout', title: 'Risk Analyst' },
        { id: 'Cara Lin', parentId: 'Ben Stout', name: 'Cara Lin', title: 'Compliance Analyst' },
        { id: 'Dev Rao', parentId: 'Cara Lin', name: 'Dev Rao', title: 'Junior Risk Analyst' },
        { id: 'Esme Roy', parentId: 'Dev Rao', name: 'Esme Roy', title: 'Risk Operations Associate' },
        { id: 'Finn Lowe', parentId: 'Justin Contreras', name: 'Finn Lowe', title: 'VP, Risk & Compliance' },
        { id: 'Gita Sen', parentId: 'Finn Lowe', name: 'Gita Sen', title: 'Director of Compliance' },
        { id: 'Hal Reed', parentId: 'Gita Sen', name: 'Hal Reed', title: 'Risk & Compliance Manager' },
        { id: 'Isla Dunn', parentId: 'Iris Vance', name: 'Isla Dunn', title: 'Director of Compliance' },
    ];
}
