// Source: https://en.wikipedia.org/wiki/Lists_of_21st-century_earthquakes?utm_source=chatgpt.com
export function getData(): any[] {
    return [
        {
            date: new Date('2003-12-26'),
            location: 'Bam, Iran',
            flag: '🇮🇷',
            magnitude: 6.6,
            deaths: 34000,
        },
        {
            date: new Date('2004-12-26'),
            location: 'Indian Ocean (Sumatra), Indonesia',
            flag: '🇮🇩',
            magnitude: 9.25,
            deaths: 227898,
        },
        {
            date: new Date('2005-01-26'),
            location: 'Gujarat, India',
            flag: '🇮🇳',
            magnitude: 7.7,
            deaths: 20085,
        },
        {
            date: new Date('2005-10-08'),
            location: 'Kashmir, Pakistan',
            flag: '🇵🇰',
            magnitude: 7.6,
            deaths: 87351,
        },
        {
            date: new Date('2008-05-12'),
            location: 'Sichuan, China',
            flag: '🇨🇳',
            magnitude: 7.9,
            deaths: 87587,
        },
        {
            date: new Date('2010-01-12'),
            location: 'Haiti (Port-au-Prince)',
            flag: '🇭🇹',
            magnitude: 7.0,
            deaths: 160000,
        },
        {
            date: new Date('2011-03-11'),
            location: 'Tohoku, Japan',
            flag: '🇯🇵',
            magnitude: 9.1,
            deaths: 19759,
        },
        {
            date: new Date('2015-04-25'),
            location: 'Nepal',
            flag: '🇳🇵',
            magnitude: 7.8,
            deaths: 8964,
        },
        {
            date: new Date('2018-09-28'),
            location: 'Sulawesi, Indonesia',
            flag: '🇮🇩',
            magnitude: 7.5,
            deaths: 4340,
        },
        {
            date: new Date('2021-08-14'),
            location: 'Haiti',
            flag: '🇭🇹',
            magnitude: 7.2,
            deaths: 2248,
        },
        {
            date: new Date('2022-06-21'),
            location: 'Afghanistan',
            flag: '🇦🇫',
            magnitude: 6.1,
            deaths: 1163,
        },
        {
            date: new Date('2023-02-06'),
            location: 'Turkey-Syria',
            flag: '🇸🇾',
            magnitude: 7.8,
            deaths: 62013,
        },
        {
            date: new Date('2023-09-08'),
            location: 'Al Haouz, Morocco',
            flag: '🇲🇦',
            magnitude: 6.8,
            deaths: 2960,
        },
        {
            date: new Date('2025-03-28'),
            location: 'Sagaing Region, Myanmar',
            flag: '🇲🇲',
            magnitude: 6.9,
            deaths: 5456,
        },
    ];
}
