export const routeData = [
    { name: 'Tipperary-Waterford' },
    { name: 'Kilkenny-Waterford' },
    { name: 'New Ross-Waterford' },
    { name: 'Waterford-Wexford' },
    { name: 'Cork-Port' },
    { name: 'Cork-Youghal' },
    { name: 'Tipperary-Tratee' },
    { name: 'Portarlington-Tipperary' },
    { name: 'Athenry-Tipperary' },
    { name: 'Galway-Athenry' },
    { name: 'Claremorris-Athenry' },
    { name: 'Athone-Galway' },
    { name: 'Athone Bypass' },
    { name: 'Athone-Portarlington' },
    { name: 'Potarlington-Dublin' },
    { name: 'Dublin-Port' },
    { name: 'Westport-Claremorris' },
    { name: 'Ballina-Westport' },
    { name: 'Foynes-Limerick' },
    { name: 'Limerick Bypass' },
    { name: 'Mallow-Cork' },
    { name: 'Kilkenny-Newbridge' },
    { name: 'Atthnoe-Dublin' },
    { name: 'Sligo-Mullngar' },
    { name: 'Dublin-Wexford' },
    { name: 'Dundalk-Dublin' },
];
