export const cycleRouteData = [
    { ROUTE_NAME: 'Clifton Moorgate S - Oakdale Rd to Kettlestring' },
    { ROUTE_NAME: 'Clifton Moorgate S - Garage to Oakdale Rd' },
    { ROUTE_NAME: 'Clifton Moorgate S - Water Ln to Garage access' },
    { ROUTE_NAME: 'Clifton Moorgate S - Tribune Wy to Water Ln' },
    { ROUTE_NAME: 'Clifton Moorgate S - Centur Wy to Tribune Wy' },
    { ROUTE_NAME: 'Clifton Moorgate S - Bumpr Cstl to Centur Wy' },
    { ROUTE_NAME: 'Bumper Castle path' },
    { ROUTE_NAME: 'Clifton Moorgate N - Eastern' },
    { ROUTE_NAME: 'Clifton Moorgate N - Western end' },
    { ROUTE_NAME: 'Clifton Moorgate rdbt N path' },
    { ROUTE_NAME: 'Hurricane Way off road' },
    { ROUTE_NAME: 'Manor Lane to Hurricane Wy path' },
    { ROUTE_NAME: 'Manor Lane - Leapfrog to Kensington Rd' },
    { ROUTE_NAME: 'Northfield Ln West' },
    { ROUTE_NAME: 'Northfield Ln East' },
    { ROUTE_NAME: 'Grange Garth to New Walk link' },
    { ROUTE_NAME: 'Designer Outlet access road path' },
    { ROUTE_NAME: 'Selby Road A64 junc N to S West' },
    { ROUTE_NAME: 'Selby Road - Naburn Ln to A64' },
    { ROUTE_NAME: 'Selby Road - Naburn Ln to Landing Ln' },
    { ROUTE_NAME: 'Thief Lane to Hull Rd link' },
    { ROUTE_NAME: 'Imphal Barracks path to Walmgate Stry' },
    { ROUTE_NAME: 'Walmgate Stray path' },
    { ROUTE_NAME: 'Retreat Ln to underpass' },
    { ROUTE_NAME: 'University Science Pk to Windmill Lane' },
    { ROUTE_NAME: 'University path from Retreat Ln to Science Pk' },
    { ROUTE_NAME: 'University path from Heslington Ln to Walmgate Str' },
    { ROUTE_NAME: 'University path from Retreat Ln to Walmgate Stry' },
    { ROUTE_NAME: 'Retreat Lane_offroad' },
    { ROUTE_NAME: 'Lawrence St to Regent St link' },
    { ROUTE_NAME: 'Paragon St to Barbican path' },
    { ROUTE_NAME: 'Barbican path across front' },
    { ROUTE_NAME: 'Barbican - Kent Street path' },
    { ROUTE_NAME: 'Fulford Ings to St Oswalds Rd link' },
    { ROUTE_NAME: 'Fulford Ings to Fulford Cross link' },
    { ROUTE_NAME: 'Hospital Fields to Fulford Ings path' },
    { ROUTE_NAME: 'Millennium Br eastern link path S' },
    { ROUTE_NAME: 'Millennium Br eastern link path N' },
    { ROUTE_NAME: 'Broadway West to Fulford Ings link' },
    { ROUTE_NAME: 'Fulford Ings to Mill Br ramp' },
    { ROUTE_NAME: 'New Walk' },
    { ROUTE_NAME: 'Blue Bridge' },
    { ROUTE_NAME: "New Walk - adj St George's Field" },
    { ROUTE_NAME: 'Tower Gardens cycle route' },
    { ROUTE_NAME: 'South Esplanade' },
    { ROUTE_NAME: 'Tanners Moat cut-through' },
    { ROUTE_NAME: 'Bridge Lane Footbridge' },
    { ROUTE_NAME: 'Bridge Lane' },
    { ROUTE_NAME: 'Bootham Hospital route' },
    { ROUTE_NAME: 'Clifton Br to Almery Terr riverside path' },
    { ROUTE_NAME: 'NCN 65 adj Almery Terrace' },
    { ROUTE_NAME: 'Marygate to Scarborough Bridge' },
    { ROUTE_NAME: 'Wilton Rise footbridge' },
    { ROUTE_NAME: 'Springfield Court path' },
    { ROUTE_NAME: 'Holgate Road - adj Ashton House' },
    { ROUTE_NAME: 'Holgate Road - Thrall access to Wilton Rise' },
    { ROUTE_NAME: 'Holgate Road - west of Thrall access' },
    { ROUTE_NAME: 'Holgate Park link path to Poppleton Rd' },
    { ROUTE_NAME: 'Holgate Park southern side of road' },
    { ROUTE_NAME: 'Holgate Park northern side of road' },
    { ROUTE_NAME: 'Poppleton Road - Holgate Pk to The Fox' },
    { ROUTE_NAME: 'Poppleton Road - Renshaw Gdns to Holgate Pk' },
    { ROUTE_NAME: 'Poppleton Road - Ash St to Renshaw Gdns' },
    { ROUTE_NAME: 'Water End jug handle turn extension' },
    { ROUTE_NAME: 'Water End jug handled turn' },
    { ROUTE_NAME: 'Water End off road Borobr Rd to Rail Br' },
    { ROUTE_NAME: 'Water End shared footway' },
    { ROUTE_NAME: 'Cinder Lane - Scarbro Br to Jubilee Terr' },
    { ROUTE_NAME: 'Marygate CP path' },
    { ROUTE_NAME: 'Scarborough Bridge NCN 65' },
    { ROUTE_NAME: 'Marble Arch Tunnel' },
    { ROUTE_NAME: 'Cinder Lane - Leeman Rd CP to Wilton Rise FB' },
    { ROUTE_NAME: 'Post Office Lane' },
    { ROUTE_NAME: 'Esplanade - Scarbro Br to York Rowing Club' },
    { ROUTE_NAME: 'Westgate Apartments access lane' },
    { ROUTE_NAME: 'Nunnery Lane gyratory avoidance lane' },
    { ROUTE_NAME: 'Bishopthorpe Road shops car park' },
    { ROUTE_NAME: 'Racecourse road from NCN 65 to Campleshon Rd' },
    { ROUTE_NAME: 'Terry Ave - Millennium Bridge to Rowntree Pk CP' },
    { ROUTE_NAME: 'Millennium Bridge' },
    { ROUTE_NAME: 'Millennium Bridge link to Butcher Terr' },
    { ROUTE_NAME: 'Terry Ave extension' },
    { ROUTE_NAME: 'Terrys path' },
    { ROUTE_NAME: 'Bishopthorpe Rd - Path adj Terrys CP' },
    { ROUTE_NAME: 'NCN 65 Green Lane to Bishopthrpe Rd_1' },
    { ROUTE_NAME: 'Bishopthorpe Rd - Allotments to Green Lane' },
    { ROUTE_NAME: 'Little Knavesmire path' },
    { ROUTE_NAME: 'The Mount - Albemarle to road' },
    { ROUTE_NAME: 'The Mount - Mill Mount to Albemarle' },
    { ROUTE_NAME: 'The Mount - Mill Mount Ct to Mill mount' },
    { ROUTE_NAME: 'The Mount - Scarcrft to Mill Mount Ct' },
    { ROUTE_NAME: 'The Mount - Scarcrft to Holgate Rd' },
    { ROUTE_NAME: 'Moor Lane rdbt N path' },
    { ROUTE_NAME: 'Moor Lane rdbt NE path' },
    { ROUTE_NAME: 'Moor Lane rdbt SE path' },
    { ROUTE_NAME: 'Green Lane - Knavesmire Wood link' },
    { ROUTE_NAME: 'NCN 65 Green Lane to Yk Selby path' },
    { ROUTE_NAME: 'Green Lane - YrkSelby_Junc_Racetrack' },
    { ROUTE_NAME: 'Sim Balk Lane to 6th form coll x-ing' },
    { ROUTE_NAME: 'Naburn Lane seage works access to houses' },
    { ROUTE_NAME: 'Naburn Lane NCN 65 to sewage works access' },
    { ROUTE_NAME: 'NCN 65 B1222 link' },
    { ROUTE_NAME: 'NCN 65 Howden Lane Bridge link' },
    { ROUTE_NAME: 'NCN 65 Moor Lane Br Access' },
    { ROUTE_NAME: 'Vangard_Path_Martello_Wy_Kathryn_Ave' },
    { ROUTE_NAME: 'Jockey_Ln_Julia_Ave_Kathryn_Ave' },
    { ROUTE_NAME: 'Wigginton_Rd_Haxby_Rd2' },
    { ROUTE_NAME: 'Wigginton_Rd_Haxby_Rd1' },
    { ROUTE_NAME: 'A59_Pop_to_Beckfld' },
    { ROUTE_NAME: 'Malton Road to Woodlands Grove' },
    { ROUTE_NAME: 'A19 Deighton to Escrick Fway' },
    { ROUTE_NAME: 'Strensall_Rd_A1237link6' },
    { ROUTE_NAME: 'Strensall_Rd_A1237_link1' },
    { ROUTE_NAME: 'Strensall_Rd_A1237link_3' },
    { ROUTE_NAME: 'Strensall_Rd_A1237link_5' },
    { ROUTE_NAME: 'Water_Ln_Hazelnut_Gr' },
    { ROUTE_NAME: 'Stratford Way to New Lane' },
    { ROUTE_NAME: 'Monks_Cross_Dr_Sainsbury_Toucan' },
    { ROUTE_NAME: 'Field_Ln_Hes_E_Rdbt_Link1' },
    { ROUTE_NAME: 'Hull Road_P&R_xings' },
    { ROUTE_NAME: 'Grimston_Bar_Access_Rd' },
    { ROUTE_NAME: 'Lakeside_Way_Hes_E_Pt1' },
    { ROUTE_NAME: 'Moor_Ln_N_side' },
    { ROUTE_NAME: 'A1237_Moor_Ln_Link1' },
    { ROUTE_NAME: 'A1237_Moor_Ln_link2' },
    { ROUTE_NAME: 'Old_Askham_Ln_A1237_Link1' },
    { ROUTE_NAME: 'Askham_Ln_A1237_link' },
    { ROUTE_NAME: 'Ask_Bry_Ln_Moor_Ln_Rdbt1' },
    { ROUTE_NAME: 'A1237_Ask_Bry_Ln_link1' },
    { ROUTE_NAME: 'Scarcroft Green' },
    { ROUTE_NAME: 'Fulford_Rd_W_Mapl_Gr_FulFX' },
    { ROUTE_NAME: 'NCN65 route under Millen Br' },
    { ROUTE_NAME: 'Fulford_Rd_E_OffRd_Barracks_Moorland_Rd' },
    { ROUTE_NAME: 'Hungate_Br_to _Palmers_Ln' },
    { ROUTE_NAME: 'Foss_Islands_Rd_W_Side N of NCN658' },
    { ROUTE_NAME: 'Foss_Islands_Retail_Pk_Link' },
    { ROUTE_NAME: 'Hallfield_Rd_E' },
    { ROUTE_NAME: 'James_St_E_front_trav_site' },
    { ROUTE_NAME: 'James_St_Hallfield_Rd_W_side' },
    { ROUTE_NAME: 'Clifton Backies to Blatchford Ct' },
    { ROUTE_NAME: 'Wigg_Rd_MSCP_path' },
    { ROUTE_NAME: 'Wigg_Rd_Inbound_opp_Hosp' },
    { ROUTE_NAME: 'Hempland Ln to Stray Road' },
    { ROUTE_NAME: 'NCN66Scoreby_Ln_to_viaduct_path_Ryedale' },
    { ROUTE_NAME: 'Field_Ln_N' },
    { ROUTE_NAME: 'Knapton_Ln_A1237_Xing' },
    { ROUTE_NAME: 'Revival_Green_Ln_N' },
    { ROUTE_NAME: 'ORR_James_St_Morrisons_Elvington' },
    { ROUTE_NAME: 'Rawcliffe_Rec_Rawcliffe_Lake' },
    { ROUTE_NAME: 'Beckfield_Ln_off_rd_Ostman_Almsford' },
    { ROUTE_NAME: 'Link_to_Racecourse_Inner_Rd' },
    { ROUTE_NAME: 'Cherry Lane off road' },
    { ROUTE_NAME: 'Knavesmire track inside racecourse' },
    { ROUTE_NAME: 'Water End N nr Clifton Br' },
    { ROUTE_NAME: 'Hull_Rd_THL_Carlton_Ave' },
    { ROUTE_NAME: 'Little Hob Moor link to Hob Moor Ter' },
    { ROUTE_NAME: 'Nairn_Cl_Moor_Ln_link' },
    { ROUTE_NAME: 'Hob_Moor_Terrace_link' },
    { ROUTE_NAME: 'St Nich Ave Rdbt end' },
    { ROUTE_NAME: 'OCR Knavesmire Rd to Pulleyn Dr toucan' },
    { ROUTE_NAME: 'Arundel_Gr_Deepdale_link' },
    { ROUTE_NAME: 'Foxwood_Ln_Chesney_Fields' },
    { ROUTE_NAME: 'Acorn_Rugby_W' },
    { ROUTE_NAME: 'Malton_Rd_Outbound_New_Ln_Martello_Wy' },
    { ROUTE_NAME: 'Malton_Rd_inbound_access_rd_Straylands' },
    { ROUTE_NAME: 'Woodland_Chase' },
    { ROUTE_NAME: 'Walmgate Stray_S_West' },
    { ROUTE_NAME: 'New_Ln_to_MXP&R' },
    { ROUTE_NAME: 'Clif Moor Bowling Rdbt' },
    { ROUTE_NAME: 'Clif Moor Bowling Rdbt 2' },
    { ROUTE_NAME: 'CM_Rdbt5' },
    { ROUTE_NAME: 'Wigg_Rd_Rdbt1' },
    { ROUTE_NAME: 'CM_Rdbt9' },
    { ROUTE_NAME: 'CM_Rdbt13' },
    { ROUTE_NAME: 'Stirling_Rd_CM_Access' },
    { ROUTE_NAME: 'City Hospital path' },
    { ROUTE_NAME: 'Minster Yard' },
    { ROUTE_NAME: 'Dales Lane' },
    { ROUTE_NAME: 'Monkton Rd to Geldof rd link' },
    { ROUTE_NAME: 'Sleeper Path' },
    { ROUTE_NAME: 'Haxby Rd underpass southbound' },
    { ROUTE_NAME: 'Haxby Rd underpass northbound' },
    { ROUTE_NAME: 'Jockey Ln Rdbt S' },
    { ROUTE_NAME: 'Monks X access W' },
    { ROUTE_NAME: 'Monks X access E' },
    { ROUTE_NAME: 'Monks Cross E & S' },
    { ROUTE_NAME: 'Monks Cross N & W' },
    { ROUTE_NAME: 'Jockey Ln- Sainsbry Delvry to rdbt' },
    { ROUTE_NAME: 'Jockey Ln - Frge Cl to edge of houses' },
    { ROUTE_NAME: 'Jockey Lane - Saddlr Cl to Forge Cl' },
    { ROUTE_NAME: 'Jockey Lane - New Ln to Saddlrs Cl' },
    { ROUTE_NAME: 'Foss Bank - corner' },
    { ROUTE_NAME: 'Hewrth_Grn_James_St_Link_Foss_Bnk' },
    { ROUTE_NAME: 'F.I. Line - Amblsde Av' },
    { ROUTE_NAME: 'F.I. Line - Tang Hall Lib' },
    { ROUTE_NAME: 'F.I. Line - Tang Hall Ln' },
    { ROUTE_NAME: 'F.I. Line - 5th Ave THL access' },
    { ROUTE_NAME: 'F.I. Line - Melrsgte S' },
    { ROUTE_NAME: 'F.I. Line - Melrsgte N' },
    { ROUTE_NAME: 'St Nicks Fld - Rawdon Av to Bull Ln' },
    { ROUTE_NAME: 'St Nicks Field - Rawdon Ave to Env Cntr link' },
    { ROUTE_NAME: 'St Nicks Field - Bull Ln to FI Line' },
    { ROUTE_NAME: 'F.I. Line - James St Trav Site' },
    { ROUTE_NAME: 'F.I. Line - Travellers Site N' },
    { ROUTE_NAME: 'F.I. Line - Layrthrpe' },
    { ROUTE_NAME: 'F.I. Line - Heworth Gr' },
    { ROUTE_NAME: 'F.I. Line - City Gym to Hewrth Crft' },
    { ROUTE_NAME: 'F.I. Line - Arran Pl' },
    { ROUTE_NAME: 'F.I. Line - White X Gdns S' },
    { ROUTE_NAME: 'F.I. Line - White X Gdns N' },
    { ROUTE_NAME: 'F.I. Line - Ashville St' },
    { ROUTE_NAME: 'F.I. Line - Kitchnr St' },
    { ROUTE_NAME: 'F.I. Line - Haxby Rd S' },
    { ROUTE_NAME: 'F.I. Line - Haxby Rd N' },
    { ROUTE_NAME: 'F.I. Line - Hambltn Terr E' },
    { ROUTE_NAME: 'F.I. Line - Hambltn Terr W' },
    { ROUTE_NAME: 'F.I. Line - Wigg Rd S' },
    { ROUTE_NAME: 'F.I. Line - Crichton Ave ramp' },
    { ROUTE_NAME: 'F.I. Line - Haxby Rd to Wigg Rd' },
    { ROUTE_NAME: 'F.I. Line - Kitchnr St to Haxby Rd' },
    { ROUTE_NAME: 'F.I. Line - Ashvill St to Kitchnr St' },
    { ROUTE_NAME: 'F.I. Line - White X Gdns to Ashvill St' },
    { ROUTE_NAME: 'F.I. Line - Arran Pl to White X Gdns' },
    { ROUTE_NAME: 'F.I. Line - City Gym to Arran Pl' },
    { ROUTE_NAME: 'F.I. Line - Hewrth Gr to City Gym' },
    { ROUTE_NAME: 'F.I. Line - Layrthrpe to Hewrth Gr' },
    { ROUTE_NAME: 'F.I. Line - Hallfld Rd to Layrthrpe' },
    { ROUTE_NAME: 'F.I. Line - Hallfld Rd to Trav Site link' },
    { ROUTE_NAME: 'F.I. Line - 5th Ave Bowes Ave link' },
    { ROUTE_NAME: 'F.I. Line - St Nicks to Ebor Ind Est' },
    { ROUTE_NAME: 'F.I. Line - Melrsgte to St Nicks' },
    { ROUTE_NAME: 'F.I. Line - Tang H Ln to Melrsgte' },
    { ROUTE_NAME: 'F.I. Line - Tang H Lib to Tang H Ln' },
    { ROUTE_NAME: 'F.I. Line - Ambl to Tang H Lib.' },
    { ROUTE_NAME: 'F.I. line - Metc Ln to Ambl.' },
    { ROUTE_NAME: 'Field Lane rdbt path SW' },
    { ROUTE_NAME: 'Field Lane rdbt path SE' },
    { ROUTE_NAME: 'Metcalfe Lane N' },
    { ROUTE_NAME: 'Metcalfe Lane S' },
    { ROUTE_NAME: 'NCN 66 Limefield Farm to Scoreby Manor junc' },
    { ROUTE_NAME: 'NCN 66 Cowslip Farm to Limefield Farm' },
    { ROUTE_NAME: 'Hagg Farm track to Cowslip Farm' },
    { ROUTE_NAME: 'Grimstn Br intrchng NW' },
    { ROUTE_NAME: 'Grimstn Br intrchng N' },
    { ROUTE_NAME: 'Grimstn Br intrchng NE' },
    { ROUTE_NAME: 'Grimston Br intrchng E' },
    { ROUTE_NAME: 'Hull Rd N Rdbt to Bore Tr B' },
    { ROUTE_NAME: 'Hull Road N Bore Tree B to Yk Rd' },
    { ROUTE_NAME: 'Hull Rd S Elv Ln to x-ing' },
    { ROUTE_NAME: 'Grim Bar intchng to Elv Ln' },
    { ROUTE_NAME: 'Grimston Bar intrchnge S' },
    { ROUTE_NAME: 'Hull Road S P&R to GBar' },
    { ROUTE_NAME: 'Grimston Bar  access from Hull Rd' },
    { ROUTE_NAME: 'Hull Road N Link Rd to xing' },
    { ROUTE_NAME: 'Osbaldwick Link Road W' },
    { ROUTE_NAME: 'Hull Road N adj B&Q' },
    { ROUTE_NAME: 'Clifton Backies path' },
    { ROUTE_NAME: 'Fairway to Water Lane link' },
    { ROUTE_NAME: 'Lanshaw Crft to Angram Cl link' },
    { ROUTE_NAME: 'Oakdale Road off road' },
    { ROUTE_NAME: 'Lakeside school path' },
    { ROUTE_NAME: 'NCN 65 Bishopthorpe to boundary' },
    { ROUTE_NAME: 'NCN 65 A64 Bridge to Appleton Ct' },
    { ROUTE_NAME: 'A64 S Top Lane underpass' },
    { ROUTE_NAME: 'A64 S A1237 to St Nich Rd' },
    { ROUTE_NAME: 'A64 S Boundary to A1237' },
    { ROUTE_NAME: 'A64 N Buckles Inn to Boundary' },
    { ROUTE_NAME: 'A64 N Ask Bry Coll to Buckles Inn' },
    { ROUTE_NAME: 'A64 N A1237 off slip to Askham Br Coll' },
    { ROUTE_NAME: 'A64 N A1237 E to W path' },
    { ROUTE_NAME: 'A64 N Pikehills to A1237' },
    { ROUTE_NAME: 'A64 / Tadcaster Road Pikehills to Cop Rd signals' },
    { ROUTE_NAME: 'Tadcaster Road - path adj to Tesco' },
    { ROUTE_NAME: 'Askham Bar path from Moor Lane to access road' },
    { ROUTE_NAME: 'Lomond Ginnel - Lowick to Moor Ln' },
    { ROUTE_NAME: 'Bellhouse Way to Ashbourne Way path' },
    { ROUTE_NAME: 'Bellhouse Way to Teal Dr path' },
    { ROUTE_NAME: 'Acomb Wood Dr - Bellwood Dr to shops' },
    { ROUTE_NAME: 'Bellwood Dr - Linnet Wy to Acomb Wd Dr' },
    { ROUTE_NAME: 'Bellwood Dr - Spindle Cl to Linnet Wy' },
    { ROUTE_NAME: 'Bellwood Dr - Bellhouse Wy to Spindle Cl' },
    { ROUTE_NAME: 'Bellhouse Way - Wenham Rd to Bellwood Dr' },
    { ROUTE_NAME: 'Bellhouse Way - Teal Dr to Wenham Rd' },
    { ROUTE_NAME: 'Bellhouse Way to rugby club link' },
    { ROUTE_NAME: 'Lovell House link to rugby club path' },
    { ROUTE_NAME: 'Acorn Rugby Club path' },
    { ROUTE_NAME: 'Thanet Road to Foxwood Ln' },
    { ROUTE_NAME: 'Green Lane - Hob Moor link' },
    { ROUTE_NAME: 'Hob Moor_KingswayW_ECML_Subway' },
    { ROUTE_NAME: 'Cross Street Acomb' },
    { ROUTE_NAME: 'Woodlea Ave to Danebury Dr link' },
    { ROUTE_NAME: 'Rawcliffe Bar P&R path_2' },
    { ROUTE_NAME: 'Shipton Road allotments link path' },
    { ROUTE_NAME: 'Clifton Business Park route' },
    { ROUTE_NAME: 'NCN 65 A1237 to Clifton Bridge' },
    { ROUTE_NAME: 'NCN 65 A1237 underpass' },
    { ROUTE_NAME: 'NCN65 N of A1237 end of riverside N Rawc landing' },
    { ROUTE_NAME: 'Shipton Road N shared footway' },
    { ROUTE_NAME: 'Shipton_Rd_Ings_House_subway path_N' },
    { ROUTE_NAME: 'Link path Manor Lane to P&R access road' },
    { ROUTE_NAME: 'A1237 / A19 rdbt SE seg' },
    { ROUTE_NAME: 'A1237 / A19 rdbt western seg' },
    { ROUTE_NAME: 'A1237 path Sewage Works to A19 rdbt' },
    { ROUTE_NAME: 'A1237 path from Poppleton Park to sewage works' },
    { ROUTE_NAME: 'Poppleton Park path from Esk Drive to Millfield Ln' },
    { ROUTE_NAME: 'Poppleton Park path between Foss Walk &  Esk Drive' },
    { ROUTE_NAME: 'Poppleton Park path Severn Green to Foss Walk' },
    { ROUTE_NAME: 'Poppleton Park path western end of Severn Green' },
    { ROUTE_NAME: 'Poppleton Park path eastern end of Severn Green' },
    { ROUTE_NAME: 'Poppleton Park path Great North Way & Severn Grn' },
    { ROUTE_NAME: 'Poppleton Park path adj playground' },
    { ROUTE_NAME: 'Poppleton Park path east of Esk Drive' },
    { ROUTE_NAME: 'Poppleton Park path south  Great North Way Esk Dr' },
    { ROUTE_NAME: 'Poppleton Park path south of Great North Way' },
    { ROUTE_NAME: 'Poppleton Park path S of E end of Great N Way' },
    { ROUTE_NAME: 'Poppleton Park N of E section of Great N Way' },
    { ROUTE_NAME: 'Poppleton Park path west of Marlborough House' },
    { ROUTE_NAME: 'Poppleton Park path east of Regency House' },
    { ROUTE_NAME: 'Poppleton Park path south of Regency House' },
    { ROUTE_NAME: "Poppleton Park path adj Maxi's" },
    { ROUTE_NAME: 'Poppleton Park path adj Bengal Brasserie' },
    { ROUTE_NAME: 'Poppleton Park path adj Nursery' },
    { ROUTE_NAME: 'Millfield Lane north of Kyle Way' },
    { ROUTE_NAME: 'Millfield Lane south of Kyle Way' },
    { ROUTE_NAME: 'Millfield Lane - Poppleton Park adj Nidd Close' },
    { ROUTE_NAME: 'Millfield Lane shared use path' },
    { ROUTE_NAME: 'Manor Drive / Sowerby Road link' },
    { ROUTE_NAME: 'Meadlands to Stockton Lane' },
    { ROUTE_NAME: 'Stirling_Rd' },
    { ROUTE_NAME: 'Foss_Islands_Rd' },
    { ROUTE_NAME: 'Gillygate' },
    { ROUTE_NAME: 'Hull_Rd_Inbound_P&Rgate_to_accessrd' },
    { ROUTE_NAME: 'Yearsley Gr Anthea Dr' },
    { ROUTE_NAME: 'Brockfield Rd Brockfield Park Dr' },
    { ROUTE_NAME: 'Stratford Way' },
    { ROUTE_NAME: 'Tadcaster Rd Copmanthorpe St Nich to bypass' },
    { ROUTE_NAME: 'NCN66_Bishh_To_Boundary' },
    { ROUTE_NAME: 'Old_Askham_Ln' },
    { ROUTE_NAME: 'OCR_Wolsley_St' },
    { ROUTE_NAME: 'OCR_Melbourne_St_Hes_Rd' },
    { ROUTE_NAME: 'OCR_Fishergate' },
    { ROUTE_NAME: 'Fulf_Rd_onroad' },
    { ROUTE_NAME: 'Main Street Fulford' },
    { ROUTE_NAME: 'Dundas St Palmer Ln' },
    { ROUTE_NAME: 'Navigation_Rd_FI_Rd_to _HungateBr' },
    { ROUTE_NAME: 'Blatchford_Ct' },
    { ROUTE_NAME: 'Newby Terr Wigginton Terr' },
    { ROUTE_NAME: 'Wigginton_Rd_S' },
    { ROUTE_NAME: 'Lowther_Terrace' },
    { ROUTE_NAME: 'Holgate_Br_onwards_inbound' },
    { ROUTE_NAME: 'NCN66_Scoreby_Ln' },
    { ROUTE_NAME: 'Heslington_Ln_Ph3' },
    { ROUTE_NAME: 'Fulfordgate' },
    { ROUTE_NAME: 'Heslington_Ln_SRTS' },
    { ROUTE_NAME: 'Hope_St_Gladstone_St' },
    { ROUTE_NAME: 'OCR_Green_Ln_Rdbt_York_Rd' },
    { ROUTE_NAME: 'Water End Govt Hs Rd to centre feed' },
    { ROUTE_NAME: 'OCR Butcher Terr South Bank Ave' },
    { ROUTE_NAME: 'OCR_Albemarle_to_Count_de_Burgh' },
    { ROUTE_NAME: 'Station_Rd_Queen_St_Br' },
    { ROUTE_NAME: 'Hallfield_Rd_Layerthorpe_inbound' },
    { ROUTE_NAME: 'Neville_St_to_Hansom_Pl_link' },
    { ROUTE_NAME: 'Heron Ave Sherringham Dr' },
    { ROUTE_NAME: 'Alder_Wy_to_Garth_Way_Offroad' },
    { ROUTE_NAME: 'Rowan Ave Alder Way' },
    { ROUTE_NAME: 'Kettlestring_Ln_Audax_Rd' },
    { ROUTE_NAME: 'City Hosp link to FI Line' },
    { ROUTE_NAME: 'Neville Street' },
    { ROUTE_NAME: 'Neville Terrace' },
    { ROUTE_NAME: 'Brownlow Street' },
    { ROUTE_NAME: 'March Street' },
    { ROUTE_NAME: 'Abbot Street' },
    { ROUTE_NAME: 'Garden Street' },
    { ROUTE_NAME: 'St John Street' },
    { ROUTE_NAME: 'Lord Mayors Walk' },
    { ROUTE_NAME: 'Monkgate' },
    { ROUTE_NAME: 'St Leonards Pl' },
    { ROUTE_NAME: 'Duncombe Place' },
    { ROUTE_NAME: 'Deangate' },
    { ROUTE_NAME: 'Goodramgate - Monk Bar to Aldwark' },
    { ROUTE_NAME: 'Jewbury' },
    { ROUTE_NAME: 'St Andrewgate' },
    { ROUTE_NAME: 'Aldwark' },
    { ROUTE_NAME: 'Peasholme Green' },
    { ROUTE_NAME: 'Stonebow' },
    { ROUTE_NAME: 'Pavement' },
    { ROUTE_NAME: 'Piccadilly - Dales Ln to Pavmnt' },
    { ROUTE_NAME: 'George Street' },
    { ROUTE_NAME: 'York Road Haxby' },
    { ROUTE_NAME: 'Haxby Rd - Rowan Ave to A1237' },
    { ROUTE_NAME: 'Huntington Road - N of Link Rd' },
    { ROUTE_NAME: 'Huntington Rd - S of Link Rd' },
    { ROUTE_NAME: 'New Lane - northbound' },
    { ROUTE_NAME: 'Hewrth Gr Magic Rdbt' },
    { ROUTE_NAME: 'Foss Bank - Layrthrp Br' },
    { ROUTE_NAME: 'Foss Bank' },
    { ROUTE_NAME: 'Hewrth Grn - Mnkgt Rdbt to CP' },
    { ROUTE_NAME: 'Hewrth Grn - Trnsco to Mag Rdbt' },
    { ROUTE_NAME: 'Derwent Ave / Melrsgte' },
    { ROUTE_NAME: 'James St to FI Line along S edge of trav site' },
    { ROUTE_NAME: 'Bull Lane' },
    { ROUTE_NAME: 'Meadlands E' },
    { ROUTE_NAME: 'Tranby Avenue' },
    { ROUTE_NAME: 'Osbaldwick village - Metcalfe Ln to Osbldwk Ln' },
    { ROUTE_NAME: 'Murton Way' },
    { ROUTE_NAME: 'Murton Lane' },
    { ROUTE_NAME: 'NCN 66 Bore Tree Baulk' },
    { ROUTE_NAME: 'Intake Lane Dunnington' },
    { ROUTE_NAME: 'The Green Dunnington' },
    { ROUTE_NAME: 'Common Road Dunnington' },
    { ROUTE_NAME: 'York Street Dunnington' },
    { ROUTE_NAME: 'York Road Dunnington' },
    { ROUTE_NAME: 'Field Ln rdbt N' },
    { ROUTE_NAME: 'Hull Road N Carlton Ave - Field Ln' },
    { ROUTE_NAME: 'Hull Road bus lane' },
    { ROUTE_NAME: 'Sutton Way' },
    { ROUTE_NAME: 'Crichton Avenue' },
    { ROUTE_NAME: 'Water Lane - Clifton Gr to Kingswy N' },
    { ROUTE_NAME: 'Kingsway North Rdbt' },
    { ROUTE_NAME: 'Bur Dyke Avenue' },
    { ROUTE_NAME: 'Fairway' },
    { ROUTE_NAME: 'Shipton Road service road' },
    { ROUTE_NAME: 'Bowness Drive' },
    { ROUTE_NAME: 'Easholme Dr - Bowness to Rawc Ln' },
    { ROUTE_NAME: 'Rawcliffe Lane - Beaverdyke to Shipton rd' },
    { ROUTE_NAME: 'Beaverdyke' },
    { ROUTE_NAME: 'Angram Close' },
    { ROUTE_NAME: 'Lanshaw Croft' },
    { ROUTE_NAME: 'Ebsay Drive' },
    { ROUTE_NAME: 'Oakdale Road route' },
    { ROUTE_NAME: 'Hurricane Way on road' },
    { ROUTE_NAME: 'Manor Lane' },
    { ROUTE_NAME: 'Thief Lane' },
    { ROUTE_NAME: 'Windmill Lane - NCN66 section' },
    { ROUTE_NAME: 'Heslington Road' },
    { ROUTE_NAME: 'Regent Street' },
    { ROUTE_NAME: 'Wellington Street' },
    { ROUTE_NAME: 'Kent Street' },
    { ROUTE_NAME: 'Blue Bridge Lane' },
    { ROUTE_NAME: 'Grange Street' },
    { ROUTE_NAME: 'Grange Garth' },
    { ROUTE_NAME: 'Alma Terrace' },
    { ROUTE_NAME: 'Hospital Fields Road' },
    { ROUTE_NAME: 'Maple Grove' },
    { ROUTE_NAME: 'Fulford Cross' },
    { ROUTE_NAME: 'Broadway West' },
    { ROUTE_NAME: "St Oswald's Road" },
    { ROUTE_NAME: 'Lower Friargate' },
    { ROUTE_NAME: 'Cumberland Street' },
    { ROUTE_NAME: 'North Street NCN 65' },
    { ROUTE_NAME: 'Wellington Row - NCN65' },
    { ROUTE_NAME: 'Tanners Moat' },
    { ROUTE_NAME: 'Esplanade - Lendal Br to locked gate' },
    { ROUTE_NAME: 'Marygate - NCN 66' },
    { ROUTE_NAME: 'Avenue Terrace' },
    { ROUTE_NAME: 'Avenue Road' },
    { ROUTE_NAME: 'Burton Stone Lane' },
    { ROUTE_NAME: 'Grosvenor Road' },
    { ROUTE_NAME: 'Bootham Terr - underpass to Bootham' },
    { ROUTE_NAME: 'Bootham - Bootham Terr to Gillygate' },
    { ROUTE_NAME: 'Clifton - Bootham Cres to Rawc Ln' },
    { ROUTE_NAME: 'Water End - Govt Ho Rd to Clifton' },
    { ROUTE_NAME: 'Government House Road' },
    { ROUTE_NAME: 'Wilton Rise' },
    { ROUTE_NAME: 'Beech Avenue' },
    { ROUTE_NAME: 'Water_End_eastbound_lane' },
    { ROUTE_NAME: 'Salisbury Road' },
    { ROUTE_NAME: 'Salisbury Terrace - with flow' },
    { ROUTE_NAME: 'Livingstone St - Bromley St to Salisbry Ter' },
    { ROUTE_NAME: 'Bromley Street - Bright St to Livingstone St' },
    { ROUTE_NAME: 'Bright Street - Salisbry Ter to Bromley St' },
    { ROUTE_NAME: 'Salisbury Terr contra-flow cycle lane' },
    { ROUTE_NAME: 'Jubilee Terrace' },
    { ROUTE_NAME: 'Leeman Road contra-flow lane' },
    { ROUTE_NAME: 'Queen Street ASL feeder' },
    { ROUTE_NAME: 'Nunnery Lane ASL feeder - station bound only' },
    { ROUTE_NAME: 'Tower Street rdbt lane' },
    { ROUTE_NAME: 'Skeldergate Bridge / Tower St left turn lane' },
    { ROUTE_NAME: 'Skeldergate Bridge lane' },
    { ROUTE_NAME: 'Bishopgate Street - Skeldergate to Prices St' },
    { ROUTE_NAME: 'Bishopthorpe Road - Scarcroft Rd to Clementhorpe' },
    { ROUTE_NAME: 'Bishopgate St - contraflow lane adj bridge' },
    { ROUTE_NAME: 'Terry Ave NCN 65 on road sectn' },
    { ROUTE_NAME: 'Skeldergate (NCN 65 section)' },
    { ROUTE_NAME: 'Fetter Lane' },
    { ROUTE_NAME: 'Bishophill Junior' },
    { ROUTE_NAME: 'Lower Priory Street' },
    { ROUTE_NAME: 'Victor Street - Nunnery Ln to Lower Priory St' },
    { ROUTE_NAME: 'Nunnery Lane - Swann St to Victor St' },
    { ROUTE_NAME: 'Swann Street' },
    { ROUTE_NAME: 'Cygnet Street' },
    { ROUTE_NAME: 'St Benedict Road' },
    { ROUTE_NAME: 'Price Street' },
    { ROUTE_NAME: 'Upper Price Street' },
    { ROUTE_NAME: 'Scarcroft Road - Thorpe St to Upper Price St' },
    { ROUTE_NAME: 'Thorpe Street' },
    { ROUTE_NAME: 'Nunthorpe Grove' },
    { ROUTE_NAME: 'Trafalgar Street' },
    { ROUTE_NAME: 'South Bank Ave - Trafalgar St to Nunthorpe Gr' },
    { ROUTE_NAME: 'Campleshon Road' },
    { ROUTE_NAME: 'The Mount - Dalton Terr to Scarcroft ln' },
    { ROUTE_NAME: 'Tadcaster Road - Moor Ln to Dalton Terr' },
    { ROUTE_NAME: 'Tadcaster Rd - 6th Frm Coll x-ing to Ask Br Rdbt' },
    { ROUTE_NAME: 'Appleton Ct Bishopthorpe' },
    { ROUTE_NAME: 'Moor Lane - rdbt to Chaloners Rd' },
    { ROUTE_NAME: 'Chaloners Road S lanes' },
    { ROUTE_NAME: 'Moor Lane RT lane to Nairn Cl' },
    { ROUTE_NAME: 'Lowick' },
    { ROUTE_NAME: 'Ryecroft Ave - Ashbourne Wy to Lowick' },
    { ROUTE_NAME: 'Ashbourne Way' },
    { ROUTE_NAME: 'Kingsway West route' },
    { ROUTE_NAME: 'Green Lane (S) Acomb' },
    { ROUTE_NAME: 'Green Lane / Kingsway West Rdbt' },
    { ROUTE_NAME: 'Green Lane (N) Acomb' },
    { ROUTE_NAME: 'York Road Beech Gr to Cross St' },
    { ROUTE_NAME: 'Beech Grove to York Road, Acomb' },
    { ROUTE_NAME: 'Rosedale Ave to Beech Gr' },
    { ROUTE_NAME: 'Woodlea Ave to Rosedale Ave route' },
    { ROUTE_NAME: 'Milner Street' },
    { ROUTE_NAME: 'Severus Street' },
    { ROUTE_NAME: 'Acomb Road - Manor Drive to Severus Street link' },
    { ROUTE_NAME: 'Manor Drive South' },
    { ROUTE_NAME: 'Sowerby Road' },
    { ROUTE_NAME: 'Lindsey Avenue' },
    { ROUTE_NAME: 'Millfield Lane - Manor School end' },
    { ROUTE_NAME: 'Low Poppleton Lane' },
    { ROUTE_NAME: 'Beckfield Lane' },
    { ROUTE_NAME: 'Ostman Road' },
    { ROUTE_NAME: 'Viking Road' },
    { ROUTE_NAME: 'Danebury Drive' },
    { ROUTE_NAME: 'Woodlea Avenue' },
    { ROUTE_NAME: 'Almsford Road' },
    { ROUTE_NAME: 'Carr Lane' },
    { ROUTE_NAME: 'Boroughbridge_Rd_Inbound' },
    { ROUTE_NAME: 'University_Road' },
    { ROUTE_NAME: 'Uni_Rd_Jughandle' },
    { ROUTE_NAME: 'Science_Park_exit' },
    { ROUTE_NAME: 'Rufforth_to_Knapton_Ph1' },
    { ROUTE_NAME: 'Jockey_Ln_Range_to_Sainsbury' },
    { ROUTE_NAME: 'Jockey_Ln_MartelloWay_to_Asda_Toucan' },
    { ROUTE_NAME: 'Malton_Rd_Hopgrove_end' },
    { ROUTE_NAME: 'Malton_Rd_N_of_MonksX_Rdbt' },
    { ROUTE_NAME: 'Haxby_Rd_Bridge' },
    { ROUTE_NAME: 'Bootham_Stray' },
    { ROUTE_NAME: 'Wigginton_Rd_Nestle' },
    { ROUTE_NAME: 'Wigg_Rd_Foss_Islands_link' },
    { ROUTE_NAME: 'Blatchford_Ct_to_Lilbourne_Dr_link' },
    { ROUTE_NAME: 'Lilbourne_Dr' },
    { ROUTE_NAME: 'Lilbourne_Dr_path' },
    { ROUTE_NAME: 'Kingsway_N_Cyclepath' },
    { ROUTE_NAME: 'Water_Ln_to_Kingsway_N' },
    { ROUTE_NAME: 'Pinfold Court to Water Lane' },
    { ROUTE_NAME: 'Water End N Guardrail to Ramp' },
    { ROUTE_NAME: 'Rawcliffe Bar link #1' },
    { ROUTE_NAME: 'Walmgate_Stray_S_East' },
    { ROUTE_NAME: 'Holmfield_Lane_path' },
    { ROUTE_NAME: 'Holmefield_Ln_link1' },
    { ROUTE_NAME: 'Holmefield_Ln_link2' },
    { ROUTE_NAME: 'Revival_Green_Ln_S' },
    { ROUTE_NAME: 'OCR_Albemarle_Brunswick' },
    { ROUTE_NAME: 'Hiscox_link' },
    { ROUTE_NAME: 'Tower_St_Toucan' },
    { ROUTE_NAME: 'Tower_St_Court_side' },
    { ROUTE_NAME: 'Tower_St_ASL_Feeder' },
    { ROUTE_NAME: 'Fishergate_toucans' },
    { ROUTE_NAME: 'Barbican_mews_link' },
    { ROUTE_NAME: 'Barbican_Rd_ASL_feeder' },
    { ROUTE_NAME: 'Barbican_Mews_Regent_St_Link' },
    { ROUTE_NAME: 'Lawrence_St_James_St_Toucan' },
    { ROUTE_NAME: 'James_St_Toucan_S' },
    { ROUTE_NAME: 'James St_on_road' },
    { ROUTE_NAME: 'Morrisons_E_Toucan' },
    { ROUTE_NAME: 'Crichton_Ave_S' },
    { ROUTE_NAME: 'Crichton_Ave_N' },
    { ROUTE_NAME: 'Kingsway_North_Rdbt_Crichton_Ave_Slip' },
    { ROUTE_NAME: 'James_St_N_Toucan' },
    { ROUTE_NAME: 'Racecourse road from NCN 65 to Campleshon Rd' },
    { ROUTE_NAME: 'Racecourse_Rd_Link' },
    { ROUTE_NAME: 'Dringthorpe_Rd_Link2' },
    { ROUTE_NAME: 'Top_Lane_offlink' },
    { ROUTE_NAME: 'A64 S A1237 to St Nich Rd' },
    { ROUTE_NAME: 'Askham_Bar_Toucan' },
    { ROUTE_NAME: 'Moor_Lane_Toucan' },
    { ROUTE_NAME: 'Thanet_Rd_Toucan' },
    { ROUTE_NAME: 'Nelsons_Ln_Park' },
    { ROUTE_NAME: 'Green_Ln_jughandle' },
    { ROUTE_NAME: 'Green_Ln_Rdbt_bypass' },
    { ROUTE_NAME: 'OCR_York_Rd' },
    { ROUTE_NAME: 'Severus_St_Manor_Dr_S_link' },
    { ROUTE_NAME: 'Slip_York_Rd_Toucan' },
    { ROUTE_NAME: 'Ostman_Rd_xing_N' },
    { ROUTE_NAME: 'Ostman_Rd_xing_S' },
    { ROUTE_NAME: 'Beckfield_Ln_Costcutter' },
    { ROUTE_NAME: 'Beckfield_Ln_Coop' },
    { ROUTE_NAME: 'Beckfield_Ln_Toucan' },
    { ROUTE_NAME: 'Beckfield_Ln_zebra_approach' },
    { ROUTE_NAME: 'Boroughbridge_Rd_Beck_Toucan' },
    { ROUTE_NAME: 'Low _Poppleton_Ln_offroad_speed_table_xing_Villa_C' },
    { ROUTE_NAME: 'Esk_Drive_link' },
    { ROUTE_NAME: 'Foss_Walk_link' },
    { ROUTE_NAME: 'Severn_Green_link' },
    { ROUTE_NAME: 'Opus_Avenue_SE' },
    { ROUTE_NAME: 'Opus_Ave_N' },
    { ROUTE_NAME: 'White_Rose_Close_NW' },
    { ROUTE_NAME: 'White_Rose_Close_W' },
    { ROUTE_NAME: 'White_Rose_Ave_splitter_islands' },
    { ROUTE_NAME: 'NCN65_Stripe_Ln' },
    { ROUTE_NAME: 'Moor_Ln_Rawcliffe_Rec' },
    { ROUTE_NAME: 'Staindale_Cl_Rawcliffe_Rec' },
    { ROUTE_NAME: 'Rawcliffe_Rec_Footbridge_CWR_School' },
    { ROUTE_NAME: 'Rawcliffe_Lake' },
    { ROUTE_NAME: 'Greystoke_Rd_Rawcliffe_Lake' },
    { ROUTE_NAME: 'Beaverdyke_Rawcliffe_Lake' },
    { ROUTE_NAME: 'Angram_Cl_exit' },
    { ROUTE_NAME: 'Angram_Cl_Link' },
    { ROUTE_NAME: 'Oakdale_Rd_S_Lakeside' },
    { ROUTE_NAME: 'Oakdale_Rd_N_Lakeside' },
    { ROUTE_NAME: 'Thornton_Moor_Close_Lakeside' },
    { ROUTE_NAME: 'Boltby_Road_Lakeside' },
    { ROUTE_NAME: 'Eldwick_Cl_Lakeside' },
    { ROUTE_NAME: 'Rishworth_Gr_Lakeside' },
    { ROUTE_NAME: 'Wellesley_Cl_Oakdale_Rd' },
    { ROUTE_NAME: 'Tribune_Way_Water_Lane' },
    { ROUTE_NAME: 'Hazelnut_Gr' },
    { ROUTE_NAME: 'Minchin_Cl_Clifton_Backies' },
    { ROUTE_NAME: 'Herdwick_Cl_Clifton_Backies' },
    { ROUTE_NAME: 'Clifton_Moorgate_Tesco_Toucan' },
    { ROUTE_NAME: 'Tesco_access_B&Q_side' },
    { ROUTE_NAME: 'Stirling_Rd_Rdbt' },
    { ROUTE_NAME: 'CM_Access_Link' },
    { ROUTE_NAME: 'CM_Access_Link2' },
    { ROUTE_NAME: 'CM_Rdbt2' },
    { ROUTE_NAME: 'CM_Rdbt3' },
    { ROUTE_NAME: 'CM_Rdbt4' },
    { ROUTE_NAME: 'CM_Rdbt6' },
    { ROUTE_NAME: 'CM_Rdbt7' },
    { ROUTE_NAME: 'CM_Rdbt8' },
    { ROUTE_NAME: 'CM_Rdbt10' },
    { ROUTE_NAME: 'CM_Rdbt11' },
    { ROUTE_NAME: 'CM_Rdbt12' },
    { ROUTE_NAME: 'CM_Rdbt14' },
    { ROUTE_NAME: 'CM_Rdbt15' },
    { ROUTE_NAME: 'Hartrigg_Oaks_offroad' },
    { ROUTE_NAME: 'Alder_Way' },
    { ROUTE_NAME: 'Nestle_Gate_xing' },
    { ROUTE_NAME: 'Woodlands Grove' },
    { ROUTE_NAME: 'Stockton_Ln_Greenfields_To_Charles_Moor' },
    { ROUTE_NAME: 'Heworth_Grn_into_Malton_Rd' },
    { ROUTE_NAME: 'Malton_Rd_outbound_side_to_Muncastergate' },
    { ROUTE_NAME: 'Malton_Rd_outbound_Elmfield_Ave' },
    { ROUTE_NAME: 'Malton_Rd_Outbound_Laburnum_New_Ln' },
    { ROUTE_NAME: 'Malton_Rd_New_Ln_Toucan' },
    { ROUTE_NAME: 'Martello_Way_MXRdbt_to_P&R_Office' },
    { ROUTE_NAME: 'Martello_Way_Toucan' },
    { ROUTE_NAME: 'New_Ln_Access' },
    { ROUTE_NAME: 'Jockey_Ln_Asda_Toucan' },
    { ROUTE_NAME: 'MX_Drive_Toucan' },
    { ROUTE_NAME: 'Alpha_Ct_link_E_Side' },
    { ROUTE_NAME: 'Alpha_Ct_Link_W_Side' },
    { ROUTE_NAME: 'Malton_Rd_inbound_busgate _Magic_Rdbt' },
    { ROUTE_NAME: 'Strensall_Rd_A1237link_2' },
    { ROUTE_NAME: 'Strensall_Rd_A1237link_4' },
    { ROUTE_NAME: 'Strensall_Rd_A1237link_7' },
    { ROUTE_NAME: 'Haxby_Rd_to_Hunt_Village1' },
    { ROUTE_NAME: 'Haxby_Rd_to_Hunt_Village2' },
    { ROUTE_NAME: 'Haxby_Rd_to_Hunt_Village3' },
    { ROUTE_NAME: 'Monkgate_Rdbt_To_Penlys' },
    { ROUTE_NAME: 'Monkgate_Rdbt_Offroad1' },
    { ROUTE_NAME: 'Monkgate_Rdbt_Offroad2' },
    { ROUTE_NAME: 'Monkgate_Rdbt_bypass' },
    { ROUTE_NAME: 'Monkgate_Rdbt_Fossbank_link' },
    { ROUTE_NAME: 'Foss_Islands_Rd_Toucan_N' },
    { ROUTE_NAME: 'Morrisons_Access_W' },
    { ROUTE_NAME: 'Foss_Islands_Rd_Toucan_S' },
    { ROUTE_NAME: 'Hungate_Br_To_George_St' },
    { ROUTE_NAME: 'Long_Close_Lane' },
    { ROUTE_NAME: 'Kent_St_to_Fishergate_Schl' },
    { ROUTE_NAME: 'Fishergate_Inbound' },
    { ROUTE_NAME: 'Tanner_Row_E' },
    { ROUTE_NAME: 'Ramped_access_to_Station_N' },
    { ROUTE_NAME: 'Blossom_St' },
    { ROUTE_NAME: 'Station_ramp_S' },
    { ROUTE_NAME: 'Holgate_Park_Dr_Toucan' },
    { ROUTE_NAME: 'Popp_Rd_Toucan_link' },
    { ROUTE_NAME: 'Popp_Rd_Toucan' },
    { ROUTE_NAME: 'Popp_Rd_Toucan_Acomb_Rd-App' },
    { ROUTE_NAME: 'Popp_Rd_Toucan_HolgateRd_App' },
    { ROUTE_NAME: 'Popp_Rd_outbound' },
    { ROUTE_NAME: 'Holgate_Rd_Acomb_Rd_link' },
    { ROUTE_NAME: 'Acomb_Rd_Popp_Rd_ASL' },
    { ROUTE_NAME: 'York_Rd_Carr_Ln_ASL_E' },
    { ROUTE_NAME: 'Carr_Ln_York_Rd_ASL' },
    { ROUTE_NAME: 'York_Rd_Carr_Ln_ASL_W' },
    { ROUTE_NAME: 'Askham_Ln_The_Green' },
    { ROUTE_NAME: 'A1237_Knapton_Xing' },
    { ROUTE_NAME: 'A59_Xing_Stn_Rd' },
    { ROUTE_NAME: 'Low_Popp_Ln_toucan' },
    { ROUTE_NAME: 'Boroughbridge_Rd_Toucan_W' },
    { ROUTE_NAME: 'A1237_Moor_Ln_xing_S' },
    { ROUTE_NAME: 'A1237_Ask_Bry_Ln_link2' },
    { ROUTE_NAME: 'A1237_Moor_Ln_Rdbt_xing_N' },
    { ROUTE_NAME: 'Moor_Ln_A1237_jughandle' },
    { ROUTE_NAME: 'Moor_Ln_A1237_Splitter_Island' },
    { ROUTE_NAME: 'A1237_Moor_Ln_Rdbt_E_bypass' },
    { ROUTE_NAME: 'A1237_Askham_Ln_splitter' },
    { ROUTE_NAME: 'St_Helens_Rd_Eason_View' },
    { ROUTE_NAME: 'Eason_View_Contraflow' },
    { ROUTE_NAME: 'York_High_rear_access' },
    { ROUTE_NAME: 'Field_Ln_Lakeside_Way_W' },
    { ROUTE_NAME: 'Lakeside_Way_Field_Ln_Toucan' },
    { ROUTE_NAME: 'Field_Ln_westbound' },
    { ROUTE_NAME: 'Hes_East_Pathway' },
    { ROUTE_NAME: 'Field_Ln_splitter_Hull_Rd_Rdbt_' },
    { ROUTE_NAME: 'Hull_Rd_W_splitter_Field_Ln' },
    { ROUTE_NAME: 'Hull_Rd_service_rd_link' },
    { ROUTE_NAME: 'Field_Ln_Church_Ln' },
    { ROUTE_NAME: 'Field_Ln_toucan' },
    { ROUTE_NAME: 'Church_Ln_jughandle' },
    { ROUTE_NAME: 'David_Lloyd_entrance' },
    { ROUTE_NAME: 'Windmill Lane_bypass' },
    { ROUTE_NAME: 'NCN66_Tang_Hall_Ln' },
    { ROUTE_NAME: 'York_Sport_Access_Rd' },
    { ROUTE_NAME: 'York_Sport_Access_2' },
    { ROUTE_NAME: 'Osb_Link_Rd_Splitter1' },
    { ROUTE_NAME: 'Osb_Link_Rd_toucan1' },
    { ROUTE_NAME: 'Osb_Link_Rd_toucan2' },
    { ROUTE_NAME: 'Osb_Link_Rd_splitter2' },
    { ROUTE_NAME: 'Osb_Link_Rd_toucan3' },
    { ROUTE_NAME: 'Hull_Rd_garage_central_Verge' },
    { ROUTE_NAME: 'Hull_Rd_Field_Ln_Rdbt_offslip' },
    { ROUTE_NAME: 'Hull_Rd_Osb_Link_Rd_ASL' },
    { ROUTE_NAME: 'Osb_Link_Rd_Hull_Rd_ASL' },
    { ROUTE_NAME: 'Murton_Ln_jughandle' },
    { ROUTE_NAME: 'A166_Murton_Ln_to_xing' },
    { ROUTE_NAME: 'A166_central_refuge' },
    { ROUTE_NAME: 'A166_xing_to_BTB' },
    { ROUTE_NAME: 'BTB_Splitter' },
    { ROUTE_NAME: 'A1079_Centre_Islands_)Elv_Ln' },
    { ROUTE_NAME: 'Grimston_Bar_Intchg_A166_splitter' },
    { ROUTE_NAME: 'A1079_GBInt_W_Central_Verge' },
    { ROUTE_NAME: 'Field_Ln_Rdbt_Hes_E_Link2' },
    { ROUTE_NAME: 'Hes_E_Access_off_Field_Ln_Rdbt' },
    { ROUTE_NAME: 'Kilburn_Rd_allotments_site' },
    { ROUTE_NAME: 'Kilburn_Rd' },
    { ROUTE_NAME: 'Uni_Wentworth_Wy_Walmgate_Stray_S' },
    { ROUTE_NAME: 'NCN66_to_Science_Pk' },
    { ROUTE_NAME: 'Alder_Way_offroad_S' },
    { ROUTE_NAME: 'Askham_Bar_onsite' },
    { ROUTE_NAME: 'Askham_Bar_onsite2' },
    { ROUTE_NAME: 'Poppleton_Bar_onsite1' },
    { ROUTE_NAME: 'Hull_Rd_Yarbrugh_Wy_Pinelands' },
    { ROUTE_NAME: 'Hull_Rd_Yarbrugh_Wy_W' },
    { ROUTE_NAME: 'Hull_Rd_Pinelands_Toucans' },
    { ROUTE_NAME: 'Hull_Rd_Pinelands_Link1' },
    { ROUTE_NAME: 'Hull_Rd_Pinelands_Link2' },
    { ROUTE_NAME: 'Hull_Rd_Black_Bull_toucan_offslip' },
    { ROUTE_NAME: 'Black_Bull_toucan_Archies_Schl_link' },
    { ROUTE_NAME: 'Black_Bull_toucan' },
    { ROUTE_NAME: 'Hull_Rd_THL_ASL_E' },
    { ROUTE_NAME: 'Hull_Rd_THL_ASL_W' },
    { ROUTE_NAME: 'Hull_Rd_Lilac_Ave_Toucan' },
    { ROUTE_NAME: 'Lilac_Ave_Hull_Rd_link' },
    { ROUTE_NAME: 'Hull_Rd_Lilac_Ave_onslip' },
    { ROUTE_NAME: 'Hull_Rd_Lilac_Ave_toucan_offslip' },
    { ROUTE_NAME: 'Lilac_Ave_toucan_Thief_Ln_link' },
    { ROUTE_NAME: 'Hull_Rd_Melrosegate_ASL' },
    { ROUTE_NAME: 'Green_Dykes_Ln_Hull_Rd_ASL' },
    { ROUTE_NAME: 'Melrosegate_Hull_Rd_ASL' },
    { ROUTE_NAME: 'Hull_Rd_Melrosegate_W_ASL' },
    { ROUTE_NAME: 'Lawrence_St_E_James_St_ASL' },
    { ROUTE_NAME: 'James_St_Lawrence_St_ASL' },
    { ROUTE_NAME: 'Lawrence_St_W_James_St_ASL' },
    { ROUTE_NAME: 'Lawrence_St_James_St_offslip' },
    { ROUTE_NAME: 'Lawrence_St_Walmgate_Bar_ASL' },
    { ROUTE_NAME: 'Barbican_Rd_Lawrence_ST_ASL' },
    { ROUTE_NAME: 'FIRd_Lawrence_St_ASL' },
    { ROUTE_NAME: 'Walmgate_Bar_bypass' },
    { ROUTE_NAME: 'Walmgate_Walmgate_Bar_ASL' },
    { ROUTE_NAME: 'FIRd_S_Waitrose_ASL' },
    { ROUTE_NAME: 'FIRd_N_Waitrose_ASL' },
    { ROUTE_NAME: 'FIRd_Navigation _Rd' },
    { ROUTE_NAME: 'Layerthorpe_Hallfield_Rd_ASLs' },
    { ROUTE_NAME: 'Layerthorpe_N_Hallfield_Rd' },
    { ROUTE_NAME: 'East_Parade_Heworth_Xroad_ASL' },
    { ROUTE_NAME: 'Heowrth_Vill_East_Parade_ASL' },
    { ROUTE_NAME: 'Heworth_Rd_East_Parade_ASL' },
    { ROUTE_NAME: 'Melrosegate_Heworth_Xroads_ASL' },
    { ROUTE_NAME: 'Melrosegate_THL_Rdbt' },
    { ROUTE_NAME: 'Melrosegate_S_app_to_THL_Rdbt' },
    { ROUTE_NAME: 'Heworth_Rd_app_Magic_Rdbt' },
    { ROUTE_NAME: 'Heworth_Rd_exit_Magic_Rdbt' },
    { ROUTE_NAME: 'Stockton_Ln_Exit_Magio_Rdbt' },
    { ROUTE_NAME: 'Malton_Rd_exit_Magic_Rdbt' },
    { ROUTE_NAME: 'Heworth_Gr_exit_Magic_Rdbt' },
    { ROUTE_NAME: 'Elmfield_Ave_offslip' },
    { ROUTE_NAME: 'Elmfield_Ave_Malton_Rd_ASL' },
    { ROUTE_NAME: 'Malton_Rd_E_Elmfield_ASL' },
    { ROUTE_NAME: 'Malton_Rd_S_New_Ln_ASL' },
    { ROUTE_NAME: 'New_Ln_Malton_Rd_ASL' },
    { ROUTE_NAME: 'Malton_Rd_N_New_Ln_ASL' },
    { ROUTE_NAME: 'Vangarde_access_mid_Jockey_Ln' },
    { ROUTE_NAME: 'Vangarde_access_nr_Rodgers' },
    { ROUTE_NAME: 'Jockey_Ln_E_Kathryn_Ave_ASL' },
    { ROUTE_NAME: 'Kathryn_Ave_Jockey_Ln_ASL' },
    { ROUTE_NAME: 'Jockey_Ln_W_Kathryn_Ave_ASL' },
    { ROUTE_NAME: 'Haxby_Rd_Link_Rd_Rdbt_Bypass' },
    { ROUTE_NAME: 'Hunt_Rd_N_Haleys_terr_ASL' },
    { ROUTE_NAME: 'Hunt_Rd_S_Haleys_Ter_ASL' },
    { ROUTE_NAME: 'Fossway_HaleysTerr_ASL' },
    { ROUTE_NAME: 'Haleys_Ter_Hunt_Rd_ASLs' },
    { ROUTE_NAME: 'Heworth_Grn_on_to_off' },
    { ROUTE_NAME: 'Heworth_Grn_Transco_James_St_Link' },
    { ROUTE_NAME: 'Innovation_Way' },
    { ROUTE_NAME: 'Mill_Ln_N_end' },
    { ROUTE_NAME: 'Jaipur_Spice_Access_to_Hansom_Pl' },
    { ROUTE_NAME: 'Haxby_Rd_Clarence_St_ASL' },
    { ROUTE_NAME: 'Wigg_Rd_Hosp_Toucan' },
    { ROUTE_NAME: 'York_Hosp_link' },
    { ROUTE_NAME: 'Clarence_St_Wigg_Rd_ASL' },
    { ROUTE_NAME: 'Wigg_Rd_S_Crichton_Ave_ASL' },
    { ROUTE_NAME: 'Crichton_Ave_Wigg_Rd_ASL:' },
    { ROUTE_NAME: 'Wigg_Rd_N_Crichton_Ave_ASL' },
    { ROUTE_NAME: 'Bootham_Stray_Wigg_Rd_gated_access' },
    { ROUTE_NAME: 'Wigg_Rd_S_CliftonMG_ASL' },
    { ROUTE_NAME: 'CliftonMG_Wigg_Rd_ASL' },
    { ROUTE_NAME: 'Wigg_Rd_N_CliftonMG_ASL' },
    { ROUTE_NAME: 'CliftonMG_Water_Ln_ASL' },
    { ROUTE_NAME: 'Water_Ln_CliftonMG_ASL' },
    { ROUTE_NAME: 'CliftonMG_W_Water_Lane_ASL' },
    { ROUTE_NAME: 'Wigg_Rd_S_Mill_Ln_ASL' },
    { ROUTE_NAME: 'Wigg_Rd_N_Mill_Ln_ASL' },
    { ROUTE_NAME: 'Mill_Ln_Wigg_Rd_ASL' },
    { ROUTE_NAME: 'St_Helens_Rd_Taddy_Rd_ASL' },
    { ROUTE_NAME: 'Albemarle_Rd_Mount_ASL' },
    { ROUTE_NAME: 'Dalton_Ter_Mount_ASL' },
    { ROUTE_NAME: 'Scarcroft_Rd_Mount_ASL' },
    { ROUTE_NAME: 'E_Mount_Rd' },
    { ROUTE_NAME: 'Scarcroft Lane' },
    { ROUTE_NAME: 'East_Mount_Rd_Scarcroft_Green' },
    { ROUTE_NAME: 'Scarcroft_Hill' },
    { ROUTE_NAME: 'Micklegate_Blossom_St_ASL' },
    { ROUTE_NAME: 'Scarcroft_Rd_Bishy_Rd_ASL' },
    { ROUTE_NAME: 'Bishy_Rd_S_Scarcroft_ASL' },
    { ROUTE_NAME: 'Popp_Rd_Acomb_Rd_ASL' },
    { ROUTE_NAME: 'Popp_Rd_N_HolgatePK_ASL' },
    { ROUTE_NAME: 'Popp_Rd_S_Holgate_Park_ASL' },
    { ROUTE_NAME: 'Popp_Rd_Water_Ln_ASL' },
    { ROUTE_NAME: 'Water_End_Popp_Rd_ASL' },
    { ROUTE_NAME: 'Station_Rs_S_Station_Rd_ASL' },
    { ROUTE_NAME: 'Lendal_Br_Rougier_St_ASL' },
    { ROUTE_NAME: 'Rougier_St_Station_Rd_ASL' },
    { ROUTE_NAME: 'Station_Ave_Rougier_St_ASL' },
    { ROUTE_NAME: 'Museum_St_SLP_ASL' },
    { ROUTE_NAME: 'Clarence_St_Gillygate_ASL' },
    { ROUTE_NAME: 'Lord_Mayors_Wk_Gillygate_ASL' },
    { ROUTE_NAME: 'Coppergate_Piccadilly_ASL' },
    { ROUTE_NAME: 'Micklegate_North_St_ASL' },
    { ROUTE_NAME: 'Bridge_St_North_Ln_ASL' },
    { ROUTE_NAME: 'Micklegate_E_GHS' },
    { ROUTE_NAME: 'Micklegate_W_GHS_ASL' },
    { ROUTE_NAME: 'GHS_Micklegate_ASL' },
    { ROUTE_NAME: 'Barbican_Rd_Hes_Rd_ASL' },
    { ROUTE_NAME: 'Cemetery_Rd_Hes_Rd_ASL' },
    { ROUTE_NAME: 'Retreat Lane_onroad' },
    { ROUTE_NAME: 'Retreat_Hes_Rd_Bypass' },
    { ROUTE_NAME: 'Broadway_Fulf_Rd_ASL' },
    { ROUTE_NAME: 'Tannery_Site_links' },
    { ROUTE_NAME: 'A19_S_of_Des_Out_W' },
    { ROUTE_NAME: 'A19_S_of_Des_Out_E' },
    { ROUTE_NAME: 'A19_between_Rdbts_E' },
    { ROUTE_NAME: 'A19_N_of_Des_Out_E' },
    { ROUTE_NAME: 'Designer Outlet access link path' },
    { ROUTE_NAME: 'Designer Outlet access road splitter' },
    { ROUTE_NAME: 'Clifton_Moor_Linkpath' },
    { ROUTE_NAME: 'MaudsRidding_Link_York_Selby' },
    { ROUTE_NAME: 'NCN65_Acaster_Lane_link' },
    { ROUTE_NAME: 'Cherry Lane on road' },
    { ROUTE_NAME: 'Skipwith Rd link' },
    { ROUTE_NAME: 'James Street' },
    { ROUTE_NAME: 'Wigg_Rd_Rdbt1part2' },
    { ROUTE_NAME: 'NCN 65 Bishopthorpe to Acaster Ln' },
    { ROUTE_NAME: 'NCN65_Acaster_Lane_link' },
    { ROUTE_NAME: 'NCN 65 London Br to Sun Sculp' },
    { ROUTE_NAME: 'Green Lane - Sim Balk Ln to Yrk Selby' },
    { ROUTE_NAME: 'Green Lane - Racecourse to Bishopthrp Rd' },
    { ROUTE_NAME: 'A64 / Tadcaster Road London Br to Tesco' },
    { ROUTE_NAME: 'A64 N Askham Bryan on slip to college path' },
    { ROUTE_NAME: 'A64 N A1237 to Askham Br Coll' },
    { ROUTE_NAME: 'NCN 65 Green Lane to Bishopthrpe Rd_4' },
    { ROUTE_NAME: 'Terry Ave link to Mill Bridge ramp' },
    { ROUTE_NAME: 'Fulford Ings - Mill Br ramp to Hosp Fld Rd link' },
    { ROUTE_NAME: 'Windmill Lane - south of NCN66' },
    { ROUTE_NAME: 'NCN Route 65 NYCC section Skelton' },
    { ROUTE_NAME: 'Almery Terrace to Scarborough Br' },
    { ROUTE_NAME: 'Skeldergate (non NCN section)' },
    { ROUTE_NAME: 'Bootham - Bootham Cres to Bootham Terr' },
    { ROUTE_NAME: 'Goodramgate - Aldwark to Dngte' },
    { ROUTE_NAME: 'Foss_Islands_Rd_W_Nav Rd to toucan' },
    { ROUTE_NAME: 'James_St NCN658 section' },
    { ROUTE_NAME: 'F.I. Line - Trav site link to 5th Ave W access' },
    { ROUTE_NAME: 'NCN66East_Riding_end_of_viaduct' },
    { ROUTE_NAME: 'NCN66 A166 to centre of viaduct' },
    { ROUTE_NAME: 'NCN Route 65 between river and Forth Br' },
    { ROUTE_NAME: 'A64 / Tadcaster Road Cop Rd sigs to Tesco' },
    { ROUTE_NAME: 'Water End to Lincoln St' },
    { ROUTE_NAME: 'Leeman Road crossing' },
    { ROUTE_NAME: 'Holgate Rd Br to Fox pub' },
    { ROUTE_NAME: 'Love Lane Footbridge' },
    { ROUTE_NAME: 'Love Lane off Driff Ter' },
    { ROUTE_NAME: 'Holgate Road_Fox to Bridge' },
    { ROUTE_NAME: 'New_Ln_to_Vangard_MXP&R' },
    { ROUTE_NAME: 'New_Ln_to_Vangard_Vangard' },
    { ROUTE_NAME: 'Malton_Rd_inbound_Straylands_Bus_Gate' },
    { ROUTE_NAME: 'Malton_Rd_inbound_MXRdbt_access_road' },
    { ROUTE_NAME: 'Malton_Rd_Outbound_Elmfield_Laburnum' },
    { ROUTE_NAME: 'Malton_Rd_outbound_Muncastergate_to_Motosave' },
    { ROUTE_NAME: 'Sim Balk Ln_Changing_Rm_Loop' },
    { ROUTE_NAME: 'Green Lane_between_racetracks' },
    { ROUTE_NAME: 'Little_Hob_Moor_ECML_Taddy_Rd' },
    { ROUTE_NAME: 'ORR_James_St_Brinkworth_Lawrence' },
    { ROUTE_NAME: 'ORR_James_St_Elvington_Brinkworth' },
    { ROUTE_NAME: 'NCN 65 Green Lane to Bishopthrpe Rd_2' },
    { ROUTE_NAME: 'NCN 65 Green Lane to Bishopthrpe Rd_3' },
    { ROUTE_NAME: 'Millennium_Br_Terry Ave extension_curved_ramp' },
    { ROUTE_NAME: 'Fulford_Rd_E_OffRd_NYP_Barracks' },
    { ROUTE_NAME: 'Fulford_Rd_E_OffRd_Broadway_Hes_Lane' },
    { ROUTE_NAME: 'Fulford_Rd_E_OffRd_Derwent_Rd_Broadway' },
    { ROUTE_NAME: 'Fulford_Rd_E_OffRd_Moorland_Rd_Derwent_Rd' },
    { ROUTE_NAME: 'Low _Poppleton_Ln_offroad_Boro_speed_table_xing' },
    { ROUTE_NAME: 'Beckfield_Ln_off_rd_Almsford_Ouseburn' },
    { ROUTE_NAME: 'Beckfield_Ln_off_rd_Ouseburn_Lidgett' },
    { ROUTE_NAME: 'Beckfield_Ln_off_rd_Lidgett_Newlands' },
    { ROUTE_NAME: 'Beckfield_Ln_off_rd_Newlands_Borobridge' },
    { ROUTE_NAME: 'Rawcliffe Bar P&R path_1_inc_toucan' },
    { ROUTE_NAME: 'NCN 65 A1237 to Clifton Bridge' },
    { ROUTE_NAME: 'NCN 65 A1237 to Clifton Bridge' },
    { ROUTE_NAME: 'NCN 65 A1237 to Clifton Bridge' },
    { ROUTE_NAME: 'A1237 / A19 rdbt subway path_S' },
    { ROUTE_NAME: 'Shipton_Rd_Manor_Ln_subway_Ramp' },
    { ROUTE_NAME: 'A1237 / A19 rdbt subway path_N' },
    { ROUTE_NAME: 'Wetherby_Rd_Milestone_Ave_Rufforth' },
    { ROUTE_NAME: 'A19_Crockey_Hill_Howden_Ln' },
    { ROUTE_NAME: 'Yk_Selby_Vicarage_Ln_Link_Naburn' },
    { ROUTE_NAME: 'Principal _Rise_Revival_Est_link_E_of_playarea' },
    { ROUTE_NAME: 'Principal_Rise_to_Revival_Est_link_W_of_playarea' },
    { ROUTE_NAME: 'Northfield_Lane_to_Knapton_Main_St' },
    { ROUTE_NAME: 'Huntington_Rd_mandatory_lane' },
    { ROUTE_NAME: 'Scarborough_Bridge_steep_cycle_ramp' },
    { ROUTE_NAME: 'Water_Ln_to_Woodland_Chase' },
    { ROUTE_NAME: 'Water_Ln_link_opp_Aldi' },
    { ROUTE_NAME: 'Green_Ln_Water_Ln_to_end _devt' },
    { ROUTE_NAME: 'Water_End_central feeder_lane_to RSPCA' },
];
