export const cycleRouteData = [
    { name: 'Clifton Moorgate S - Tribune Wy to Water Ln' },
    { name: 'Clifton Moorgate S - Bumpr Cstl to Centur Wy' },
    { name: 'Bumper Castle path' },
    { name: 'Clifton Moorgate N - Eastern' },
    { name: 'Clifton Moorgate N - Western end' },
    { name: 'Manor Lane - Leapfrog to Kensington Rd' },
    { name: 'Northfield Ln West' },
    { name: 'Northfield Ln East' },
    { name: 'Designer Outlet access road path' },
    { name: 'Selby Road A64 junc N to S West' },
    { name: 'Selby Road - Naburn Ln to A64' },
    { name: 'Imphal Barracks path to Walmgate Stry' },
    { name: 'Walmgate Stray path' },
    { name: 'University path from Retreat Ln to Science Pk' },
    { name: 'University path from Heslington Ln to Walmgate Str' },
    { name: 'University path from Retreat Ln to Walmgate Stry' },
    { name: 'Retreat Lane offroad' },
    { name: 'Lawrence St to Regent St link' },
    { name: 'Fulford Ings to St Oswalds Rd link' },
    { name: 'Fulford Ings to Fulford Cross link' },
    { name: 'Fulford Ings to Mill Br ramp' },
    { name: 'New Walk' },
    { name: "New Walk - adj St George's Field" },
    { name: 'South Esplanade' },
    { name: 'Bridge Lane' },
    { name: 'Bootham Hospital route' },
    { name: 'Clifton Br to Almery Terr riverside path' },
    { name: 'Holgate Park southern side of road' },
    { name: 'Holgate Park northern side of road' },
    { name: 'Poppleton Road - Holgate Pk to The Fox' },
    { name: 'Water End shared footway' },
    { name: 'Cinder Lane - Scarbro Br to Jubilee Terr' },
    { name: 'Marygate CP path' },
    { name: 'Scarborough Bridge NCN 65' },
    { name: 'Cinder Lane - Leeman Rd CP to Wilton Rise FB' },
    { name: 'Esplanade - Scarbro Br to York Rowing Club' },
    { name: 'Racecourse road from NCN 65 to Campleshon Rd' },
    { name: 'Terry Ave - Millennium Bridge to Rowntree Pk CP' },
    { name: 'Terry Ave extension' },
    { name: 'NCN 65 Green Lane to Bishopthrpe Rd 1' },
    { name: 'Bishopthorpe Rd - Allotments to Green Lane' },
    { name: 'Little Knavesmire path' },
    { name: 'NCN 65 Green Lane to Yk Selby path' },
    { name: 'Green Lane - YrkSelby Junc Racetrack' },
    { name: 'Sim Balk Lane to 6th form coll x-ing' },
    { name: 'Naburn Lane seage works access to houses' },
    { name: 'Vangard Path Martello Wy Kathryn Ave' },
    { name: 'Wigginton Rd Haxby Rd2' },
    { name: 'Wigginton Rd Haxby Rd1' },
    { name: 'A59 Pop to Beckfld' },
    { name: 'Water Ln Hazelnut Gr' },
    { name: 'Lakeside Way Hes E Pt1' },
    { name: 'Moor Ln N side' },
    { name: 'Fulford Rd E OffRd Barracks Moorland Rd' },
    { name: 'Hungate Br to  Palmers Ln' },
    { name: 'Foss Islands Retail Pk Link' },
    { name: 'James St Hallfield Rd W side' },
    { name: 'Wigg Rd MSCP path' },
    { name: 'Hempland Ln to Stray Road' },
    { name: 'Field Ln N' },
    { name: 'Revival Green Ln N' },
    { name: 'ORR James St Morrisons Elvington' },
    { name: 'Rawcliffe Rec Rawcliffe Lake' },
    { name: 'Beckfield Ln off rd Ostman Almsford' },
    { name: 'Cherry Lane off road' },
    { name: 'Knavesmire track inside racecourse' },
    { name: 'Water End N nr Clifton Br' },
    { name: 'Hull Rd THL Carlton Ave' },
    { name: 'OCR Knavesmire Rd to Pulleyn Dr toucan' },
    { name: 'Acorn Rugby W' },
    { name: 'Malton Rd Outbound New Ln Martello Wy' },
    { name: 'Malton Rd inbound access rd Straylands' },
    { name: 'New Ln to MXP&R' },
    { name: 'Stirling Rd CM Access' },
    { name: 'Haxby Rd underpass southbound' },
    { name: 'Haxby Rd underpass northbound' },
    { name: 'Monks X access W' },
    { name: 'Monks X access E' },
    { name: 'Monks Cross N & W' },
    { name: 'St Nicks Field - Bull Ln to FI Line' },
    { name: 'F.I. Line - City Gym to Hewrth Crft' },
    { name: 'F.I. Line - Haxby Rd to Wigg Rd' },
    { name: 'F.I. Line - White X Gdns to Ashvill St' },
    { name: 'F.I. Line - City Gym to Arran Pl' },
    { name: 'F.I. Line - Hewrth Gr to City Gym' },
    { name: 'F.I. Line - Layrthrpe to Hewrth Gr' },
    { name: 'F.I. Line - Hallfld Rd to Layrthrpe' },
    { name: 'F.I. Line - Hallfld Rd to Trav Site link' },
    { name: 'F.I. Line - St Nicks to Ebor Ind Est' },
    { name: 'F.I. Line - Tang H Ln to Melrsgte' },
    { name: 'F.I. line - Metc Ln to Ambl.' },
    { name: 'Metcalfe Lane N' },
    { name: 'Hagg Farm track to Cowslip Farm' },
    { name: 'Grimstn Br intrchng NW' },
    { name: 'Hull Rd N Rdbt to Bore Tr B' },
    { name: 'Hull Road N Bore Tree B to Yk Rd' },
    { name: 'Grim Bar intchng to Elv Ln' },
    { name: 'Hull Road S P&R to GBar' },
    { name: 'Hull Road N Link Rd to xing' },
    { name: 'Osbaldwick Link Road W' },
    { name: 'Hull Road N adj B&Q' },
    { name: 'Clifton Backies path' },
    { name: 'Lakeside school path' },
    { name: 'NCN 65 A64 Bridge to Appleton Ct' },
    { name: 'A64 S Top Lane underpass' },
    { name: 'A64 S A1237 to St Nich Rd' },
    { name: 'A64 S Boundary to A1237' },
    { name: 'A64 N Ask Bry Coll to Buckles Inn' },
    { name: 'A64 N A1237 off slip to Askham Br Coll' },
    { name: 'A64 N A1237 E to W path' },
    { name: 'A64 N Pikehills to A1237' },
    { name: 'A64 / Tadcaster Road Pikehills to Cop Rd signals' },
    { name: 'Tadcaster Road - path adj to Tesco' },
    { name: 'Lomond Ginnel - Lowick to Moor Ln' },
    { name: 'Bellhouse Way - Wenham Rd to Bellwood Dr' },
    { name: 'Acorn Rugby Club path' },
    { name: 'Green Lane - Hob Moor link' },
    { name: 'Hob Moor KingswayW ECML Subway' },
    { name: 'Woodlea Ave to Danebury Dr link' },
    { name: 'Shipton Road allotments link path' },
    { name: 'Clifton Business Park route' },
    { name: 'NCN 65 A1237 to Clifton Bridge' },
    { name: 'NCN 65 A1237 underpass' },
    { name: 'NCN65 N of A1237 end of riverside N Rawc landing' },
    { name: 'Shipton Road N shared footway' },
    { name: 'A1237 path from Poppleton Park to sewage works' },
    { name: 'Poppleton Park N of E section of Great N Way' },
    { name: 'Millfield Lane shared use path' },
    { name: 'Meadlands to Stockton Lane' },
    { name: 'Stirling Rd' },
    { name: 'Gillygate' },
    { name: 'Hull Rd Inbound P&Rgate to accessrd' },
    { name: 'Yearsley Gr Anthea Dr' },
    { name: 'Brockfield Rd Brockfield Park Dr' },
    { name: 'Stratford Way' },
    { name: 'Tadcaster Rd Copmanthorpe St Nich to bypass' },
    { name: 'Old Askham Ln' },
    { name: 'OCR Melbourne St Hes Rd' },
    { name: 'Fulf Rd onroad' },
    { name: 'Dundas St Palmer Ln' },
    { name: 'Wigginton Rd S' },
    { name: 'Holgate Br onwards inbound' },
    { name: 'Heslington Ln Ph3' },
    { name: 'Heslington Ln SRTS' },
    { name: 'Hope St Gladstone St' },
    { name: 'OCR Green Ln Rdbt York Rd' },
    { name: 'Water End Govt Hs Rd to centre feed' },
    { name: 'OCR Butcher Terr South Bank Ave' },
    { name: 'OCR Albemarle to Count de Burgh' },
    { name: 'Station Rd Queen St Br' },
    { name: 'Alder Wy to Garth Way Offroad' },
    { name: 'Rowan Ave Alder Way' },
    { name: 'Kettlestring Ln Audax Rd' },
    { name: 'City Hosp link to FI Line' },
    { name: 'Monkgate' },
    { name: 'St Leonards Pl' },
    { name: 'Jewbury' },
    { name: 'St Andrewgate' },
    { name: 'Aldwark' },
    { name: 'Peasholme Green' },
    { name: 'Stonebow' },
    { name: 'Piccadilly - Dales Ln to Pavmnt' },
    { name: 'George Street' },
    { name: 'York Road Haxby' },
    { name: 'Haxby Rd - Rowan Ave to A1237' },
    { name: 'Huntington Road - N of Link Rd' },
    { name: 'Huntington Rd - S of Link Rd' },
    { name: 'New Lane - northbound' },
    { name: 'Foss Bank' },
    { name: 'Hewrth Grn - Trnsco to Mag Rdbt' },
    { name: 'Bull Lane' },
    { name: 'Meadlands E' },
    { name: 'Tranby Avenue' },
    { name: 'Osbaldwick village - Metcalfe Ln to Osbldwk Ln' },
    { name: 'Murton Way' },
    { name: 'Murton Lane' },
    { name: 'NCN 66 Bore Tree Baulk' },
    { name: 'Intake Lane Dunnington' },
    { name: 'Common Road Dunnington' },
    { name: 'York Street Dunnington' },
    { name: 'York Road Dunnington' },
    { name: 'Hull Road N Carlton Ave - Field Ln' },
    { name: 'Hull Road bus lane' },
    { name: 'Crichton Avenue' },
    { name: 'Bur Dyke Avenue' },
    { name: 'Fairway' },
    { name: 'Shipton Road service road' },
    { name: 'Bowness Drive' },
    { name: 'Easholme Dr - Bowness to Rawc Ln' },
    { name: 'Rawcliffe Lane - Beaverdyke to Shipton rd' },
    { name: 'Oakdale Road route' },
    { name: 'Manor Lane' },
    { name: 'Thief Lane' },
    { name: 'Windmill Lane - NCN66 section' },
    { name: 'Heslington Road' },
    { name: 'Wellington Street' },
    { name: 'Grange Garth' },
    { name: 'Alma Terrace' },
    { name: 'Hospital Fields Road' },
    { name: 'Maple Grove' },
    { name: 'Broadway West' },
    { name: "St Oswald's Road" },
    { name: 'Lower Friargate' },
    { name: 'North Street NCN 65' },
    { name: 'Marygate - NCN 66' },
    { name: 'Avenue Terrace' },
    { name: 'Burton Stone Lane' },
    { name: 'Grosvenor Road' },
    { name: 'Bootham - Bootham Terr to Gillygate' },
    { name: 'Clifton - Bootham Cres to Rawc Ln' },
    { name: 'Water End - Govt Ho Rd to Clifton' },
    { name: 'Wilton Rise' },
    { name: 'Beech Avenue' },
    { name: 'Water End eastbound lane' },
    { name: 'Nunnery Lane ASL feeder - station bound only' },
    { name: 'Bishopthorpe Road - Scarcroft Rd to Clementhorpe' },
    { name: 'Terry Ave NCN 65 on road sectn' },
    { name: 'Skeldergate (NCN 65 section)' },
    { name: 'Lower Priory Street' },
    { name: 'Thorpe Street' },
    { name: 'Nunthorpe Grove' },
    { name: 'Trafalgar Street' },
    { name: 'Campleshon Road' },
    { name: 'Tadcaster Road - Moor Ln to Dalton Terr' },
    { name: 'Tadcaster Rd - 6th Frm Coll x-ing to Ask Br Rdbt' },
    { name: 'Moor Lane - rdbt to Chaloners Rd' },
    { name: 'Chaloners Road S lanes' },
    { name: 'Ashbourne Way' },
    { name: 'Kingsway West route' },
    { name: 'Green Lane (N) Acomb' },
    { name: 'Beech Grove to York Road, Acomb' },
    { name: 'Milner Street' },
    { name: 'Manor Drive South' },
    { name: 'Lindsey Avenue' },
    { name: 'Low Poppleton Lane' },
    { name: 'Beckfield Lane' },
    { name: 'Viking Road' },
    { name: 'Danebury Drive' },
    { name: 'Carr Lane' },
    { name: 'Boroughbridge Rd Inbound' },
    { name: 'University Road' },
    { name: 'Rufforth to Knapton Ph1' },
    { name: 'Jockey Ln Range to Sainsbury' },
    { name: 'Jockey Ln MartelloWay to Asda Toucan' },
    { name: 'Malton Rd Hopgrove end' },
    { name: 'Malton Rd N of MonksX Rdbt' },
    { name: 'Haxby Rd Bridge' },
    { name: 'Bootham Stray' },
    { name: 'Wigginton Rd Nestle' },
    { name: 'Lilbourne Dr path' },
    { name: 'Kingsway N Cyclepath' },
    { name: 'Walmgate Stray S East' },
    { name: 'Holmfield Lane path' },
    { name: 'Revival Green Ln S' },
    { name: 'OCR Albemarle Brunswick' },
    { name: 'Barbican Mews Regent St Link' },
    { name: 'Nelsons Ln Park' },
    { name: 'Moor Ln Rawcliffe Rec' },
    { name: 'Rawcliffe Lake' },
    { name: 'Alder Way' },
    { name: 'Woodlands Grove' },
    { name: 'Stockton Ln Greenfields To Charles Moor' },
    { name: 'Malton Rd outbound side to Muncastergate' },
    { name: 'Malton Rd Outbound Laburnum New Ln' },
    { name: 'Martello Way MXRdbt to P&R Office' },
    { name: 'Alpha Ct link E Side' },
    { name: 'Haxby Rd to Hunt Village1' },
    { name: 'Haxby Rd to Hunt Village2' },
    { name: 'Hungate Br To George St' },
    { name: 'Long Close Lane' },
    { name: 'Blossom St' },
    { name: 'Askham Ln The Green' },
    { name: 'Hes East Pathway' },
    { name: 'NCN66 Tang Hall Ln' },
    { name: 'York Sport Access Rd' },
    { name: 'Kilburn Rd allotments site' },
    { name: 'Kilburn Rd' },
    { name: 'Askham Bar onsite' },
    { name: 'Askham Bar onsite2' },
    { name: 'Poppleton Bar onsite1' },
    { name: 'Innovation Way' },
    { name: 'E Mount Rd' },
    { name: 'Scarcroft Lane' },
    { name: 'Scarcroft Hill' },
    { name: 'A19 S of Des Out W' },
    { name: 'A19 S of Des Out E' },
    { name: 'A19 between Rdbts E' },
    { name: 'A19 N of Des Out E' },
    { name: 'NCN 65 Bishopthorpe to Acaster Ln' },
    { name: 'NCN 65 London Br to Sun Sculp' },
    { name: 'Green Lane - Sim Balk Ln to Yrk Selby' },
    { name: 'A64 N Askham Bryan on slip to college path' },
    { name: 'A64 N A1237 to Askham Br Coll' },
    { name: 'Windmill Lane - south of NCN66' },
    { name: 'NCN Route 65 NYCC section Skelton' },
    { name: 'NCN Route 65 between river and Forth Br' },
    { name: 'A64 / Tadcaster Road Cop Rd sigs to Tesco' },
    { name: 'Holgate Rd Br to Fox pub' },
    { name: 'Holgate Road Fox to Bridge' },
    { name: 'Malton Rd inbound Straylands Bus Gate' },
    { name: 'Malton Rd outbound Muncastergate to Motosave' },
    { name: 'Little Hob Moor ECML Taddy Rd' },
    { name: 'NCN 65 Green Lane to Bishopthrpe Rd 2' },
    { name: 'Fulford Rd E OffRd Broadway Hes Lane' },
    { name: 'Beckfield Ln off rd Newlands Borobridge' },
    { name: 'NCN 65 A1237 to Clifton Bridge' },
    { name: 'NCN 65 A1237 to Clifton Bridge' },
    { name: 'Wetherby Rd Milestone Ave Rufforth' },
    { name: 'Northfield Lane to Knapton Main St' },
];
