export const cycleCounterData = [
    { RoadName: 'Cinder Lane' },
    { RoadName: 'Crichton Avenue' },
    { RoadName: 'Hob Moor' },
    { RoadName: 'Maple Grove' },
    { RoadName: 'Millennium Bridge' },
    { RoadName: 'A1237 - Shipton Rd & Millfield Lane' },
    { RoadName: 'A1237 - Wigginton Rd to Haxby Rd' },
    { RoadName: 'Rawcliffe Lane' },
    { RoadName: 'Skeldergate Bridge' },
    { RoadName: 'St.Georges Field' },
    { RoadName: 'Terrys' },
    { RoadName: 'A1079 Hull Road' },
    { RoadName: 'James Street Orbital Cycle Track' },
    { RoadName: 'path connecting Tribune Way to Water Lane' },
    { RoadName: 'path connecting Manor Lane to Hurricane Way' },
    { RoadName: 'Oakdale Road South' },
    { RoadName: 'Sterling Road' },
    { RoadName: 'Malton Road (Outbound)' },
    { RoadName: 'Malton Road (Inbound)' },
    { RoadName: 'Beckfield Lane' },
    { RoadName: 'Woodlea Avenue' },
    { RoadName: 'Scarcroft Lane' },
    { RoadName: 'A1079 Lawrence Street' },
    { RoadName: 'Cemetery Road' },
    { RoadName: 'Terry Avenue' },
    { RoadName: 'Millfield Lane' },
    { RoadName: 'A1176 Clifton Bridge' },
    { RoadName: 'A1036 Heworth Green' },
    { RoadName: 'Huntington Road' },
    { RoadName: 'James Street Morrisons' },
    { RoadName: 'Naburn Bridge' },
    { RoadName: 'Scarborough Bridge' },
    { RoadName: 'Almery Terrace' },
    { RoadName: 'Rawcliffe Bar' },
    { RoadName: 'Millfield Lane' },
    { RoadName: 'Windmill Lane' },
    { RoadName: 'Clarence Street' },
    { RoadName: 'Crichton Avenue' },
    { RoadName: 'Retreat Lane' },
    { RoadName: 'Leeman Road' },
    { RoadName: 'Eboracum Way' },
];
