export const cycleRouteData = [
    { name: 'Clifton Moorgate S - Tribune Wy to Water Ln' },
    { name: 'Clifton Moorgate S - Bumpr Cstl to Centur Wy' },
    { name: 'Bumper Castle path' },
    { name: 'Clifton Moorgate N - Eastern' },
    { name: 'Clifton Moorgate N - Western end' },
    { name: 'Manor Lane - Leapfrog to Kensington Rd' },
    { name: 'Northfield Ln West' },
    { name: 'Northfield Ln East' },
    { name: 'Designer Outlet access road path' },
    { name: 'Selby Road A64 junc N to S West' },
    { name: 'Selby Road - Naburn Ln to A64' },
    { name: 'Imphal Barracks path to Walmgate Stry' },
    { name: 'Walmgate Stray path' },
    { name: 'University path from Retreat Ln to Science Pk' },
    { name: 'University path from Heslington Ln to Walmgate Str' },
    { name: 'University path from Retreat Ln to Walmgate Stry' },
    { name: 'Retreat Lane_offroad' },
    { name: 'Lawrence St to Regent St link' },
    { name: 'Fulford Ings to St Oswalds Rd link' },
    { name: 'Fulford Ings to Fulford Cross link' },
    { name: 'Fulford Ings to Mill Br ramp' },
    { name: 'New Walk' },
    { name: "New Walk - adj St George's Field" },
    { name: 'South Esplanade' },
    { name: 'Bridge Lane' },
    { name: 'Bootham Hospital route' },
    { name: 'Clifton Br to Almery Terr riverside path' },
    { name: 'Holgate Park southern side of road' },
    { name: 'Holgate Park northern side of road' },
    { name: 'Poppleton Road - Holgate Pk to The Fox' },
    { name: 'Water End shared footway' },
    { name: 'Cinder Lane - Scarbro Br to Jubilee Terr' },
    { name: 'Marygate CP path' },
    { name: 'Scarborough Bridge NCN 65' },
    { name: 'Cinder Lane - Leeman Rd CP to Wilton Rise FB' },
    { name: 'Esplanade - Scarbro Br to York Rowing Club' },
    { name: 'Racecourse road from NCN 65 to Campleshon Rd' },
    { name: 'Terry Ave - Millennium Bridge to Rowntree Pk CP' },
    { name: 'Terry Ave extension' },
    { name: 'NCN 65 Green Lane to Bishopthrpe Rd_1' },
    { name: 'Bishopthorpe Rd - Allotments to Green Lane' },
    { name: 'Little Knavesmire path' },
    { name: 'NCN 65 Green Lane to Yk Selby path' },
    { name: 'Green Lane - YrkSelby_Junc_Racetrack' },
    { name: 'Sim Balk Lane to 6th form coll x-ing' },
    { name: 'Naburn Lane seage works access to houses' },
    { name: 'Vangard_Path_Martello_Wy_Kathryn_Ave' },
    { name: 'Wigginton_Rd_Haxby_Rd2' },
    { name: 'Wigginton_Rd_Haxby_Rd1' },
    { name: 'A59_Pop_to_Beckfld' },
    { name: 'Water_Ln_Hazelnut_Gr' },
    { name: 'Lakeside_Way_Hes_E_Pt1' },
    { name: 'Moor_Ln_N_side' },
    { name: 'Fulford_Rd_E_OffRd_Barracks_Moorland_Rd' },
    { name: 'Hungate_Br_to _Palmers_Ln' },
    { name: 'Foss_Islands_Retail_Pk_Link' },
    { name: 'James_St_Hallfield_Rd_W_side' },
    { name: 'Wigg_Rd_MSCP_path' },
    { name: 'Hempland Ln to Stray Road' },
    { name: 'Field_Ln_N' },
    { name: 'Revival_Green_Ln_N' },
    { name: 'ORR_James_St_Morrisons_Elvington' },
    { name: 'Rawcliffe_Rec_Rawcliffe_Lake' },
    { name: 'Beckfield_Ln_off_rd_Ostman_Almsford' },
    { name: 'Cherry Lane off road' },
    { name: 'Knavesmire track inside racecourse' },
    { name: 'Water End N nr Clifton Br' },
    { name: 'Hull_Rd_THL_Carlton_Ave' },
    { name: 'OCR Knavesmire Rd to Pulleyn Dr toucan' },
    { name: 'Acorn_Rugby_W' },
    { name: 'Malton_Rd_Outbound_New_Ln_Martello_Wy' },
    { name: 'Malton_Rd_inbound_access_rd_Straylands' },
    { name: 'New_Ln_to_MXP&R' },
    { name: 'Stirling_Rd_CM_Access' },
    { name: 'Haxby Rd underpass southbound' },
    { name: 'Haxby Rd underpass northbound' },
    { name: 'Monks X access W' },
    { name: 'Monks X access E' },
    { name: 'Monks Cross N & W' },
    { name: 'St Nicks Field - Bull Ln to FI Line' },
    { name: 'F.I. Line - City Gym to Hewrth Crft' },
    { name: 'F.I. Line - Haxby Rd to Wigg Rd' },
    { name: 'F.I. Line - White X Gdns to Ashvill St' },
    { name: 'F.I. Line - City Gym to Arran Pl' },
    { name: 'F.I. Line - Hewrth Gr to City Gym' },
    { name: 'F.I. Line - Layrthrpe to Hewrth Gr' },
    { name: 'F.I. Line - Hallfld Rd to Layrthrpe' },
    { name: 'F.I. Line - Hallfld Rd to Trav Site link' },
    { name: 'F.I. Line - St Nicks to Ebor Ind Est' },
    { name: 'F.I. Line - Tang H Ln to Melrsgte' },
    { name: 'F.I. line - Metc Ln to Ambl.' },
    { name: 'Metcalfe Lane N' },
    { name: 'Hagg Farm track to Cowslip Farm' },
    { name: 'Grimstn Br intrchng NW' },
    { name: 'Hull Rd N Rdbt to Bore Tr B' },
    { name: 'Hull Road N Bore Tree B to Yk Rd' },
    { name: 'Grim Bar intchng to Elv Ln' },
    { name: 'Hull Road S P&R to GBar' },
    { name: 'Hull Road N Link Rd to xing' },
    { name: 'Osbaldwick Link Road W' },
    { name: 'Hull Road N adj B&Q' },
    { name: 'Clifton Backies path' },
    { name: 'Lakeside school path' },
    { name: 'NCN 65 A64 Bridge to Appleton Ct' },
    { name: 'A64 S Top Lane underpass' },
    { name: 'A64 S A1237 to St Nich Rd' },
    { name: 'A64 S Boundary to A1237' },
    { name: 'A64 N Ask Bry Coll to Buckles Inn' },
    { name: 'A64 N A1237 off slip to Askham Br Coll' },
    { name: 'A64 N A1237 E to W path' },
    { name: 'A64 N Pikehills to A1237' },
    { name: 'A64 / Tadcaster Road Pikehills to Cop Rd signals' },
    { name: 'Tadcaster Road - path adj to Tesco' },
    { name: 'Lomond Ginnel - Lowick to Moor Ln' },
    { name: 'Bellhouse Way - Wenham Rd to Bellwood Dr' },
    { name: 'Acorn Rugby Club path' },
    { name: 'Green Lane - Hob Moor link' },
    { name: 'Hob Moor_KingswayW_ECML_Subway' },
    { name: 'Woodlea Ave to Danebury Dr link' },
    { name: 'Shipton Road allotments link path' },
    { name: 'Clifton Business Park route' },
    { name: 'NCN 65 A1237 to Clifton Bridge' },
    { name: 'NCN 65 A1237 underpass' },
    { name: 'NCN65 N of A1237 end of riverside N Rawc landing' },
    { name: 'Shipton Road N shared footway' },
    { name: 'A1237 path from Poppleton Park to sewage works' },
    { name: 'Poppleton Park N of E section of Great N Way' },
    { name: 'Millfield Lane shared use path' },
    { name: 'Meadlands to Stockton Lane' },
    { name: 'Stirling_Rd' },
    { name: 'Gillygate' },
    { name: 'Hull_Rd_Inbound_P&Rgate_to_accessrd' },
    { name: 'Yearsley Gr Anthea Dr' },
    { name: 'Brockfield Rd Brockfield Park Dr' },
    { name: 'Stratford Way' },
    { name: 'Tadcaster Rd Copmanthorpe St Nich to bypass' },
    { name: 'Old_Askham_Ln' },
    { name: 'OCR_Melbourne_St_Hes_Rd' },
    { name: 'Fulf_Rd_onroad' },
    { name: 'Dundas St Palmer Ln' },
    { name: 'Wigginton_Rd_S' },
    { name: 'Holgate_Br_onwards_inbound' },
    { name: 'Heslington_Ln_Ph3' },
    { name: 'Heslington_Ln_SRTS' },
    { name: 'Hope_St_Gladstone_St' },
    { name: 'OCR_Green_Ln_Rdbt_York_Rd' },
    { name: 'Water End Govt Hs Rd to centre feed' },
    { name: 'OCR Butcher Terr South Bank Ave' },
    { name: 'OCR_Albemarle_to_Count_de_Burgh' },
    { name: 'Station_Rd_Queen_St_Br' },
    { name: 'Alder_Wy_to_Garth_Way_Offroad' },
    { name: 'Rowan Ave Alder Way' },
    { name: 'Kettlestring_Ln_Audax_Rd' },
    { name: 'City Hosp link to FI Line' },
    { name: 'Monkgate' },
    { name: 'St Leonards Pl' },
    { name: 'Jewbury' },
    { name: 'St Andrewgate' },
    { name: 'Aldwark' },
    { name: 'Peasholme Green' },
    { name: 'Stonebow' },
    { name: 'Piccadilly - Dales Ln to Pavmnt' },
    { name: 'George Street' },
    { name: 'York Road Haxby' },
    { name: 'Haxby Rd - Rowan Ave to A1237' },
    { name: 'Huntington Road - N of Link Rd' },
    { name: 'Huntington Rd - S of Link Rd' },
    { name: 'New Lane - northbound' },
    { name: 'Foss Bank' },
    { name: 'Hewrth Grn - Trnsco to Mag Rdbt' },
    { name: 'Bull Lane' },
    { name: 'Meadlands E' },
    { name: 'Tranby Avenue' },
    { name: 'Osbaldwick village - Metcalfe Ln to Osbldwk Ln' },
    { name: 'Murton Way' },
    { name: 'Murton Lane' },
    { name: 'NCN 66 Bore Tree Baulk' },
    { name: 'Intake Lane Dunnington' },
    { name: 'Common Road Dunnington' },
    { name: 'York Street Dunnington' },
    { name: 'York Road Dunnington' },
    { name: 'Hull Road N Carlton Ave - Field Ln' },
    { name: 'Hull Road bus lane' },
    { name: 'Crichton Avenue' },
    { name: 'Bur Dyke Avenue' },
    { name: 'Fairway' },
    { name: 'Shipton Road service road' },
    { name: 'Bowness Drive' },
    { name: 'Easholme Dr - Bowness to Rawc Ln' },
    { name: 'Rawcliffe Lane - Beaverdyke to Shipton rd' },
    { name: 'Oakdale Road route' },
    { name: 'Manor Lane' },
    { name: 'Thief Lane' },
    { name: 'Windmill Lane - NCN66 section' },
    { name: 'Heslington Road' },
    { name: 'Wellington Street' },
    { name: 'Grange Garth' },
    { name: 'Alma Terrace' },
    { name: 'Hospital Fields Road' },
    { name: 'Maple Grove' },
    { name: 'Broadway West' },
    { name: "St Oswald's Road" },
    { name: 'Lower Friargate' },
    { name: 'North Street NCN 65' },
    { name: 'Marygate - NCN 66' },
    { name: 'Avenue Terrace' },
    { name: 'Burton Stone Lane' },
    { name: 'Grosvenor Road' },
    { name: 'Bootham - Bootham Terr to Gillygate' },
    { name: 'Clifton - Bootham Cres to Rawc Ln' },
    { name: 'Water End - Govt Ho Rd to Clifton' },
    { name: 'Wilton Rise' },
    { name: 'Beech Avenue' },
    { name: 'Water_End_eastbound_lane' },
    { name: 'Nunnery Lane ASL feeder - station bound only' },
    { name: 'Bishopthorpe Road - Scarcroft Rd to Clementhorpe' },
    { name: 'Terry Ave NCN 65 on road sectn' },
    { name: 'Skeldergate (NCN 65 section)' },
    { name: 'Lower Priory Street' },
    { name: 'Thorpe Street' },
    { name: 'Nunthorpe Grove' },
    { name: 'Trafalgar Street' },
    { name: 'Campleshon Road' },
    { name: 'Tadcaster Road - Moor Ln to Dalton Terr' },
    { name: 'Tadcaster Rd - 6th Frm Coll x-ing to Ask Br Rdbt' },
    { name: 'Moor Lane - rdbt to Chaloners Rd' },
    { name: 'Chaloners Road S lanes' },
    { name: 'Ashbourne Way' },
    { name: 'Kingsway West route' },
    { name: 'Green Lane (N) Acomb' },
    { name: 'Beech Grove to York Road, Acomb' },
    { name: 'Milner Street' },
    { name: 'Manor Drive South' },
    { name: 'Lindsey Avenue' },
    { name: 'Low Poppleton Lane' },
    { name: 'Beckfield Lane' },
    { name: 'Viking Road' },
    { name: 'Danebury Drive' },
    { name: 'Carr Lane' },
    { name: 'Boroughbridge_Rd_Inbound' },
    { name: 'University_Road' },
    { name: 'Rufforth_to_Knapton_Ph1' },
    { name: 'Jockey_Ln_Range_to_Sainsbury' },
    { name: 'Jockey_Ln_MartelloWay_to_Asda_Toucan' },
    { name: 'Malton_Rd_Hopgrove_end' },
    { name: 'Malton_Rd_N_of_MonksX_Rdbt' },
    { name: 'Haxby_Rd_Bridge' },
    { name: 'Bootham_Stray' },
    { name: 'Wigginton_Rd_Nestle' },
    { name: 'Lilbourne_Dr_path' },
    { name: 'Kingsway_N_Cyclepath' },
    { name: 'Walmgate_Stray_S_East' },
    { name: 'Holmfield_Lane_path' },
    { name: 'Revival_Green_Ln_S' },
    { name: 'OCR_Albemarle_Brunswick' },
    { name: 'Barbican_Mews_Regent_St_Link' },
    { name: 'Nelsons_Ln_Park' },
    { name: 'Moor_Ln_Rawcliffe_Rec' },
    { name: 'Rawcliffe_Lake' },
    { name: 'Alder_Way' },
    { name: 'Woodlands Grove' },
    { name: 'Stockton_Ln_Greenfields_To_Charles_Moor' },
    { name: 'Malton_Rd_outbound_side_to_Muncastergate' },
    { name: 'Malton_Rd_Outbound_Laburnum_New_Ln' },
    { name: 'Martello_Way_MXRdbt_to_P&R_Office' },
    { name: 'Alpha_Ct_link_E_Side' },
    { name: 'Haxby_Rd_to_Hunt_Village1' },
    { name: 'Haxby_Rd_to_Hunt_Village2' },
    { name: 'Hungate_Br_To_George_St' },
    { name: 'Long_Close_Lane' },
    { name: 'Blossom_St' },
    { name: 'Askham_Ln_The_Green' },
    { name: 'Hes_East_Pathway' },
    { name: 'NCN66_Tang_Hall_Ln' },
    { name: 'York_Sport_Access_Rd' },
    { name: 'Kilburn_Rd_allotments_site' },
    { name: 'Kilburn_Rd' },
    { name: 'Askham_Bar_onsite' },
    { name: 'Askham_Bar_onsite2' },
    { name: 'Poppleton_Bar_onsite1' },
    { name: 'Innovation_Way' },
    { name: 'E_Mount_Rd' },
    { name: 'Scarcroft Lane' },
    { name: 'Scarcroft_Hill' },
    { name: 'A19_S_of_Des_Out_W' },
    { name: 'A19_S_of_Des_Out_E' },
    { name: 'A19_between_Rdbts_E' },
    { name: 'A19_N_of_Des_Out_E' },
    { name: 'NCN 65 Bishopthorpe to Acaster Ln' },
    { name: 'NCN 65 London Br to Sun Sculp' },
    { name: 'Green Lane - Sim Balk Ln to Yrk Selby' },
    { name: 'A64 N Askham Bryan on slip to college path' },
    { name: 'A64 N A1237 to Askham Br Coll' },
    { name: 'Windmill Lane - south of NCN66' },
    { name: 'NCN Route 65 NYCC section Skelton' },
    { name: 'NCN Route 65 between river and Forth Br' },
    { name: 'A64 / Tadcaster Road Cop Rd sigs to Tesco' },
    { name: 'Holgate Rd Br to Fox pub' },
    { name: 'Holgate Road_Fox to Bridge' },
    { name: 'Malton_Rd_inbound_Straylands_Bus_Gate' },
    { name: 'Malton_Rd_outbound_Muncastergate_to_Motosave' },
    { name: 'Little_Hob_Moor_ECML_Taddy_Rd' },
    { name: 'NCN 65 Green Lane to Bishopthrpe Rd_2' },
    { name: 'Fulford_Rd_E_OffRd_Broadway_Hes_Lane' },
    { name: 'Beckfield_Ln_off_rd_Newlands_Borobridge' },
    { name: 'NCN 65 A1237 to Clifton Bridge' },
    { name: 'NCN 65 A1237 to Clifton Bridge' },
    { name: 'Wetherby_Rd_Milestone_Ave_Rufforth' },
    { name: 'Northfield_Lane_to_Knapton_Main_St' },
];
