export function getData() {
    return [
        { initiative: 'Online co-op', effort: 8.4, impact: 9.1 },
        { initiative: 'Invert camera axis', effort: 1.4, impact: 6.2 },
        { initiative: 'VR support', effort: 7.2, impact: 1.4 },
        { initiative: 'Weapon skins', effort: 3.6, impact: 4.4 },
        { initiative: 'Seamless open world', effort: 9.6, impact: 8.8 },
        { initiative: 'Checkpoint autosave', effort: 3.8, impact: 8.2 },
        { initiative: 'Mod marketplace', effort: 9.4, impact: 4.2 },
        { initiative: 'Emote wheel', effort: 2.2, impact: 2.4 },
        { initiative: 'Combat overhaul', effort: 6.8, impact: 9.4 },
        { initiative: 'Skippable cutscenes', effort: 1.8, impact: 6.9 },
        { initiative: 'Level editor', effort: 8.6, impact: 3.8 },
        { initiative: 'Collectible codex', effort: 2.8, impact: 3.1 },
        { initiative: 'Base building', effort: 7.4, impact: 8.6 },
        { initiative: 'Photo mode', effort: 3.4, impact: 7.8 },
        { initiative: 'Voice command casting', effort: 9.1, impact: 1.9 },
        { initiative: 'New game plus', effort: 4.2, impact: 4.8 },
        { initiative: 'Console port', effort: 8.8, impact: 8.4 },
        { initiative: 'Remappable controls', effort: 2.6, impact: 7.1 },
        { initiative: 'Dedicated servers', effort: 8.2, impact: 3.4 },
        { initiative: 'Credits easter egg', effort: 1.1, impact: 1.8 },
        { initiative: 'Cross-platform play', effort: 9.2, impact: 7.6 },
        { initiative: 'Colourblind palettes', effort: 2.9, impact: 7.4 },
        { initiative: 'Ragdoll physics polish', effort: 6.4, impact: 2.2 },
        { initiative: 'Pet companions', effort: 4.6, impact: 4.2 },
        { initiative: 'Full voice acting', effort: 7.8, impact: 6.8 },
        { initiative: 'Subtitle size options', effort: 1.2, impact: 6.4 },
        { initiative: 'Daily login rewards', effort: 6.8, impact: 2.8 },
        { initiative: 'Main menu parallax', effort: 0.6, impact: 0.9 },
        { initiative: 'Dynamic weather', effort: 6.2, impact: 7.2 },
        { initiative: 'Loading screen tips', effort: 2.1, impact: 5.8 },
        { initiative: 'In-game movie editor', effort: 9.8, impact: 3.2 },
        { initiative: 'Title screen remix', effort: 1.6, impact: 1.2 },
    ];
}
