export function getBenchmark1Data() {
    return [
        {
            name: 'b9.3.0',
            timeMs: 29.4,
            memoryUsage: 20,
            heapUsed: 18,
            canvasCount: 11,
            canvasBytes: 21,
        },
        {
            name: 'b10.0.0',
            timeMs: 37.1,
            memoryUsage: 21,
            heapUsed: 19,
            canvasCount: 14,
            canvasBytes: 21,
        },
        {
            name: 'b10.1.0',
            timeMs: 43.3,
            memoryUsage: 18,
            heapUsed: 16,
            canvasCount: 20,
            canvasBytes: 21,
        },
        {
            name: 'b10.2.0',
            timeMs: 43.4,
            memoryUsage: 18,
            heapUsed: 16,
            canvasCount: 19,
            canvasBytes: 21,
        },
        {
            name: 'b10.3.0',
            timeMs: 42.9,
            memoryUsage: 18,
            heapUsed: 16,
            canvasCount: 19,
            canvasBytes: 21,
        },
        {
            name: 'b11.0.0',
            timeMs: 31.7,
            memoryUsage: 17,
            heapUsed: 15,
            canvasCount: 38,
            canvasBytes: 23,
        },
        {
            name: 'b11.1.0',
            timeMs: 32.8,
            memoryUsage: 17,
            heapUsed: 15,
            canvasCount: 30,
            canvasBytes: 23,
        },
        {
            name: 'b11.2.1',
            timeMs: 31.7,
            memoryUsage: 16,
            heapUsed: 15,
            relativeUsage: 15,
            canvasCount: 12,
            canvasBytes: 57,
        },
        {
            name: 'latest',
            timeMs: 33.2,
            memoryUsage: 15,
            heapUsed: 15,
            relativeUsage: 15,
            canvasCount: 12,
            canvasBytes: 57,
        },
    ];
}

export function getBenchmark2Data() {
    return [
        {
            name: 'b9.3.0',
            timeMs: 11.2,
            memoryUsage: 20,
            heapUsed: 18,
            canvasCount: 9,
            canvasBytes: 17,
        },
        {
            name: 'b10.0.0',
            timeMs: 59.3,
            memoryUsage: 21,
            heapUsed: 19,
            canvasCount: 10,
            canvasBytes: 19,
        },
        {
            name: 'b10.1.0',
            timeMs: 61.1,
            memoryUsage: 18,
            heapUsed: 16,
            canvasCount: 11,
            canvasBytes: 19,
        },
        {
            name: 'b10.2.0',
            timeMs: 62.3,
            memoryUsage: 18,
            heapUsed: 16,
            canvasCount: 11,
            canvasBytes: 19,
        },
        {
            name: 'b10.3.0',
            timeMs: 62.6,
            memoryUsage: 18,
            heapUsed: 16,
            canvasCount: 11,
            canvasBytes: 19,
        },
        {
            name: 'b11.0.0',
            timeMs: 66.0,
            memoryUsage: 15,
            heapUsed: 15,
            canvasCount: 32,
            canvasBytes: 38,
        },
        // {
        //     name: 'b11.1.0',
        //     timeMs: 32.8,
        //     memoryUsage: 17,
        //     heapUsed: 15,
        //     canvasCount: 30,
        //     canvasBytes: 23,
        // },
        {
            name: 'b11.2.1',
            timeMs: 56.7,
            memoryUsage: 16,
            heapUsed: 15,
            relativeUsage: 50,
            canvasCount: 11,
            canvasBytes: 38,
        },
        {
            name: 'latest',
            timeMs: 56.4,
            memoryUsage: 15,
            heapUsed: 15,
            relativeUsage: 50,
            canvasCount: 11,
            canvasBytes: 38,
        },
    ];
}
