//Source: https://datacatalog.worldbank.org/search/dataset/0037712andor
export const currencyData = [
    { name: 'Aruba', currency: 'Aruban florin' },
    { name: 'Afghanistan', currency: 'Afghan afghani' },
    { name: 'Angola', currency: 'Angolan kwanza' },
    { name: 'Albania', currency: 'Albanian lek' },
    { name: 'United Arab Emirates', currency: 'U.A.E. dirham' },
    { name: 'Argentina', currency: 'Argentine peso' },
    { name: 'Armenia', currency: 'Armenian dram' },
    { name: 'Australia', currency: 'Australian dollar' },
    { name: 'Austria', currency: 'Euro' },
    { name: 'Azerbaijan', currency: 'New Azeri manat' },
    { name: 'Burundi', currency: 'Burundi franc' },
    { name: 'Belgium', currency: 'Euro' },
    { name: 'Benin', currency: 'West African CFA franc' },
    { name: 'Burkina Faso', currency: 'West African CFA franc' },
    { name: 'Bangladesh', currency: 'Bangladeshi taka' },
    { name: 'Bulgaria', currency: 'Bulgarian lev' },
    { name: 'Bosnia and Herzegovina', currency: 'Bosnia and Herzegovina convertible mark' },
    { name: 'Belarus', currency: 'Belarusian rubel' },
    { name: 'Belize', currency: 'Belize dollar' },
    { name: 'Bolivia', currency: 'Bolivian Boliviano' },
    { name: 'Brazil', currency: 'Brazilian real' },
    { name: 'Brunei', currency: 'Brunei dollar' },
    { name: 'Bhutan', currency: 'Bhutanese ngultrum' },
    { name: 'Botswana', currency: 'Botswana pula' },
    { name: 'Central African Republic', currency: 'Central African CFA franc' },
    { name: 'Canada', currency: 'Canadian dollar' },
    { name: 'Switzerland', currency: 'Swiss franc' },
    { name: 'Chile', currency: 'Chilean peso' },
    { name: 'China', currency: 'Chinese yuan' },
    { name: 'Cameroon', currency: 'Central African CFA franc' },
    { name: 'Congo', currency: 'Central African CFA franc' },
    { name: 'Colombia', currency: 'Colombian peso' },
    { name: 'Cabo Verde', currency: 'Cabo Verde escudo' },
    { name: 'Costa Rica', currency: 'Costa Rican colon' },
    { name: 'Cuba', currency: 'Cuban peso' },
    { name: 'Curaçao', currency: 'Netherlands Antillean guilder' },
    { name: 'Cyprus', currency: 'Euro' },
    { name: 'Czechia', currency: 'Czech koruna' },
    { name: 'Germany', currency: 'Euro' },
    { name: 'Djibouti', currency: 'Djibouti franc' },
    { name: 'Denmark', currency: 'Danish krone' },
    { name: 'Algeria', currency: 'Algerian dinar' },
    { name: 'Ecuador', currency: 'U.S. dollar' },
    { name: 'Egypt', currency: 'Egyptian pound' },
    { name: 'Eritrea', currency: 'Eritrean nakfa' },
    { name: 'Spain', currency: 'Euro' },
    { name: 'Estonia', currency: 'Euro' },
    { name: 'Ethiopia', currency: 'Ethiopian birr' },
    { name: 'Finland', currency: 'Euro' },
    { name: 'Fiji', currency: 'Fijian dollar' },
    { name: 'France', currency: 'Euro' },
    { name: 'Faroe Islands', currency: 'Danish krone' },
    { name: 'Gabon', currency: 'Central African CFA franc' },
    { name: 'United Kingdom', currency: 'Pound sterling' },
    { name: 'Georgia', currency: 'Georgian lari' },
    { name: 'Ghana', currency: 'New Ghanaian cedi' },
    { name: 'Guinea', currency: 'Guinean franc' },
    { name: 'The Gambia', currency: 'Gambian dalasi' },
    { name: 'Guinea-Bissau', currency: 'West African CFA franc' },
    { name: 'Equatorial Guinea', currency: 'Central African CFA franc' },
    { name: 'Greece', currency: 'Euro' },
    { name: 'Greenland', currency: 'Danish krone' },
    { name: 'Guatemala', currency: 'Guatemalan quetzal' },
    { name: 'Guyana', currency: 'Guyana dollar' },
    { name: 'Honduras', currency: 'Honduran lempira' },
    { name: 'Croatia', currency: 'Euro' },
    { name: 'Haiti', currency: 'Haitian gourde' },
    { name: 'Hungary', currency: 'Hungarian forint' },
    { name: 'Indonesia', currency: 'Indonesian rupiah' },
    { name: 'India', currency: 'Indian rupee' },
    { name: 'Ireland', currency: 'Euro' },
    { name: 'Iran', currency: 'Iranian rial' },
    { name: 'Iraq', currency: 'Iraqi dinar' },
    { name: 'Iceland', currency: 'Iceland krona' },
    { name: 'Israel', currency: 'Israeli new shekel' },
    { name: 'Italy', currency: 'Euro' },
    { name: 'Jamaica', currency: 'Jamaican dollar' },
    { name: 'Jordan', currency: 'Jordanian dinar' },
    { name: 'Japan', currency: 'Japanese yen' },
    { name: 'Kazakhstan', currency: 'Kazakh tenge' },
    { name: 'Kenya', currency: 'Kenyan shilling' },
    { name: 'Kyrgyz Republic', currency: 'Kyrgyz som' },
    { name: 'Cambodia', currency: 'Cambodian riel' },
    { name: 'Korea', currency: 'Korean won' },
    { name: 'Kuwait', currency: 'Kuwaiti dinar' },
    { name: 'Lao PDR', currency: 'Lao kip' },
    { name: 'Lebanon', currency: 'Lebanese pound' },
    { name: 'Liberia', currency: 'Liberian dollar' },
    { name: 'Libya', currency: 'Libyan dinar' },
    { name: 'Sri Lanka', currency: 'Sri Lankan rupee' },
    { name: 'Lesotho', currency: 'Lesotho loti' },
    { name: 'Lithuania', currency: 'Euro' },
    { name: 'Luxembourg', currency: 'Euro' },
    { name: 'Latvia', currency: 'Euro' },
    { name: 'Macao SAR, China', currency: 'Macao pataca' },
    { name: 'Morocco', currency: 'Moroccan dirham' },
    { name: 'Moldova', currency: 'Moldovan leu' },
    { name: 'Madagascar', currency: 'Malagasy ariary' },
    { name: 'Maldives', currency: 'Maldivian rufiyaa' },
    { name: 'Mexico', currency: 'Mexican peso' },
    { name: 'North Macedonia', currency: 'Macedonian denar' },
    { name: 'Mali', currency: 'West African CFA franc' },
    { name: 'Myanmar', currency: 'Myanmar kyat' },
    { name: 'Montenegro', currency: 'Euro' },
    { name: 'Mongolia', currency: 'Mongolian tugrik' },
    { name: 'Mozambique', currency: 'New Mozambican metical' },
    { name: 'Mauritania', currency: 'Mauritanian ouguiya' },
    { name: 'Malawi', currency: 'Malawi kwacha' },
    { name: 'Malaysia', currency: 'Malaysian ringgit' },
    { name: 'Namibia', currency: 'Namibian dollar' },
    { name: 'New Caledonia', currency: 'CFP franc' },
    { name: 'Niger', currency: 'West African CFA franc' },
    { name: 'Nigeria', currency: 'Nigerian naira' },
    { name: 'Nicaragua', currency: 'Nicaraguan gold cordoba' },
    { name: 'Netherlands', currency: 'Euro' },
    { name: 'Norway', currency: 'Norwegian krone' },
    { name: 'Nepal', currency: 'Nepalese rupee' },
    { name: 'New Zealand', currency: 'New Zealand dollar' },
    { name: 'Oman', currency: 'Omani rial' },
    { name: 'Pakistan', currency: 'Pakistani rupee' },
    { name: 'Panama', currency: 'Panamanian balboa' },
    { name: 'Peru', currency: 'Peruvian new sol' },
    { name: 'Philippines', currency: 'Philippine peso' },
    { name: 'Papua New Guinea', currency: 'Papua New Guinea kina' },
    { name: 'Poland', currency: 'Polish zloty' },
    { name: "Dem. People's Rep. Korea", currency: "Democratic People's Republic of Korean won" },
    { name: 'Portugal', currency: 'Euro' },
    { name: 'Paraguay', currency: 'Paraguayan guarani' },
    { name: 'West Bank and Gaza', currency: 'Israeli new shekel' },
    { name: 'Qatar', currency: 'Qatari riyal' },
    { name: 'Romania', currency: 'New Romanian leu' },
    { name: 'Russia', currency: 'Russian ruble' },
    { name: 'Rwanda', currency: 'Rwandan franc' },
    { name: 'Saudi Arabia', currency: 'Saudi Arabian riyal' },
    { name: 'Sudan', currency: 'Sudanese pound' },
    { name: 'Senegal', currency: 'West African CFA franc' },
    { name: 'Sierra Leone', currency: 'Sierra Leonean leone' },
    { name: 'El Salvador', currency: 'U.S. dollar' },
    { name: 'Somalia', currency: 'Somali shilling' },
    { name: 'Serbia', currency: 'New Serbian dinar' },
    { name: 'South Sudan', currency: 'South Sudanese Pound' },
    { name: 'São Tomé and Principe', currency: 'São Tomé and Principe dobra' },
    { name: 'Suriname', currency: 'Suriname dollar' },
    { name: 'Slovenia', currency: 'Euro' },
    { name: 'Sweden', currency: 'Swedish krona' },
    { name: 'Eswatini', currency: 'Swazi lilangeni' },
    { name: 'Sint Maarten (Dutch part)', currency: 'Netherlands Antillean guilder' },
    { name: 'Chad', currency: 'Central African CFA franc' },
    { name: 'Togo', currency: 'West African CFA franc' },
    { name: 'Thailand', currency: 'Thai baht' },
    { name: 'Tajikistan', currency: 'Tajik somoni' },
    { name: 'Turkmenistan', currency: 'New Turkmen manat' },
    { name: 'Tonga', currency: "Tongan pa'anga" },
    { name: 'Tunisia', currency: 'Tunisian dinar' },
    { name: 'Türkiye', currency: 'New Turkish lira' },
    { name: 'Tanzania', currency: 'Tanzanian shilling' },
    { name: 'Uganda', currency: 'Ugandan shilling' },
    { name: 'Ukraine', currency: 'Ukrainian hryvnia' },
    { name: 'Uruguay', currency: 'Uruguayan peso' },
    { name: 'United States', currency: 'U.S. dollar' },
    { name: 'Uzbekistan', currency: 'Uzbek som' },
    { name: 'Venezuela', currency: 'Venezuelan bolivar fuerte' },
    { name: 'Viet Nam', currency: 'Vietnamese dong' },
    { name: 'Vanuatu', currency: 'Vanuatu vatu' },
    { name: 'Samoa', currency: 'Samoan tala' },
    { name: 'Yemen', currency: 'Yemeni rial' },
    { name: 'South Africa', currency: 'South African rand' },
    { name: 'Zambia', currency: 'New Zambian kwacha' },
    { name: 'Zimbabwe', currency: 'Zimbabwean Dollar' },
];

export function getCurrencyData(currency: string) {
    return currencyData.filter((x) => x.currency.toLowerCase().includes(currency));
}
