import { AgChartOptions, AgCharts } from 'ag-charts-enterprise';

import { currencyData, getCurrencyData } from './data';
import { cables, capitals, topology } from './topology';

const options: AgChartOptions = {
    container: document.getElementById('myChart'),
    topology,
    series: [
        {
            type: 'map-shape-background',
        },
        {
            type: 'map-shape',
            legendItemName: 'Shapes',
            title: 'Other Currency',
            // fillOpacity: 0.7,
            stroke: 'rgb(246,255,255)',
            data: topology.features.map((t: any) => {
                const { name } = t.properties;
                return { name };
            }),
            idKey: 'name',
            fill: '#BBDEFB',
        },
        {
            type: 'map-shape',
            legendItemName: 'Shapes',
            showInLegend: false,
            fillOpacity: 0.7,
            stroke: 'rgb(246,255,255)',
            title: 'Dollar',
            idKey: 'name',
            data: getCurrencyData('dollar'),
            fill: '#FFCCBC',
        },
        {
            type: 'map-shape',
            legendItemName: 'Shapes',
            showInLegend: false,
            fillOpacity: 0.7,
            stroke: 'rgb(246,255,255)',
            title: 'Euro',
            idKey: 'name',
            data: getCurrencyData('euro'),
            fill: '#DCEDC8',
        },
        {
            type: 'map-shape',
            legendItemName: 'Shapes',
            showInLegend: false,
            fillOpacity: 0.7,
            stroke: 'rgb(246,255,255)',
            title: 'Franc',
            idKey: 'name',
            data: getCurrencyData('franc'),
            fill: '#B2EBF2',
        },
        {
            type: 'map-shape',
            legendItemName: 'Shapes',
            showInLegend: false,
            fillOpacity: 0.7,
            stroke: 'rgb(246,255,255)',
            title: 'Pound',
            idKey: 'name',
            data: getCurrencyData('pound'),
            fill: '#FFE0B2',
        },
        {
            type: 'map-shape',
            legendItemName: 'Shapes',
            showInLegend: false,
            fillOpacity: 0.7,
            stroke: 'rgb(246,255,255)',
            title: 'Dinar',
            idKey: 'name',
            data: getCurrencyData('dinar'),
            fill: '#E1BEE7',
        },
        {
            type: 'map-shape',
            legendItemName: 'Shapes',
            showInLegend: false,
            fillOpacity: 0.7,
            stroke: 'rgb(246,255,255)',
            title: 'Peso',
            idKey: 'name',
            data: getCurrencyData('peso'),
            fill: '#CFD8DC',
        },
        {
            type: 'map-shape',
            legendItemName: 'Shapes',
            showInLegend: false,
            fillOpacity: 0.7,
            stroke: 'rgb(246,255,255)',
            title: 'Rupee',
            idKey: 'name',
            data: getCurrencyData('rupee'),
            fill: '#FFF9C4',
        },
        {
            type: 'map-shape',
            legendItemName: 'Shapes',
            showInLegend: false,
            fillOpacity: 0.7,
            stroke: 'rgb(246,255,255)',
            title: 'Rial',
            idKey: 'name',
            data: getCurrencyData('rial'),
            fill: '#D7CCC8',
        },
        {
            type: 'map-line',
            topology: cables,
            legendItemName: 'Lines',
            data: cables.features.map((t: any) => {
                return { name: t.properties.name };
            }),
            idKey: 'name',
            title: 'Submarine Cables',
            stroke: '#B0C4DE',
        },
        {
            type: 'map-marker',
            topology: capitals,
            legendItemName: 'Markers',
            showInLegend: false,
            data: capitals.features.map((t: any) => {
                return { name: t.properties.city };
            }),
            idKey: 'name',
            title: 'Capital City',
            topologyIdKey: 'city',
            fillOpacity: 1,
            fill: 'orange',
        },
        {
            type: 'map-marker',
            legendItemName: 'Markers',
            title: 'Stock Exchange',
            data: [
                { name: 'New York', lat: 40.707, long: -74.011 },
                { name: 'Tokyo', lat: 35.681, long: 139.777 },
                { name: 'London', lat: 51.515, long: -0.09 },
                { name: 'Hong Kong', lat: 22.32, long: 114.171 },
                { name: 'India', lat: 28.624, long: 77.214 },
            ],
            latitudeKey: 'lat',
            longitudeKey: 'long',
            labelKey: 'name',
            labelName: 'Name',
            label: { enabled: false },
            shape: 'pin',
            size: 40,
            fillOpacity: 1,
            fill: '#EF5452',
            // stroke: 'rgb(246,255,255)',
        },
    ],
    legend: {
        enabled: true,
        item: {
            showSeriesStroke: true,
        },
    },
};

AgCharts.create(options);
