// https://en.wikipedia.org/wiki/List_of_islands_of_Greece
export const islandData = [
    { name: 'Alonnisos', population: 3138 },
    { name: 'Andros', population: 8826 },
    { name: 'Astypalaia', population: 1300 },
    { name: 'Chios', population: 50361 },
    { name: 'Crete', population: 636504 },
    { name: 'Icaria', population: 8843 },
    { name: 'Ithaca', population: 2862 },
    { name: 'Ios', population: 2024 },
    { name: 'Kalymnos', population: 17752 },
    { name: 'Karpathos', population: 6567 },
    { name: 'Kea', population: 2335 },
    { name: 'Kythira', population: 3644 },
    { name: 'Kythnos', population: 1456 },
    { name: 'Lemnos', population: 16411 },
    { name: 'Lesbos', population: 83755 },
    { name: 'Milos', population: 5302 },
    { name: 'Mykonos', population: 10704 },
    { name: 'Naxos', population: 20578 },
    { name: 'Paros', population: 14520 },
    { name: 'Rhodes', population: 125113 },
    { name: 'Salamis', population: 37220 },
    { name: 'Samos', population: 32642 },
    { name: 'Samothrace', population: 2596 },
    { name: 'Santorini', population: 15480 },
    { name: 'Serifos', population: 1400 },
    { name: 'Sifnos', population: 2777 },
    { name: 'Skopelos', population: 4518 },
    { name: 'Skyros', population: 3052 },
    { name: 'Syros', population: 21507 },
    { name: 'Thasos', population: 13104 },
    { name: 'Tinos', population: 8934 },
];
