export const londonBoroughData = [
    { name: 'Kingston upon Thames' },
    { name: 'Croydon' },
    { name: 'Bromley' },
    { name: 'Hounslow' },
    { name: 'Ealing' },
    { name: 'Havering' },
    { name: 'Hillingdon' },
    { name: 'Harrow' },
    { name: 'Brent' },
    { name: 'Barnet' },
    { name: 'Lambeth' },
    { name: 'Southwark' },
    { name: 'Lewisham' },
    { name: 'Greenwich' },
    { name: 'Bexley' },
    { name: 'Enfield' },
    { name: 'Waltham Forest' },
    { name: 'Redbridge' },
    { name: 'Sutton' },
    { name: 'Richmond upon Thames' },
    { name: 'Merton' },
    { name: 'Wandsworth' },
    { name: 'Hammersmith and Fulham' },
    { name: 'Kensington and Chelsea' },
    { name: 'Westminster' },
    { name: 'Camden' },
    { name: 'Tower Hamlets' },
    { name: 'Islington' },
    { name: 'Hackney' },
    { name: 'Haringey' },
    { name: 'Newham' },
    { name: 'Barking and Dagenham' },
    { name: 'City of London' },
];
