export const otherCountiesData = [
    { county: 'Thurrock' },
    { county: 'Slough' },
    { county: 'Windsor and Maidenhead' },
    { county: 'Chiltern' },
    { county: 'South Bucks' },
    { county: 'Basildon' },
    { county: 'Brentwood' },
    { county: 'Chelmsford' },
    { county: 'Epping Forest' },
    { county: 'Broxbourne' },
    { county: 'Dacorum' },
    { county: 'Hertsmere' },
    { county: 'Three Rivers' },
    { county: 'Watford' },
    { county: 'Dartford' },
    { county: 'Gravesham' },
    { county: 'Sevenoaks' },
    { county: 'Tonbridge and Malling' },
    { county: 'Elmbridge' },
    { county: 'Epsom and Ewell' },
    { county: 'Guildford' },
    { county: 'Mole Valley' },
    { county: 'Reigate and Banstead' },
    { county: 'Runnymede' },
    { county: 'Spelthorne' },
    { county: 'Surrey Heath' },
    { county: 'Tandridge' },
    { county: 'Woking' },
    { county: 'St Albans' },
    { county: 'Welwyn Hatfield' },
];
