export function getData() {
    return [
        {
            year: new Date(1975, 0, 1),
            vinyl: 3000,
            cassette: 1000,
            eightTrack: 800,
            cd: 0,
            minidisc: 0,
            digitalDownloads: 0,
            streaming: 0,
            ringtones: 0,
            concertTicketSales: 500,
        },
        {
            year: new Date(1976, 0, 1),
            vinyl: 3200,
            cassette: 1200,
            eightTrack: 900,
            cd: 0,
            minidisc: 0,
            digitalDownloads: 0,
            streaming: 0,
            ringtones: 0,
            concertTicketSales: 550,
        },
        {
            year: new Date(1977, 0, 1),
            vinyl: 3500,
            cassette: 1500,
            eightTrack: 950,
            cd: 0,
            minidisc: 0,
            digitalDownloads: 0,
            streaming: 0,
            ringtones: 0,
            concertTicketSales: 600,
        },
        {
            year: new Date(1978, 0, 1),
            vinyl: 4000,
            cassette: 2000,
            eightTrack: 1000,
            cd: 0,
            minidisc: 0,
            digitalDownloads: 0,
            streaming: 0,
            ringtones: 0,
            concertTicketSales: 650,
        },
        {
            year: new Date(1979, 0, 1),
            vinyl: 4500,
            cassette: 2800,
            eightTrack: 950,
            cd: 0,
            minidisc: 0,
            digitalDownloads: 0,
            streaming: 0,
            ringtones: 0,
            concertTicketSales: 700,
        },
        {
            year: new Date(1980, 0, 1),
            vinyl: 5000,
            cassette: 4000,
            eightTrack: 900,
            cd: 0,
            minidisc: 0,
            digitalDownloads: 0,
            streaming: 0,
            ringtones: 0,
            concertTicketSales: 750,
        },
        {
            year: new Date(1981, 0, 1),
            vinyl: 4800,
            cassette: 5000,
            eightTrack: 500,
            cd: 0,
            minidisc: 0,
            digitalDownloads: 0,
            streaming: 0,
            ringtones: 0,
            concertTicketSales: 800,
        },
        {
            year: new Date(1982, 0, 1),
            vinyl: 4500,
            cassette: 5500,
            eightTrack: 300,
            cd: 200,
            minidisc: 0,
            digitalDownloads: 0,
            streaming: 0,
            ringtones: 0,
            concertTicketSales: 850,
        },
        {
            year: new Date(1983, 0, 1),
            vinyl: 4200,
            cassette: 6000,
            eightTrack: 100,
            cd: 500,
            minidisc: 0,
            digitalDownloads: 0,
            streaming: 0,
            ringtones: 0,
            concertTicketSales: 900,
        },
        {
            year: new Date(1984, 0, 1),
            vinyl: 3800,
            cassette: 6500,
            eightTrack: 0,
            cd: 1000,
            minidisc: 0,
            digitalDownloads: 0,
            streaming: 0,
            ringtones: 0,
            concertTicketSales: 950,
        },
        {
            year: new Date(1985, 0, 1),
            vinyl: 3500,
            cassette: 7000,
            eightTrack: 0,
            cd: 1500,
            minidisc: 0,
            digitalDownloads: 0,
            streaming: 0,
            ringtones: 0,
            concertTicketSales: 1000,
        },
        {
            year: new Date(1986, 0, 1),
            vinyl: 3000,
            cassette: 7500,
            eightTrack: 0,
            cd: 2500,
            minidisc: 100,
            digitalDownloads: 0,
            streaming: 0,
            ringtones: 0,
            concertTicketSales: 1050,
        },
        {
            year: new Date(1987, 0, 1),
            vinyl: 2500,
            cassette: 8000,
            eightTrack: 0,
            cd: 4000,
            minidisc: 200,
            digitalDownloads: 0,
            streaming: 0,
            ringtones: 0,
            concertTicketSales: 1100,
        },
        {
            year: new Date(1988, 0, 1),
            vinyl: 2000,
            cassette: 8500,
            eightTrack: 0,
            cd: 6000,
            minidisc: 300,
            digitalDownloads: 0,
            streaming: 0,
            ringtones: 0,
            concertTicketSales: 1150,
        },
        {
            year: new Date(1989, 0, 1),
            vinyl: 1500,
            cassette: 9000,
            eightTrack: 0,
            cd: 8000,
            minidisc: 400,
            digitalDownloads: 0,
            streaming: 0,
            ringtones: 0,
            concertTicketSales: 1200,
        },
        {
            year: new Date(1990, 0, 1),
            vinyl: 1000,
            cassette: 9500,
            eightTrack: 0,
            cd: 10000,
            minidisc: 500,
            digitalDownloads: 0,
            streaming: 0,
            ringtones: 0,
            concertTicketSales: 1250,
        },
        {
            year: new Date(1991, 0, 1),
            vinyl: 800,
            cassette: 9200,
            eightTrack: 0,
            cd: 12000,
            minidisc: 600,
            digitalDownloads: 0,
            streaming: 0,
            ringtones: 0,
            concertTicketSales: 1300,
        },
        {
            year: new Date(1992, 0, 1),
            vinyl: 700,
            cassette: 8800,
            eightTrack: 0,
            cd: 14000,
            minidisc: 800,
            digitalDownloads: 0,
            streaming: 0,
            ringtones: 0,
            concertTicketSales: 1400,
        },
        {
            year: new Date(1993, 0, 1),
            vinyl: 600,
            cassette: 8500,
            eightTrack: 0,
            cd: 15000,
            minidisc: 900,
            digitalDownloads: 0,
            streaming: 0,
            ringtones: 0,
            concertTicketSales: 1500,
        },
        {
            year: new Date(1994, 0, 1),
            vinyl: 500,
            cassette: 8000,
            eightTrack: 0,
            cd: 16000,
            minidisc: 1000,
            digitalDownloads: 0,
            streaming: 0,
            ringtones: 0,
            concertTicketSales: 1600,
        },
        {
            year: new Date(1995, 0, 1),
            vinyl: 400,
            cassette: 7500,
            eightTrack: 0,
            cd: 17000,
            minidisc: 1200,
            digitalDownloads: 0,
            streaming: 0,
            ringtones: 0,
            concertTicketSales: 1800,
        },
        {
            year: new Date(1996, 0, 1),
            vinyl: 350,
            cassette: 7000,
            eightTrack: 0,
            cd: 18000,
            minidisc: 1500,
            digitalDownloads: 0,
            streaming: 0,
            ringtones: 0,
            concertTicketSales: 2000,
        },
        {
            year: new Date(1997, 0, 1),
            vinyl: 300,
            cassette: 6500,
            eightTrack: 0,
            cd: 18500,
            minidisc: 1600,
            digitalDownloads: 0,
            streaming: 0,
            ringtones: 0,
            concertTicketSales: 2300,
        },
        {
            year: new Date(1998, 0, 1),
            vinyl: 250,
            cassette: 6000,
            eightTrack: 0,
            cd: 19000,
            minidisc: 1500,
            digitalDownloads: 0,
            streaming: 0,
            ringtones: 0,
            concertTicketSales: 2600,
        },
        {
            year: new Date(1999, 0, 1),
            vinyl: 200,
            cassette: 5000,
            eightTrack: 0,
            cd: 19500,
            minidisc: 1200,
            digitalDownloads: 0,
            streaming: 0,
            ringtones: 0,
            concertTicketSales: 3000,
        },
        {
            year: new Date(2000, 0, 1),
            vinyl: 150,
            cassette: 4000,
            eightTrack: 0,
            cd: 20000,
            minidisc: 800,
            digitalDownloads: 500,
            streaming: 0,
            ringtones: 0,
            concertTicketSales: 3500,
        },
        {
            year: new Date(2001, 0, 1),
            vinyl: 120,
            cassette: 3000,
            eightTrack: 0,
            cd: 19500,
            minidisc: 400,
            digitalDownloads: 1000,
            streaming: 0,
            ringtones: 0,
            concertTicketSales: 4000,
        },
        {
            year: new Date(2002, 0, 1),
            vinyl: 100,
            cassette: 2500,
            eightTrack: 0,
            cd: 19000,
            minidisc: 200,
            digitalDownloads: 1500,
            streaming: 0,
            ringtones: 0,
            concertTicketSales: 4500,
        },
        {
            year: new Date(2003, 0, 1),
            vinyl: 90,
            cassette: 2000,
            eightTrack: 0,
            cd: 18000,
            minidisc: 100,
            digitalDownloads: 2000,
            streaming: 0,
            ringtones: 100,
            concertTicketSales: 5000,
        },
        {
            year: new Date(2004, 0, 1),
            vinyl: 80,
            cassette: 1500,
            eightTrack: 0,
            cd: 17000,
            minidisc: 0,
            digitalDownloads: 2500,
            streaming: 0,
            ringtones: 300,
            concertTicketSales: 5500,
        },
        {
            year: new Date(2005, 0, 1),
            vinyl: 70,
            cassette: 1000,
            eightTrack: 0,
            cd: 16000,
            minidisc: 0,
            digitalDownloads: 3000,
            streaming: 0,
            ringtones: 500,
            concertTicketSales: 6000,
        },
        {
            year: new Date(2006, 0, 1),
            vinyl: 65,
            cassette: 800,
            eightTrack: 0,
            cd: 14000,
            minidisc: 0,
            digitalDownloads: 4000,
            streaming: 100,
            ringtones: 800,
            concertTicketSales: 7000,
        },
        {
            year: new Date(2007, 0, 1),
            vinyl: 70,
            cassette: 600,
            eightTrack: 0,
            cd: 12000,
            minidisc: 0,
            digitalDownloads: 5000,
            streaming: 200,
            ringtones: 1000,
            concertTicketSales: 8000,
        },
        {
            year: new Date(2008, 0, 1),
            vinyl: 80,
            cassette: 500,
            eightTrack: 0,
            cd: 11000,
            minidisc: 0,
            digitalDownloads: 5500,
            streaming: 400,
            ringtones: 1200,
            concertTicketSales: 9000,
        },
        {
            year: new Date(2009, 0, 1),
            vinyl: 100,
            cassette: 400,
            eightTrack: 0,
            cd: 9000,
            minidisc: 0,
            digitalDownloads: 6000,
            streaming: 800,
            ringtones: 1500,
            concertTicketSales: 10000,
        },
        {
            year: new Date(2010, 0, 1),
            vinyl: 200,
            cassette: 200,
            eightTrack: 0,
            cd: 7000,
            minidisc: 0,
            digitalDownloads: 8000,
            streaming: 1200,
            ringtones: 1800,
            concertTicketSales: 11000,
        },
        {
            year: new Date(2011, 0, 1),
            vinyl: 300,
            cassette: 100,
            eightTrack: 0,
            cd: 6000,
            minidisc: 0,
            digitalDownloads: 9000,
            streaming: 2000,
            ringtones: 1500,
            concertTicketSales: 12000,
        },
        {
            year: new Date(2012, 0, 1),
            vinyl: 400,
            cassette: 50,
            eightTrack: 0,
            cd: 5000,
            minidisc: 0,
            digitalDownloads: 10000,
            streaming: 3000,
            ringtones: 800,
            concertTicketSales: 13000,
        },
        {
            year: new Date(2013, 0, 1),
            vinyl: 500,
            cassette: 30,
            eightTrack: 0,
            cd: 4000,
            minidisc: 0,
            digitalDownloads: 9500,
            streaming: 6000,
            ringtones: 400,
            concertTicketSales: 14000,
        },
        {
            year: new Date(2014, 0, 1),
            vinyl: 600,
            cassette: 20,
            eightTrack: 0,
            cd: 3000,
            minidisc: 0,
            digitalDownloads: 8000,
            streaming: 9000,
            ringtones: 100,
            concertTicketSales: 15000,
        },
        {
            year: new Date(2015, 0, 1),
            vinyl: 800,
            cassette: 10,
            eightTrack: 0,
            cd: 2000,
            minidisc: 0,
            digitalDownloads: 7000,
            streaming: 12000,
            ringtones: 0,
            concertTicketSales: 16000,
        },
        {
            year: new Date(2016, 0, 1),
            vinyl: 1000,
            cassette: 5,
            eightTrack: 0,
            cd: 1000,
            minidisc: 0,
            digitalDownloads: 5000,
            streaming: 15000,
            ringtones: 0,
            concertTicketSales: 17000,
        },
        {
            year: new Date(2017, 0, 1),
            vinyl: 1200,
            cassette: 2,
            eightTrack: 0,
            cd: 500,
            minidisc: 0,
            digitalDownloads: 3000,
            streaming: 18000,
            ringtones: 0,
            concertTicketSales: 18000,
        },
        {
            year: new Date(2018, 0, 1),
            vinyl: 1500,
            cassette: 1,
            eightTrack: 0,
            cd: 200,
            minidisc: 0,
            digitalDownloads: 1500,
            streaming: 20000,
            ringtones: 0,
            concertTicketSales: 19000,
        },
        {
            year: new Date(2019, 0, 1),
            vinyl: 1800,
            cassette: 1,
            eightTrack: 0,
            cd: 100,
            minidisc: 0,
            digitalDownloads: 1000,
            streaming: 22000,
            ringtones: 0,
            concertTicketSales: 20000,
        },
        {
            year: new Date(2020, 0, 1),
            vinyl: 2000,
            cassette: 0,
            eightTrack: 0,
            cd: 50,
            minidisc: 0,
            digitalDownloads: 500,
            streaming: 25000,
            ringtones: 0,
            concertTicketSales: 21000,
        },
        {
            year: new Date(2021, 0, 1),
            vinyl: 2500,
            cassette: 0,
            eightTrack: 0,
            cd: 20,
            minidisc: 0,
            digitalDownloads: 200,
            streaming: 28000,
            ringtones: 0,
            concertTicketSales: 22000,
        },
        {
            year: new Date(2022, 0, 1),
            vinyl: 3000,
            cassette: 0,
            eightTrack: 0,
            cd: 10,
            minidisc: 0,
            digitalDownloads: 100,
            streaming: 30000,
            ringtones: 0,
            concertTicketSales: 23000,
        },
        {
            year: new Date(2023, 0, 1),
            vinyl: 3500,
            cassette: 0,
            eightTrack: 0,
            cd: 5,
            minidisc: 0,
            digitalDownloads: 50,
            streaming: 32000,
            ringtones: 0,
            concertTicketSales: 24000,
        },
        {
            year: new Date(2024, 0, 1),
            vinyl: 4000,
            cassette: 0,
            eightTrack: 0,
            cd: 2,
            minidisc: 0,
            digitalDownloads: 10,
            streaming: 35000,
            ringtones: 0,
            concertTicketSales: 25000,
        },
    ];
}
