// Source: https://www.gov.uk/government/statistical-data-sets/banana-prices
export function getData() {
    return [
        {
            week: 1,
            belize: 0.66,
            columbia: 0.97,
            costaRica: 0.98,
            ecuador: 0.88,
            panama: 0.96,
            guatemala: 0.94,
        },
        {
            week: 2,
            belize: 0.66,
            columbia: 0.96,
            costaRica: 0.97,
            ecuador: 0.88,
            panama: 0.96,
            guatemala: 0.94,
        },
        {
            week: 3,
            belize: 1,
            columbia: 1.06,
            costaRica: 0.99,
            ecuador: 0.88,
            panama: 0.96,
            guatemala: 0.96,
        },
        {
            week: 4,
            belize: 0.88,
            columbia: 1.06,
            costaRica: 1,
            ecuador: 0.93,
            panama: 0.96,
            guatemala: 0.99,
        },
        {
            week: 5,
            columbia: 1.06,
            costaRica: 1.04,
            ecuador: 1.06,
            ivoryCoast: 0.9,
            panama: 1.08,
            guatemala: 1.01,
        },
        {
            week: 6,
            columbia: 0.94,
            costaRica: 1,
            ecuador: 0.93,
            panama: 1.05,
            guatemala: 0.96,
            nicaragua: 0.86,
        },
        {
            week: 7,
            columbia: 0.95,
            costaRica: 1,
            ecuador: 0.93,
            panama: 1.05,
            guatemala: 0.97,
            nicaragua: 0.86,
        },
        {
            week: 8,
            belize: 1.06,
            columbia: 0.94,
            costaRica: 0.98,
            ecuador: 0.93,
            panama: 1.05,
            guatemala: 0.96,
        },
        {
            week: 9,
            columbia: 0.93,
            costaRica: 0.97,
            ecuador: 0.93,
            panama: 1.05,
            guatemala: 0.93,
        },
        {
            week: 10,
            columbia: 0.96,
            costaRica: 0.99,
            ecuador: 0.96,
            panama: 1.05,
            guatemala: 0.97,
        },
        {
            week: 11,
            columbia: 0.95,
            costaRica: 0.99,
            ecuador: 0.96,
            panama: 0.99,
            guatemala: 0.97,
        },
        {
            week: 12,
            columbia: 0.95,
            costaRica: 0.99,
            ecuador: 0.96,
            panama: 0.9,
            guatemala: 0.97,
        },
        {
            week: 13,
            columbia: 0.95,
            costaRica: 1,
            ecuador: 0.96,
            panama: 0.9,
            guatemala: 0.97,
        },
        {
            week: 14,
            columbia: 0.88,
            costaRica: 0.97,
            ecuador: 0.96,
            panama: 0.9,
            guatemala: 0.96,
        },
        {
            week: 15,
            columbia: 0.97,
            costaRica: 1,
            ecuador: 0.96,
            panama: 0.9,
            guatemala: 0.98,
        },
        {
            week: 16,
            columbia: 0.97,
            costaRica: 1,
            ecuador: 0.96,
            panama: 0.9,
            guatemala: 0.97,
        },
        {
            week: 17,
            columbia: 0.93,
            costaRica: 1.01,
            ecuador: 0.96,
            panama: 0.9,
            guatemala: 0.96,
        },
        {
            week: 18,
            columbia: 0.96,
            costaRica: 1.01,
            ecuador: 0.9,
            panama: 0.9,
            guatemala: 1.01,
        },
        {
            week: 19,
            columbia: 0.96,
            costaRica: 1.01,
            ecuador: 0.9,
            panama: 0.9,
            guatemala: 1.01,
        },
        {
            week: 20,
            belize: 0.68,
            columbia: 0.93,
            costaRica: 0.99,
            ecuador: 0.94,
            panama: 0.9,
            guatemala: 1.01,
        },
        {
            week: 21,
            belize: 0.68,
            columbia: 0.93,
            costaRica: 0.97,
            ecuador: 0.94,
            panama: 0.94,
            guatemala: 1.01,
            nicaragua: 0.99,
        },
        {
            week: 22,
            belize: 0.68,
            columbia: 0.85,
            costaRica: 0.98,
            ecuador: 0.81,
            ivoryCoast: 0.92,
            panama: 0.94,
            nicaragua: 0.99,
        },
        {
            week: 23,
            belize: 0.68,
            columbia: 0.94,
            costaRica: 1.02,
            ecuador: 0.94,
            panama: 0.99,
            guatemala: 1.01,
            nicaragua: 0.99,
        },
        {
            week: 24,
            belize: 0.68,
            columbia: 0.94,
            costaRica: 1.02,
            ecuador: 0.94,
            ivoryCoast: 0.97,
            panama: 0.99,
            guatemala: 1.01,
            nicaragua: 0.99,
        },
        {
            week: 25,
            belize: 0.68,
            columbia: 0.94,
            costaRica: 1.01,
            ecuador: 0.94,
            panama: 0.99,
            guatemala: 0.97,
            nicaragua: 0.81,
        },
        {
            week: 26,
            belize: 0.68,
            columbia: 0.9,
            costaRica: 0.92,
            ecuador: 0.85,
            panama: 0.95,
        },
        {
            week: 27,
            belize: 0.7,
            columbia: 0.9,
            costaRica: 0.95,
            ecuador: 0.81,
            guatemala: 0.86,
        },
        {
            week: 28,
            belize: 0.9,
            columbia: 0.93,
            costaRica: 0.96,
            ecuador: 0.9,
            ivoryCoast: 0.93,
            panama: 0.93,
            guatemala: 1.01,
        },
        {
            week: 29,
            belize: 0.9,
            columbia: 0.96,
            costaRica: 0.96,
            ecuador: 0.96,
            ivoryCoast: 0.93,
            panama: 0.99,
            guatemala: 1.01,
        },
        {
            week: 30,
            belize: 0.95,
            columbia: 0.97,
            costaRica: 1.05,
            ecuador: 0.96,
            ivoryCoast: 0.99,
            guatemala: 1.01,
        },
        {
            week: 31,
            belize: 1.06,
            columbia: 1.06,
            costaRica: 1.05,
            ecuador: 1.02,
            ivoryCoast: 0.99,
            guatemala: 1.01,
        },
        {
            week: 32,
            belize: 1.06,
            columbia: 1.04,
            costaRica: 1.07,
            dominicanRepublic: 0.84,
            ecuador: 1.1,
            guatemala: 1.01,
        },
        {
            week: 33,
            belize: 1.06,
            columbia: 1.06,
            costaRica: 1.06,
            dominicanRepublic: 0.84,
            ecuador: 1.1,
            guatemala: 0.97,
        },
        {
            week: 34,
            belize: 1.06,
            columbia: 1.08,
            costaRica: 1.08,
            ecuador: 1.1,
            guatemala: 1,
        },
        {
            week: 35,
            columbia: 1.08,
            costaRica: 1.08,
            ecuador: 1.1,
            guatemala: 1,
        },
        {
            week: 36,
            columbia: 1.1,
            costaRica: 1.07,
            honduras: 1.1,
            guatemala: 0.97,
            nicaragua: 1.1,
        },
        {
            week: 37,
            columbia: 1.1,
            costaRica: 1.07,
            honduras: 1.1,
            guatemala: 0.97,
            nicaragua: 1.1,
        },
        {
            week: 38,
            columbia: 1.1,
            costaRica: 1.07,
            honduras: 1.1,
            ivoryCoast: 0.84,
            guatemala: 0.99,
            nicaragua: 1.1,
        },
        {
            week: 39,
            columbia: 1.07,
            costaRica: 1.06,
            ivoryCoast: 0.97,
            guatemala: 1.01,
        },
        {
            week: 40,
            columbia: 0.95,
            costaRica: 1.01,
            ivoryCoast: 0.97,
            panama: 0.95,
            guatemala: 1.01,
        },
        {
            week: 41,
            costaRica: 1.05,
            ivoryCoast: 0.97,
            guatemala: 1.01,
        },
        {
            week: 42,
            costaRica: 1.09,
            ivoryCoast: 0.97,
            guatemala: 1.01,
        },
        {
            week: 43,
            columbia: 1.12,
            costaRica: 1.07,
            ivoryCoast: 0.97,
            panama: 1.12,
            guatemala: 1.01,
        },
        {
            week: 44,
            columbia: 1.09,
            costaRica: 1.06,
            guatemala: 1.01,
        },
        {
            week: 45,
            columbia: 1.12,
            costaRica: 0.99,
            ecuador: 1.12,
            panama: 1.1,
        },
        {
            week: 46,
            columbia: 0.77,
            costaRica: 0.79,
            ecuador: 0.88,
            ivoryCoast: 0.88,
            panama: 0.88,
        },
        {
            week: 47,
            columbia: 0.97,
            costaRica: 1.03,
            ecuador: 0.88,
            ivoryCoast: 0.79,
            panama: 0.99,
            guatemala: 0.91,
        },
        {
            week: 48,
            cameroon: 0.66,
            columbia: 0.97,
            costaRica: 1,
            ecuador: 0.85,
            panama: 0.99,
            guatemala: 0.82,
        },
        {
            week: 49,
            costaRica: 1.02,
            dominicanRepublic: 0.77,
            guatemala: 0.99,
        },
    ];
}
