export function getData() {
    return [
        {
            category: ['2015', 'Shannon (H)'],
            drought: 4,
            control: 4.5,
            drought_low: 3.8,
            drought_high: 4.2,
            control_low: 4.3,
            control_high: 4.7,
        },
        {
            category: ['2015', 'Simpson (D)'],
            drought: 8,
            control: 8.5,
            drought_low: 7.7,
            drought_high: 8.3,
            control_low: 8.2,
            control_high: 8.8,
        },
        {
            category: ['2015', 'Species Richness'],
            drought: 10,
            control: 10.5,
            drought_low: 9.5,
            drought_high: 10.3,
            control_low: 10.2,
            control_high: 10.8,
        },
        {
            category: ['2016', 'Shannon (H)'],
            drought: 5,
            control: 5.5,
            drought_low: 4.8,
            drought_high: 5.2,
            control_low: 5.3,
            control_high: 5.7,
        },
        {
            category: ['2016', 'Simpson (D)'],
            drought: 9,
            control: 9.5,
            drought_low: 8.7,
            drought_high: 9.3,
            control_low: 9.2,
            control_high: 9.8,
        },
        {
            category: ['2016', 'Species Richness'],
            drought: 11,
            control: 11.5,
            drought_low: 10.8,
            drought_high: 11.3,
            control_low: 11.2,
            control_high: 11.8,
        },
        {
            category: ['2017', 'Shannon (H)'],
            drought: 6,
            control: 6.5,
            drought_low: 5.8,
            drought_high: 6.2,
            control_low: 6.3,
            control_high: 6.7,
        },
        {
            category: ['2017', 'Simpson (D)'],
            drought: 12,
            control: 12.5,
            drought_low: 11.8,
            drought_high: 12.3,
            control_low: 12.2,
            control_high: 12.8,
        },
        {
            category: ['2017', 'Species Richness'],
            drought: 14,
            control: 14.5,
            drought_low: 13.8,
            drought_high: 14.3,
            control_low: 14.2,
            control_high: 14.8,
        },
        {
            category: ['2018', 'Shannon (H)'],
            drought: 7,
            control: 7.5,
            drought_low: 6.8,
            drought_high: 7.2,
            control_low: 7.3,
            control_high: 7.7,
        },
        {
            category: ['2018', 'Simpson (D)'],
            drought: 13,
            control: 13.5,
            drought_low: 12.7,
            drought_high: 13.3,
            control_low: 13.2,
            control_high: 13.8,
        },
        {
            category: ['2018', 'Species Richness'],
            drought: 16,
            control: 16.5,
            drought_low: 15.7,
            drought_high: 16.3,
            control_low: 16.2,
            control_high: 16.8,
        },
    ];
}
