import type {
    AgMapLineSeriesOptions,
    AgMapLineSeriesStyle,
    AgMapLineSeriesThemeableOptions,
} from 'ag-charts-community';
import {
    type OptionsDefs,
    and,
    arrayLength,
    arrayOf,
    callbackDefs,
    colorScaleOptionsDef,
    commonSeriesOptionsDefs,
    commonSeriesThemeableOptionsDefs,
    constant,
    geoJson,
    labelCollisionFitOptionsDefs,
    lineDashOptionsDef,
    lineHighlightOptionsDef,
    multiSeriesHighlightOptionsDef,
    positiveNumber,
    positiveNumericValue,
    required,
    seriesLabelOptionsDefs,
    string,
    strokeOptionsDef,
    tooltipOptionsDefs,
    undocumentedDefs,
    without,
} from 'ag-charts-core';

export const mapLineSeriesThemeableOptionsDef: OptionsDefs<AgMapLineSeriesThemeableOptions> = {
    colorScale: colorScaleOptionsDef,
    minStrokeWidth: positiveNumber,
    maxStrokeWidth: positiveNumber,
    itemStyler: callbackDefs<AgMapLineSeriesStyle>({
        ...strokeOptionsDef,
        ...lineDashOptionsDef,
    }),
    sizeDomain: and(arrayOf(positiveNumericValue), arrayLength(2, 2)),
    label: {
        ...seriesLabelOptionsDefs,
        ...labelCollisionFitOptionsDefs,
    },
    tooltip: tooltipOptionsDefs,
    ...commonSeriesThemeableOptionsDefs,
    ...strokeOptionsDef,
    ...lineDashOptionsDef,
    highlight: multiSeriesHighlightOptionsDef(lineHighlightOptionsDef, lineHighlightOptionsDef),
    ...undocumentedDefs({
        topologyIdKey: string,
    }),
};

export const mapLineSeriesOptionsDef: OptionsDefs<AgMapLineSeriesOptions> = {
    ...without(commonSeriesOptionsDefs, ['highlightStyle', 'highlight']),
    ...mapLineSeriesThemeableOptionsDef,
    type: required(constant('map-line')),
    idKey: required(string),
    sizeKey: string,
    colorKey: string,
    labelKey: string,
    idName: string,
    sizeName: string,
    colorName: string,
    labelName: string,
    topology: geoJson,
    topologyIdKey: string,
    legendItemName: string,
    title: string,
};
