// UK monthly mean temperature (°C), with gaps representing unavailable readings
export function getData() {
    return [
        { year: '2019', month: 'Jan', temperature: 4 },
        { year: '2019', month: 'Feb', temperature: 7 },
        { year: '2019', month: 'Mar', temperature: 8 },
        { year: '2019', month: 'Apr', temperature: 9 },
        { year: '2019', month: 'May', temperature: 12 },
        { year: '2019', month: 'Jun', temperature: 14 },
        { year: '2019', month: 'Jul', temperature: 18 },
        { year: '2019', month: 'Aug', temperature: 17 },
        { year: '2019', month: 'Sep', temperature: 14 },
        { year: '2019', month: 'Oct', temperature: 9 },
        { year: '2019', month: 'Nov', temperature: 5 },
        { year: '2019', month: 'Dec', temperature: 5 },
        { year: '2020', month: 'Jan', temperature: 6 },
        { year: '2020', month: 'Feb', temperature: 6 },
        { year: '2020', month: 'Mar', temperature: null },
        { year: '2020', month: 'Apr', temperature: null },
        { year: '2020', month: 'May', temperature: 13 },
        { year: '2020', month: 'Jun', temperature: 15 },
        { year: '2020', month: 'Jul', temperature: 16 },
        { year: '2020', month: 'Aug', temperature: 17 },
        { year: '2020', month: 'Sep', temperature: 14 },
        { year: '2020', month: 'Oct', temperature: 10 },
        { year: '2020', month: 'Nov', temperature: 8 },
        { year: '2020', month: 'Dec', temperature: 5 },
        { year: '2021', month: 'Jan', temperature: 3 },
        { year: '2021', month: 'Feb', temperature: 4 },
        { year: '2021', month: 'Mar', temperature: 7 },
        { year: '2021', month: 'Apr', temperature: 7 },
        { year: '2021', month: 'May', temperature: 10 },
        { year: '2021', month: 'Jun', temperature: 16 },
        { year: '2021', month: 'Jul', temperature: 18 },
        { year: '2021', month: 'Aug', temperature: 16 },
        { year: '2021', month: 'Sep', temperature: 16 },
        { year: '2021', month: 'Oct', temperature: 12 },
        { year: '2021', month: 'Nov', temperature: 8 },
        { year: '2021', month: 'Dec', temperature: 5 },
        { year: '2022', month: 'Jan', temperature: 5 },
        { year: '2022', month: 'Feb', temperature: 6 },
        { year: '2022', month: 'Mar', temperature: 7 },
        { year: '2022', month: 'Apr', temperature: 9 },
        { year: '2022', month: 'May', temperature: 13 },
        { year: '2022', month: 'Jun', temperature: 16 },
        { year: '2022', month: 'Jul', temperature: 19 },
        { year: '2022', month: 'Aug', temperature: 18 },
        { year: '2022', month: 'Sep', temperature: 15 },
        { year: '2022', month: 'Oct', temperature: 12 },
        { year: '2022', month: 'Nov', temperature: 8 },
        { year: '2022', month: 'Dec', temperature: 4 },
        { year: '2023', month: 'Jan', temperature: 5 },
        { year: '2023', month: 'Feb', temperature: 5 },
        { year: '2023', month: 'Mar', temperature: 7 },
        { year: '2023', month: 'Apr', temperature: 9 },
        { year: '2023', month: 'May', temperature: 12 },
        { year: '2023', month: 'Jun', temperature: 16 },
        { year: '2023', month: 'Jul', temperature: 17 },
        { year: '2023', month: 'Aug', temperature: 17 },
        { year: '2023', month: 'Sep' },
        { year: '2023', month: 'Oct', temperature: 11 },
        { year: '2023', month: 'Nov', temperature: 7 },
        { year: '2023', month: 'Dec', temperature: 5 },
    ];
}
