// https://www.openflights.org
export const flightData = [
    { name: 'AOK-ATH', duration: 59 },
    { name: 'ATH-AXD', duration: 57 },
    { name: 'ATH-CHQ', duration: 49 },
    { name: 'ATH-HER', duration: 52 },
    { name: 'ATH-JIK', duration: 45 },
    { name: 'ATH-JKH', duration: 44 },
    { name: 'ATH-JKL', duration: 51 },
    { name: 'ATH-JMK', duration: 40 },
    { name: 'ATH-JNX', duration: 41 },
    { name: 'ATH-JSH', duration: 56 },
    { name: 'ATH-JSI', duration: 40 },
    { name: 'ATH-JSY', duration: 37 },
    { name: 'ATH-JTR', duration: 46 },
    { name: 'ATH-JTY', duration: 49 },
    { name: 'ATH-KGS', duration: 52 },
    { name: 'ATH-KIT', duration: 45 },
    { name: 'ATH-KVA', duration: 54 },
    { name: 'ATH-LRS', duration: 49 },
    { name: 'ATH-LXS', duration: 48 },
    { name: 'ATH-MJT', duration: 49 },
    { name: 'ATH-MLO', duration: 40 },
    { name: 'ATH-PAS', duration: 40 },
    { name: 'ATH-RHO', duration: 60 },
    { name: 'ATH-SKU', duration: 39 },
    { name: 'ATH-SMI', duration: 49 },
];
