// Source: https://www.gov.uk/government/statistics/renewable-sources-of-energy-chapter-6-digest-of-united-kingdom-energy-statistics-dukes
export function getData() {
    return [
        {
            year: new Date(1990, 0, 1),
            'Onshore wind': 1,
            'Offshore wind': 0,
            'Marine energy': 0,
            'Solar photovoltaics': 0,
            'Small scale Hydro': 11,
            'Large scale Hydro': 437,
            'Plant biomass': 0,
            'Animal biomass': 0,
            'Landfill gas': 46,
            'Sewage gas': 104,
        },
        {
            year: new Date(2000, 0, 1),
            'Onshore wind': 81,
            'Offshore wind': 0,
            'Marine energy': 0,
            'Solar photovoltaics': 0,
            'Small scale Hydro': 18,
            'Large scale Hydro': 419,
            'Plant biomass': 11,
            'Animal biomass': 183,
            'Landfill gas': 718,
            'Sewage gas': 120,
        },
        {
            year: new Date(2010, 0, 1),
            'Onshore wind': 621,
            'Offshore wind': 263,
            'Marine energy': 0,
            'Solar photovoltaics': 3,
            'Small scale Hydro': 43,
            'Large scale Hydro': 266,
            'Plant biomass': 461,
            'Animal biomass': 239,
            'Landfill gas': 1711,
            'Sewage gas': 237,
        },
        {
            year: new Date(2021, 0, 1),
            'Onshore wind': 2507,
            'Offshore wind': 3053,
            'Marine energy': 0,
            'Solar photovoltaics': 1044,
            'Small scale Hydro': 119,
            'Large scale Hydro': 353,
            'Plant biomass': 5990,
            'Animal biomass': 240,
            'Landfill gas': 791,
            'Sewage gas': 233,
        },
    ];
}
