import { defineConfig } from 'vitest/config';

// The demo's history is generated by advancing local calendar days, so its invariants
// only bite in a DST-observing zone. `pool: 'forks'` keeps TZ applied per worker.
export default defineConfig({
    test: {
        root: new URL('.', import.meta.url).pathname,
        globals: true,
        include: ['src/**/*Timezone.test.ts'],
        exclude: ['**/node_modules/**', '**/dist/**'],
        pool: 'forks',
        env: {
            TZ: 'US/Pacific',
        },
    },
});
