export function getData() {
    return [
        {
            category: ['April', 'Deal'],
            salary: 20,
            subcon: 20,
            travel: 30,
            visa: 10,
            others: 20,
        },
        {
            category: ['April', 'Plan'],
            salary: 20,
            subcon: 20,
            travel: 30,
            visa: 10,
            others: 20,
        },
        {
            category: ['April', 'Actual'],
            salary: 20,
            subcon: 20,
            travel: 30,
            visa: 10,
            others: 20,
        },
        {
            category: ['May', 'Deal'],
            salary: 20,
            subcon: 20,
            travel: 30,
            visa: 10,
            others: 20,
        },
        {
            category: ['May', 'Plan'],
            salary: 20,
            subcon: 20,
            travel: 30,
            visa: 10,
            others: 20,
        },
        {
            category: ['May', 'Actual'],
            salary: 20,
            subcon: 20,
            travel: 30,
            visa: 10,
            others: 20,
        },
        {
            category: ['June', 'Deal'],
            salary: 20,
            subcon: 20,
            travel: 30,
            visa: 10,
            others: 20,
        },
        {
            category: ['June', 'Plan'],
            salary: 20,
            subcon: 20,
            travel: 30,
            visa: 10,
            others: 20,
        },
        {
            category: ['June', 'Actual'],
            salary: 20,
            subcon: 20,
            travel: 30,
            visa: 10,
            others: 20,
        },
        {
            category: ['July', 'Deal'],
            salary: 20,
            subcon: 20,
            travel: 30,
            visa: 10,
            others: 20,
        },
        {
            category: ['July', 'Plan'],
            salary: 20,
            subcon: 20,
            travel: 30,
            visa: 10,
            others: 20,
        },
        {
            category: ['July', 'Actual'],
            salary: 20,
            subcon: 20,
            travel: 30,
            visa: 10,
            others: 20,
        },
        {
            category: ['August', 'Deal'],
            salary: 20,
            subcon: 20,
            travel: 30,
            visa: 10,
            others: 20,
        },
        {
            category: ['August', 'Plan'],
            salary: 20,
            subcon: 20,
            travel: 30,
            visa: 10,
            others: 20,
        },
        {
            category: ['August', 'Actual'],
            salary: 20,
            subcon: 20,
            travel: 30,
            visa: 10,
            others: 20,
        },
    ];
}
