import { AgCartesianChartOptions, AgCharts } from 'ag-charts-enterprise';

import { getData } from './data';

const options: AgCartesianChartOptions = {
    container: document.getElementById('myChart'),
    data: getData(),
    title: {
        text: 'Electricity Generated By Fossil Fuel vs Renewables',
    },
    subtitle: {
        text: '2019 - 2025',
    },
    series: [
        {
            type: 'range-area',
            xKey: 'date',
            yLowKey: 'fossil_twh',
            yHighKey: 'renewables_twh',
            fillOpacity: 0.2,
            strokeWidth: 2,
            invertedStyle: {
                fillOpacity: 0.8,
            },
            item: {
                high: {
                    lineDash: [4, 6],
                },
            },
            marker: {
                fill: 'white',
                itemStyler: ({ itemId }) => {
                    return {
                        size: itemId === 'high' ? 0 : 8,
                    };
                },
            },
        },
    ],
    axes: [
        {
            position: 'left',
            type: 'number',
            title: {
                text: 'Average Price',
            },
        },
        {
            position: 'bottom',
            type: 'unit-time',
        },
    ],
};

AgCharts.create(options);
