import {
    AgCartesianChartOptions,
    AgCharts,
    ContextMenuModule,
    ModuleRegistry,
    NumberAxisModule,
    RangeAreaSeriesModule,
    UnitTimeAxisModule,
} from 'ag-charts-enterprise';

import { getData } from './data';

ModuleRegistry.registerModules([NumberAxisModule, RangeAreaSeriesModule, UnitTimeAxisModule]);
const options: AgCartesianChartOptions = {
    container: document.getElementById('myChart'),
    data: getData(),
    title: {
        text: 'Electricity Generated By Fossil Fuel vs Renewables',
    },
    subtitle: {
        text: 'Darker shading indicates fossil fuel dominance',
    },
    series: [
        {
            type: 'range-area',
            xKey: 'date',
            yLowKey: 'fossil_twh',
            yHighKey: 'renewables_twh',
            yLowName: 'Fossil Fuel',
            yHighName: 'Renewables',
            fillOpacity: 0.2,
            strokeWidth: 2,
            marker: {
                fill: 'white',
                size: 0,
            },
            invertedStyle: {
                fillOpacity: 0.8,
            },
            item: {
                high: {
                    lineDash: [4, 6],
                },
                low: {
                    marker: {
                        size: 8,
                    },
                },
            },
            tooltip: {
                renderer: ({ datum, yLowKey, yHighKey }) => {
                    const fossil = datum[yLowKey];
                    const renewables = datum[yHighKey];
                    const difference = renewables - fossil;
                    const leader = difference > 0 ? 'Renewables' : 'Fossil Fuel';

                    return {
                        heading: datum.date?.toLocaleDateString('en-US', {
                            month: 'short',
                            year: 'numeric',
                        }),
                        title: 'Energy Generation',
                        data: [
                            { label: 'Fossil Fuel', value: `${fossil.toFixed(1)} TWh` },
                            { label: 'Renewables', value: `${renewables.toFixed(1)} TWh` },
                            { label: 'Difference', value: `${Math.abs(difference).toFixed(1)} TWh (${leader} ahead)` },
                        ],
                    };
                },
            },
        },
    ],
    axes: {
        y: {
            type: 'number',
            title: {
                text: 'Electricity Generation (TWh)',
            },
        },
        x: {
            type: 'unit-time',
        },
    },
};

AgCharts.create(options);
