export function getData() {
    return [
        {
            year: 2024,
            USACoal: 900,
            USAGas: 1600,
            USARenewables: 800,
            USANuclear: 780,
            GermanyCoal: 420,
            GermanyGas: 500,
            GermanyRenewables: 620,
            GermanyNuclear: 60,
            ChinaCoal: 4200,
            ChinaGas: 350,
            ChinaRenewables: 1400,
            ChinaNuclear: 420,
        },
        {
            year: 2025,
            USACoal: 850,
            USAGas: 1650,
            USARenewables: 900,
            USANuclear: 790,
            GermanyCoal: 380,
            GermanyGas: 480,
            GermanyRenewables: 700,
            GermanyNuclear: 40,
            ChinaCoal: 4000,
            ChinaGas: 380,
            ChinaRenewables: 1600,
            ChinaNuclear: 450,
        },
        {
            year: 2026,
            USACoal: 800,
            USAGas: 1700,
            USARenewables: 1050,
            USANuclear: 800,
            GermanyCoal: 320,
            GermanyGas: 460,
            GermanyRenewables: 820,
            GermanyNuclear: 0,
            ChinaCoal: 3800,
            ChinaGas: 420,
            ChinaRenewables: 1900,
            ChinaNuclear: 500,
        },
    ];
}
