export function getData() {
    return {
        'Jan - Mar 2023': [
            {
                countryOfArrival: 'Bulgaria',
                xKey: 'department',
                min: 350,
                q1: 694,
                median: 945,
                q3: 1197,
                max: 1257,
            },
            {
                countryOfArrival: 'Cyprus',
                xKey: 'department',
                min: 117,
                q1: 204,
                median: 266,
                q3: 447,
                max: 681,
            },
            {
                countryOfArrival: 'Spain',
                xKey: 'department',
                min: 150,
                q1: 407,
                median: 518,
                q3: 717,
                max: 1555,
            },
            {
                countryOfArrival: 'Greece',
                xKey: 'department',
                min: 68,
                q1: 101,
                median: 161,
                q3: 171,
                max: 188,
            },
            {
                countryOfArrival: 'Italy',
                xKey: 'department',
                min: 132,
                q1: 320,
                median: 1141,
                q3: 1461,
                max: 2366,
            },
        ],
        'April - June 2023': [
            {
                countryOfArrival: 'Bulgaria',
                xKey: 'department',
                min: 123,
                q1: 672,
                median: 1746,
                q3: 2418,
                max: 2714,
            },
            {
                countryOfArrival: 'Cyprus',
                xKey: 'department',
                min: 109,
                q1: 172,
                median: 210,
                q3: 340,
                max: 2013,
            },
            {
                countryOfArrival: 'Spain',
                xKey: 'department',
                min: 144,
                q1: 343,
                median: 408,
                q3: 709,
                max: 1214,
            },
            {
                countryOfArrival: 'Greece',
                xKey: 'department',
                min: 124,
                q1: 163,
                median: 215,
                q3: 437,
                max: 1098,
            },
            {
                countryOfArrival: 'Italy',
                xKey: 'department',
                min: 105,
                q1: 165,
                median: 385,
                q3: 855,
                max: 2346,
            },
        ],
    };
}
