// EU Member States using the Euro
export const EUEurozoneMembers = [
    {
        pop_est: 67059887,
        pop_rank: 16,
        gdp_md: 2715518,
        iso2: 'FR',
        iso3: 'FRA',
        name: 'France',
    },
    {
        pop_est: 83132799,
        pop_rank: 16,
        gdp_md: 3861123,
        iso2: 'DE',
        iso3: 'DEU',
        name: 'Germany',
    },
    {
        pop_est: 47076781,
        pop_rank: 15,
        gdp_md: 1393490,
        iso2: 'ES',
        iso3: 'ESP',
        name: 'Spain',
    },
    {
        pop_est: 60297396,
        pop_rank: 16,
        gdp_md: 2003576,
        iso2: 'IT',
        iso3: 'ITA',
        name: 'Italy',
    },
    {
        pop_est: 17332850,
        pop_rank: 14,
        gdp_md: 907050,
        iso2: 'NL',
        iso3: 'NLD',
        name: 'Netherlands',
    },
    {
        pop_est: 11484055,
        pop_rank: 14,
        gdp_md: 533097,
        iso2: 'BE',
        iso3: 'BEL',
        name: 'Belgium',
    },
    {
        pop_est: 619896,
        pop_rank: 11,
        gdp_md: 71104,
        iso2: 'LU',
        iso3: 'LUX',
        name: 'Luxembourg',
    },
    {
        pop_est: 4941444,
        pop_rank: 12,
        gdp_md: 388698,
        iso2: 'IE',
        iso3: 'IRL',
        name: 'Ireland',
    },
    {
        pop_est: 10716322,
        pop_rank: 14,
        gdp_md: 209852,
        iso2: 'GR',
        iso3: 'GRC',
        name: 'Greece',
    },
    {
        pop_est: 8877067,
        pop_rank: 13,
        gdp_md: 445075,
        iso2: 'AT',
        iso3: 'AUT',
        name: 'Austria',
    },
    {
        pop_est: 5454073,
        pop_rank: 13,
        gdp_md: 105079,
        iso2: 'SK',
        iso3: 'SVK',
        name: 'Slovakia',
    },
    {
        pop_est: 2087946,
        pop_rank: 12,
        gdp_md: 54174,
        iso2: 'SI',
        iso3: 'SVN',
        name: 'Slovenia',
    },
    {
        pop_est: 4067500,
        pop_rank: 12,
        gdp_md: 60752,
        iso2: 'HR',
        iso3: 'HRV',
        name: 'Croatia',
    },
    {
        pop_est: 6975761,
        pop_rank: 13,
        gdp_md: 68558,
        iso2: 'BG',
        iso3: 'BGR',
        name: 'Bulgaria',
    }, // joined 2024
    {
        pop_est: 2657637,
        pop_rank: 12,
        gdp_md: 11968,
        iso2: 'MD',
        iso3: 'MDA',
        name: 'Moldova',
    }, // NOTE: Not EU — remove below
    {
        pop_est: 1326590,
        pop_rank: 12,
        gdp_md: 31471,
        iso2: 'EE',
        iso3: 'EST',
        name: 'Estonia',
    },
    {
        pop_est: 1912789,
        pop_rank: 12,
        gdp_md: 34102,
        iso2: 'LV',
        iso3: 'LVA',
        name: 'Latvia',
    },
    {
        pop_est: 2786844,
        pop_rank: 12,
        gdp_md: 54627,
        iso2: 'LT',
        iso3: 'LTU',
        name: 'Lithuania',
    },
    {
        pop_est: 502653,
        pop_rank: 11,
        gdp_md: 14989,
        iso2: 'MT',
        iso3: 'MLT',
        name: 'Malta',
    },
    {
        pop_est: 10269417,
        pop_rank: 14,
        gdp_md: 238785,
        iso2: 'PT',
        iso3: 'PRT',
        name: 'Portugal',
    },
    {
        pop_est: 5520314,
        pop_rank: 13,
        gdp_md: 269296,
        iso2: 'FI',
        iso3: 'FIN',
        name: 'Finland',
    },
    {
        pop_est: 1198575,
        pop_rank: 12,
        gdp_md: 24948,
        iso2: 'CY',
        iso3: 'CYP',
        name: 'Cyprus',
    },
];

// EU Member States NOT using the Euro
export const EUNonEurozoneMembers = [
    {
        pop_est: 5818553,
        pop_rank: 13,
        gdp_md: 350104,
        iso2: 'DK',
        iso3: 'DNK',
        name: 'Denmark',
    },
    {
        pop_est: 10285453,
        pop_rank: 14,
        gdp_md: 530883,
        iso2: 'SE',
        iso3: 'SWE',
        name: 'Sweden',
    },
    {
        pop_est: 37970874,
        pop_rank: 15,
        gdp_md: 595858,
        iso2: 'PL',
        iso3: 'POL',
        name: 'Poland',
    },
    {
        pop_est: 9769949,
        pop_rank: 13,
        gdp_md: 163469,
        iso2: 'HU',
        iso3: 'HUN',
        name: 'Hungary',
    },
    {
        pop_est: 19356544,
        pop_rank: 14,
        gdp_md: 250077,
        iso2: 'RO',
        iso3: 'ROU',
        name: 'Romania',
    },
    {
        pop_est: 10669709,
        pop_rank: 14,
        gdp_md: 250680,
        iso2: 'CZ',
        iso3: 'CZE',
        name: 'Czechia',
    },
];

// Former EU Members
export const FormerEUMembers = [
    {
        pop_est: 66834405,
        pop_rank: 16,
        gdp_md: 2829108,
        iso2: 'GB',
        iso3: 'GBR',
        name: 'United Kingdom',
    },
];

// Official EU Candidate Countries
export const EUCandidateCountries = [
    {
        pop_est: 44385155,
        pop_rank: 15,
        gdp_md: 153781,
        iso2: 'UA',
        iso3: 'UKR',
        name: 'Ukraine',
    },
    {
        pop_est: 2083459,
        pop_rank: 12,
        gdp_md: 12547,
        iso2: 'MK',
        iso3: 'MKD',
        name: 'North Macedonia',
    },
    {
        pop_est: 2854191,
        pop_rank: 12,
        gdp_md: 15279,
        iso2: 'AL',
        iso3: 'ALB',
        name: 'Albania',
    },
    {
        pop_est: 6944975,
        pop_rank: 13,
        gdp_md: 51475,
        iso2: 'RS',
        iso3: 'SRB',
        name: 'Serbia',
    },
    {
        pop_est: 622137,
        pop_rank: 11,
        gdp_md: 5542,
        iso2: 'ME',
        iso3: 'MNE',
        name: 'Montenegro',
    },
    {
        pop_est: 3301000,
        pop_rank: 12,
        gdp_md: 20164,
        iso2: 'BA',
        iso3: 'BIH',
        name: 'Bosnia and Herzegovina',
    },
    {
        pop_est: 3720382,
        pop_rank: 12,
        gdp_md: 17477,
        iso2: 'GE',
        iso3: 'GEO',
        name: 'Georgia',
    },
    {
        pop_est: 83429615,
        pop_rank: 16,
        gdp_md: 761425,
        iso2: 'TR',
        iso3: 'TUR',
        name: 'Türkiye',
    },
    {
        pop_est: 2657637,
        pop_rank: 12,
        gdp_md: 11968,
        iso2: 'MD',
        iso3: 'MDA',
        name: 'Moldova',
    },
];

// European Single Market / EEA-aligned states (non-EU)
export const EEASingleMarketStates = [
    {
        pop_est: 5347896,
        pop_rank: 13,
        gdp_md: 403336,
        iso2: 'NO',
        iso3: 'NOR',
        name: 'Norway',
    },
    {
        pop_est: 361313,
        pop_rank: 10,
        gdp_md: 24188,
        iso2: 'IS',
        iso3: 'ISL',
        name: 'Iceland',
    },
    {
        pop_est: 38019,
        pop_rank: 7,
        gdp_md: 6876,
        iso2: 'LI',
        iso3: 'LIE',
        name: 'Liechtenstein',
    },
    {
        pop_est: 8574832,
        pop_rank: 13,
        gdp_md: 703082,
        iso2: 'CH',
        iso3: 'CHE',
        name: 'Switzerland',
    },
];

// Euro-using microstates (not EU members)
export const EuroUsingMicrostates = [
    {
        pop_est: 38964,
        pop_rank: 7,
        gdp_md: 7188,
        iso2: 'MC',
        iso3: 'MCO',
        name: 'Monaco',
    },
    {
        pop_est: 33860,
        pop_rank: 7,
        gdp_md: 1655,
        iso2: 'SM',
        iso3: 'SMR',
        name: 'San Marino',
    },
    {
        pop_est: 825,
        pop_rank: 2,
        gdp_md: -99,
        iso2: 'VA',
        iso3: 'VAT',
        name: 'Vatican City',
    },
    {
        pop_est: 77142,
        pop_rank: 8,
        gdp_md: 3154,
        iso2: 'AD',
        iso3: 'AND',
        name: 'Andorra',
    },
];

// Other European states (not EU / Candidate / EEA / Euro microstate)
export const OtherEuropeanStates = [
    {
        pop_est: 9466856,
        pop_rank: 13,
        gdp_md: 63080,
        iso2: 'BY',
        iso3: 'BLR',
        name: 'Belarus',
    },
    {
        pop_est: 144373535,
        pop_rank: 17,
        gdp_md: 1699876,
        iso2: 'RU',
        iso3: 'RUS',
        name: 'Russian Federation',
    },
    {
        pop_est: 10023318,
        pop_rank: 14,
        gdp_md: 48047,
        iso2: 'AZ',
        iso3: 'AZE',
        name: 'Azerbaijan',
    },
    {
        pop_est: 2957731,
        pop_rank: 12,
        gdp_md: 13672,
        iso2: 'AM',
        iso3: 'ARM',
        name: 'Armenia',
    },
    {
        pop_est: 107800,
        pop_rank: 9,
        gdp_md: 5080,
        iso2: 'JE',
        iso3: 'JEY',
        name: 'Jersey',
    },
    {
        pop_est: 62792,
        pop_rank: 8,
        gdp_md: 3465,
        iso2: 'GG',
        iso3: 'GGY',
        name: 'Guernsey',
    },
    {
        pop_est: 84584,
        pop_rank: 8,
        gdp_md: 7491,
        iso2: 'IM',
        iso3: 'IMN',
        name: 'Isle of Man',
    },
    {
        pop_est: 48678,
        pop_rank: 7,
        gdp_md: 3116,
        iso2: 'FO',
        iso3: 'FRO',
        name: 'Faroes',
    },
];
