export function getData() {
    return [
        {
            volume: 0.5,
            volumeLower: 0.45,
            volumeUpper: 0.55,
            pressure: 9.5,
            pressureLower: 10.3,
            pressureUpper: 8.7,
        },
        {
            volume: 1.0,
            volumeLower: 0.9,
            volumeUpper: 1.1,
            pressure: 8.1,
            pressureLower: 8.9,
            pressureUpper: 7.4,
        },
        {
            volume: 1.5,
            volumeLower: 1.35,
            volumeUpper: 1.65,
            pressure: 6.8,
            pressureLower: 7.5,
            pressureUpper: 6.2,
        },
        {
            volume: 2.0,
            volumeLower: 1.8,
            volumeUpper: 2.2,
            pressure: 5.5,
            pressureLower: 5.9,
            pressureUpper: 5.0,
        },
        {
            volume: 2.5,
            volumeLower: 2.25,
            volumeUpper: 2.75,
            pressure: 4.2,
            pressureLower: 4.7,
            pressureUpper: 3.8,
        },
        {
            volume: 3.0,
            volumeLower: 2.7,
            volumeUpper: 3.3,
            pressure: 3.1,
            pressureLower: 3.5,
            pressureUpper: 2.8,
        },
        {
            volume: 3.5,
            volumeLower: 3.15,
            volumeUpper: 3.85,
            pressure: 2.0,
            pressureLower: 2.3,
            pressureUpper: 1.8,
        },
        {
            volume: 4.0,
            volumeLower: 3.6,
            volumeUpper: 4.4,
            pressure: 1.2,
            pressureLower: 1.4,
            pressureUpper: 1.1,
        },
    ];
}
