import type { ExtensibleSeriesTheme } from 'ag-charts-community';
import {
    BASE_FONT_SIZE,
    COMMON_SERIES_THEME_DEFAULTS,
    FONT_SIZE_RATIO,
    SERIES_SELECTION_THEME,
    undocumentedThemeOptions,
} from 'ag-charts-core';

// Text tiers draw no backing box until `fill` or `stroke` is set; these keep the box geometry defined.
const NODE_TEXT_BOX_DEFAULTS = { cornerRadius: 0, fillOpacity: 1, strokeOpacity: 1, strokeWidth: 0 } as const;

export const organizationSeriesTheme: ExtensibleSeriesTheme<'organization'> = {
    zoom: {
        enabled: true,
        enableAxisDragging: false,
        enableAxisScrolling: false,
        enablePanning: true,
        enableScrolling: true,
        enableTwoFingerZoom: true,
        enableDoubleClickToReset: true,
        axes: 'xy',
        keepAspectRatio: true,
        anchorPointX: 'pointer',
        anchorPointY: 'pointer',
        autoScaling: { enabled: false },
        onDataChange: { strategy: 'preserveRatios' },
        minVisibleItems: 1,
        buttons: { enabled: false },
    },
    series: {
        ...COMMON_SERIES_THEME_DEFAULTS,
        ...undocumentedThemeOptions({ idKey: 'id', parentIdKey: 'parentId' }),
        direction: 'vertical',
        reverse: false,
        depthSpacing: { $path: ['./verticalSpacing', 52] },
        innerSpacing: 20,
        outerSpacing: 40,
        expander: {
            enabled: true,
            cornerRadius: { $path: '../node/cornerRadius' },
            fill: { $path: '../node/fill' },
            fillOpacity: 1,
            stroke: { $path: '../node/stroke' },
            strokeOpacity: { $path: '../node/strokeOpacity' },
            strokeWidth: { $path: '../node/strokeWidth' },
            lineDash: { $path: '../node/lineDash' },
            lineDashOffset: { $path: '../node/lineDashOffset' },
            padding: { $applyPadding: { top: 5, right: 7.5, bottom: 5, left: 7.5 } },
            hoverStyle: {
                // Background-only, matching the default toolbar and range button hover background — an
                // accentColor/backgroundColor mix.
                fill: { $ref: 'focusColor' },
            },
            text: {
                color: { $ref: 'subtleTextColor' },
                fontFamily: { $ref: 'fontFamily' },
                fontSize: { $rem: FONT_SIZE_RATIO.SMALL },
                fontStyle: 'normal',
                fontWeight: 'normal',
                showAllChildren: true,
                showDirectChildren: false,
                textAlign: 'left',
            },
        },
        highlight: {
            enabled: { $path: ['/highlight/enabled', true] },
            highlightedItem: {
                stroke: { $ref: 'accentColor' },
                strokeWidth: 2,
            },
        },
        selection: SERIES_SELECTION_THEME,
        layout: {
            linkIndentation: { $if: [{ $eq: [{ $path: '../direction' }, 'horizontal'] }, 18, 26] },
            nodeIndentation: 26,
            stackFromDepth: 4,
        } as any,
        link: {
            interpolation: {
                type: 'step',
                cornerRadius: 8,
            },
            lineDash: [],
            lineDashOffset: 0,
            stroke: { $foregroundBackgroundMix: 0.2 },
            strokeOpacity: 1,
            strokeWidth: 1,
        },
        tooltip: {
            enabled: false,
            interaction: { enabled: false },
        },
        node: {
            cornerRadius: 4,
            fill: { $foregroundBackgroundMix: 0.02 },
            fillOpacity: 1,
            lineDash: [],
            lineDashOffset: 0,
            padding: { $applyPadding: 8 },
            stroke: { $foregroundBackgroundMix: 0.2 },
            strokeOpacity: 1,
            strokeWidth: 1,
            image: {
                cornerRadius: 0,
                enabled: true,
                key: 'image',
                height: 50,
                position: 'top',
                spacing: 8,
                width: 50,
            },
            title: {
                ...NODE_TEXT_BOX_DEFAULTS,
                enabled: true,
                color: { $ref: 'foregroundColor' },
                fontFamily: { $ref: 'fontFamily' },
                fontSize: { $rem: FONT_SIZE_RATIO.LARGE },
                fontStyle: 'normal',
                fontWeight: 'bold',
                key: 'title',
                overflowStrategy: 'ellipsis',
                padding: { $applyPadding: 0 },
                spacing: 4,
                textAlign: 'center',
                wrapping: 'on-space',
            },
            subtitle: {
                ...NODE_TEXT_BOX_DEFAULTS,
                enabled: true,
                color: { $ref: 'subtleTextColor' },
                fontFamily: { $ref: 'fontFamily' },
                fontSize: { $rem: FONT_SIZE_RATIO.SMALL },
                fontStyle: 'normal',
                fontWeight: 'normal',
                key: 'subtitle',
                overflowStrategy: 'ellipsis',
                padding: { $applyPadding: 0 },
                spacing: 4,
                textAlign: 'center',
                wrapping: 'on-space',
            },
            labels: {
                $apply: {
                    ...NODE_TEXT_BOX_DEFAULTS,
                    enabled: true,
                    color: { $ref: 'subtleTextColor' },
                    fontFamily: { $ref: 'fontFamily' },
                    fontSize: { $rem: 11 / BASE_FONT_SIZE },
                    fontStyle: 'normal',
                    fontWeight: 'normal',
                    overflowStrategy: 'ellipsis',
                    padding: { $applyPadding: 0 },
                    spacing: 4,
                    textAlign: 'center',
                    wrapping: 'on-space',
                },
            },
            clickToExpand: {
                $not: {
                    $or: [
                        { $path: ['/series/$index/selection/enabled', false] },
                        { $isUserOption: '/listeners/seriesNodeClick' },
                        { $isUserOption: '/listeners/seriesNodeDoubleClick' },
                        { $isUserOption: '/series/$index/listeners/seriesNodeClick' },
                        { $isUserOption: '/series/$index/listeners/seriesNodeDoubleClick' },
                    ],
                },
            },
        },
    },
};
