// Source: http://www.sheffieldweather.co.uk/Averages/MONTHLYAIRAVERAGE.htm
export function getData() {
    return [
        // 2011
        {
            year: '2011',
            month: 'Jan',
            temperature: 3.9,
            change: 3.9 / 1.2 - 1,
        },
        {
            year: '2011',
            month: 'Feb',
            temperature: 6,
            change: 6 / 1.9 - 1,
        },
        {
            year: '2011',
            month: 'Mar',
            temperature: 6.6,
            change: 6.6 / 5.9 - 1,
        },
        {
            year: '2011',
            month: 'Apr',
            temperature: 12,
            change: 12 / 9.1 - 1,
        },
        {
            year: '2011',
            month: 'May',
            temperature: 12,
            change: 12 / 10.9 - 1,
        },
        {
            year: '2011',
            month: 'Jun',
            temperature: 14.2,
            change: 14.2 / 15.2 - 1,
        },
        {
            year: '2011',
            month: 'Jul',
            temperature: 15.8,
            change: 15.8 / 16.2 - 1,
        },
        {
            year: '2011',
            month: 'Aug',
            temperature: 15.8,
            change: 15.8 / 14.9 - 1,
        },
        {
            year: '2011',
            month: 'Sep',
            temperature: 14.9,
            change: 14.9 / 13.4 - 1,
        },
        {
            year: '2011',
            month: 'Oct',
            temperature: 12.2,
            change: 12.2 / 9.5 - 1,
        },
        {
            year: '2011',
            month: 'Nov',
            temperature: 8.9,
            change: 8.9 / 4.9 - 1,
        },
        {
            year: '2011',
            month: 'Dec',
            temperature: 5.4,
            change: 5.4 / 0.4 - 1,
        },
        // 2012
        {
            year: '2012',
            month: 'Jan',
            temperature: 5.1,
            change: 5.1 / 3.9 - 1,
        },
        {
            year: '2012',
            month: 'Feb',
            temperature: 4.5,
            change: 4.5 / 6 - 1,
        },
        {
            year: '2012',
            month: 'Mar',
            temperature: 8.6,
            change: 8.6 / 6.6 - 1,
        },
        {
            year: '2012',
            month: 'Apr',
            temperature: 6.7,
            change: 6.7 / 12 - 1,
        },
        {
            year: '2012',
            month: 'May',
            temperature: 11.6,
            change: 11.6 / 12 - 1,
        },
        {
            year: '2012',
            month: 'Jun',
            temperature: 13.4,
            change: 13.4 / 14.2 - 1,
        },
        {
            year: '2012',
            month: 'Jul',
            temperature: 15.5,
            change: 15.5 / 15.8 - 1,
        },
        {
            year: '2012',
            month: 'Aug',
            temperature: 16.2,
            change: 16.2 / 15.8 - 1,
        },
        {
            year: '2012',
            month: 'Sep',
            temperature: 12.7,
            change: 12.7 / 14.9 - 1,
        },
        {
            year: '2012',
            month: 'Oct',
            temperature: 8.8,
            change: 8.8 / 12.2 - 1,
        },
        {
            year: '2012',
            month: 'Nov',
            temperature: 6.1,
            change: 6.1 / 8.9 - 1,
        },
        {
            year: '2012',
            month: 'Dec',
            temperature: 4.2,
            change: 4.2 / 5.4 - 1,
        },
        // 2013
        {
            year: '2013',
            month: 'Jan',
            temperature: 3.4,
            change: 3.4 / 5.1 - 1,
        },
        {
            year: '2013',
            month: 'Feb',
            temperature: 2.7,
            change: 2.7 / 4.5 - 1,
        },
        {
            year: '2013',
            month: 'Mar',
            temperature: 1.7,
            change: 1.7 / 8.6 - 1,
        },
        {
            year: '2013',
            month: 'Apr',
            temperature: 7.4,
            change: 7.4 / 6.7 - 1,
        },
        {
            year: '2013',
            month: 'May',
            temperature: 10.6,
            change: 10.6 / 11.6 - 1,
        },
        {
            year: '2013',
            month: 'Jun',
            temperature: 14.1,
            change: 14.1 / 13.4 - 1,
        },
        {
            year: '2013',
            month: 'Jul',
            temperature: 18.4,
            change: 18.4 / 15.5 - 1,
        },
        {
            year: '2013',
            month: 'Aug',
            temperature: 16.8,
            change: 16.8 / 16.2 - 1,
        },
        {
            year: '2013',
            month: 'Sep',
            temperature: 13.3,
            change: 13.3 / 12.7 - 1,
        },
        {
            year: '2013',
            month: 'Oct',
            temperature: 11.7,
            change: 11.7 / 8.8 - 1,
        },
        {
            year: '2013',
            month: 'Nov',
            temperature: 6.2,
            change: 6.2 / 6.1 - 1,
        },
        {
            year: '2013',
            month: 'Dec',
            temperature: 6.3,
            change: 6.3 / 4.2 - 1,
        },
        // 2014
        {
            year: '2014',
            month: 'Jan',
            temperature: 5,
            change: 5 / 3.4 - 1,
        },
        {
            year: '2014',
            month: 'Feb',
            temperature: 5.6,
            change: 5.6 / 2.7 - 1,
        },
        {
            year: '2014',
            month: 'Mar',
            temperature: 7.4,
            change: 7.4 / 1.7 - 1,
        },
        {
            year: '2014',
            month: 'Apr',
            temperature: 10.1,
            change: 10.1 / 7.4 - 1,
        },
        {
            year: '2014',
            month: 'May',
            temperature: 12.2,
            change: 12.2 / 10.6 - 1,
        },
        {
            year: '2014',
            month: 'Jun',
            temperature: 15.3,
            change: 15.3 / 14.1 - 1,
        },
        {
            year: '2014',
            month: 'Jul',
            temperature: 17.9,
            change: 17.9 / 18.4 - 1,
        },
        {
            year: '2014',
            month: 'Aug',
            temperature: 14.9,
            change: 14.9 / 16.8 - 1,
        },
        {
            year: '2014',
            month: 'Sep',
            temperature: 14.4,
            change: 14.4 / 13.3 - 1,
        },
        {
            year: '2014',
            month: 'Oct',
            temperature: 11.4,
            change: 11.4 / 11.7 - 1,
        },
        {
            year: '2014',
            month: 'Nov',
            temperature: 7.8,
            change: 7.8 / 6.2 - 1,
        },
        {
            year: '2014',
            month: 'Dec',
            temperature: 5.2,
            change: 5.2 / 6.3 - 1,
        },
        // 2015
        {
            year: '2015',
            month: 'Jan',
            temperature: 4.1,
            change: 4.1 / 5 - 1,
        },
        {
            year: '2015',
            month: 'Feb',
            temperature: 3.8,
            change: 3.8 / 5.6 - 1,
        },
        {
            year: '2015',
            month: 'Mar',
            temperature: 5.9,
            change: 5.9 / 7.4 - 1,
        },
        {
            year: '2015',
            month: 'Apr',
            temperature: 9.1,
            change: 9.1 / 10.1 - 1,
        },
        {
            year: '2015',
            month: 'May',
            temperature: 10.6,
            change: 10.6 / 12.2 - 1,
        },
        {
            year: '2015',
            month: 'Jun',
            temperature: 13.9,
            change: 13.9 / 15.3 - 1,
        },
        {
            year: '2015',
            month: 'Jul',
            temperature: 15.7,
            change: 15.7 / 17.9 - 1,
        },
        {
            year: '2015',
            month: 'Aug',
            temperature: 15.8,
            change: 15.8 / 14.9 - 1,
        },
        {
            year: '2015',
            month: 'Sep',
            temperature: 12.2,
            change: 12.2 / 14.4 - 1,
        },
        {
            year: '2015',
            month: 'Oct',
            temperature: 10.2,
            change: 10.2 / 11.4 - 1,
        },
        {
            year: '2015',
            month: 'Nov',
            temperature: 8.7,
            change: 8.7 / 7.8 - 1,
        },
        {
            year: '2015',
            month: 'Dec',
            temperature: 8.6,
            change: 8.6 / 5.2 - 1,
        },
        // 2016
        {
            year: '2016',
            month: 'Jan',
            temperature: 4.8,
            change: 4.8 / 4.1 - 1,
        },
        {
            year: '2016',
            month: 'Feb',
            temperature: 4.2,
            change: 4.2 / 3.8 - 1,
        },
        {
            year: '2016',
            month: 'Mar',
            temperature: 5.5,
            change: 5.5 / 5.9 - 1,
        },
        {
            year: '2016',
            month: 'Apr',
            temperature: 7,
            change: 7 / 9.1 - 1,
        },
        {
            year: '2016',
            month: 'May',
            temperature: 11.8,
            change: 11.8 / 10.6 - 1,
        },
        {
            year: '2016',
            month: 'Jun',
            temperature: 14.6,
            change: 14.6 / 13.9 - 1,
        },
        {
            year: '2016',
            month: 'Jul',
            temperature: 16.6,
            change: 16.6 / 15.7 - 1,
        },
        {
            year: '2016',
            month: 'Aug',
            temperature: 16.6,
            change: 16.6 / 15.8 - 1,
        },
        {
            year: '2016',
            month: 'Sep',
            temperature: 15.4,
            change: 15.4 / 12.2 - 1,
        },
        {
            year: '2016',
            month: 'Oct',
            temperature: 10.2,
            change: 10.2 / 10.2 - 1,
        },
        {
            year: '2016',
            month: 'Nov',
            temperature: 5.4,
            change: 5.4 / 8.7 - 1,
        },
        {
            year: '2016',
            month: 'Dec',
            temperature: 6.3,
            change: 6.3 / 8.6 - 1,
        },
        // 2017
        {
            year: '2017',
            month: 'Jan',
            temperature: 3.9,
            change: 3.9 / 4.8 - 1,
        },
        {
            year: '2017',
            month: 'Feb',
            temperature: 5.2,
            change: 5.2 / 4.2 - 1,
        },
        {
            year: '2017',
            month: 'Mar',
            temperature: 8,
            change: 8 / 5.5 - 1,
        },
        {
            year: '2017',
            month: 'Apr',
            temperature: 8.6,
            change: 8.6 / 7 - 1,
        },
        {
            year: '2017',
            month: 'May',
            temperature: 12.8,
            change: 12.8 / 11.8 - 1,
        },
        {
            year: '2017',
            month: 'Jun',
            temperature: 15.7,
            change: 15.7 / 14.6 - 1,
        },
        {
            year: '2017',
            month: 'Jul',
            temperature: 16.4,
            change: 16.4 / 16.6 - 1,
        },
        {
            year: '2017',
            month: 'Aug',
            temperature: 15.2,
            change: 15.2 / 16.6 - 1,
        },
        {
            year: '2017',
            month: 'Sep',
            temperature: 13,
            change: 13 / 15.4 - 1,
        },
        {
            year: '2017',
            month: 'Oct',
            temperature: 11.9,
            change: 11.9 / 10.2 - 1,
        },
        {
            year: '2017',
            month: 'Nov',
            temperature: 6.5,
            change: 6.5 / 5.4 - 1,
        },
        {
            year: '2017',
            month: 'Dec',
            temperature: 4.7,
            change: 4.7 / 6.3 - 1,
        },
        // 2018
        {
            year: '2018',
            month: 'Jan',
            temperature: 4.4,
            change: 4.4 / 3.9 - 1,
        },
        {
            year: '2018',
            month: 'Feb',
            temperature: 2.3,
            change: 2.3 / 5.2 - 1,
        },
        {
            year: '2018',
            month: 'Mar',
            temperature: 3.7,
            change: 3.7 / 8 - 1,
        },
        {
            year: '2018',
            month: 'Apr',
            temperature: 8.8,
            change: 8.8 / 8.6 - 1,
        },
        {
            year: '2018',
            month: 'May',
            temperature: 13.8,
            change: 13.8 / 12.8 - 1,
        },
        {
            year: '2018',
            month: 'Jun',
            temperature: 16.4,
            change: 16.4 / 15.7 - 1,
        },
        {
            year: '2018',
            month: 'Jul',
            temperature: 19.5,
            change: 19.5 / 16.4 - 1,
        },
        {
            year: '2018',
            month: 'Aug',
            temperature: 17,
            change: 17 / 15.2 - 1,
        },
        {
            year: '2018',
            month: 'Sep',
            temperature: 13.4,
            change: 13.4 / 13 - 1,
        },
        {
            year: '2018',
            month: 'Oct',
            temperature: 10.3,
            change: 10.3 / 11.9 - 1,
        },
        {
            year: '2018',
            month: 'Nov',
            temperature: 7.4,
            change: 7.4 / 6.5 - 1,
        },
        {
            year: '2018',
            month: 'Dec',
            temperature: 6.4,
            change: 6.4 / 4.7 - 1,
        },
        // 2019
        {
            year: '2019',
            month: 'Jan',
            temperature: 4.4,
            change: 4.4 / 4.4 - 1,
        },
        {
            year: '2019',
            month: 'Feb',
            temperature: 6.9,
            change: 6.9 / 2.3 - 1,
        },
        {
            year: '2019',
            month: 'Mar',
            temperature: 7.5,
            change: 7.5 / 3.7 - 1,
        },
        {
            year: '2019',
            month: 'Apr',
            temperature: 8.9,
            change: 8.9 / 8.8 - 1,
        },
        {
            year: '2019',
            month: 'May',
            temperature: 11.5,
            change: 11.5 / 13.8 - 1,
        },
        {
            year: '2019',
            month: 'Jun',
            temperature: 14.1,
            change: 14.1 / 16.4 - 1,
        },
        {
            year: '2019',
            month: 'Jul',
            temperature: 17.8,
            change: 17.8 / 19.5 - 1,
        },
        {
            year: '2019',
            month: 'Aug',
            temperature: 17.1,
            change: 17.1 / 17 - 1,
        },
        {
            year: '2019',
            month: 'Sep',
            temperature: 13.7,
            change: 13.7 / 13.4 - 1,
        },
        {
            year: '2019',
            month: 'Oct',
            temperature: 9.2,
            change: 9.2 / 10.3 - 1,
        },
        {
            year: '2019',
            month: 'Nov',
            temperature: 5.4,
            change: 5.4 / 7.4 - 1,
        },
        {
            year: '2019',
            month: 'Dec',
            temperature: 5.4,
            change: 5.4 / 6.4 - 1,
        },
        // 2020
        {
            year: '2020',
            month: 'Jan',
            temperature: 6.4,
            change: 6.4 / 4.4 - 1,
        },
        {
            year: '2020',
            month: 'Feb',
            temperature: 5.6,
            change: 5.6 / 6.9 - 1,
        },
        {
            year: '2020',
            month: 'Mar',
            temperature: 6.3,
            change: 6.3 / 7.5 - 1,
        },
        {
            year: '2020',
            month: 'Apr',
            temperature: 10.3,
            change: 10.3 / 8.9 - 1,
        },
        {
            year: '2020',
            month: 'May',
            temperature: 12.8,
            change: 12.8 / 11.5 - 1,
        },
        {
            year: '2020',
            month: 'Jun',
            temperature: 15,
            change: 15 / 14.1 - 1,
        },
        {
            year: '2020',
            month: 'Jul',
            temperature: 15.6,
            change: 15.6 / 17.8 - 1,
        },
        {
            year: '2020',
            month: 'Aug',
            temperature: 17.2,
            change: 17.2 / 17.1 - 1,
        },
        {
            year: '2020',
            month: 'Sep',
            temperature: 13.7,
            change: 13.7 / 13.7 - 1,
        },
        {
            year: '2020',
            month: 'Oct',
            temperature: 9.8,
            change: 9.8 / 9.2 - 1,
        },
        {
            year: '2020',
            month: 'Nov',
            temperature: 8.1,
            change: 8.1 / 5.4 - 1,
        },
        {
            year: '2020',
            month: 'Dec',
            temperature: 4.6,
            change: 4.6 / 5.4 - 1,
        },
        // 2021
        {
            year: '2021',
            month: 'Jan',
            temperature: 2.8,
            change: 2.8 / 6.4 - 1,
        },
        {
            year: '2021',
            month: 'Feb',
            temperature: 4.3,
            change: 4.3 / 5.6 - 1,
        },
        {
            year: '2021',
            month: 'Mar',
            temperature: 7.2,
            change: 7.2 / 6.3 - 1,
        },
        {
            year: '2021',
            month: 'Apr',
            temperature: 6.5,
            change: 6.5 / 10.3 - 1,
        },
        {
            year: '2021',
            month: 'May',
            temperature: 10,
            change: 10 / 12.8 - 1,
        },
        {
            year: '2021',
            month: 'Jun',
            temperature: 16.1,
            change: 16.1 / 15 - 1,
        },
        {
            year: '2021',
            month: 'Jul',
            temperature: 18.4,
            change: 18.4 / 15.6 - 1,
        },
        {
            year: '2021',
            month: 'Aug',
            temperature: 16.1,
            change: 16.1 / 17.2 - 1,
        },
        {
            year: '2021',
            month: 'Sep',
            temperature: 16.2,
            change: 16.2 / 13.7 - 1,
        },
        {
            year: '2021',
            month: 'Oct',
            temperature: 11.6,
            change: 11.6 / 9.8 - 1,
        },
        {
            year: '2021',
            month: 'Nov',
            temperature: 7.7,
            change: 7.7 / 8.1 - 1,
        },
        {
            year: '2021',
            month: 'Dec',
            temperature: 5.4,
            change: 5.4 / 4.6 - 1,
        },
        // 2022
        {
            year: '2022',
            month: 'Jan',
            temperature: 5.2,
            change: 5.2 / 2.8 - 1,
        },
        {
            year: '2022',
            month: 'Feb',
            temperature: 6.1,
            change: 6.1 / 4.3 - 1,
        },
        {
            year: '2022',
            month: 'Mar',
            temperature: 7.4,
            change: 7.4 / 7.2 - 1,
        },
        {
            year: '2022',
            month: 'Apr',
            temperature: 9.2,
            change: 9.2 / 6.5 - 1,
        },
        {
            year: '2022',
            month: 'May',
            temperature: 13.3,
            change: 13.3 / 10 - 1,
        },
        {
            year: '2022',
            month: 'Jun',
            temperature: 15.5,
            change: 15.5 / 16.1 - 1,
        },
        {
            year: '2022',
            month: 'Jul',
            temperature: 18.5,
            change: 18.5 / 18.4 - 1,
        },
        {
            year: '2022',
            month: 'Aug',
            temperature: 18.4,
            change: 18.4 / 16.1 - 1,
        },
        {
            year: '2022',
            month: 'Sep',
            temperature: 14.5,
            change: 14.5 / 16.2 - 1,
        },
        {
            year: '2022',
            month: 'Oct',
            temperature: 12.1,
            change: 12.1 / 11.6 - 1,
        },
        {
            year: '2022',
            month: 'Nov',
            temperature: 8.4,
            change: 8.4 / 7.7 - 1,
        },
        {
            year: '2022',
            month: 'Dec',
            temperature: 3.6,
            change: 3.6 / 5.4 - 1,
        },
    ];
}
