export function getData() {
    return [
        { day: 1, distance: 0, elevation: 1100, altitudeGain: 100, location: 'Start (Pokhara)', direction: 'Ascent' },
        { day: 1, distance: 2, elevation: 1300, altitudeGain: 200, location: 'Birethanti', direction: 'Ascent' },
        { day: 1, distance: 4, elevation: 1400, altitudeGain: 100, location: 'Hile', direction: 'Ascent' },
        { day: 1, distance: 7, elevation: 1500, altitudeGain: 100, location: 'Tikhedhunga (End)', direction: 'Ascent' },
        {
            day: 2,
            distance: 7,
            elevation: 1500,
            altitudeGain: 100,
            location: 'Start (Tikhedhunga)',
            direction: 'Ascent',
        },
        { day: 2, distance: 9, elevation: 2000, altitudeGain: 500, location: 'Ulleri', direction: 'Ascent' },
        { day: 2, distance: 10, elevation: 2300, altitudeGain: 300, location: 'Banthanti', direction: 'Ascent' },
        { day: 2, distance: 12, elevation: 2600, altitudeGain: 300, location: 'Nange Thanti', direction: 'Ascent' },
        { day: 2, distance: 13, elevation: 2800, altitudeGain: 200, location: 'Ghorepani (End)', direction: 'Ascent' },
        {
            day: 3,
            distance: 13,
            elevation: 2800,
            altitudeGain: 200,
            location: 'Start (Ghorepani)',
            direction: 'Ascent',
        },
        {
            day: 3,
            distance: 14,
            elevation: 3100,
            altitudeGain: 300,
            location: 'Poon Hill (Start)',
            direction: 'Ascent',
        },
        {
            day: 3,
            distance: 15,
            elevation: 3200,
            altitudeGain: 100,
            location: 'Poon Hill (Sunrise View)',
            direction: 'Ascent',
        },
        {
            day: 3,
            distance: 17,
            elevation: 2700,
            altitudeGain: -500,
            location: 'Tadapani (Midway)',
            direction: 'Ascent',
        },
        { day: 3, distance: 19, elevation: 2600, altitudeGain: -100, location: 'Tadapani (End)', direction: 'Ascent' },
        {
            day: 4,
            distance: 19,
            elevation: 2600,
            altitudeGain: -100,
            location: 'Start (Tadapani)',
            direction: 'Ascent',
        },
        { day: 4, distance: 21, elevation: 2500, altitudeGain: -100, location: 'Chomrong Danda', direction: 'Ascent' },
        { day: 4, distance: 23, elevation: 2300, altitudeGain: -200, location: 'Chhomrong', direction: 'Ascent' },
        { day: 4, distance: 26, elevation: 2170, altitudeGain: -150, location: 'Chhomrong (End)', direction: 'Ascent' },
        {
            day: 5,
            distance: 26,
            elevation: 2170,
            altitudeGain: -150,
            location: 'Start (Chhomrong)',
            direction: 'Ascent',
        },
        { day: 5, distance: 28, elevation: 2300, altitudeGain: 150, location: 'Kymrong', direction: 'Ascent' },
        { day: 5, distance: 30, elevation: 2400, altitudeGain: 100, location: 'Sinuwa', direction: 'Ascent' },
        { day: 5, distance: 34, elevation: 2700, altitudeGain: 300, location: 'Dovan', direction: 'Ascent' },
        { day: 5, distance: 36, elevation: 2900, altitudeGain: 100, location: 'Himalaya (End)', direction: 'Ascent' },
        { day: 6, distance: 36, elevation: 2900, altitudeGain: 100, location: 'Start (Himalaya)', direction: 'Ascent' },
        { day: 6, distance: 38, elevation: 3300, altitudeGain: 300, location: 'Deurali', direction: 'Ascent' },
        {
            day: 6,
            distance: 42,
            elevation: 3700,
            altitudeGain: 400,
            location: 'MBC (Machapuchare Base Camp)',
            direction: 'Ascent',
        },
        {
            day: 6,
            distance: 44,
            elevation: 3900,
            altitudeGain: 200,
            location: 'Annapurna South Base Camp',
            direction: 'Ascent',
        },
        {
            day: 6,
            distance: 46,
            elevation: 4130,
            altitudeGain: 230,
            location: 'Annapurna Base Camp (End)',
            direction: 'Ascent',
        },
        {
            day: 7,
            distance: 46,
            elevation: 4130,
            altitudeGain: -130,
            location: 'Start (Annapurna Base Camp)',
            direction: 'Descent',
        },
        {
            day: 7,
            distance: 48,
            elevation: 3700,
            altitudeGain: -300,
            location: 'MBC (Machapuchare Base Camp)',
            direction: 'Descent',
        },
        { day: 7, distance: 52, elevation: 3300, altitudeGain: -400, location: 'Deurali', direction: 'Descent' },
        { day: 7, distance: 54, elevation: 2900, altitudeGain: -400, location: 'Himalaya', direction: 'Descent' },
        { day: 7, distance: 56, elevation: 2700, altitudeGain: -200, location: 'Sinuwa', direction: 'Descent' },
        { day: 7, distance: 59, elevation: 2500, altitudeGain: -200, location: 'Chomrong', direction: 'Descent' },
        { day: 7, distance: 62, elevation: 2310, altitudeGain: -190, location: 'Bamboo (End)', direction: 'Descent' },
        { day: 8, distance: 62, elevation: 2310, altitudeGain: -190, location: 'Start (Bamboo)', direction: 'Descent' },
        { day: 8, distance: 64, elevation: 2400, altitudeGain: -110, location: 'Sinuwa', direction: 'Descent' },
        { day: 8, distance: 67, elevation: 2000, altitudeGain: -400, location: 'Chomrong', direction: 'Descent' },
        {
            day: 8,
            distance: 69,
            elevation: 1700,
            altitudeGain: -300,
            location: 'Jhinu Danda (Hot Springs)',
            direction: 'Descent',
        },
        {
            day: 9,
            distance: 69,
            elevation: 1700,
            altitudeGain: -300,
            location: 'Start (Jhinu Danda)',
            direction: 'Descent',
        },
        { day: 9, distance: 71, elevation: 1300, altitudeGain: -400, location: 'Birethanti', direction: 'Descent' },
        { day: 9, distance: 74, elevation: 1200, altitudeGain: -100, location: 'Nayapul', direction: 'Descent' },
        { day: 9, distance: 77, elevation: 1000, altitudeGain: -100, location: 'Pokhara (End)', direction: 'Descent' },
    ];
}
