export function getData() {
    return [
        {
            vol: 0.5,
            volLower: 0.45,
            volUpper: 0.55,
            pres: 8.9,
            presLower: 8.1,
            presUpper: 9.6,
        },
        {
            vol: 1.0,
            volLower: 0.9,
            volUpper: 1.1,
            pres: 8.1,
            presLower: 7.4,
            presUpper: 8.9,
        },
        {
            vol: 1.5,
            volLower: 1.35,
            volUpper: 1.65,
            pres: 6.8,
            presLower: 6.2,
            presUpper: 7.5,
        },
        {
            vol: 2.0,
            volLower: 1.8,
            volUpper: 2.2,
            pres: 5.5,
            presLower: 5.0,
            presUpper: 5.9,
        },
        {
            vol: 2.5,
            volLower: 2.25,
            volUpper: 2.75,
            pres: 4.2,
            presLower: 3.8,
            presUpper: 4.7,
        },
        {
            vol: 3.0,
            volLower: 2.7,
            volUpper: 3.3,
            pres: 3.1,
            presLower: 2.8,
            presUpper: 3.5,
        },
        {
            vol: 3.5,
            volLower: 3.15,
            volUpper: 3.85,
            pres: 2.0,
            presLower: 1.8,
            presUpper: 2.3,
        },
        {
            vol: 4.0,
            volLower: 3.6,
            volUpper: 4.4,
            pres: 1.2,
            presLower: 1,
            presUpper: 1.6,
        },
    ];
}
