// Illustrative values following documented regional patterns, not measured station records.
export function getData() {
    return [
        { country: 'Iceland', tempAnomaly: 1.43, precipAnomaly: 8.2 },
        { country: 'Norway', tempAnomaly: 1.68, precipAnomaly: 9.9 },
        { country: 'Sweden', tempAnomaly: 1.8, precipAnomaly: 8.4 },
        { country: 'Finland', tempAnomaly: 1.98, precipAnomaly: 9.3 },
        { country: 'Estonia', tempAnomaly: 1.93, precipAnomaly: 8.2 },
        { country: 'Denmark', tempAnomaly: 1.61, precipAnomaly: 7.3 },
        { country: 'United Kingdom', tempAnomaly: 1.27, precipAnomaly: 6.3 },
        { country: 'Ireland', tempAnomaly: 1.09, precipAnomaly: 5.3 },
        { country: 'Netherlands', tempAnomaly: 1.59, precipAnomaly: 7.3 },
        { country: 'Belgium', tempAnomaly: 1.69, precipAnomaly: 4.6 },
        { country: 'France', tempAnomaly: 1.74, precipAnomaly: 1.8 },
        { country: 'Germany', tempAnomaly: 1.8, precipAnomaly: 3.8 },
        { country: 'Poland', tempAnomaly: 1.78, precipAnomaly: 3.4 },
        { country: 'Czechia', tempAnomaly: 1.89, precipAnomaly: 2.1 },
        { country: 'Austria', tempAnomaly: 1.98, precipAnomaly: 2.8 },
        { country: 'Hungary', tempAnomaly: 1.83, precipAnomaly: -0.8 },
        { country: 'Romania', tempAnomaly: 1.71, precipAnomaly: -1.8 },
        { country: 'Ukraine', tempAnomaly: 1.64, precipAnomaly: 1.2 },
        { country: 'Russia', tempAnomaly: 1.9, precipAnomaly: 5.7 },
        { country: 'Spain', tempAnomaly: 1.59, precipAnomaly: -8.9 },
        { country: 'Portugal', tempAnomaly: 1.4, precipAnomaly: -9.9 },
        { country: 'Italy', tempAnomaly: 1.71, precipAnomaly: -6.3 },
        { country: 'Greece', tempAnomaly: 1.47, precipAnomaly: -8.6 },
        { country: 'Turkey', tempAnomaly: 1.53, precipAnomaly: -8.1 },
        { country: 'Morocco', tempAnomaly: 1.29, precipAnomaly: -13.6 },
        { country: 'Algeria', tempAnomaly: 1.43, precipAnomaly: -12.2 },
        { country: 'Egypt', tempAnomaly: 1.36, precipAnomaly: -11.4 },
        { country: 'Iran', tempAnomaly: 1.71, precipAnomaly: -15.1 },
        { country: 'Iraq', tempAnomaly: 1.8, precipAnomaly: -16.2 },
        { country: 'Saudi Arabia', tempAnomaly: 1.92, precipAnomaly: -9.8 },
        { country: 'Senegal', tempAnomaly: 1.11, precipAnomaly: 6.6 },
        { country: 'Mali', tempAnomaly: 1.31, precipAnomaly: 6.1 },
        { country: 'Nigeria', tempAnomaly: 1.02, precipAnomaly: 5.3 },
        { country: 'Ghana', tempAnomaly: 1.03, precipAnomaly: 6.1 },
        { country: 'Ethiopia', tempAnomaly: 1.11, precipAnomaly: -3.0 },
        { country: 'Kenya', tempAnomaly: 1.06, precipAnomaly: -3.7 },
        { country: 'South Africa', tempAnomaly: 1.19, precipAnomaly: -6.1 },
        { country: 'Zimbabwe', tempAnomaly: 1.23, precipAnomaly: -5.2 },
        { country: 'India', tempAnomaly: 0.88, precipAnomaly: -2.3 },
        { country: 'Pakistan', tempAnomaly: 1.09, precipAnomaly: 2.9 },
        { country: 'Bangladesh', tempAnomaly: 0.98, precipAnomaly: 3.9 },
        { country: 'Sri Lanka', tempAnomaly: 0.86, precipAnomaly: 2.0 },
        { country: 'Thailand', tempAnomaly: 0.99, precipAnomaly: 3.9 },
        { country: 'Vietnam', tempAnomaly: 1.03, precipAnomaly: 2.9 },
        { country: 'Indonesia', tempAnomaly: 0.91, precipAnomaly: 5.3 },
        { country: 'Philippines', tempAnomaly: 0.87, precipAnomaly: 6.0 },
        { country: 'China', tempAnomaly: 1.53, precipAnomaly: 2.9 },
        { country: 'Mongolia', tempAnomaly: 2.11, precipAnomaly: -7.0 },
        { country: 'Japan', tempAnomaly: 1.38, precipAnomaly: 4.9 },
        { country: 'South Korea', tempAnomaly: 1.49, precipAnomaly: 6.0 },
        { country: 'Australia', tempAnomaly: 1.46, precipAnomaly: -5.1 },
        { country: 'New Zealand', tempAnomaly: 1.13, precipAnomaly: 3.4 },
        { country: 'United States', tempAnomaly: 1.3, precipAnomaly: 4.0 },
        { country: 'Canada', tempAnomaly: 1.81, precipAnomaly: 7.1 },
        { country: 'Mexico', tempAnomaly: 1.4, precipAnomaly: -6.3 },
        { country: 'Brazil', tempAnomaly: 1.1, precipAnomaly: -3.0 },
        { country: 'Argentina', tempAnomaly: 1.02, precipAnomaly: 4.9 },
        { country: 'Chile', tempAnomaly: 1.09, precipAnomaly: -17.7 },
        { country: 'Peru', tempAnomaly: 1.04, precipAnomaly: -1.6 },
    ];
}
