export function getData() {
  return [
    {
      dolphin: 'Peter',
      interactionDurationTM: 1.23,
      interactionDurationTMLower: 0.8,
      interactionDurationTMUpper: 1.44,
      interactionDurationYM: 2.85,
      interactionDurationYMLower: 3.45,
      interactionDurationYMUpper: 4.84,
      numberOfLooksTM: 60,
      numberOfLooksYM: 64,
    },
    {
      dolphin: 'Mary',
      interactionDurationTM: 1.35,
      interactionDurationTMLower: 0.9,
      interactionDurationTMUpper: 1.59,
      interactionDurationYM: 2.59,
      interactionDurationYMLower: 3.44,
      interactionDurationYMUpper: 4.2,
      numberOfLooksTM: 57,
      numberOfLooksYM: 93,
    },
    {
      dolphin: 'Mercutio',
      interactionDurationTM: 1.4,
      interactionDurationTMLower: 1.32,
      interactionDurationTMUpper: 1.46,
      interactionDurationYM: 1.45,
      interactionDurationYMLower: 2.5,
      interactionDurationYMUpper: 2.94,
      numberOfLooksTM: 238,
      numberOfLooksYM: 217,
    },
    {
      dolphin: 'Ada',
      interactionDurationTM: 1.1,
      interactionDurationTMLower: 0.89,
      interactionDurationTMUpper: 1.45,
      interactionDurationYM: 1.47,
      interactionDurationYMLower: 2.45,
      interactionDurationYMUpper: 2.74,
      numberOfLooksTM: 237,
      numberOfLooksYM: 217,
    },
  ];
}
