// Module placeholders generated from the exported module definitions by
// packages/ag-charts-enterprise/src/moduleTables.test.ts. Do not edit by hand:
// Run `UPDATE_MODULE_TABLES=1 yarn nx test ag-charts-enterprise -- moduleTables` to regenerate.
import { array, callback } from 'ag-charts-core';

import type { ModulePlaceholder } from './modulePlaceholder';

export const expectedModuleTable: readonly ModulePlaceholder[] = [
    {
        type: 'chart',
        name: 'cartesian',
        moduleId: 'CartesianChartModule',
    },
    {
        type: 'chart',
        name: 'polar',
        moduleId: 'PolarChartModule',
    },
    {
        type: 'chart',
        name: 'standalone',
        moduleId: 'AllGaugeModule',
        enterprise: true,
    },
    {
        type: 'chart',
        name: 'topology',
        moduleId: 'AllMapSeriesModule',
        enterprise: true,
    },
    {
        type: 'axis',
        name: 'angle-category',
        moduleId: 'AngleCategoryAxisModule',
        chartType: 'polar',
        enterprise: true,
    },
    {
        type: 'axis',
        name: 'angle-number',
        moduleId: 'AngleNumberAxisModule',
        chartType: 'polar',
        enterprise: true,
    },
    {
        type: 'axis',
        name: 'category',
        moduleId: 'CategoryAxisModule',
        chartType: 'cartesian',
    },
    {
        type: 'axis',
        name: 'grouped-category',
        moduleId: 'GroupedCategoryAxisModule',
        chartType: 'cartesian',
    },
    {
        type: 'axis',
        name: 'log',
        moduleId: 'LogAxisModule',
        chartType: 'cartesian',
    },
    {
        type: 'axis',
        name: 'number',
        moduleId: 'NumberAxisModule',
        chartType: 'cartesian',
    },
    {
        type: 'axis',
        name: 'ordinal-time',
        moduleId: 'OrdinalTimeAxisModule',
        chartType: 'cartesian',
        enterprise: true,
    },
    {
        type: 'axis',
        name: 'radius-category',
        moduleId: 'RadiusCategoryAxisModule',
        chartType: 'polar',
        enterprise: true,
    },
    {
        type: 'axis',
        name: 'radius-number',
        moduleId: 'RadiusNumberAxisModule',
        chartType: 'polar',
        enterprise: true,
    },
    {
        type: 'axis',
        name: 'time',
        moduleId: 'TimeAxisModule',
        chartType: 'cartesian',
    },
    {
        type: 'axis',
        name: 'unit-time',
        moduleId: 'UnitTimeAxisModule',
        chartType: 'cartesian',
    },
    {
        type: 'series',
        name: 'area',
        moduleId: 'AreaSeriesModule',
        chartType: 'cartesian',
    },
    {
        type: 'series',
        name: 'bar',
        moduleId: 'BarSeriesModule',
        chartType: 'cartesian',
    },
    {
        type: 'series',
        name: 'box-plot',
        moduleId: 'BoxPlotSeriesModule',
        chartType: 'cartesian',
        enterprise: true,
    },
    {
        type: 'series',
        name: 'bubble',
        moduleId: 'BubbleSeriesModule',
        chartType: 'cartesian',
    },
    {
        type: 'series',
        name: 'candlestick',
        moduleId: 'CandlestickSeriesModule',
        chartType: 'cartesian',
        enterprise: true,
    },
    {
        type: 'series',
        name: 'chord',
        moduleId: 'ChordSeriesModule',
        chartType: 'standalone',
        enterprise: true,
    },
    {
        type: 'series',
        name: 'cone-funnel',
        moduleId: 'ConeFunnelSeriesModule',
        chartType: 'cartesian',
        enterprise: true,
    },
    {
        type: 'series',
        name: 'donut',
        moduleId: 'DonutSeriesModule',
        chartType: 'polar',
    },
    {
        type: 'series',
        name: 'funnel',
        moduleId: 'FunnelSeriesModule',
        chartType: 'cartesian',
        enterprise: true,
    },
    {
        type: 'series',
        name: 'heatmap',
        moduleId: 'HeatmapSeriesModule',
        chartType: 'cartesian',
        enterprise: true,
    },
    {
        type: 'series',
        name: 'histogram',
        moduleId: 'HistogramSeriesModule',
        chartType: 'cartesian',
    },
    {
        type: 'series',
        name: 'line',
        moduleId: 'LineSeriesModule',
        chartType: 'cartesian',
    },
    {
        type: 'series',
        name: 'linear-gauge',
        moduleId: 'LinearGaugeModule',
        chartType: 'standalone',
        enterprise: true,
    },
    {
        type: 'series',
        name: 'map-line',
        moduleId: 'MapLineSeriesModule',
        chartType: 'topology',
        enterprise: true,
    },
    {
        type: 'series',
        name: 'map-line-background',
        moduleId: 'MapLineBackgroundSeriesModule',
        chartType: 'topology',
        enterprise: true,
    },
    {
        type: 'series',
        name: 'map-marker',
        moduleId: 'MapMarkerSeriesModule',
        chartType: 'topology',
        enterprise: true,
    },
    {
        type: 'series',
        name: 'map-shape',
        moduleId: 'MapShapeSeriesModule',
        chartType: 'topology',
        enterprise: true,
    },
    {
        type: 'series',
        name: 'map-shape-background',
        moduleId: 'MapShapeBackgroundSeriesModule',
        chartType: 'topology',
        enterprise: true,
    },
    {
        type: 'series',
        name: 'nightingale',
        moduleId: 'NightingaleSeriesModule',
        chartType: 'polar',
        enterprise: true,
    },
    {
        type: 'series',
        name: 'ohlc',
        moduleId: 'OhlcSeriesModule',
        chartType: 'cartesian',
        enterprise: true,
    },
    {
        type: 'series',
        name: 'organization',
        moduleId: 'OrganizationSeriesModule',
        chartType: 'standalone',
        enterprise: true,
    },
    {
        type: 'series',
        name: 'pie',
        moduleId: 'PieSeriesModule',
        chartType: 'polar',
    },
    {
        type: 'series',
        name: 'pyramid',
        moduleId: 'PyramidSeriesModule',
        chartType: 'standalone',
        enterprise: true,
    },
    {
        type: 'series',
        name: 'radar-area',
        moduleId: 'RadarAreaSeriesModule',
        chartType: 'polar',
        enterprise: true,
    },
    {
        type: 'series',
        name: 'radar-line',
        moduleId: 'RadarLineSeriesModule',
        chartType: 'polar',
        enterprise: true,
    },
    {
        type: 'series',
        name: 'radial-bar',
        moduleId: 'RadialBarSeriesModule',
        chartType: 'polar',
        enterprise: true,
    },
    {
        type: 'series',
        name: 'radial-column',
        moduleId: 'RadialColumnSeriesModule',
        chartType: 'polar',
        enterprise: true,
    },
    {
        type: 'series',
        name: 'radial-gauge',
        moduleId: 'RadialGaugeModule',
        chartType: 'standalone',
        enterprise: true,
    },
    {
        type: 'series',
        name: 'range-area',
        moduleId: 'RangeAreaSeriesModule',
        chartType: 'cartesian',
        enterprise: true,
    },
    {
        type: 'series',
        name: 'range-bar',
        moduleId: 'RangeBarSeriesModule',
        chartType: 'cartesian',
        enterprise: true,
    },
    {
        type: 'series',
        name: 'sankey',
        moduleId: 'SankeySeriesModule',
        chartType: 'standalone',
        enterprise: true,
    },
    {
        type: 'series',
        name: 'scatter',
        moduleId: 'ScatterSeriesModule',
        chartType: 'cartesian',
    },
    {
        type: 'series',
        name: 'sunburst',
        moduleId: 'SunburstSeriesModule',
        chartType: 'standalone',
        enterprise: true,
    },
    {
        type: 'series',
        name: 'treemap',
        moduleId: 'TreemapSeriesModule',
        chartType: 'standalone',
        enterprise: true,
    },
    {
        type: 'series',
        name: 'waterfall',
        moduleId: 'WaterfallSeriesModule',
        chartType: 'cartesian',
        enterprise: true,
    },
    {
        type: 'plugin',
        name: 'animation',
        moduleId: 'AnimationModule',
        enterprise: true,
    },
    {
        type: 'plugin',
        name: 'annotations',
        moduleId: 'AnnotationsModule',
        chartType: 'cartesian',
        enterprise: true,
    },
    {
        type: 'plugin',
        name: 'axis-interaction',
        moduleId: 'AxisInteractionModule',
        chartType: 'cartesian',
        enterprise: true,
        contributes: [
            {
                path: 'axes[].listeners.click',
                options: callback,
            },
            {
                path: 'axes[].listeners.doubleClick',
                options: callback,
            },
            {
                path: 'listeners.axisClick',
                options: callback,
            },
            {
                path: 'listeners.axisDoubleClick',
                options: callback,
            },
        ],
    },
    {
        type: 'plugin',
        name: 'chartToolbar',
        moduleId: 'ChartToolbarModule',
        chartType: 'cartesian',
        enterprise: true,
    },
    {
        type: 'plugin',
        name: 'contextMenu',
        moduleId: 'ContextMenuModule',
        enterprise: true,
    },
    {
        type: 'plugin',
        name: 'dataSource',
        moduleId: 'DataSourceModule',
        enterprise: true,
    },
    {
        type: 'plugin',
        name: 'flashOnUpdate',
        moduleId: 'FlashOnUpdateModule',
        enterprise: true,
    },
    {
        type: 'plugin',
        name: 'gradientLegend',
        moduleId: 'GradientLegendModule',
        enterprise: true,
    },
    {
        type: 'plugin',
        name: 'legend',
        moduleId: 'LegendModule',
    },
    {
        type: 'plugin',
        name: 'locale',
        moduleId: 'LocaleModule',
    },
    {
        type: 'plugin',
        name: 'navigator',
        moduleId: 'NavigatorModule',
        chartType: 'cartesian',
        enterprise: true,
    },
    {
        type: 'plugin',
        name: 'ranges',
        moduleId: 'RangesModule',
        chartType: 'cartesian',
        enterprise: true,
    },
    {
        type: 'plugin',
        name: 'scrollbar',
        moduleId: 'ScrollbarModule',
        chartType: 'cartesian',
        enterprise: true,
    },
    {
        type: 'plugin',
        name: 'selection',
        moduleId: 'SelectionModule',
        enterprise: true,
    },
    {
        type: 'plugin',
        name: 'series-area',
        moduleId: 'SeriesAreaModule',
        enterprise: true,
        contributes: [
            {
                path: 'seriesArea.backgroundRegions',
                options: array,
                chartTypes: ['cartesian'],
            },
        ],
    },
    {
        type: 'plugin',
        name: 'statusBar',
        moduleId: 'StatusBarModule',
        chartType: 'cartesian',
        enterprise: true,
    },
    {
        type: 'plugin',
        name: 'sync',
        moduleId: 'SyncModule',
        chartType: 'cartesian',
        enterprise: true,
    },
    {
        type: 'plugin',
        name: 'zoom',
        moduleId: 'ZoomModule',
        enterprise: true,
    },
    {
        type: 'plugin',
        name: 'zoom-base',
        moduleId: 'QuadrantChartModule',
        contributes: [],
    },
    {
        type: 'axis:plugin',
        name: 'bandHighlight',
        moduleId: 'BandHighlightModule',
        chartType: 'cartesian',
        enterprise: true,
        axisTypes: ['category', 'ordinal-time', 'unit-time', 'grouped-category'],
    },
    {
        type: 'axis:plugin',
        name: 'crosshair',
        moduleId: 'CrosshairModule',
        chartType: 'cartesian',
        enterprise: true,
    },
    {
        type: 'axis:plugin',
        name: 'crossLines',
        moduleId: 'CrossLinesModule',
        chartType: 'cartesian',
    },
    {
        type: 'axis:plugin',
        name: 'polarCrossLines',
        moduleId: 'PolarCrossLinesModule',
        chartType: 'polar',
        enterprise: true,
        optionsKey: 'crossLines',
        axisTypes: ['angle-category', 'angle-number', 'radius-category', 'radius-number'],
    },
    {
        type: 'series:plugin',
        name: 'errorBar',
        moduleId: 'ErrorBarsModule',
        chartType: 'cartesian',
        enterprise: true,
        seriesTypes: ['bar', 'line', 'scatter'],
    },
    {
        type: 'preset',
        name: 'gauge-preset',
        moduleId: 'AllGaugeModule',
        enterprise: true,
        apiName: 'AgCharts.createGauge',
    },
    {
        type: 'preset',
        name: 'price-volume',
        moduleId: 'FinancialChartModule',
        enterprise: true,
        apiName: 'AgCharts.createFinancialChart',
    },
    {
        type: 'preset',
        name: 'quadrant',
        moduleId: 'QuadrantChartModule',
        enterprise: true,
        apiName: 'AgCharts.createQuadrantChart',
    },
    {
        type: 'preset',
        name: 'sparkline',
        moduleId: 'SparklinePresetModule',
    },
];
