export function getData() {
    return [
        {
          year: 2013,
          crWon: 12,
          crLost: -5,
          lmWon: 10,
          lmLost: -5,
          kbWon: 14,
          kbLost: -8,
        },
        {
          year: 2014,
          crWon: 13,
          crLost: -8,
          lmWon: 15,
          lmLost: -6,
          kbWon: 18,
          kbLost: -11,
        },
        {
          year: 2015,
          crWon: 10,
          crLost: -10,
          lmWon: 18,
          lmLost: -6,
          kbWon: 11,
          kbLost: -9,
        },
        {
          year: 2016,
          crWon: 19,
          crLost: -8,
          lmWon: 12,
          lmLost: -6,
          kbWon: 10,
          kbLost: -10,
        },
        {
          year: 2017,
          crWon: 13,
          crLost: -7,
          lmWon: 17,
          lmLost: -6,
          kbWon: 11,
          kbLost: -6,
        },
        {
          year: 2018,
          crWon: 11,
          crLost: -11,
          lmWon: 12,
          lmLost: -5,
          kbWon: 18,
          kbLost: -10,
        },
        {
          year: 2019,
          crWon: 19,
          crLost: -10,
          lmWon: 11,
          lmLost: -4,
          kbWon: 12,
          kbLost: -8,
        },
        {
          year: 2020,
          crWon: 12,
          crLost: -7,
          lmWon: 16,
          lmLost: -6,
          kbWon: 10,
          kbLost: -9,
        },
        {
          year: 2021,
          crWon: 11,
          crLost: -10,
          lmWon: 18,
          lmLost: -6,
          kbWon: 19,
          kbLost: -10,
        },
        {
          year: 2022,
          crWon: 19,
          crLost: -11,
          lmWon: 19,
          lmLost: -7,
          kbWon: 11,
          kbLost: -8,
        },
        {
          year: 2023,
          crWon: 11,
          crLost: -9,
          lmWon: 10,
          lmLost: -6,
          kbWon: 13,
          kbLost: -7,
        },
      ];
}
