import type { AstroUserConfig } from 'astro';

import { SITE_BASE_URL } from '../../constants';
import { urlWithBaseUrl } from '../urlWithBaseUrl';
import type { CspEnv } from './cspRules';
import { getCspHtaccessBlock } from './cspRules';
import { SITE_301_REDIRECTS, type SimpleRedirectRule } from './redirects';

export type HtaccessEnv = Extract<CspEnv, 'staging' | 'production'>;

export function getHtaccessContent(options: { env: HtaccessEnv }) {
    const { env } = options;
    return `### AUTOGENERATED DO NOT EDIT
ErrorDocument 404 ${urlWithBaseUrl('/404.html')}

# add MIME types for serving example files
AddType text/javascript mjs ts jsx

# Content-Security-Policy — enforced (the report-only validation window is complete).
# Charts is served from /charts on www.ag-grid.com and inherits the grid root CSP, so
# this block overrides it for charts pages (see getCspHtaccessBlock). In enforce mode
# the block unsets BOTH inherited headers (the grid root policy and the legacy wildcard)
# and sets this enforced policy. The trial-form origin is env-split, so the policy is
# generated per environment.
${getCspHtaccessBlock({ env }, 'enforce')}

${getRedirectRules()}

Options -Indexes
`;
}

export function getRedirectRules() {
    // mod_alias `RedirectMatch` matches against the full request URL-path (e.g. `/charts/react/`),
    // even when the .htaccess lives inside the base folder — unlike mod_rewrite, it does not strip
    // the directory prefix. So patterns must be base-aware to match the deployed paths. Rule
    // definitions stay base-relative (`^/react/?$`); the base is spliced in here, matching how
    // `from` rules get the base via `urlWithBaseUrl`.
    const basePath = (SITE_BASE_URL ?? '').replace(/\/$/, '');
    return `${SITE_301_REDIRECTS.map((redirect) => {
        const { from, fromPattern, to } = redirect as any;
        if (!to) {
            // eslint-disable-next-line no-console
            console.warn('Missing `to` in redirect', redirect);
            return;
        } else if (!from && !fromPattern) {
            // eslint-disable-next-line no-console
            console.warn('Missing `from` in redirect', redirect);
            return;
        }
        if (from) {
            return `Redirect 301 ${urlWithBaseUrl(from)} ${urlWithBaseUrl(to)}`;
        }
        const baseAwarePattern = fromPattern.startsWith('^')
            ? `^${basePath}${fromPattern.slice(1)}`
            : `${basePath}${fromPattern}`;
        return `RedirectMatch 301 "${baseAwarePattern}" "${urlWithBaseUrl(to)}"`;
    })
        .filter(Boolean)
        .join('\n')}`;
}

export function getAstroRedirectRules(): AstroUserConfig['redirects'] {
    // Only for simple redirects, not pattern matches
    const simpleRedirects = SITE_301_REDIRECTS.filter((redirect) =>
        Boolean((redirect as SimpleRedirectRule).from)
    ) as SimpleRedirectRule[];

    return Object.fromEntries(
        simpleRedirects.map(({ from, to }) => {
            // NOTE: Don't need to add base to the `from` side, as Astro handles that
            return [from, urlWithBaseUrl(to)];
        })
    );
}
