import type { AstroUserConfig } from 'astro';

import { SITE_BASE_URL } from '../../constants';
import { urlWithBaseUrl } from '../urlWithBaseUrl';
import type { CspEnv } from './cspRules';
import { getCspHtaccessBlock, getScopedCspHtaccessBlock } from './cspRules';
import { SITE_301_REDIRECTS, type SimpleRedirectRule } from './redirects';

export type HtaccessEnv = Extract<CspEnv, 'staging' | 'production'>;

// Rollout state for removing 'unsafe-eval' from the production main-site CSP.
// While 'report-only', production keeps enforcing the previous policy (which
// allows 'unsafe-eval' everywhere) and reports violations of the tightened
// path-scoped split. Flip to 'enforce' once the report-only window is clean.
// Staging always enforces the split.
export const PRODUCTION_CSP_PHASE: 'report-only' | 'enforce' = 'report-only';

export function getHtaccessContent(options: { env: HtaccessEnv }) {
    const { env } = options;
    return `### AUTOGENERATED DO NOT EDIT
ErrorDocument 404 ${urlWithBaseUrl('/404.html')}

# add MIME types for serving example files
AddType text/javascript mjs ts jsx

# Content-Security-Policy — path-scoped. Charts is served from /charts on www.ag-grid.com
# and inherits the grid root CSP, so this block overrides it for charts pages (see
# getCspHtaccessBlock). Ordinary pages get the tightened policy (no 'unsafe-eval'); the
# <If> override re-allows it for example-runner documents. The trial-form origin is
# env-split, so the policy is generated per environment.
${getCspContent(env)}

${getRedirectRules()}

Options -Indexes
`;
}

function getCspContent(env: HtaccessEnv): string {
    // Staging enforces the split immediately. Production keeps enforcing the previous
    // policy (which allows 'unsafe-eval' on every page) and reports the tightened split
    // via Report-Only until the validation window is clean. The Report-Only <If> override
    // matters: without it, every example-runner page would report eval violations.
    if (env === 'staging' || PRODUCTION_CSP_PHASE === 'enforce') {
        return getScopedCspHtaccessBlock({ env }, 'enforce');
    }
    return `${getCspHtaccessBlock({ env, scope: 'examples' }, 'enforce')}

${getScopedCspHtaccessBlock({ env }, 'report-only')}`;
}

export function getRedirectRules() {
    // mod_alias `RedirectMatch` matches against the full request URL-path (e.g. `/charts/react/`),
    // even when the .htaccess lives inside the base folder — unlike mod_rewrite, it does not strip
    // the directory prefix. So patterns must be base-aware to match the deployed paths. Rule
    // definitions stay base-relative (`^/react/?$`); the base is spliced in here, matching how
    // `from` rules get the base via `urlWithBaseUrl`.
    const basePath = (SITE_BASE_URL ?? '').replace(/\/$/, '');
    const toBaseAwarePattern = (fromPattern: string) =>
        fromPattern.startsWith('^') ? `^${basePath}${fromPattern.slice(1)}` : `${basePath}${fromPattern}`;
    return `${SITE_301_REDIRECTS.map((redirect) => {
        const { from, fromPattern, to, gone } = redirect as any;
        if (!from && !fromPattern) {
            // eslint-disable-next-line no-console
            console.warn('Missing `from` in redirect', redirect);
            return;
        }
        // 410 Gone: permanently removed, no target.
        if (gone) {
            return from
                ? `Redirect 410 ${urlWithBaseUrl(from)}`
                : `RedirectMatch 410 "${toBaseAwarePattern(fromPattern)}"`;
        }
        if (!to) {
            // eslint-disable-next-line no-console
            console.warn('Missing `to` in redirect', redirect);
            return;
        }
        if (from) {
            return `Redirect 301 ${urlWithBaseUrl(from)} ${urlWithBaseUrl(to)}`;
        }
        return `RedirectMatch 301 "${toBaseAwarePattern(fromPattern)}" "${urlWithBaseUrl(to)}"`;
    })
        .filter(Boolean)
        .join('\n')}`;
}

export function getAstroRedirectRules(): AstroUserConfig['redirects'] {
    // Only for simple redirects, not pattern matches. Gone rules have no `to`, so skip them.
    const simpleRedirects = SITE_301_REDIRECTS.filter(
        (redirect) => Boolean((redirect as SimpleRedirectRule).from) && !(redirect as { gone?: true }).gone
    ) as SimpleRedirectRule[];

    return Object.fromEntries(
        simpleRedirects.map(({ from, to }) => {
            // NOTE: Don't need to add base to the `from` side, as Astro handles that
            return [from, urlWithBaseUrl(to)];
        })
    );
}
