import type { AstroUserConfig } from 'astro';

import { SITE_BASE_URL } from '../../constants';
import { markdownPathAlternation } from '../markdownPages';
import { urlWithBaseUrl } from '../urlWithBaseUrl';
import type { CspEnv } from './cspRules';
import { getCspHtaccessBlock, getScopedCspHtaccessBlock } from './cspRules';
import { type Redirect, SITE_301_REDIRECTS, type SimpleRedirectRule } from './redirects';

export type HtaccessEnv = Extract<CspEnv, 'staging' | 'production'>;

// Rollout state for removing 'unsafe-eval' from the production main-site CSP. Staging always
// enforces the split; flip this to 'enforce' once production's report-only window is clean.
export const PRODUCTION_CSP_PHASE: 'report-only' | 'enforce' = 'enforce';

export function getHtaccessContent(options: { env: HtaccessEnv }) {
    const { env } = options;
    return `### AUTOGENERATED DO NOT EDIT
ErrorDocument 404 ${urlWithBaseUrl('/404.html')}

# add MIME types for serving example files
AddType text/javascript mjs ts jsx

# Apache has no built-in .webp type, so without this the images are served with no Content-Type.
AddType image/webp .webp

# serve the per-page LLM markdown files as markdown
AddType text/markdown md
# ...as UTF-8, so glyphs like ✓/✗ in generated tables aren't mojibaked by a
# Latin-1 fallback (the .md endpoint sets this charset; static hosting must too).
AddCharset utf-8 .md

# Content-Security-Policy — path-scoped. Charts is served from /charts on www.ag-grid.com
# and inherits the grid root CSP, so this block overrides it for charts pages (see
# getCspHtaccessBlock). Ordinary pages get the tightened policy (no 'unsafe-eval'); the
# <If> override re-allows it for example-runner documents. The trial-form origin is
# env-split, so the policy is generated per environment.
${getCspContent(env)}

${getRedirectRules(env)}

${getMarkdownNegotiationRules()}

Options -Indexes
`;
}

function getCspContent(env: HtaccessEnv): string {
    // The Report-Only <If> override is load-bearing: without it every example-runner page
    // would report eval violations.
    if (env === 'staging' || PRODUCTION_CSP_PHASE === 'enforce') {
        return getScopedCspHtaccessBlock({ env }, 'enforce');
    }
    return `${getCspHtaccessBlock({ env, scope: 'examples' }, 'enforce')}

${getScopedCspHtaccessBlock({ env }, 'report-only')}`;
}

// Archive builds omit the `sitemap()` integration (see astro.config.mjs) and are the only
// builds whose base URL carries `archive`, so this is the same signal used there.
const isArchiveBuild = () => (SITE_BASE_URL ?? '').includes('archive');

const dropArchiveOnlyRedirects = (redirects: Redirect[]) =>
    isArchiveBuild()
        ? redirects.filter((redirect) => !(redirect as { skipForArchive?: true }).skipForArchive)
        : redirects;

const CANONICAL_ORIGIN = 'https://www.ag-grid.com';

// Every other host that reaches this docroot. Each must 301 to www rather than serve pages, which
// would be duplicate content. Kept in step with the host rules in the grid root .htaccess, which
// never runs for /charts: a child .htaccess with `RewriteEngine On` replaces its parent's rewrite
// rules rather than inheriting them. An allowlist, not "anything but www", so that requests on a
// host we don't own (origin health checks, a proxy's internal name) are served rather than looped.
const NON_CANONICAL_HOSTS =
    '^(?:ag-grid\\.com|(?:blog|angulargrid|angular-grid|javascript-grid|react-grid)\\.ag-grid\\.com|(?:www\\.)?angulargrid\\.com)$';

function escapeRegExp(value: string): string {
    return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

// The base as it appears in REQUEST_URI, with its archive version dots (14.2.0) made literal.
const getBasePath = () => (SITE_BASE_URL ?? '').replace(/\/$/, '');
const getBasePattern = () => escapeRegExp(getBasePath());

// A per-directory RewriteRule pattern is matched against the path below the .htaccess directory -
// the deployed base - so a base-relative rule pattern applies as-is once its leading slash goes.
function toPerDirPattern(fromPattern: string): string {
    if (!fromPattern.startsWith('^/')) {
        throw new Error(`Redirect pattern must be anchored base-relative (^/…): ${fromPattern}`);
    }
    return `^${fromPattern.slice(2)}`;
}

// Matches the page exactly, with or without its trailing slash. A prefix match (mod_alias
// `Redirect`) would also catch longer slugs, and append the remainder to the target.
const toExactPagePattern = (from: string) => `^${escapeRegExp(from.replace(/^\/|\/$/g, ''))}/?$`;

/**
 * Every redirect is a mod_rewrite rule, so that one engine applies them in a known order, ahead of
 * the host canonicalisation: a legacy URL on any host lands on its final www URL in one hop, where
 * a mod_alias redirect would run only after the host redirect had already spent one.
 *
 * Production targets are absolute on the canonical origin. Staging has a single host, so its
 * targets stay relative and it has no host or trailing-slash rules.
 */
export function getRedirectRules(env: HtaccessEnv = 'production') {
    const origin = env === 'production' ? CANONICAL_ORIGIN : '';
    const redirects = dropArchiveOnlyRedirects(SITE_301_REDIRECTS)
        .map((redirect) => {
            const { from, fromPattern, to, gone } = redirect as any;
            if (!from && !fromPattern) {
                // eslint-disable-next-line no-console
                console.warn('Missing `from` in redirect', redirect);
                return;
            }
            const pattern = from ? toExactPagePattern(from) : toPerDirPattern(fromPattern);
            // 410 Gone: permanently removed, no target.
            if (gone) {
                return `    RewriteRule "${pattern}" - [G]`;
            }
            if (!to) {
                // eslint-disable-next-line no-console
                console.warn('Missing `to` in redirect', redirect);
                return;
            }
            // [NE] keeps a fragment's `#` verbatim; otherwise it is escaped into a broken path.
            const flags = to.includes('#') ? 'R=301,NE,L' : 'R=301,L';
            return `    RewriteRule "${pattern}" "${origin}${urlWithBaseUrl(to)}" [${flags}]`;
        })
        .filter(Boolean)
        .join('\n');

    return `<IfModule mod_rewrite.c>
    RewriteEngine On

${redirects}
${env === 'production' ? getHostCanonicalizationRules() : ''}</IfModule>`;
}

// Production only: the redirects above have already sent legacy URLs to their final page, so these
// only add a missing trailing slash and swap the host - together, in one hop. Both use the full
// REQUEST_URI, so an archived version keeps its own path.
function getHostCanonicalizationRules(): string {
    return `
    # Without this, mod_rewrite skips the base directory's own slash-less URL and leaves it to
    # mod_dir, whose slash redirect stays on the requesting host - a second hop from any other host.
    RewriteOptions AllowNoSlash

    # A directory URL without its trailing slash goes straight to the slashed canonical URL, rather
    # than via mod_dir's slash redirect on the requesting host. A path whose last segment has a dot
    # is taken for a file unless it is a real directory (an archive version such as 14.2.0).
    RewriteCond %{HTTP_HOST} ^www\\.ag-grid\\.com$ [NC,OR]
    RewriteCond %{HTTP_HOST} ${NON_CANONICAL_HOSTS} [NC]
    RewriteCond %{REQUEST_URI} /+[^.]+$ [OR]
    RewriteCond %{REQUEST_FILENAME} -d
    RewriteCond %{REQUEST_URI} [^/]$
    RewriteRule ^ ${CANONICAL_ORIGIN}%{REQUEST_URI}/ [R=301,L]

    # Canonical host is www.ag-grid.com; no other host may serve pages directly.
    RewriteCond %{HTTP_HOST} ${NON_CANONICAL_HOSTS} [NC]
    RewriteRule ^ ${CANONICAL_ORIGIN}%{REQUEST_URI} [R=301,L]
`;
}

export function getMarkdownNegotiationRules() {
    // %1 must be document-root-relative for both the on-disk `-f` test and the rewrite target to
    // resolve, so the base is captured inside it rather than matched outside.
    const basePath = getBasePath();
    const basePattern = getBasePattern();
    const capturePrefix = basePattern === '' ? '' : `${basePattern.slice(1)}/`;
    const pages = markdownPathAlternation();
    const negotiatedPath = `^/(${capturePrefix}(?:${pages}))/?$`;
    // Must match negotiatedPath's shape, or Vary: Accept lands on non-negotiating URLs and
    // fragments shared caches. The HTML variant is served through mod_dir's DirectoryIndex, which
    // has already rewritten REQUEST_URI to <page>/index.html by the time headers are set, so that
    // form must match too - otherwise only the markdown variant carries Vary: Accept.
    const varyScope = `^${basePattern}/(?:${pages})(?:/|/index\\.html)?$`;
    const varyRootScope = `^${basePattern}(?:/|/index\\.html)?$`;

    // Serve the per-page markdown twin on Accept: text/markdown. An internal rewrite gated by an
    // on-disk check, so a path with no twin is left untouched.
    return `<IfModule mod_rewrite.c>
    RewriteEngine On

    RewriteCond %{HTTP_ACCEPT} text/markdown
    RewriteCond %{REQUEST_URI} ${negotiatedPath}
    RewriteCond %{DOCUMENT_ROOT}/%1.md -f
    RewriteRule ^ /%1.md [L]

    # The homepage twin (${basePath}/ -> ${basePath}/index.md). Handled separately because the
    # site root has no path segment to capture in %1; the pattern matches only the base root.
    RewriteCond %{HTTP_ACCEPT} text/markdown
    RewriteCond %{REQUEST_URI} ^${basePattern}/?$
    RewriteCond %{DOCUMENT_ROOT}${basePath}/index.md -f
    RewriteRule ^ ${basePath}/index.md [L]
</IfModule>

# Docs pages content-negotiate on Accept (see the markdown rewrite), so shared caches must
# key on it. Scoped to the negotiated paths (incl. the homepage) so the rest of the site keeps
# its default.
<If "%{REQUEST_URI} =~ m#${varyScope}# || %{REQUEST_URI} =~ m#${varyRootScope}#">
    Header append Vary Accept
</If>`;
}

export function getAstroRedirectRules(): AstroUserConfig['redirects'] {
    // Gone rules have no `to`, so skip them.
    const simpleRedirects = dropArchiveOnlyRedirects(SITE_301_REDIRECTS).filter(
        (redirect) => Boolean((redirect as SimpleRedirectRule).from) && !(redirect as { gone?: true }).gone
    ) as SimpleRedirectRule[];

    return Object.fromEntries(
        simpleRedirects.map(({ from, to }) => {
            // Astro adds the base to the `from` side.
            return [from, urlWithBaseUrl(to)];
        })
    );
}
