export const data = [
    {
        title: 'Health Care',
        children: [{ title: 'Medical service', total: 205.6, change: 25 }],
    },
    {
        title: 'Pensions',
        children: [
            { title: 'Sickness and disability', total: 61.2, change: -18 },
            { title: 'Old age', total: 141.8, change: 32 },
        ],
    },
    {
        title: 'Other Spending',
        children: [
            { title: 'General economic, commercial and labour', total: 18.8, change: -12 },
            { title: 'Agriculture, forestry, fishing and hunt', total: 6.5, change: 3 },
            { title: 'Fuel and energy', total: 8.8, change: -35 },
            { title: 'Communication', total: 0.2, change: -5 },
            { title: 'Other industries', total: 0.2, change: -1 },
            { title: 'R&D Economic affairs', total: 12.6, change: 15 },
            { title: 'Economic affairs n.e.c.', total: 1.1, change: 0 },
            { title: 'Waste management', total: 3.4, change: 8 },
            { title: 'Pollution abatement', total: 1, change: -7 },
            { title: 'Protection of biodiversity and landscap', total: 0.5, change: -22 },
            { title: 'R&D Environmental protection', total: 0.5, change: 4 },
            { title: 'Environmental protection n.e.c.', total: 2.3, change: -9 },
            { title: 'Housing development', total: 3.4, change: 12 },
            { title: 'Community development', total: 0.6, change: -3 },
            { title: 'Water supply', total: 0.4, change: -15 },
            { title: 'Housing and community amenities n.e.c.', total: 0.3, change: 1 },
            { title: 'Recreational and sporting services', total: 0.5, change: -8 },
            { title: 'Cultural services', total: 2.3, change: -4 },
            { title: 'Broadcasting and publishing services', total: 7.7, change: 18 },
            { title: 'Religious and other community services', total: 0.1, change: -2 },
            { title: 'R&D Recreation, culture and religion', total: 0.2, change: 6 },
            { title: 'Recreation, culture and religion n.e.c.', total: 0.2, change: 0 },
            { title: 'Other Spending', total: 59.4, change: 22 },
        ],
    },
    {
        title: 'Welfare',
        children: [
            { title: 'Family and children', total: 16.8, change: -10 },
            { title: 'Housing', total: 6.2, change: -6 },
            { title: 'Social exclusion n.e.c.', total: 65.4, change: 28 },
            { title: 'Social protection n.e.c.', total: 15.1, change: 10 },
        ],
    },
    {
        title: 'Interest',
        children: [{ title: 'Public debt transactions', total: 76.9, change: -30 }],
    },
    {
        title: 'Defence',
        children: [
            { title: 'Military defence', total: 50.4, change: 5 },
            { title: 'Foreign military aid', total: 0.4, change: -25 },
            { title: 'Foreign economic aid', total: 6.6, change: 7 },
            { title: 'R&D Defence', total: 2.6, change: -14 },
            { title: 'Defence n.e.c.', total: 0.2, change: 2 },
        ],
    },
    {
        title: 'Education',
        children: [
            { title: 'Pre-primary and primary education', total: 1.3, change: 9 },
            { title: 'Secondary education', total: 43.3, change: 2 },
            { title: 'Tertiary education', total: 5.1, change: -11 },
            { title: 'Education not definable by level', total: 1.9, change: 14 },
            { title: 'Subsidiary services to education', total: 0.8, change: 0 },
            { title: 'R&D Education', total: 2.7, change: -6 },
            { title: 'Education n.e.c.', total: 2.8, change: -3 },
        ],
    },
    {
        title: 'Transport',
        children: [{ title: 'Transport', total: 33.7, change: 11 }],
    },
    {
        title: 'Protection',
        children: [
            { title: 'Police services', total: 5.5, change: -4 },
            { title: 'Fire-protection services', total: 0.6, change: 1 },
            { title: 'Law courts', total: 8.2, change: 6 },
            { title: 'Prisons', total: 7.7, change: -16 },
            { title: 'R&D Public order and safety', total: 1, change: -20 },
            { title: 'Public order and safety n.e.c.', total: 1.2, change: 0 },
        ],
    },
    {
        title: 'General Government',
        children: [
            { title: 'Executive and legislative organs, finan', total: 19.8, change: -8 },
            { title: 'General services', total: 1.5, change: 3 },
            { title: 'R&D General public services', total: 0.5, change: 16 },
            { title: 'General public services n.e.c.', total: 0.7, change: -2 },
        ],
    },
];
