name: snapshot-notify

inputs:
    branch:
        description: 'Snapshot branch name to use.'
        required: true
    github_token:
        description: 'GitHub token to use for PR creation.'
        required: true
    slack_webhook:
        description: 'Slack webhook to use for notification.'
        required: true
outputs:
    updated:
        description: 'If any snapshots were updated.'
        value: ${{ steps.snapshot_check.outputs.updated }}

runs:
    using: 'composite'
    steps:
        - name: Check for snapshot updates
          id: snapshot_check
          if: inputs.branch != ''
          shell: bash
          run: |
              set -eux

              branch=${{ inputs.branch }}

              if (git ls-remote --exit-code --heads origin ${branch} >/dev/null) ; then
                  echo "updated=true" >> $GITHUB_OUTPUT
              else
                  echo "updated=false" >> $GITHUB_OUTPUT
              fi

        - name: Add PR Comment
          if: steps.snapshot_check.outputs.updated == 'true' && github.ref != 'refs/heads/latest'
          uses: actions/github-script@v7
          continue-on-error: true
          with:
              script: |
                  github.rest.issues.createComment({
                      issue_number: context.issue.number,
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      body: `Snapshots automatically updated, please review before merge: [diff](https://github.com/ag-grid/ag-charts/compare/${{github.head_ref}}...${{inputs.branch}})`
                  })

        - name: Raise PR with Snapshot Changes on latest
          id: raise-pr
          if: steps.snapshot_check.outputs.updated == 'true' && github.ref == 'refs/heads/latest'
          env:
              GITHUB_TOKEN: ${{ inputs.github_token }}
          shell: bash
          run: |
              set -eux

              pr_count=$(
              gh pr list \
                  --base ${{ github.ref }} \
                  --head ${{ inputs.branch }} \
                  --json title \
                  --jq 'length'
              )

              if ((prs > 0)); then
                  echo "Existing PRs for snapshots, skipping PR creation."
                  echo "skip=true" >> "$GITHUB_OUTPUT"
                  exit
              fi

              gh pr create \
              --base ${{ github.ref }} \
              --head ${{ inputs.branch }} \
              --title "Snapshot updates at $(date +%Y/%m/%d-%H:%M)" \
              --body "Automatically generated for review."

              url=$(
              gh pr view \
              --base ${{ github.ref }} \
              --head ${{ inputs.branch }} \
              --json url | jq -r .url
              )

              echo "url=${url}" >> $GITHUB_OUTPUT

        - name: Slack Notification
          uses: rtCamp/action-slack-notify@v2
          if: steps.snapshot_check.outputs.updated == 'true' && github.ref == 'refs/heads/latest'
          env:
              SLACK_WEBHOOK: ${{ inputs.slack_webhook }}
              SLACK_COLOR: 'warning'
              SLACK_ICON: https://avatars.slack-edge.com/2020-11-25/1527503386626_319578f21381f9641cd8_192.png
              SLACK_USERNAME: ag-charts CI
              SLACK_FOOTER: ''
              SLACK_MESSAGE: >
                  New E2E Snapshot PR: ${{ steps.raise-pr.outputs.url }}
