export function getData() {
    return [
        {
            id: 'Ashley Rivers',
            parentId: null,
            name: 'Ashley Rivers',
            job: 'CEO',
            department: 'Executive',
            status: 'In Office',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/19.webp',
        },

        // Technology
        {
            id: 'Joseph Howe',
            parentId: 'Ashley Rivers',
            name: 'Joseph Howe',
            job: 'CTO',
            department: 'Technology',
            status: 'Hybrid',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/25.webp',
        },
        {
            id: 'Jeffrey Brown',
            parentId: 'Joseph Howe',
            name: 'Jeffrey Brown',
            job: 'Engineering Lead',
            department: 'Technology',
            status: 'In Office',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/22.webp',
        },
        {
            id: 'Melissa Vazquez',
            parentId: 'Jeffrey Brown',
            name: 'Melissa Vazquez',
            job: 'Software Engineer',
            department: 'Technology',
            status: 'Hybrid',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/4.webp',
        },
        {
            id: 'John Thomas',
            parentId: 'Jeffrey Brown',
            name: 'John Thomas',
            job: 'Software Engineer',
            department: 'Technology',
            status: 'Hybrid',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/5.webp',
        },
        {
            id: 'Susan Hernandez',
            parentId: 'Jeffrey Brown',
            name: 'Susan Hernandez',
            job: 'Dev Ops',
            department: 'Technology',
            status: 'In Office',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/20.webp',
        },
        {
            id: 'Aisha Khan',
            parentId: 'Jeffrey Brown',
            name: 'Aisha Khan',
            job: 'Software Engineer',
            department: 'Technology',
            status: 'Remote',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/7.webp',
        },
        {
            id: 'Justin Contreras',
            parentId: 'Joseph Howe',
            name: 'Justin Contreras',
            job: 'Engineering Lead',
            department: 'Technology',
            status: 'In Office',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/10.webp',
        },
        {
            id: 'Rachel Ibarra',
            parentId: 'Justin Contreras',
            name: 'Rachel Ibarra',
            job: 'Software Engineer',
            department: 'Technology',
            status: 'Remote',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/2.webp',
        },
        {
            id: 'John Gomez',
            parentId: 'Justin Contreras',
            name: 'John Gomez',
            job: 'Software Engineer',
            department: 'Technology',
            status: 'In Office',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/17.webp',
        },
        {
            id: 'Sam Carter',
            parentId: 'Justin Contreras',
            name: 'Sam Carter',
            job: 'QA Engineer',
            department: 'Technology',
            status: 'Hybrid',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/8.webp',
        },
        {
            id: 'Priya Nair',
            parentId: 'Joseph Howe',
            name: 'Priya Nair',
            job: 'Data Lead',
            department: 'Technology',
            status: 'In Office',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/9.webp',
        },
        {
            id: 'Lena Fischer',
            parentId: 'Priya Nair',
            name: 'Lena Fischer',
            job: 'Data Scientist',
            department: 'Technology',
            status: 'Remote',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/11.webp',
        },
        {
            id: 'Mark Daniels',
            parentId: 'Priya Nair',
            name: 'Mark Daniels',
            job: 'Data Engineer',
            department: 'Technology',
            status: 'Hybrid',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/12.webp',
        },

        // Product
        {
            id: 'Gary Garcia',
            parentId: 'Ashley Rivers',
            name: 'Gary Garcia',
            job: 'CPO',
            department: 'Product',
            status: 'In Office',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/29.webp',
        },
        {
            id: 'Lawrence Martinez',
            parentId: 'Gary Garcia',
            name: 'Lawrence Martinez',
            job: 'Product Manager',
            department: 'Product',
            status: 'Hybrid',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/33.webp',
        },
        {
            id: 'Tom Whitfield',
            parentId: 'Lawrence Martinez',
            name: 'Tom Whitfield',
            job: 'Product Analyst',
            department: 'Product',
            status: 'In Office',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/13.webp',
        },
        {
            id: 'Olivia Bennett',
            parentId: 'Lawrence Martinez',
            name: 'Olivia Bennett',
            job: 'UX Researcher',
            department: 'Product',
            status: 'Hybrid',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/14.webp',
        },
        {
            id: 'Devin Pittman',
            parentId: 'Gary Garcia',
            name: 'Devin Pittman',
            job: 'Design Lead',
            department: 'Product',
            status: 'In Office',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/18.webp',
        },
        {
            id: 'Emily Barajas',
            parentId: 'Devin Pittman',
            name: 'Emily Barajas',
            job: 'Visual Designer',
            department: 'Product',
            status: 'Hybrid',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/28.webp',
        },
        {
            id: 'Noah Kim',
            parentId: 'Devin Pittman',
            name: 'Noah Kim',
            job: 'Product Designer',
            department: 'Product',
            status: 'Remote',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/15.webp',
        },

        // Finance & Operations
        {
            id: 'Eric Jensen',
            parentId: 'Ashley Rivers',
            name: 'Eric Jensen',
            job: 'CFO/COO',
            department: 'Finance & Operations',
            status: 'Remote',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/35.webp',
        },
        {
            id: 'Hannah Lee',
            parentId: 'Eric Jensen',
            name: 'Hannah Lee',
            job: 'Finance Manager',
            department: 'Finance & Operations',
            status: 'In Office',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/23.webp',
        },
        {
            id: 'Carlos Mendez',
            parentId: 'Hannah Lee',
            name: 'Carlos Mendez',
            job: 'Accountant',
            department: 'Finance & Operations',
            status: 'Hybrid',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/24.webp',
        },
        {
            id: 'Grace Liu',
            parentId: 'Hannah Lee',
            name: 'Grace Liu',
            job: 'Financial Analyst',
            department: 'Finance & Operations',
            status: 'Remote',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/26.webp',
        },
        {
            id: 'Robert Frank',
            parentId: 'Eric Jensen',
            name: 'Robert Frank',
            job: 'Operations Manager',
            department: 'Finance & Operations',
            status: 'In Office',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/27.webp',
        },
        {
            id: 'Sofia Russo',
            parentId: 'Robert Frank',
            name: 'Sofia Russo',
            job: 'Operations Coordinator',
            department: 'Finance & Operations',
            status: 'Hybrid',
            avatar: '${baseWWWUrl}/example-assets/docs-images/hr/30.webp',
        },
    ];
}
