export function getData() {
    return [
        {
            id: 'NexusCloud Platform',
            parentId: null,
            name: 'NexusCloud Platform',
            productFamily: 'platform',
            status: 'released',
        },

        // Infrastructure
        {
            id: 'Infrastructure',
            parentId: 'NexusCloud Platform',
            name: 'Infrastructure',
            productFamily: 'infrastructure',
            status: 'released',
        },
        {
            id: 'Compute',
            parentId: 'Infrastructure',
            name: 'Compute',
            productFamily: 'infrastructure',
            status: 'released',
        },
        {
            id: 'Virtual Machines',
            parentId: 'Compute',
            name: 'Virtual Machines',
            productFamily: 'infrastructure',
            status: 'released',
        },
        {
            id: 'GPU Instances',
            parentId: 'Virtual Machines',
            name: 'GPU Instances',
            productFamily: 'infrastructure',
            status: 'released',
        },
        {
            id: 'ML-Optimized VM',
            parentId: 'GPU Instances',
            name: 'ML-Optimized VM',
            productFamily: 'infrastructure',
            status: 'released',
        },
        {
            id: 'Serverless Functions',
            parentId: 'Compute',
            name: 'Serverless Functions',
            productFamily: 'infrastructure',
            status: 'released',
        },
        {
            id: 'Function Runtime',
            parentId: 'Serverless Functions',
            name: 'Function Runtime',
            productFamily: 'infrastructure',
            status: 'released',
        },
        {
            id: 'Storage',
            parentId: 'Infrastructure',
            name: 'Storage',
            productFamily: 'infrastructure',
            status: 'released',
        },
        {
            id: 'Object Storage',
            parentId: 'Storage',
            name: 'Object Storage',
            productFamily: 'infrastructure',
            status: 'released',
        },
        {
            id: 'Block Storage',
            parentId: 'Storage',
            name: 'Block Storage',
            productFamily: 'infrastructure',
            status: 'released',
        },

        // Data & Analytics
        {
            id: 'Data & Analytics',
            parentId: 'NexusCloud Platform',
            name: 'Data & Analytics',
            productFamily: 'data & analytics',
            status: 'released',
        },
        {
            id: 'Databases',
            parentId: 'Data & Analytics',
            name: 'Databases',
            productFamily: 'data & analytics',
            status: 'released',
        },
        {
            id: 'Relational DB',
            parentId: 'Databases',
            name: 'Relational DB',
            productFamily: 'data & analytics',
            status: 'released',
        },
        {
            id: 'Read Replicas',
            parentId: 'Relational DB',
            name: 'Read Replicas',
            productFamily: 'data & analytics',
            status: 'released',
        },
        {
            id: 'NoSQL DB',
            parentId: 'Databases',
            name: 'NoSQL DB',
            productFamily: 'data & analytics',
            status: 'released',
        },
        {
            id: 'Time-Series DB',
            parentId: 'NoSQL DB',
            name: 'Time-Series DB',
            productFamily: 'data & analytics',
            status: 'released',
        },
        {
            id: 'Data Pipeline',
            parentId: 'Data & Analytics',
            name: 'Data Pipeline',
            productFamily: 'data & analytics',
            status: 'beta',
        },
        {
            id: 'Stream Processor',
            parentId: 'Data Pipeline',
            name: 'Stream Processor',
            productFamily: 'data & analytics',
            status: 'beta',
        },
        {
            id: 'Batch ETL',
            parentId: 'Data Pipeline',
            name: 'Batch ETL',
            productFamily: 'data & analytics',
            status: 'beta',
        },

        // AI & ML
        {
            id: 'AI & ML',
            parentId: 'NexusCloud Platform',
            name: 'AI & ML',
            productFamily: 'ai & ml',
            status: 'released',
        },
        {
            id: 'Model Training',
            parentId: 'AI & ML',
            name: 'Model Training',
            productFamily: 'ai & ml',
            status: 'released',
        },
        { id: 'AutoML', parentId: 'Model Training', name: 'AutoML', productFamily: 'ai & ml', status: 'released' },
        {
            id: 'Hyperparameter Tuning',
            parentId: 'AutoML',
            name: 'Hyperparameter Tuning',
            productFamily: 'ai & ml',
            status: 'released',
        },
        {
            id: 'Custom Training Jobs',
            parentId: 'Model Training',
            name: 'Custom Training Jobs',
            productFamily: 'ai & ml',
            status: 'released',
        },
        { id: 'Model Serving', parentId: 'AI & ML', name: 'Model Serving', productFamily: 'ai & ml', status: 'beta' },
        {
            id: 'Inference API',
            parentId: 'Model Serving',
            name: 'Inference API',
            productFamily: 'ai & ml',
            status: 'beta',
        },
    ];
}
