export function getData() {
    return [
        { weight: 6000, lifespan: 60, population: 0.5, animal: 'Elephant' },
        { weight: 190, lifespan: 15, population: 0.2, animal: 'Lion' },
        { weight: 200, lifespan: 40, population: 1.5, animal: 'Dolphin' },
        { weight: 180, lifespan: 35, population: 0.1, animal: 'Gorilla' },
        { weight: 80, lifespan: 12, population: 50, animal: 'Kangaroo' },
        { weight: 70, lifespan: 12, population: 0.03, animal: 'Cheetah' },
        { weight: 1200, lifespan: 30, population: 0.4, animal: 'Rhino' },
        { weight: 60, lifespan: 15, population: 25, animal: 'Koala' },
        { weight: 600, lifespan: 50, population: 0.3, animal: 'Tiger' },
        { weight: 5500, lifespan: 70, population: 0.03, animal: 'Blue Whale' },
        { weight: 90, lifespan: 20, population: 8.0, animal: 'Penguin' },
        { weight: 500, lifespan: 40, population: 3.5, animal: 'Polar Bear' },
        { weight: 150, lifespan: 10, population: 1.0, animal: 'Red Panda' },
        { weight: 50, lifespan: 12, population: 12.5, animal: 'Rabbit' },
        { weight: 4000, lifespan: 40, population: 0.1, animal: 'Hippopotamus' },
        {
            weight: 8000,
            lifespan: 70,
            population: 0.02,
            animal: 'White Rhinoceros',
        },
        { weight: 18000, lifespan: 50, population: 0.03, animal: 'Bison' },
        { weight: 13000, lifespan: 45, population: 0.05, animal: 'Gaur' },
        {
            weight: 12000,
            lifespan: 40,
            population: 0.01,
            animal: 'Asian Elephant',
        },
        { weight: 30000, lifespan: 70, population: 0.005, animal: 'Fin Whale' },
        {
            weight: 25000,
            lifespan: 70,
            population: 0.004,
            animal: 'Sperm Whale',
        },
        { weight: 10000, lifespan: 50, population: 0.2, animal: 'Walrus' },
        { weight: 5000, lifespan: 30, population: 0.8, animal: 'Giraffe' },
        { weight: 7000, lifespan: 35, population: 1.0, animal: 'Killer Whale' },
        { weight: 4000, lifespan: 20, population: 0.4, animal: 'Crocodile' },
        { weight: 9000, lifespan: 30, population: 0.6, animal: 'Camel' },
        { weight: 7000, lifespan: 40, population: 0.3, animal: 'Zebra' },
    ];
}
