export function getData() {
    return [
        {
            label: 'Western Europe',
            min: 5.03,
            q1: 6.36,
            median: 6.91,
            q3: 7.34,
            max: 7.53,
        },
        {
            label: 'North America',
            min: 7.1,
            q1: 7.18,
            median: 7.25,
            q3: 7.33,
            max: 7.4,
        },
        {
            label: 'Australia and New Zealand',
            min: 7.31,
            q1: 7.32,
            median: 7.32,
            q3: 7.33,
            max: 7.33,
        },
        {
            label: 'Middle East and Northern Africa',
            min: 3.07,
            q1: 4.78,
            median: 5.3,
            q3: 6.3,
            max: 7.27,
        },
        {
            label: 'Latin America and Caribbean',
            min: 4.87,
            q1: 5.8,
            median: 6.13,
            q3: 6.66,
            max: 7.09,
            outliers: [4.03],
        },
        {
            label: 'Southeastern Asia',
            min: 3.91,
            q1: 4.88,
            median: 5.28,
            q3: 6.01,
            max: 6.74,
        },
        {
            label: 'Central and Eastern Europe',
            min: 4.22,
            q1: 5.15,
            median: 5.49,
            q3: 5.81,
            max: 6.6,
        },
        {
            label: 'Eastern Asia',
            min: 4.91,
            q1: 5.3,
            median: 5.65,
            q3: 5.9,
            max: 6.38,
        },
        {
            label: 'Sub-Saharan Africa',
            min: 2.91,
            q1: 3.74,
            median: 4.13,
            q3: 4.43,
            max: 5.44,
            outliers: [5.648],
        },
        {
            label: 'Southern Asia',
            min: 4.4,
            q1: 4.41,
            median: 4.64,
            q3: 4.96,
            max: 5.2,
            outliers: [3.36],
        },
    ];
}
