export const eastern = [
    { name: 'Connecticut' },
    { name: 'Delaware' },
    { name: 'District of Columbia' },
    { name: 'Florida' },
    { name: 'Georgia' },
    { name: 'Indiana' },
    { name: 'Kentucky' },
    { name: 'Maine' },
    { name: 'Maryland' },
    { name: 'Massachusetts' },
    { name: 'Michigan' },
    { name: 'New Hampshire' },
    { name: 'New Jersey' },
    { name: 'New York' },
    { name: 'North Carolina' },
    { name: 'Ohio' },
    { name: 'Pennsylvania' },
    { name: 'Rhode Island' },
    { name: 'South Carolina' },
    { name: 'Vermont' },
    { name: 'Virginia' },
    { name: 'West Virginia' },
];

export const central = [
    { name: 'Alabama' },
    { name: 'Arkansas' },
    { name: 'Illinois' },
    { name: 'Iowa' },
    { name: 'Kansas' },
    { name: 'Louisiana' },
    { name: 'Minnesota' },
    { name: 'Mississippi' },
    { name: 'Missouri' },
    { name: 'Nebraska' },
    { name: 'North Dakota' },
    { name: 'Oklahoma' },
    { name: 'South Dakota' },
    { name: 'Tennessee' },
    { name: 'Texas' },
    { name: 'Wisconsin' },
];

export const mountain = [
    { name: 'Arizona' },
    { name: 'Colorado' },
    { name: 'Idaho' },
    { name: 'Montana' },
    { name: 'New Mexico' },
    { name: 'Utah' },
    { name: 'Wyoming' },
];

export const pacific = [{ name: 'California' }, { name: 'Washington' }, { name: 'Nevada' }, { name: 'Oregon' }];
