export function getData() {
    return [
        {
            company: 'AlphaTech',
            industry: 'Tech',
            revenue: 120,
            employees: 80,
            growth: 15,
        },
        {
            company: 'CloudNine',
            industry: 'Tech',
            revenue: 117,
            employees: 77,
            growth: 14,
        },
        {
            company: 'DevSolutions',
            industry: 'Tech',
            revenue: 125,
            employees: 82,
            growth: 13,
        },
        // {
        //     company: 'NextNova',
        //     industry: 'Tech',
        //     revenue: 123,
        //     employees: 79,
        //     growth: 12,
        // },
        // {
        //     company: 'BitLogic',
        //     industry: 'Tech',
        //     revenue: 121,
        //     employees: 76,
        //     growth: 13,
        // },
        // {
        //     company: 'SoftCore',
        //     industry: 'Tech',
        //     revenue: 119,
        //     employees: 81,
        //     growth: 11,
        // },
        // {
        //     company: 'CodeCatalyst',
        //     industry: 'Tech',
        //     revenue: 124,
        //     employees: 78,
        //     growth: 12,
        // },
        // {
        //     company: 'NeuralEdge',
        //     industry: 'Tech',
        //     revenue: 122,
        //     employees: 83,
        //     growth: 14,
        // },
        // {
        //     company: 'PixelForge',
        //     industry: 'Tech',
        //     revenue: 126,
        //     employees: 75,
        //     growth: 13,
        // },
        // {
        //     company: 'QuantumSoft',
        //     industry: 'Tech',
        //     revenue: 127,
        //     employees: 80,
        //     growth: 12,
        // },
        // {
        //     company: 'AppSage',
        //     industry: 'Tech',
        //     revenue: 118,
        //     employees: 79,
        //     growth: 11,
        // },
        // {
        //     company: 'ByteWave',
        //     industry: 'Tech',
        //     revenue: 123,
        //     employees: 82,
        //     growth: 15,
        // },
    ];
}
