export function getData() {
    return [
        {
            company: 'AlphaTech',
            industry: 'Tech',
            revenue: 120,
            employees: 80,
            growth: 15,
        },
        {
            company: 'CloudNine',
            industry: 'Tech',
            revenue: 117,
            employees: 77,
            growth: 14,
        },
        {
            company: 'DevSolutions',
            industry: 'Tech',
            revenue: 125,
            employees: 82,
            growth: 13,
        },
        {
            company: 'NextNova',
            industry: 'Tech',
            revenue: 123,
            employees: 79,
            growth: 12,
        },
        {
            company: 'BitLogic',
            industry: 'Tech',
            revenue: 121,
            employees: 76,
            growth: 13,
        },
        {
            company: 'SoftCore',
            industry: 'Tech',
            revenue: 119,
            employees: 81,
            growth: 11,
        },
        {
            company: 'CodeCatalyst',
            industry: 'Tech',
            revenue: 124,
            employees: 78,
            growth: 12,
        },
        {
            company: 'NeuralEdge',
            industry: 'Tech',
            revenue: 122,
            employees: 83,
            growth: 14,
        },
        {
            company: 'PixelForge',
            industry: 'Tech',
            revenue: 126,
            employees: 75,
            growth: 13,
        },
        {
            company: 'QuantumSoft',
            industry: 'Tech',
            revenue: 127,
            employees: 80,
            growth: 12,
        },
        {
            company: 'AppSage',
            industry: 'Tech',
            revenue: 118,
            employees: 79,
            growth: 11,
        },
        {
            company: 'ByteWave',
            industry: 'Tech',
            revenue: 123,
            employees: 82,
            growth: 15,
        },
        {
            company: 'MediCore',
            industry: 'Healthcare',
            revenue: 102,
            employees: 93,
            growth: 11,
        },
        {
            company: 'HealthSpring',
            industry: 'Healthcare',
            revenue: 97,
            employees: 96,
            growth: 10,
        },
        {
            company: 'LifeAxis',
            industry: 'Healthcare',
            revenue: 105,
            employees: 91,
            growth: 12,
        },
        {
            company: 'CureWell',
            industry: 'Healthcare',
            revenue: 99,
            employees: 94,
            growth: 9,
        },
        {
            company: 'PulseOne',
            industry: 'Healthcare',
            revenue: 104,
            employees: 90,
            growth: 10,
        },
        {
            company: 'TheraPlus',
            industry: 'Healthcare',
            revenue: 101,
            employees: 92,
            growth: 9,
        },
        {
            company: 'BioUnity',
            industry: 'Healthcare',
            revenue: 98,
            employees: 95,
            growth: 10,
        },
        {
            company: 'HealBridge',
            industry: 'Healthcare',
            revenue: 100,
            employees: 89,
            growth: 11,
        },
        {
            company: 'MediFlex',
            industry: 'Healthcare',
            revenue: 96,
            employees: 97,
            growth: 10,
        },
        {
            company: 'NovaClinic',
            industry: 'Healthcare',
            revenue: 103,
            employees: 93,
            growth: 12,
        },
        {
            company: 'GeneCare',
            industry: 'Healthcare',
            revenue: 95,
            employees: 98,
            growth: 9,
        },
        {
            company: 'VitalSphere',
            industry: 'Healthcare',
            revenue: 106,
            employees: 88,
            growth: 11,
        },
        {
            company: 'Finverse',
            industry: 'Finance',
            revenue: 88,
            employees: 74,
            growth: 12,
        },
        {
            company: 'CrediSure',
            industry: 'Finance',
            revenue: 91,
            employees: 69,
            growth: 13,
        },
        {
            company: 'MoneyMap',
            industry: 'Finance',
            revenue: 85,
            employees: 72,
            growth: 11,
        },
        {
            company: 'Investra',
            industry: 'Finance',
            revenue: 90,
            employees: 71,
            growth: 10,
        },
        {
            company: 'CapBridge',
            industry: 'Finance',
            revenue: 86,
            employees: 73,
            growth: 10,
        },
        {
            company: 'SafeTrust',
            industry: 'Finance',
            revenue: 87,
            employees: 68,
            growth: 9,
        },
        {
            company: 'Wealtho',
            industry: 'Finance',
            revenue: 89,
            employees: 70,
            growth: 12,
        },
        {
            company: 'Fundia',
            industry: 'Finance',
            revenue: 92,
            employees: 67,
            growth: 13,
        },
        {
            company: 'Investo',
            industry: 'Finance',
            revenue: 93,
            employees: 75,
            growth: 11,
        },
        {
            company: 'PrimeBank',
            industry: 'Finance',
            revenue: 84,
            employees: 66,
            growth: 10,
        },
        {
            company: 'YieldBridge',
            industry: 'Finance',
            revenue: 83,
            employees: 76,
            growth: 9,
        },
        {
            company: 'SecureAssets',
            industry: 'Finance',
            revenue: 94,
            employees: 65,
            growth: 12,
        },
        {
            company: 'Retailly',
            industry: 'Retail',
            revenue: 113,
            employees: 87,
            growth: 9,
        },
        {
            company: 'MegaMart',
            industry: 'Retail',
            revenue: 109,
            employees: 84,
            growth: 8,
        },
        {
            company: 'ShopSphere',
            industry: 'Retail',
            revenue: 115,
            employees: 89,
            growth: 7,
        },
        {
            company: 'QuickBuy',
            industry: 'Retail',
            revenue: 111,
            employees: 85,
            growth: 6,
        },
        {
            company: 'DailyGoods',
            industry: 'Retail',
            revenue: 116,
            employees: 90,
            growth: 8,
        },
        {
            company: 'SwiftShop',
            industry: 'Retail',
            revenue: 112,
            employees: 88,
            growth: 7,
        },
        {
            company: 'UrbanMart',
            industry: 'Retail',
            revenue: 114,
            employees: 83,
            growth: 9,
        },
        {
            company: 'ClickCart',
            industry: 'Retail',
            revenue: 110,
            employees: 86,
            growth: 8,
        },
        {
            company: 'PriceHopper',
            industry: 'Retail',
            revenue: 117,
            employees: 91,
            growth: 7,
        },
        {
            company: 'FastLane',
            industry: 'Retail',
            revenue: 108,
            employees: 82,
            growth: 6,
        },
        {
            company: 'MarketZone',
            industry: 'Retail',
            revenue: 118,
            employees: 92,
            growth: 8,
        },
        {
            company: 'ValueCenter',
            industry: 'Retail',
            revenue: 107,
            employees: 81,
            growth: 7,
        },
        {
            company: 'Energen',
            industry: 'Energy',
            revenue: 128,
            employees: 62,
            growth: 7,
        },
        {
            company: 'Voltix',
            industry: 'Energy',
            revenue: 132,
            employees: 59,
            growth: 6,
        },
        {
            company: 'GreenGrid',
            industry: 'Energy',
            revenue: 127,
            employees: 64,
            growth: 8,
        },
        {
            company: 'PowerNova',
            industry: 'Energy',
            revenue: 130,
            employees: 61,
            growth: 5,
        },
        {
            company: 'EcoCurrent',
            industry: 'Energy',
            revenue: 129,
            employees: 63,
            growth: 7,
        },
        {
            company: 'SolarBase',
            industry: 'Energy',
            revenue: 126,
            employees: 60,
            growth: 6,
        },
        {
            company: 'Watthor',
            industry: 'Energy',
            revenue: 131,
            employees: 65,
            growth: 7,
        },
        {
            company: 'FlowVolt',
            industry: 'Energy',
            revenue: 125,
            employees: 66,
            growth: 6,
        },
        {
            company: 'HydroCore',
            industry: 'Energy',
            revenue: 133,
            employees: 58,
            growth: 5,
        },
        {
            company: 'FusionGrid',
            industry: 'Energy',
            revenue: 134,
            employees: 67,
            growth: 6,
        },
        {
            company: 'ChargeWave',
            industry: 'Energy',
            revenue: 124,
            employees: 68,
            growth: 7,
        },
        {
            company: 'PowerPulse',
            industry: 'Energy',
            revenue: 135,
            employees: 57,
            growth: 5,
        },
    ];
}
