export const gmt = [{ name: 'Greenland' }, { name: 'Iceland' }, { name: 'Portugal' }, { name: 'United Kingdom' }];

export const cet = [
    { name: 'Albania' },
    { name: 'Andorra' },
    { name: 'Austria' },
    { name: 'Belgium' },
    { name: 'Bosnia and Herzegovina' },
    { name: 'Croatia' },
    { name: 'Czech Republic' },
    { name: 'Denmark' },
    { name: 'France' },
    { name: 'Germany' },
    { name: 'Gibraltar' },
    { name: 'Holy See/Vatican City' },
    { name: 'Hungary' },
    { name: 'Italy' },
    { name: 'Kosovo' },
    { name: 'Liechtenstein' },
    { name: 'Luxembourg' },
    { name: 'Malta' },
    { name: 'Monaco' },
    { name: 'Montenegro' },
    { name: 'Netherlands' },
    { name: 'Norway' },
    { name: 'Poland' },
    { name: 'San Marino' },
    { name: 'Serbia' },
    { name: 'Slovakia' },
    { name: 'Slovenia' },
    { name: 'Spain' },
    { name: 'Sweden' },
    { name: 'Switzerland' },
    { name: 'The former Yugoslav Republic of Macedonia' },
];

export const eet = [
    { name: 'Belarus' },
    { name: 'Bulgaria' },
    { name: 'Cyprus' },
    { name: 'Estonia' },
    { name: 'Finland' },
    { name: 'Greece' },
    { name: 'Latvia' },
    { name: 'Lithuania' },
    { name: 'Moldova' },
    { name: 'Romania' },
    { name: 'Ukraine' },
];

export const msk = [{ name: 'Russia' }];
