export function getData() {
    return [
        {
            year: new Date('1958-01-01T00:00:00.000Z'),
            magnitudeLow: 7.5,
            magnitudeHigh: 7.5,
            magnitudeLowRegion: 'Ryukyu Islands',
            magnitudeHighRegion: 'Ryukyu Islands',
            depthLow: 56,
            depthHigh: 56,
            deathTotal: 0,
        },
        {
            year: new Date('1960-01-01T00:00:00.000Z'),
            magnitudeLow: 6.7,
            magnitudeHigh: 7.5,
            magnitudeLowRegion: 'Sanriku',
            magnitudeHighRegion: 'Sanriku',
            depthLow: 30,
            depthHigh: 45,
            deathTotal: 0,
        },
        {
            year: new Date('1961-01-01T00:00:00.000Z'),
            magnitudeLow: 7.3,
            magnitudeHigh: 7.3,
            magnitudeLowRegion: 'Miyazaki',
            magnitudeHighRegion: 'Miyazaki',
            depthLow: 48,
            depthHigh: 48,
            deathTotal: 2,
        },
        {
            year: new Date('1962-01-01T00:00:00.000Z'),
            magnitudeLow: 6.8,
            magnitudeHigh: 7.2,
            magnitudeLowRegion: 'Honshu (Sendai)',
            magnitudeHighRegion: 'Sanriku',
            depthLow: 30,
            depthHigh: 43,
            deathTotal: 1,
        },
        {
            year: new Date('1964-01-01T00:00:00.000Z'),
            magnitudeLow: 6.9,
            magnitudeHigh: 7.5,
            magnitudeLowRegion: 'Nw. Honshu Island',
            magnitudeHighRegion: 'Honshu (W Coast)',
            depthLow: 14,
            depthHigh: 44,
            deathTotal: 26,
        },
        {
            year: new Date('1965-01-01T00:00:00.000Z'),
            magnitudeLow: 6,
            magnitudeHigh: 6,
            magnitudeLowRegion: 'Aichi, Shizouka Prefectures',
            magnitudeHighRegion: 'Aichi, Shizouka Prefectures',
            depthLow: 58,
            depthHigh: 58,
            deathTotal: 1,
        },
        {
            year: new Date('1968-01-01T00:00:00.000Z'),
            magnitudeLow: 7.2,
            magnitudeHigh: 8.2,
            magnitudeLowRegion: 'Sanriku',
            magnitudeHighRegion: 'Off East Coast Of Honshu Island',
            depthLow: 1,
            depthHigh: 55,
            deathTotal: 53,
        },
        {
            year: new Date('1969-01-01T00:00:00.000Z'),
            magnitudeLow: 7.6,
            magnitudeHigh: 7.6,
            magnitudeLowRegion: 'Hokkaido',
            magnitudeHighRegion: 'Hokkaido',
            depthLow: 4,
            depthHigh: 4,
            deathTotal: 0,
        },
        {
            year: new Date('1970-01-01T00:00:00.000Z'),
            magnitudeLow: 7,
            magnitudeHigh: 7,
            magnitudeLowRegion: 'Seikaido, Japan',
            magnitudeHighRegion: 'Seikaido, Japan',
            depthLow: 10,
            depthHigh: 10,
            deathTotal: 0,
        },
        {
            year: new Date('1971-01-01T00:00:00.000Z'),
            magnitudeLow: 7.3,
            magnitudeHigh: 7.3,
            magnitudeLowRegion: 'Japan Trench',
            magnitudeHighRegion: 'Japan Trench',
            depthLow: 56,
            depthHigh: 56,
            deathTotal: 0,
        },
        {
            year: new Date('1972-01-01T00:00:00.000Z'),
            magnitudeLow: 7.2,
            magnitudeHigh: 7.4,
            magnitudeLowRegion: 'South Of Honshu (Hachijojima, Tokyo)',
            magnitudeHighRegion: 'South Of Honshu, Hachijojima',
            depthLow: 12,
            depthHigh: 59,
            deathTotal: 0,
        },
        {
            year: new Date('1973-01-01T00:00:00.000Z'),
            magnitudeLow: 7.7,
            magnitudeHigh: 7.7,
            magnitudeLowRegion: 'Hokkaido Island',
            magnitudeHighRegion: 'Hokkaido Island',
            depthLow: 2,
            depthHigh: 2,
            deathTotal: 0,
        },
        {
            year: new Date('1974-01-01T00:00:00.000Z'),
            magnitudeLow: 5.7,
            magnitudeHigh: 6.5,
            magnitudeLowRegion: 'Honshu (Kakiota, Mito, Tokyo)',
            magnitudeHighRegion: 'Nakagi',
            depthLow: 25,
            depthHigh: 34,
            deathTotal: 32,
        },
        {
            year: new Date('1975-01-01T00:00:00.000Z'),
            magnitudeLow: 5.8,
            magnitudeHigh: 6.1,
            magnitudeLowRegion: 'Arosan',
            magnitudeHighRegion: 'Oita, Arosan',
            depthLow: 14,
            depthHigh: 50,
            deathTotal: 0,
        },
        {
            year: new Date('1978-01-01T00:00:00.000Z'),
            magnitudeLow: 4.9,
            magnitudeHigh: 7.7,
            magnitudeLowRegion: 'South Honshu (Hiroshima)',
            magnitudeHighRegion: 'Sanriku',
            depthLow: 26,
            depthHigh: 58,
            deathTotal: 53,
        },
        {
            year: new Date('1979-01-01T00:00:00.000Z'),
            magnitudeLow: 6.4,
            magnitudeHigh: 6.4,
            magnitudeLowRegion: 'Iwate, Japan',
            magnitudeHighRegion: 'Iwate, Japan',
            depthLow: 32,
            depthHigh: 32,
            deathTotal: 0,
        },
        {
            year: new Date('1980-01-01T00:00:00.000Z'),
            magnitudeLow: 6,
            magnitudeHigh: 6.2,
            magnitudeLowRegion: 'Tokyo, Yokohama',
            magnitudeHighRegion: 'Honshu (S Coast)',
            depthLow: 5,
            depthHigh: 24,
            deathTotal: 2,
        },
        {
            year: new Date('1981-01-01T00:00:00.000Z'),
            magnitudeLow: 6.9,
            magnitudeHigh: 6.9,
            magnitudeLowRegion: 'E. Honshu Island',
            magnitudeHighRegion: 'E. Honshu Island',
            depthLow: 24,
            depthHigh: 24,
            deathTotal: 0,
        },
        {
            year: new Date('1982-01-01T00:00:00.000Z'),
            magnitudeLow: 6.1,
            magnitudeHigh: 6.8,
            magnitudeLowRegion: 'S. Of Honshu Island',
            magnitudeHighRegion: 'Ibaraki, Japan',
            depthLow: 7,
            depthHigh: 53,
            deathTotal: 110,
        },
        {
            year: new Date('1983-01-01T00:00:00.000Z'),
            magnitudeLow: 5.2,
            magnitudeHigh: 7.7,
            magnitudeLowRegion: 'Tottori, Yonango',
            magnitudeHighRegion: 'Honshu (Akita)',
            depthLow: 3,
            depthHigh: 59,
            deathTotal: 5,
        },
        {
            year: new Date('1984-01-01T00:00:00.000Z'),
            magnitudeLow: 5.5,
            magnitudeHigh: 6.9,
            magnitudeLowRegion: 'Tori Shima, Okinawa',
            magnitudeHighRegion: 'Honshu Island',
            depthLow: 25,
            depthHigh: 49,
            deathTotal: 49,
        },
        {
            year: new Date('1987-01-01T00:00:00.000Z'),
            magnitudeLow: 5.1,
            magnitudeHigh: 6.7,
            magnitudeLowRegion: 'Honshu Island',
            magnitudeHighRegion: 'Kyushu (Miyazaki, Naze)',
            depthLow: 17,
            depthHigh: 47,
            deathTotal: 4,
        },
        {
            year: new Date('1989-01-01T00:00:00.000Z'),
            magnitudeLow: 5,
            magnitudeHigh: 7.4,
            magnitudeLowRegion: 'Honshu (Ito, Ajiro)',
            magnitudeHighRegion: 'Honshu (N, Aomori, Misawa)',
            depthLow: 9,
            depthHigh: 38,
            deathTotal: 0,
        },
        {
            year: new Date('1990-01-01T00:00:00.000Z'),
            magnitudeLow: 6.4,
            magnitudeHigh: 6.5,
            magnitudeLowRegion: 'Near S. Coast Of Honshu',
            magnitudeHighRegion: 'W. Of Bonin Islands, Izu Is.',
            depthLow: 7,
            depthHigh: 39,
            deathTotal: 0,
        },
        {
            year: new Date('1992-01-01T00:00:00.000Z'),
            magnitudeLow: 5.6,
            magnitudeHigh: 7,
            magnitudeLowRegion: 'Honshu (Tokyo)',
            magnitudeHighRegion: 'Honshu Island',
            depthLow: 4,
            depthHigh: 58,
            deathTotal: 0,
        },
        {
            year: new Date('1993-01-01T00:00:00.000Z'),
            magnitudeLow: 6.3,
            magnitudeHigh: 7.7,
            magnitudeLowRegion: 'Japan',
            magnitudeHighRegion: 'Hokkaido; Russia (Southeast; South Korea)',
            depthLow: 5,
            depthHigh: 42,
            deathTotal: 25,
        },
        {
            year: new Date('1994-01-01T00:00:00.000Z'),
            magnitudeLow: 6.4,
            magnitudeHigh: 7.8,
            magnitudeLowRegion: 'Off East Coast Of Honshu Island',
            magnitudeHighRegion: 'Honshu',
            depthLow: 23,
            depthHigh: 40,
            deathTotal: 3,
        },
        {
            year: new Date('1995-01-01T00:00:00.000Z'),
            magnitudeLow: 5.4,
            magnitudeHigh: 7.1,
            magnitudeLowRegion: 'Niigata Prefecture, Sado',
            magnitudeHighRegion: 'Ryuku Is.',
            depthLow: 26,
            depthHigh: 52,
            deathTotal: 5502,
        },
        {
            year: new Date('1996-01-01T00:00:00.000Z'),
            magnitudeLow: 5.7,
            magnitudeHigh: 6.7,
            magnitudeLowRegion: 'Honshu Island, Japan',
            magnitudeHighRegion: 'Kyushu',
            depthLow: 1,
            depthHigh: 59,
            deathTotal: 0,
        },
        {
            year: new Date('1997-01-01T00:00:00.000Z'),
            magnitudeLow: 6.1,
            magnitudeHigh: 6.2,
            magnitudeLowRegion: 'Kyushu, Kagoshima',
            magnitudeHighRegion: 'Honshu',
            depthLow: 24,
            depthHigh: 47,
            deathTotal: 0,
        },
        {
            year: new Date('2000-01-01T00:00:00.000Z'),
            magnitudeLow: 6.1,
            magnitudeHigh: 7.6,
            magnitudeLowRegion: 'Near S Coast Honshu (Nii-Jima)',
            magnitudeHighRegion: 'Volcano Islands',
            depthLow: 19,
            depthHigh: 55,
            deathTotal: 1,
        },
        {
            year: new Date('2001-01-01T00:00:00.000Z'),
            magnitudeLow: 6.8,
            magnitudeHigh: 6.8,
            magnitudeLowRegion: 'Hiroshima, Okayama, Honshu, Kagama',
            magnitudeHighRegion: 'Hiroshima, Okayama, Honshu, Kagama',
            depthLow: 53,
            depthHigh: 53,
            deathTotal: 2,
        },
        {
            year: new Date('2002-01-01T00:00:00.000Z'),
            magnitudeLow: 6.4,
            magnitudeHigh: 6.4,
            magnitudeLowRegion: 'Ryukyu Islands',
            magnitudeHighRegion: 'Ryukyu Islands',
            depthLow: 48,
            depthHigh: 48,
            deathTotal: 0,
        },
        {
            year: new Date('2003-01-01T00:00:00.000Z'),
            magnitudeLow: 5.2,
            magnitudeHigh: 8.3,
            magnitudeLowRegion: 'Near S Coast Honshu (Atsugi)',
            magnitudeHighRegion: 'Hokkaido',
            depthLow: 6,
            depthHigh: 50,
            deathTotal: 0,
        },
        {
            year: new Date('2004-01-01T00:00:00.000Z'),
            magnitudeLow: 5.5,
            magnitudeHigh: 7.4,
            magnitudeLowRegion: 'Honshu (Niigata Prefecture)',
            magnitudeHighRegion: 'Honshu (W Coast: Kyoto, Wakayama, Sakai)',
            depthLow: 0,
            depthHigh: 58,
            deathTotal: 40,
        },
        {
            year: new Date('2005-01-01T00:00:00.000Z'),
            magnitudeLow: 5.9,
            magnitudeHigh: 7.2,
            magnitudeLowRegion: 'Honshu (Tokyo)',
            magnitudeHighRegion: 'East Coast Honshu',
            depthLow: 28,
            depthHigh: 56,
            deathTotal: 1,
        },
        {
            year: new Date('2006-01-01T00:00:00.000Z'),
            magnitudeLow: 6.3,
            magnitudeHigh: 6.3,
            magnitudeLowRegion: 'Kyushu',
            magnitudeHighRegion: 'Kyushu',
            depthLow: 26,
            depthHigh: 26,
            deathTotal: 0,
        },
        {
            year: new Date('2007-01-01T00:00:00.000Z'),
            magnitudeLow: 4.6,
            magnitudeHigh: 7.5,
            magnitudeLowRegion: 'Honshu',
            magnitudeHighRegion: 'Volcano Islands',
            depthLow: 22,
            depthHigh: 57,
            deathTotal: 10,
        },
        {
            year: new Date('2008-01-01T00:00:00.000Z'),
            magnitudeLow: 6.8,
            magnitudeHigh: 6.9,
            magnitudeLowRegion: 'Hokkaido',
            magnitudeHighRegion: 'Off East Coast Of Honshu Island',
            depthLow: 19,
            depthHigh: 50,
            deathTotal: 14,
        },
        {
            year: new Date('2009-01-01T00:00:00.000Z'),
            magnitudeLow: 4.9,
            magnitudeHigh: 6.4,
            magnitudeLowRegion: 'Honshu (Ito)',
            magnitudeHighRegion: 'Honshu (S Coast)',
            depthLow: 9,
            depthHigh: 36,
            deathTotal: 1,
        },
        {
            year: new Date('2010-01-01T00:00:00.000Z'),
            magnitudeLow: 7,
            magnitudeHigh: 7.4,
            magnitudeLowRegion: 'Tori Shima, Okinawa',
            magnitudeHighRegion: 'Bonin Islands',
            depthLow: 26,
            depthHigh: 40,
            deathTotal: 0,
        },
        {
            year: new Date('2011-01-01T00:00:00.000Z'),
            magnitudeLow: 6.6,
            magnitudeHigh: 9.1,
            magnitudeLowRegion: 'Honshu',
            magnitudeHighRegion: 'Hokkaido',
            depthLow: 10,
            depthHigh: 50,
            deathTotal: 1485,
        },
        {
            year: new Date('2012-01-01T00:00:00.000Z'),
            magnitudeLow: 6.9,
            magnitudeHigh: 7.2,
            magnitudeLowRegion: 'Hokkaido',
            magnitudeHighRegion: 'Honshu (Miyagi Prefecture)',
            depthLow: 23,
            depthHigh: 35,
            deathTotal: 0,
        },
        {
            year: new Date('2013-01-01T00:00:00.000Z'),
            magnitudeLow: 5.8,
            magnitudeHigh: 7.1,
            magnitudeLowRegion: 'Miyakejima',
            magnitudeHighRegion: 'Honshu (E Coast)',
            depthLow: 0,
            depthHigh: 33,
            deathTotal: 0,
        },
        {
            year: new Date('2014-01-01T00:00:00.000Z'),
            magnitudeLow: 6.2,
            magnitudeHigh: 6.5,
            magnitudeLowRegion: 'Nagano (Hakuba, Otari)',
            magnitudeHighRegion: 'Sanriku',
            depthLow: 17,
            depthHigh: 42,
            deathTotal: 0,
        },
        {
            year: new Date('2015-01-01T00:00:00.000Z'),
            magnitudeLow: 5.7,
            magnitudeHigh: 7.8,
            magnitudeLowRegion: 'Honshu (S. Of)',
            magnitudeHighRegion: 'Bonin Islands [chichijima Island]',
            depthLow: 3,
            depthHigh: 39,
            deathTotal: 0,
        },
        {
            year: new Date('2016-01-01T00:00:00.000Z'),
            magnitudeLow: 6,
            magnitudeHigh: 7,
            magnitudeLowRegion: 'Off East Coast Honshu',
            magnitudeHighRegion: 'Kumamoto, Oita',
            depthLow: 22,
            depthHigh: 39,
            deathTotal: 50,
        },
        {
            year: new Date('2018-01-01T00:00:00.000Z'),
            magnitudeLow: 5.4,
            magnitudeHigh: 6.6,
            magnitudeLowRegion: 'Honshu (S. Of)',
            magnitudeHighRegion: 'Hokkaido',
            depthLow: 10,
            depthHigh: 35,
            deathTotal: 49,
        },
        {
            year: new Date('2019-01-01T00:00:00.000Z'),
            magnitudeLow: 6.4,
            magnitudeHigh: 6.4,
            magnitudeLowRegion: 'Niigata Prefecture',
            magnitudeHighRegion: 'Niigata Prefecture',
            depthLow: 12,
            depthHigh: 12,
            deathTotal: 0,
        },
        {
            year: new Date('2021-01-01T00:00:00.000Z'),
            magnitudeLow: 7,
            magnitudeHigh: 7.1,
            magnitudeLowRegion: 'Honshu Island',
            magnitudeHighRegion: 'Off Fukushima',
            depthLow: 43,
            depthHigh: 49,
            deathTotal: 1,
        },
        {
            year: new Date('2022-01-01T00:00:00.000Z'),
            magnitudeLow: 7.3,
            magnitudeHigh: 7.3,
            magnitudeLowRegion: 'Off Fukushima',
            magnitudeHighRegion: 'Off Fukushima',
            depthLow: 63,
            depthHigh: 63,
            deathTotal: 4,
        },
        {
            year: new Date('2023-01-01T00:00:00.000Z'),
            magnitudeLow: 4.9,
            magnitudeHigh: 6.2,
            magnitudeLowRegion: 'Izu Islands',
            magnitudeHighRegion: 'Honshu (Ishikawa, Toyama)',
            depthLow: 8,
            depthHigh: 10,
            deathTotal: 1,
        },
    ];
}
