export function getData() {
    return [
        {
            id: 'Ashley Rivers',
            parentId: null,
            name: 'Ashley Rivers',
            job: 'CEO',
            department: 'Executive',
            location: 'United Kingdom',
            status: 'In Office',
            avatar: '${baseWWWUrl}example-assets/docs-images/hr/19.webp',
            flag: '${baseWWWUrl}example-assets/flags/gb.png',
        },
        {
            id: 'Joseph Howe',
            parentId: 'Ashley Rivers',
            name: 'Joseph Howe',
            job: 'CTO',
            department: 'Technology',
            location: 'United States',
            status: 'Hybrid',
            avatar: '${baseWWWUrl}example-assets/docs-images/hr/25.webp',
            flag: '${baseWWWUrl}example-assets/flags/us.png',
        },
        {
            id: 'Jeffrey Brown',
            parentId: 'Joseph Howe',
            name: 'Jeffrey Brown',
            job: 'Engineering Lead',
            department: 'Technology',
            location: 'United States',
            status: 'In Office',
            avatar: '${baseWWWUrl}example-assets/docs-images/hr/22.webp',
            flag: '${baseWWWUrl}example-assets/flags/us.png',
        },
        {
            id: 'Melissa Vazquez',
            parentId: 'Jeffrey Brown',
            name: 'Melissa Vazquez',
            job: 'Software Engineer',
            department: 'Technology',
            location: 'United States',
            status: 'Hybrid',
            avatar: '${baseWWWUrl}example-assets/docs-images/hr/4.webp',
            flag: '${baseWWWUrl}example-assets/flags/us.png',
        },
        {
            id: 'John Thomas',
            parentId: 'Jeffrey Brown',
            name: 'John Thomas',
            job: 'Software Engineer',
            department: 'Technology',
            location: 'United States',
            status: 'Hybrid',
            avatar: '${baseWWWUrl}example-assets/docs-images/hr/5.webp',
            flag: '${baseWWWUrl}example-assets/flags/us.png',
        },
        {
            id: 'Susan Hernandez',
            parentId: 'Jeffrey Brown',
            name: 'Susan Hernandez',
            job: 'Dev Ops',
            department: 'Technology',
            location: 'Ireland',
            status: 'In Office',
            avatar: '${baseWWWUrl}example-assets/docs-images/hr/20.webp',
            flag: '${baseWWWUrl}example-assets/flags/ie.png',
        },
        {
            id: 'Justin Contreras',
            parentId: 'Joseph Howe',
            name: 'Justin Contreras',
            job: 'Engineering Lead',
            department: 'Technology',
            location: 'Italy',
            status: 'In Office',
            avatar: '${baseWWWUrl}example-assets/docs-images/hr/10.webp',
            flag: '${baseWWWUrl}example-assets/flags/it.png',
        },
        {
            id: 'Rachel Ibarra',
            parentId: 'Justin Contreras',
            name: 'Rachel Ibarra',
            job: 'Software Engineer',
            department: 'Technology',
            location: 'Italy',
            status: 'Remote',
            avatar: '${baseWWWUrl}example-assets/docs-images/hr/2.webp',
            flag: '${baseWWWUrl}example-assets/flags/it.png',
        },
        {
            id: 'John Gomez',
            parentId: 'Justin Contreras',
            name: 'John Gomez',
            job: 'Software Engineer',
            department: 'Technology',
            location: 'France',
            status: 'In Office',
            avatar: '${baseWWWUrl}example-assets/docs-images/hr/17.webp',
            flag: '${baseWWWUrl}example-assets/flags/fr.png',
        },
        {
            id: 'Gary Garcia',
            parentId: 'Ashley Rivers',
            name: 'Gary Garcia',
            job: 'CPO',
            department: 'Product',
            location: 'United Kingdom',
            status: 'In Office',
            avatar: '${baseWWWUrl}example-assets/docs-images/hr/29.webp',
            flag: '${baseWWWUrl}example-assets/flags/gb.png',
        },
        {
            id: 'Lawrence Martinez',
            parentId: 'Gary Garcia',
            name: 'Lawrence Martinez',
            job: 'Product Manager',
            department: 'Product',
            location: 'United Kingdom',
            status: 'Hybrid',
            avatar: '${baseWWWUrl}example-assets/docs-images/hr/33.webp',
            flag: '${baseWWWUrl}example-assets/flags/gb.png',
        },
        {
            id: 'Devin Pittman',
            parentId: 'Gary Garcia',
            name: 'Devin Pittman',
            job: 'Design Lead',
            department: 'Product',
            location: 'United Kingdom',
            status: 'In Office',
            avatar: '${baseWWWUrl}example-assets/docs-images/hr/18.webp',
            flag: '${baseWWWUrl}example-assets/flags/gb.png',
        },
        {
            id: 'Emily Barajas',
            parentId: 'Devin Pittman',
            name: 'Emily Barajas',
            job: 'Visual Designer',
            department: 'Product',
            location: 'United Kingdom',
            status: 'Hybrid',
            avatar: '${baseWWWUrl}example-assets/docs-images/hr/28.webp',
            flag: '${baseWWWUrl}example-assets/flags/gb.png',
        },
        {
            id: 'Eric Jensen',
            parentId: 'Ashley Rivers',
            name: 'Eric Jensen',
            job: 'CFO/COO',
            department: 'Finance & Operations',
            location: 'Spain',
            status: 'Remote',
            avatar: '${baseWWWUrl}example-assets/docs-images/hr/35.webp',
            flag: '${baseWWWUrl}example-assets/flags/es.png',
        },
    ];
}
