// source: https://www.gov.uk/government/statistical-data-sets/monthly-domestic-energy-price-stastics

export function getData() {
    return [
        {
            Year: [1990, 'Jan to Mar'],
            'Current Gas': 33.8,
            'Current Electricity': 45.4,
            'Real Gas': 62.4,
            'Real Electricity': 83.8,
        },
        {
            Year: [1990, 'Apr to June'],
            'Current Gas': 35.7,
            'Current Electricity': 47.4,
            'Real Gas': 64.8,
            'Real Electricity': 86.2,
        },
        {
            Year: [1990, 'July to Sept'],
            'Current Gas': 36.2,
            'Current Electricity': 49.6,
            'Real Gas': 63.7,
            'Real Electricity': 87.3,
        },
        {
            Year: [1990, 'Oct to Dec'],
            'Current Gas': 36.4,
            'Current Electricity': 49.6,
            'Real Gas': 63.5,
            'Real Electricity': 86.4,
        },
        {
            Year: [1991, 'Jan to Mar'],
            'Current Gas': 37.3,
            'Current Electricity': 49.6,
            'Real Gas': 63.8,
            'Real Electricity': 84.8,
        },
        {
            Year: [1991, 'Apr to June'],
            'Current Gas': 37.9,
            'Current Electricity': 52,
            'Real Gas': 63.8,
            'Real Electricity': 87.7,
        },
        {
            Year: [1991, 'July to Sept'],
            'Current Gas': 38.5,
            'Current Electricity': 54.8,
            'Real Gas': 64.1,
            'Real Electricity': 91.2,
        },
        {
            Year: [1991, 'Oct to Dec'],
            'Current Gas': 38.5,
            'Current Electricity': 54.8,
            'Real Gas': 63.3,
            'Real Electricity': 90.2,
        },
        {
            Year: [1992, 'Jan to Mar'],
            'Current Gas': 38.5,
            'Current Electricity': 54.8,
            'Real Gas': 62.7,
            'Real Electricity': 89.3,
        },
        {
            Year: [1992, 'Apr to June'],
            'Current Gas': 38.5,
            'Current Electricity': 55.2,
            'Real Gas': 62.5,
            'Real Electricity': 89.7,
        },
        {
            Year: [1992, 'July to Sept'],
            'Current Gas': 37.9,
            'Current Electricity': 56,
            'Real Gas': 61.5,
            'Real Electricity': 90.9,
        },
        {
            Year: [1992, 'Oct to Dec'],
            'Current Gas': 36.9,
            'Current Electricity': 56,
            'Real Gas': 59.6,
            'Real Electricity': 90.4,
        },
        {
            Year: [1993, 'Jan to Mar'],
            'Current Gas': 36.5,
            'Current Electricity': 56,
            'Real Gas': 57.9,
            'Real Electricity': 88.7,
        },
        {
            Year: [1993, 'Apr to June'],
            'Current Gas': 36.5,
            'Current Electricity': 55.5,
            'Real Gas': 58.1,
            'Real Electricity': 88.3,
        },
        {
            Year: [1993, 'July to Sept'],
            'Current Gas': 36.5,
            'Current Electricity': 55,
            'Real Gas': 57.5,
            'Real Electricity': 86.6,
        },
        {
            Year: [1993, 'Oct to Dec'],
            'Current Gas': 36.5,
            'Current Electricity': 54.9,
            'Real Gas': 56.8,
            'Real Electricity': 85.4,
        },
        {
            Year: [1994, 'Jan to Mar'],
            'Current Gas': 36.5,
            'Current Electricity': 54.3,
            'Real Gas': 56.6,
            'Real Electricity': 84.2,
        },
        {
            Year: [1994, 'Apr to June'],
            'Current Gas': 39.5,
            'Current Electricity': 58,
            'Real Gas': 61.4,
            'Real Electricity': 90.2,
        },
        {
            Year: [1994, 'July to Sept'],
            'Current Gas': 39.5,
            'Current Electricity': 58.3,
            'Real Gas': 61.3,
            'Real Electricity': 90.6,
        },
        {
            Year: [1994, 'Oct to Dec'],
            'Current Gas': 39.5,
            'Current Electricity': 58,
            'Real Gas': 60.4,
            'Real Electricity': 88.8,
        },
        {
            Year: [1995, 'Jan to Mar'],
            'Current Gas': 39.7,
            'Current Electricity': 58,
            'Real Gas': 60.7,
            'Real Electricity': 88.6,
        },
        {
            Year: [1995, 'Apr to June'],
            'Current Gas': 40.1,
            'Current Electricity': 57.9,
            'Real Gas': 60.7,
            'Real Electricity': 87.7,
        },
        {
            Year: [1995, 'July to Sept'],
            'Current Gas': 40.1,
            'Current Electricity': 58,
            'Real Gas': 60.3,
            'Real Electricity': 87.2,
        },
        {
            Year: [1995, 'Oct to Dec'],
            'Current Gas': 40.1,
            'Current Electricity': 57.9,
            'Real Gas': 59.5,
            'Real Electricity': 86,
        },
        {
            Year: [1996, 'Jan to Mar'],
            'Current Gas': 40.1,
            'Current Electricity': 57.9,
            'Real Gas': 59,
            'Real Electricity': 85.2,
        },
        {
            Year: [1996, 'Apr to June'],
            'Current Gas': 40.1,
            'Current Electricity': 58,
            'Real Gas': 57.9,
            'Real Electricity': 83.8,
        },
        {
            Year: [1996, 'July to Sept'],
            'Current Gas': 40.1,
            'Current Electricity': 58,
            'Real Gas': 57.5,
            'Real Electricity': 83.3,
        },
        {
            Year: [1996, 'Oct to Dec'],
            'Current Gas': 40.1,
            'Current Electricity': 56.9,
            'Real Gas': 57.7,
            'Real Electricity': 82,
        },
        {
            Year: [1997, 'Jan to Mar'],
            'Current Gas': 40.1,
            'Current Electricity': 56.2,
            'Real Gas': 58.5,
            'Real Electricity': 82.1,
        },
        {
            Year: [1997, 'Apr to June'],
            'Current Gas': 39.9,
            'Current Electricity': 56,
            'Real Gas': 58.2,
            'Real Electricity': 81.6,
        },
        {
            Year: [1997, 'July to Sept'],
            'Current Gas': 39.7,
            'Current Electricity': 54.7,
            'Real Gas': 56.5,
            'Real Electricity': 77.8,
        },
        {
            Year: [1997, 'Oct to Dec'],
            'Current Gas': 40.1,
            'Current Electricity': 54.4,
            'Real Gas': 58.4,
            'Real Electricity': 79.3,
        },
        {
            Year: [1998, 'Jan to Mar'],
            'Current Gas': 39.5,
            'Current Electricity': 54.4,
            'Real Gas': 56.9,
            'Real Electricity': 78.4,
        },
        {
            Year: [1998, 'Apr to June'],
            'Current Gas': 39.5,
            'Current Electricity': 54.3,
            'Real Gas': 56.8,
            'Real Electricity': 78.1,
        },
        {
            Year: [1998, 'July to Sept'],
            'Current Gas': 39.5,
            'Current Electricity': 53.4,
            'Real Gas': 56.4,
            'Real Electricity': 76.3,
        },
        {
            Year: [1998, 'Oct to Dec'],
            'Current Gas': 39.5,
            'Current Electricity': 53.4,
            'Real Gas': 56,
            'Real Electricity': 75.8,
        },
        {
            Year: [1999, 'Jan to Mar'],
            'Current Gas': 39.7,
            'Current Electricity': 53.4,
            'Real Gas': 56.3,
            'Real Electricity': 75.7,
        },
        {
            Year: [1999, 'Apr to June'],
            'Current Gas': 39.3,
            'Current Electricity': 53.3,
            'Real Gas': 55.5,
            'Real Electricity': 75.1,
        },
        {
            Year: [1999, 'July to Sept'],
            'Current Gas': 39.3,
            'Current Electricity': 53.2,
            'Real Gas': 55.7,
            'Real Electricity': 75.3,
        },
        {
            Year: [1999, 'Oct to Dec'],
            'Current Gas': 39.3,
            'Current Electricity': 53.2,
            'Real Gas': 55.3,
            'Real Electricity': 74.7,
        },
        {
            Year: [2000, 'Jan to Mar'],
            'Current Gas': 39.3,
            'Current Electricity': 53.2,
            'Real Gas': 54.9,
            'Real Electricity': 74.2,
        },
        {
            Year: [2000, 'Apr to June'],
            'Current Gas': 38.3,
            'Current Electricity': 52.4,
            'Real Gas': 53.6,
            'Real Electricity': 73.3,
        },
        {
            Year: [2000, 'July to Sept'],
            'Current Gas': 38.3,
            'Current Electricity': 51.6,
            'Real Gas': 53.5,
            'Real Electricity': 72,
        },
        {
            Year: [2000, 'Oct to Dec'],
            'Current Gas': 38.4,
            'Current Electricity': 51.6,
            'Real Gas': 53.6,
            'Real Electricity': 71.9,
        },
        {
            Year: [2001, 'Jan to Mar'],
            'Current Gas': 38.6,
            'Current Electricity': 51.6,
            'Real Gas': 53.4,
            'Real Electricity': 71.4,
        },
        {
            Year: [2001, 'Apr to June'],
            'Current Gas': 40.1,
            'Current Electricity': 51.6,
            'Real Gas': 55,
            'Real Electricity': 70.8,
        },
        {
            Year: [2001, 'July to Sept'],
            'Current Gas': 40.2,
            'Current Electricity': 51.7,
            'Real Gas': 55.2,
            'Real Electricity': 70.9,
        },
        {
            Year: [2001, 'Oct to Dec'],
            'Current Gas': 40.2,
            'Current Electricity': 51.8,
            'Real Gas': 55.3,
            'Real Electricity': 71.3,
        },
        {
            Year: [2002, 'Jan to Mar'],
            'Current Gas': 42,
            'Current Electricity': 51.8,
            'Real Gas': 57.1,
            'Real Electricity': 70.5,
        },
        {
            Year: [2002, 'Apr to June'],
            'Current Gas': 42.2,
            'Current Electricity': 51.9,
            'Real Gas': 57.1,
            'Real Electricity': 70.2,
        },
        {
            Year: [2002, 'July to Sept'],
            'Current Gas': 42.3,
            'Current Electricity': 51.9,
            'Real Gas': 57,
            'Real Electricity': 69.9,
        },
        {
            Year: [2002, 'Oct to Dec'],
            'Current Gas': 42.3,
            'Current Electricity': 51.9,
            'Real Gas': 56.5,
            'Real Electricity': 69.3,
        },
        {
            Year: [2003, 'Jan to Mar'],
            'Current Gas': 42.5,
            'Current Electricity': 52.1,
            'Real Gas': 56.4,
            'Real Electricity': 69.2,
        },
        {
            Year: [2003, 'Apr to June'],
            'Current Gas': 42.8,
            'Current Electricity': 52.2,
            'Real Gas': 56.4,
            'Real Electricity': 68.7,
        },
        {
            Year: [2003, 'July to Sept'],
            'Current Gas': 43.3,
            'Current Electricity': 52.7,
            'Real Gas': 56.8,
            'Real Electricity': 69.1,
        },
        {
            Year: [2003, 'Oct to Dec'],
            'Current Gas': 43.6,
            'Current Electricity': 52.9,
            'Real Gas': 57.1,
            'Real Electricity': 69.3,
        },
        {
            Year: [2004, 'Jan to Mar'],
            'Current Gas': 44.5,
            'Current Electricity': 53.8,
            'Real Gas': 58,
            'Real Electricity': 70.2,
        },
        {
            Year: [2004, 'Apr to June'],
            'Current Gas': 45.6,
            'Current Electricity': 55.1,
            'Real Gas': 58.6,
            'Real Electricity': 70.8,
        },
        {
            Year: [2004, 'July to Sept'],
            'Current Gas': 46,
            'Current Electricity': 55.9,
            'Real Gas': 58.9,
            'Real Electricity': 71.6,
        },
        {
            Year: [2004, 'Oct to Dec'],
            'Current Gas': 48.2,
            'Current Electricity': 57.6,
            'Real Gas': 60.9,
            'Real Electricity': 72.7,
        },
        {
            Year: [2005, 'Jan to Mar'],
            'Current Gas': 51,
            'Current Electricity': 60,
            'Real Gas': 64.3,
            'Real Electricity': 75.6,
        },
        {
            Year: [2005, 'Apr to June'],
            'Current Gas': 51.5,
            'Current Electricity': 60.7,
            'Real Gas': 64.2,
            'Real Electricity': 75.7,
        },
        {
            Year: [2005, 'July to Sept'],
            'Current Gas': 52,
            'Current Electricity': 61.2,
            'Real Gas': 64.6,
            'Real Electricity': 76.1,
        },
        {
            Year: [2005, 'Oct to Dec'],
            'Current Gas': 56.2,
            'Current Electricity': 64.1,
            'Real Gas': 69.5,
            'Real Electricity': 79.3,
        },
        {
            Year: [2006, 'Jan to Mar'],
            'Current Gas': 58.9,
            'Current Electricity': 66.7,
            'Real Gas': 72.4,
            'Real Electricity': 81.9,
        },
        {
            Year: [2006, 'Apr to June'],
            'Current Gas': 67.2,
            'Current Electricity': 73.7,
            'Real Gas': 81.6,
            'Real Electricity': 89.4,
        },
        {
            Year: [2006, 'July to Sept'],
            'Current Gas': 71.7,
            'Current Electricity': 77.3,
            'Real Gas': 86.4,
            'Real Electricity': 93.1,
        },
        {
            Year: [2006, 'Oct to Dec'],
            'Current Gas': 78.8,
            'Current Electricity': 81.6,
            'Real Gas': 94.8,
            'Real Electricity': 98.2,
        },
        {
            Year: [2007, 'Jan to Mar'],
            'Current Gas': 80.8,
            'Current Electricity': 83.3,
            'Real Gas': 97.1,
            'Real Electricity': 100.1,
        },
        {
            Year: [2007, 'Apr to June'],
            'Current Gas': 75.8,
            'Current Electricity': 81.7,
            'Real Gas': 89.6,
            'Real Electricity': 96.6,
        },
        {
            Year: [2007, 'July to Sept '],
            'Current Gas': 71.1,
            'Current Electricity': 79.3,
            'Real Gas': 84,
            'Real Electricity': 93.6,
        },
        {
            Year: [2007, 'Oct to Dec'],
            'Current Gas': 70.2,
            'Current Electricity': 79,
            'Real Gas': 82.8,
            'Real Electricity': 93.2,
        },
        {
            Year: [2008, 'Jan to Mar'],
            'Current Gas': 76.5,
            'Current Electricity': 85,
            'Real Gas': 89.4,
            'Real Electricity': 99.3,
        },
        {
            Year: [2008, 'Apr to June'],
            'Current Gas': 81,
            'Current Electricity': 89.6,
            'Real Gas': 93.5,
            'Real Electricity': 103.4,
        },
        {
            Year: [2008, 'July to Sept'],
            'Current Gas': 92.5,
            'Current Electricity': 95.4,
            'Real Gas': 105.3,
            'Real Electricity': 108.5,
        },
        {
            Year: [2008, 'Oct to Dec'],
            'Current Gas': 105.7,
            'Current Electricity': 103.8,
            'Real Gas': 119,
            'Real Electricity': 116.9,
        },
        {
            Year: [2009, 'Jan to Mar'],
            'Current Gas': 104.2,
            'Current Electricity': 103.4,
            'Real Gas': 117.5,
            'Real Electricity': 116.6,
        },
        {
            Year: [2009, 'Apr to June'],
            'Current Gas': 100.1,
            'Current Electricity': 96.3,
            'Real Gas': 112.6,
            'Real Electricity': 108.4,
        },
        {
            Year: [2009, 'July to Sept'],
            'Current Gas': 99.6,
            'Current Electricity': 95.7,
            'Real Gas': 111.6,
            'Real Electricity': 107.3,
        },
        {
            Year: [2009, 'Oct to Dec'],
            'Current Gas': 99.5,
            'Current Electricity': 95.4,
            'Real Gas': 112.2,
            'Real Electricity': 107.5,
        },
        {
            Year: [2010, 'Jan to Mar'],
            'Current Gas': 97.8,
            'Current Electricity': 95.4,
            'Real Gas': 108.7,
            'Real Electricity': 106,
        },
        {
            Year: [2010, 'Apr to June'],
            'Current Gas': 94,
            'Current Electricity': 95.1,
            'Real Gas': 104.3,
            'Real Electricity': 105.6,
        },
        {
            Year: [2010, 'July to Sept'],
            'Current Gas': 94,
            'Current Electricity': 95.1,
            'Real Gas': 104.1,
            'Real Electricity': 105.3,
        },
        {
            Year: [2010, 'Oct to Dec'],
            'Current Gas': 95.4,
            'Current Electricity': 95.4,
            'Real Gas': 105.1,
            'Real Electricity': 105.1,
        },
        {
            Year: [2011, 'Jan to Mar'],
            'Current Gas': 99.6,
            'Current Electricity': 98,
            'Real Gas': 108,
            'Real Electricity': 106.2,
        },
        {
            Year: [2011, 'Apr to June'],
            'Current Gas': 100,
            'Current Electricity': 99,
            'Real Gas': 109.1,
            'Real Electricity': 108,
        },
        {
            Year: [2011, 'July to Sept'],
            'Current Gas': 105.5,
            'Current Electricity': 102.2,
            'Real Gas': 114.4,
            'Real Electricity': 110.7,
        },
        {
            Year: [2011, 'Oct to Dec'],
            'Current Gas': 117.4,
            'Current Electricity': 109.4,
            'Real Gas': 126.4,
            'Real Electricity': 117.8,
        },
        {
            Year: [2012, 'Jan to Mar'],
            'Current Gas': 116.8,
            'Current Electricity': 108.3,
            'Real Gas': 125.3,
            'Real Electricity': 116.2,
        },
        {
            Year: [2012, 'Apr to June'],
            'Current Gas': 115.5,
            'Current Electricity': 106.9,
            'Real Gas': 123.7,
            'Real Electricity': 114.6,
        },
        {
            Year: [2012, 'July to Sept'],
            'Current Gas': 115.5,
            'Current Electricity': 106.9,
            'Real Gas': 123.1,
            'Real Electricity': 114,
        },
        {
            Year: [2012, 'Oct to Dec'],
            'Current Gas': 119,
            'Current Electricity': 109.6,
            'Real Gas': 126.1,
            'Real Electricity': 116.1,
        },
        {
            Year: [2013, 'Jan to Mar'],
            'Current Gas': 124.6,
            'Current Electricity': 114.7,
            'Real Gas': 130.9,
            'Real Electricity': 120.5,
        },
        {
            Year: [2013, 'Apr to June'],
            'Current Gas': 125,
            'Current Electricity': 115.2,
            'Real Gas': 131.1,
            'Real Electricity': 120.9,
        },
        {
            Year: [2013, 'July to Sept'],
            'Current Gas': 125,
            'Current Electricity': 115.6,
            'Real Gas': 130.2,
            'Real Electricity': 120.4,
        },
        {
            Year: [2013, 'Oct to Dec'],
            'Current Gas': 127.8,
            'Current Electricity': 118.2,
            'Real Gas': 132.9,
            'Real Electricity': 122.9,
        },
        {
            Year: [2014, 'Jan to Mar'],
            'Current Gas': 132.2,
            'Current Electricity': 123,
            'Real Gas': 137,
            'Real Electricity': 127.5,
        },
        {
            Year: [2014, 'Apr to June'],
            'Current Gas': 131.4,
            'Current Electricity': 122.2,
            'Real Gas': 136.4,
            'Real Electricity': 126.8,
        },
        {
            Year: [2014, 'July to Sept'],
            'Current Gas': 131.4,
            'Current Electricity': 122.2,
            'Real Gas': 134.7,
            'Real Electricity': 125.3,
        },
        {
            Year: [2014, 'Oct to Dec'],
            'Current Gas': 131.4,
            'Current Electricity': 122.2,
            'Real Gas': 135.1,
            'Real Electricity': 125.6,
        },
        {
            Year: [2015, 'Jan to Mar'],
            'Current Gas': 129,
            'Current Electricity': 122.2,
            'Real Gas': 132.4,
            'Real Electricity': 125.4,
        },
        {
            Year: [2015, 'Apr to June'],
            'Current Gas': 125.9,
            'Current Electricity': 121.8,
            'Real Gas': 129.5,
            'Real Electricity': 125.3,
        },
        {
            Year: [2015, 'July to Sept'],
            'Current Gas': 124.8,
            'Current Electricity': 121.8,
            'Real Gas': 127.9,
            'Real Electricity': 124.9,
        },
        {
            Year: [2015, 'Oct to Dec'],
            'Current Gas': 122.9,
            'Current Electricity': 121.8,
            'Real Gas': 125.4,
            'Real Electricity': 124.3,
        },
        {
            Year: [2016, 'Jan to Mar'],
            'Current Gas': 121.2,
            'Current Electricity': 121.8,
            'Real Gas': 123,
            'Real Electricity': 123.6,
        },
        {
            Year: [2016, 'Apr to June'],
            'Current Gas': 117.2,
            'Current Electricity': 121.6,
            'Real Gas': 118.6,
            'Real Electricity': 123,
        },
        {
            Year: [2016, 'July to Sept'],
            'Current Gas': 117.2,
            'Current Electricity': 121.6,
            'Real Gas': 117.4,
            'Real Electricity': 121.7,
        },
        {
            Year: [2016, 'Oct to Dec'],
            'Current Gas': 117.2,
            'Current Electricity': 121.6,
            'Real Gas': 116.5,
            'Real Electricity': 120.9,
        },
        {
            Year: [2017, 'Jan to Mar'],
            'Current Gas': 116.7,
            'Current Electricity': 122.1,
            'Real Gas': 115.6,
            'Real Electricity': 120.9,
        },
        {
            Year: [2017, 'Apr to June'],
            'Current Gas': 116.5,
            'Current Electricity': 129.3,
            'Real Gas': 115.3,
            'Real Electricity': 127.9,
        },
        {
            Year: [2017, 'July to Sept'],
            'Current Gas': 117.2,
            'Current Electricity': 132.6,
            'Real Gas': 115.9,
            'Real Electricity': 131,
        },
        {
            Year: [2017, 'Oct to Dec'],
            'Current Gas': 117.2,
            'Current Electricity': 135.5,
            'Real Gas': 114.8,
            'Real Electricity': 132.7,
        },
        {
            Year: [2018, 'Jan to Mar'],
            'Current Gas': 117.5,
            'Current Electricity': 135.5,
            'Real Gas': 114.9,
            'Real Electricity': 132.5,
        },
        {
            Year: [2018, 'Apr to June'],
            'Current Gas': 118.9,
            'Current Electricity': 137.8,
            'Real Gas': 115.5,
            'Real Electricity': 133.9,
        },
        {
            Year: [2018, 'July to Sept'],
            'Current Gas': 122.8,
            'Current Electricity': 143.2,
            'Real Gas': 118.6,
            'Real Electricity': 138.3,
        },
        {
            Year: [2018, 'Oct to Dec'],
            'Current Gas': 126.1,
            'Current Electricity': 147.8,
            'Real Gas': 120.9,
            'Real Electricity': 141.7,
        },
        {
            Year: [2019, 'Jan to Mar'],
            'Current Gas': 115.5,
            'Current Electricity': 140.6,
            'Real Gas': 110.7,
            'Real Electricity': 134.8,
        },
        {
            Year: [2019, 'Apr to June'],
            'Current Gas': 126.3,
            'Current Electricity': 156,
            'Real Gas': 119.8,
            'Real Electricity': 148,
        },
        {
            Year: [2019, 'July to Sept'],
            'Current Gas': 126.3,
            'Current Electricity': 156,
            'Real Gas': 119.3,
            'Real Electricity': 147.4,
        },
        {
            Year: [2019, 'Oct to Dec'],
            'Current Gas': 115.2,
            'Current Electricity': 152.7,
            'Real Gas': 108.3,
            'Real Electricity': 143.5,
        },
        {
            Year: [2020, 'Jan to Mar'],
            'Current Gas': 115.2,
            'Current Electricity': 152.7,
            'Real Gas': 107.3,
            'Real Electricity': 142.2,
        },
        {
            Year: [2020, 'Apr to June'],
            'Current Gas': 111.2,
            'Current Electricity': 152.9,
            'Real Gas': 96.3,
            'Real Electricity': 132.5,
        },
        {
            Year: [2020, 'July to Sept'],
            'Current Gas': 111.1,
            'Current Electricity': 152.8,
            'Real Gas': 100.2,
            'Real Electricity': 137.8,
        },
        {
            Year: [2020, 'Oct to Dec'],
            'Current Gas': 97.5,
            'Current Electricity': 147.8,
            'Real Gas': 88.5,
            'Real Electricity': 134.2,
        },
        {
            Year: [2021, 'Jan to Mar'],
            'Current Gas': 97.5,
            'Current Electricity': 147.8,
            'Real Gas': 87.6,
            'Real Electricity': 132.8,
        },
        {
            Year: [2021, 'Apr to June'],
            'Current Gas': 106.7,
            'Current Electricity': 161.3,
            'Real Gas': 97.2,
            'Real Electricity': 147.1,
        },
        {
            Year: [2021, 'July to Sept'],
            'Current Gas': 106.7,
            'Current Electricity': 161.6,
            'Real Gas': 96.6,
            'Real Electricity': 146.4,
        },
        {
            Year: [2021, 'Oct to Dec'],
            'Current Gas': 124.9,
            'Current Electricity': 175.6,
            'Real Gas': 111.8,
            'Real Electricity': 157.2,
        },
        {
            Year: [2022, 'Jan to Mar'],
            'Current Gas': 125,
            'Current Electricity': 176.2,
            'Real Gas': 110.3,
            'Real Electricity': 155.5,
        },
        {
            Year: [2022, 'Apr to June'],
            'Current Gas': 208.4,
            'Current Electricity': 247.8,
            'Real Gas': 180,
            'Real Electricity': 214,
        },
        {
            Year: [2022, 'July to Sept'],
            'Current Gas': 208.7,
            'Current Electricity': 248.9,
            'Real Gas': 177.4,
            'Real Electricity': 211.6,
        },
        {
            Year: [2022, 'Oct to Dec'],
            'Current Gas': 285.7,
            'Current Electricity': 290.6,
            'Real Gas': 237,
            'Real Electricity': 241,
        },
        {
            Year: [2023, 'Jan to Mar'],
            'Current Gas': 286.7,
            'Current Electricity': 293.8,
            'Real Gas': 233.1,
            'Real Electricity': 238.8,
        },
        {
            Year: [2023, 'Apr to June'],
            'Current Gas': 283.8,
            'Current Electricity': 290.6,
            'Real Gas': 226.6,
            'Real Electricity': 232,
        },
        {
            Year: [2023, 'July to Sept'],
            'Current Gas': 212.2,
            'Current Electricity': 265.5,
            'Real Gas': 167.9,
            'Real Electricity': 210,
        },
        {
            Year: [2023, 'Oct to Dec'],
            'Current Gas': 197.3,
            'Current Electricity': 245.6,
            'Real Gas': 155.5,
            'Real Electricity': 193.6,
        },
        {
            Year: [2024, 'Jan to Mar'],
            'Current Gas': 210.7,
            'Current Electricity': 255.6,
            'Real Gas': 165,
            'Real Electricity': 200.2,
        },
        {
            Year: [2024, 'Apr to June'],
            'Current Gas': 177.5,
            'Current Electricity': 229.4,
            'Real Gas': 138.2,
            'Real Electricity': 178.5,
        },
        {
            Year: [2024, 'July to Sept'],
            'Current Gas': 163.7,
            'Current Electricity': 213.8,
            'Real Gas': 126.6,
            'Real Electricity': 165.3,
        },
    ];
}
