export function getData() {
    return [
        {
            category: ['RFG', 'Words'],
            recollection: 0.4,
            familiarity: 0.35,
            guessing: 0.15,
            recollection_error_low: 0.35,
            recollection_error_high: 0.45,
            familiarity_error_low: 0.3,
            familiarity_error_high: 0.4,
            guessing_error_low: 0.1,
            guessing_error_high: 0.2,
        },
        {
            category: ['RFG', 'Pictures'],
            recollection: 0.6,
            familiarity: 0.25,
            guessing: 0.1,
            recollection_error_low: 0.55,
            recollection_error_high: 0.65,
            familiarity_error_low: 0.2,
            familiarity_error_high: 0.3,
            guessing_error_low: 0.05,
            guessing_error_high: 0.15,
        },
        {
            category: ['RFBG', 'Words'],
            recollection: 0.45,
            familiarity: 0.3,
            guessing: 0.1,
            recollection_error_low: 0.4,
            recollection_error_high: 0.5,
            familiarity_error_low: 0.25,
            familiarity_error_high: 0.35,
            guessing_error_low: 0.05,
            guessing_error_high: 0.15,
        },
        {
            category: ['RFBG', 'Pictures'],
            recollection: 0.65,
            familiarity: 0.2,
            guessing: 0.1,
            recollection_error_low: 0.6,
            recollection_error_high: 0.7,
            familiarity_error_low: 0.15,
            familiarity_error_high: 0.25,
            guessing_error_low: 0.05,
            guessing_error_high: 0.15,
        },
        {
            category: ['RF-Ratings', 'Words'],
            recollection: 0.5,
            familiarity: 0.35,
            guessing: 0.05,
            recollection_error_low: 0.45,
            recollection_error_high: 0.55,
            familiarity_error_low: 0.3,
            familiarity_error_high: 0.4,
            guessing_error_low: 0.02,
            guessing_error_high: 0.08,
        },
        {
            category: ['RF-Ratings', 'Pictures'],
            recollection: 0.7,
            familiarity: 0.25,
            guessing: 0.05,
            recollection_error_low: 0.65,
            recollection_error_high: 0.75,
            familiarity_error_low: 0.2,
            familiarity_error_high: 0.3,
            guessing_error_low: 0.02,
            guessing_error_high: 0.08,
        },
    ];
}
