// https://www.openstreetmap.org
export const ferryData = [
    {
        '@id': 'way/30603364',
        duration: 75,
        foot: 'yes',
        int_name: 'Chíos - Oinoússes',
        motor_vehicle: 'yes',
        motorcar: 'yes',
        name: 'Χίος - Οινούσσες',
        'name:en': 'Chios - Oinousses',
        operator: 'Σύλλογος «Φίλοι Οινουσσών»',
        route: 'ferry',
    },
    {
        '@id': 'way/59804720',
        bicycle: 'yes',
        duration: 45,
        fee: 'yes',
        foot: 'yes',
        hgv: 'yes',
        int_name: 'Keramotí - Thásos (Liménas)',
        motorcar: 'yes',
        name: 'Κεραμωτή - Θάσος (Λιμένας)',
        'name:bg': 'Керамоти - Лименас',
        'name:en': 'Keramoti - Thassos (Limenas)',
        'name:mk': 'Керемидли - Боровец',
        'name:sr': 'Керамоти - Лименас',
        'public_transport:version': '2',
        reservation: 'no',
        route: 'ferry',
        tourist_bus: 'yes',
    },
    {
        '@id': 'way/118108544',
        bicycle: 'yes',
        duration: 70,
        foot: 'yes',
        from: 'Anafi',
        int_name: 'Santoríni (Athínios) - Anáfi',
        motor_vehicle: 'yes',
        name: 'Σαντορίνη (Αθήνιος) - Ανάφη',
        'name:en': 'Santorini (Athinios) - Anafi',
        operator: 'Blue Star',
        route: 'ferry',
        source: 'https://github.com/osmlab/appledata/issues/161',
        to: 'Santorini',
    },
    {
        '@id': 'way/118642741',
        access: 'yes',
        duration: 45,
        foot: 'yes',
        int_name: 'Folégandros - Síkinos',
        motor_vehicle: 'yes',
        motorcar: 'yes',
        name: 'Φολέγανδρος - Σίκινος',
        'name:el': 'Φολέγανδρος - Σίκινος',
        'name:en': 'Folegandros - Sikinos',
        route: 'ferry',
    },
    {
        '@id': 'way/186819688',
        bicycle: 'yes',
        description: 'Segment of Blue Star ferry from Rhodos to Piraeus',
        duration: 70,
        foot: 'yes',
        int_name: 'Kásos - Kárpathos',
        motor_vehicle: 'yes',
        name: 'Κάσος - Κάρπαθος',
        'name:en': 'Kasos - Karpathos',
        route: 'ferry',
        source: 'https://github.com/osmlab/appledata/issues/161',
    },
    {
        '@id': 'way/203708770',
        duration: 90,
        foot: 'yes',
        int_name: 'Kýthnos - Sérifos',
        motor_vehicle: 'yes',
        motorcar: 'yes',
        name: 'Κύθνος - Σέριφος',
        'name:en': 'Kythnos - Serifos',
        note: 'Many direct connections from Kythnos to Serifos and vice versa, during the summer',
        route: 'ferry',
    },
    {
        '@id': 'way/254841508',
        duration: 35,
        foot: 'yes',
        int_name: 'Ýdra - Spétses',
        motor_vehicle: 'no',
        name: 'Ύδρα - Σπέτσες',
        'name:en': 'Hydra - Spetses',
        note: 'Some Flying Dolphin services may skip Ermioni.',
        route: 'ferry',
        waterway: 'seaway',
    },
    {
        '@id': 'way/255883210',
        duration: 285,
        ferry: 'tertiary',
        foot: 'yes',
        hgv: 'yes',
        int_name: 'Peiraiás - Sýros',
        motor_vehicle: 'yes',
        motorcar: 'yes',
        name: 'Πειραιάς - Σύρος',
        'name:en': 'Piraeus - Syros',
        route: 'ferry',
        website: 'http://www.bluestarferries.gr/',
    },
    {
        '@id': 'way/277123252',
        bicycle: 'yes',
        duration: 120,
        ferry: 'secondary',
        foot: 'yes',
        int_name: 'Kýthira - Antikýthira',
        motor_vehicle: 'yes',
        name: 'Κύθηρα - Αντικύθηρα',
        'name:en': 'Kythira - Antikythira',
        operator: 'ANEN',
        route: 'ferry',
    },
    {
        '@id': 'way/277123253',
        bicycle: 'yes',
        duration: 150,
        foot: 'yes',
        int_name: 'Kýthira - Gýtheio',
        motor_vehicle: 'yes',
        name: 'Κύθηρα - Γύθειο',
        'name:en': 'Kythira - Gythio',
        operator: 'ANEN',
        route: 'ferry',
    },
    {
        '@id': 'way/289406731',
        duration: 30,
        foot: 'yes',
        int_name: 'Síkinos - Íos',
        motor_vehicle: 'yes',
        motorcar: 'yes',
        name: 'Σίκινος - Ίος',
        'name:en': 'Sikinos - Ios',
        route: 'ferry',
    },
    {
        '@id': 'way/289406736',
        access: 'yes',
        duration: 55,
        foot: 'yes',
        hgv: 'yes',
        int_name: 'Mílos - Kímolos',
        motor_vehicle: 'yes',
        motorcar: 'yes',
        name: 'Μήλος - Κίμωλος',
        'name:en': 'Milos - Kimolos',
        note: 'As of May 2015, there are a few direct connections from Milos to Kimolos and vice versa.',
        route: 'ferry',
    },
    {
        '@id': 'way/300407598',
        duration: 440,
        ferry: 'tertiary',
        foot: 'yes',
        hgv: 'yes',
        int_name: 'Peiraiás - Chíos',
        motor_vehicle: 'yes',
        motorcar: 'yes',
        name: 'Πειραιάς - Χίος',
        'name:el': 'Πειραιάς - Χίος',
        'name:en': 'Piraeus - Chios',
        route: 'ferry',
    },
    {
        '@id': 'way/302589937',
        duration: 150,
        foot: 'yes',
        int_name: 'Alexandroúpoli - Samothráki',
        name: 'Αλεξανδρούπολη - Σαμοθράκη',
        'name:el': 'Αλεξανδρούπολη - Σαμοθράκη',
        'name:en': 'Alexandroupolis - Samothrace',
        'name:es': 'Alejandrópolis - Samotracia',
        'name:lt': 'Aleksandrupolis - Samotrakė',
        'name:mk': 'Дедеагач - Самотракија',
        operator: 'SAOS FERRIES',
        route: 'ferry',
        vehicle: 'yes',
        website: 'https://www.saos.gr/',
    },
    {
        '@id': 'way/344649665',
        duration: 30,
        foot: 'yes',
        hgv: 'no',
        int_name: 'Pollónia - Psáthi',
        motor_vehicle: 'yes',
        motorcar: 'yes',
        name: 'Πολλώνια - Ψάθη',
        'name:en': 'Pollonia - Psathi',
        note: 'A few daily direct connections from Pollonia (Milos) to Psathi (Kimolos) with a small ferry boat - able to carry a few (small) vehicles.',
        route: 'ferry',
        source: 'survey',
    },
    {
        '@id': 'way/344649666',
        access: 'yes',
        duration: 135,
        foot: 'yes',
        int_name: 'Mílos - Folégandros',
        motor_vehicle: 'yes',
        name: 'Μήλος - Φολέγανδρος',
        'name:el': 'Μήλος - Φολέγανδρος',
        'name:en': 'Milos - Folegandros',
        note: 'As of May 2015, there are various direct connections from Milos to Folegandros and vice versa.',
        route: 'ferry',
        source: 'survey',
    },
    {
        '@id': 'way/344870260',
        duration: 160,
        ferry: 'tertiary',
        foot: 'yes',
        hgv: 'yes',
        int_name: 'Peiraiás - Sérifos',
        motor_vehicle: 'yes',
        motorcar: 'yes',
        name: 'Πειραιάς - Σέριφος',
        'name:en': 'Piraeus - Serifos',
        route: 'ferry',
        waterway: 'seaway',
    },
    {
        '@id': 'way/345734628',
        duration: 190,
        ferry: 'tertiary',
        foot: 'yes',
        hgv: 'yes',
        int_name: 'Peiraiás - Kýthnos',
        motor_vehicle: 'yes',
        motorcar: 'yes',
        name: 'Πειραιάς - Κύθνος',
        'name:en': 'Piraeus - Kythnos',
        route: 'ferry',
    },
    {
        '@id': 'way/345834457',
        duration: 85,
        foot: 'yes',
        hgv: 'yes',
        int_name: 'Kímolos - Folégandros',
        motor_vehicle: 'yes',
        motorcar: 'yes',
        name: 'Κίμωλος - Φολέγανδρος',
        'name:en': 'Kimolos - Folegandros',
        note: 'As of May 2015, F/B Adamantios Korais goes directly from Kimolos to Folegandros and vice versa a few times per week.',
        route: 'ferry',
    },
    {
        '@id': 'way/394511845',
        bicycle: 'yes',
        duration: 285,
        ferry: 'tertiary',
        foot: 'yes',
        from: 'Piraeus',
        hgv: 'yes',
        int_name: 'Peiraiás - Mílos',
        motor_vehicle: 'yes',
        motorcar: 'yes',
        name: 'Πειραιάς - Μήλος',
        'name:el': 'Πειραιάς - Μήλος',
        'name:en': 'Piraeus - Milos',
        operator: 'Blue Star',
        route: 'ferry',
        to: 'Milos',
    },
    {
        '@id': 'way/455579568',
        duration: 110,
        foot: 'yes',
        hgv: 'yes',
        int_name: 'Skýros - Kými',
        motor_vehicle: 'yes',
        motorcar: 'yes',
        name: 'Σκύρος - Κύμη',
        'name:en': 'Skyros - Kymi',
        note: 'route not accurate',
        route: 'ferry',
    },
    {
        '@id': 'way/500480451',
        duration: 45,
        foot: 'yes',
        hgv: 'no',
        int_name: 'Peiraiás - Kamateró',
        motor_vehicle: 'no',
        motorcar: 'no',
        name: 'Πειραιάς - Καματερό',
        'name:en': 'Piraeus - Kamatero',
        route: 'ferry',
        source: 'https://github.com/osmlab/appledata/issues/161',
    },
    {
        '@id': 'way/579134996',
        duration: 245,
        foot: 'yes',
        from: 'Ρέθυμνο',
        int_name: 'Réthymno - Santoríni',
        motor_vehicle: 'yes',
        name: 'Ρέθυμνο - Σαντορίνη',
        'name:en': 'Rethymno - Santorini',
        operator: 'SeaSpeed Lines',
        route: 'ferry',
        to: 'Σαντορίνη',
        website: 'https://www.seaspeedferries.gr/',
    },
    {
        '@id': 'way/692382996',
        duration: 45,
        fee: 'yes',
        foot: 'yes',
        from: 'Ρέθυμνο',
        horse: 'no',
        int_name: 'Réthymno - Irákleio',
        motor_vehicle: 'yes',
        name: 'Ρέθυμνο - Ηράκλειο',
        'name:en': 'Rethymno - Heraklion',
        operator: 'Seajets',
        route: 'ferry',
        source: 'https://static.seajets.gr/seajets-files/docs/default-source/schedule/itinerary-heraklio-rethymno-thira-ios-naxos-paros-mykonos-2019-gr.pdf?sfvrsn=7564fd4c_26',
        to: 'Ηράκλειο',
    },
    {
        '@id': 'way/971711318',
        bicycle: 'yes',
        duration: 215,
        foot: 'yes',
        from: 'Santorini',
        int_name: 'Mílos - Santoríni (Athínios)',
        motor_vehicle: 'yes',
        name: 'Μήλος - Σαντορίνη (Αθήνιος)',
        'name:en': 'Milos - Santorini (Athinios)',
        operator: 'Blue Star',
        route: 'ferry',
        source: 'https://github.com/osmlab/appledata/issues/161',
        to: 'Milos',
    },
    {
        '@id': 'way/974838594',
        bicycle: 'yes',
        duration: 45,
        foot: 'yes',
        from: 'Karpathos',
        int_name: 'Kárpathos - Kárpathos (Diafáni)',
        motor_vehicle: 'yes',
        name: 'Κάρπαθος - Κάρπαθος (Διαφάνι)',
        'name:en': 'Karpathos - Karpathos (Diafani)',
        operator: 'Blue Star',
        route: 'ferry',
        source: 'https://github.com/osmlab/appledata/issues/161',
        to: 'Karpathos (Diafani)',
    },
    {
        '@id': 'way/974840158',
        bicycle: 'yes',
        duration: 90,
        foot: 'yes',
        from: 'Karpathos (Diafani)',
        int_name: 'Kárpathos (Diafáni) - Chálki',
        motor_vehicle: 'yes',
        name: 'Κάρπαθος (Διαφάνι) - Χάλκη',
        'name:en': 'Karpathos (Diafani) - Chalki',
        operator: 'Blue Star',
        route: 'ferry',
        source: 'https://github.com/osmlab/appledata/issues/161',
        to: 'Chalki',
    },
    {
        '@id': 'way/975717239',
        bicycle: 'yes',
        duration: 95,
        foot: 'yes',
        from: 'Rhodes',
        int_name: 'Ródos - Chálki',
        motor_vehicle: 'yes',
        name: 'Ρόδος - Χάλκη',
        'name:en': 'Rhodes - Chalki',
        operator: 'Blue Star',
        route: 'ferry',
        source: 'https://github.com/osmlab/appledata/issues/161',
        to: 'Chalki',
    },
    {
        '@id': 'way/1011917984',
        bicycle: 'yes',
        description: 'Segment of Blue Star ferry from Rhodos to Piraeus',
        duration: 170,
        foot: 'yes',
        from: 'Sitia',
        int_name: 'Siteía - Irákleio',
        motor_vehicle: 'yes',
        name: 'Σητεία - Ηράκλειο',
        'name:en': 'Sitia - Heraklion',
        operator: 'Blue Star',
        route: 'ferry',
        to: 'Heraklion',
    },
    {
        '@id': 'way/1011917986',
        bicycle: 'yes',
        description: 'Segment of Blue Star ferry from Rhodos to Piraeus',
        duration: 215,
        foot: 'yes',
        from: 'Heraklion',
        int_name: 'Irákleio - Anáfi',
        motor_vehicle: 'yes',
        name: 'Ηράκλειο - Ανάφη',
        'name:en': 'Heraklion - Anafi',
        operator: 'Blue Star',
        route: 'ferry',
        to: 'Anafi',
    },
    {
        '@id': 'way/1070034091',
        duration: 45,
        fee: 'yes',
        foot: 'yes',
        from: 'Ρέθυμνο',
        horse: 'no',
        int_name: 'Réthymno - Irákleio',
        motor_vehicle: 'yes',
        name: 'Ρέθυμνο - Ηράκλειο',
        'name:en': 'Rethymno - Heraklion',
        operator: 'Seajets',
        route: 'ferry',
        source: 'https://static.seajets.gr/seajets-files/docs/default-source/schedule/itinerary-heraklio-rethymno-thira-ios-naxos-paros-mykonos-2019-gr.pdf?sfvrsn=7564fd4c_26',
        to: 'Ηράκλειο',
    },
];
