//Source: https://datacatalog.worldbank.org/search/dataset/0037712andor
export const data = [
    { name: 'Algeria', value: 99.7 },
    { name: 'Angola', value: 50 },
    { name: 'Benin', value: 4.6 },
    { name: 'Botswana', value: 65.7 },
    { name: 'Burkina Faso', value: 11.7 },
    { name: 'Burundi', value: 0.2 },
    { name: 'Cape Verde', value: 81.8 },
    { name: 'Cameroon', value: 22.8 },
    { name: 'Central African Republic', value: 0.900000000000001 },
    { name: 'Chad', value: 8 },
    { name: 'Comoros', value: 11.3 },
    { name: 'Democratic Republic of The Congo', value: 4.3 },
    { name: 'Congo', value: 35.6 },
    { name: 'Ivory Coast', value: 31.7 },
    { name: 'Djibouti', value: 9.6 },
    { name: 'Egypt', value: 99.9 },
    { name: 'Equatorial Guinea', value: 24.1 },
    { name: 'Eritrea', value: 11.5 },
    { name: 'Eswatini', value: 58.1 },
    { name: 'Ethiopia', value: 7.5 },
    { name: 'Gabon', value: 89.7 },
    { name: 'Gambia', value: 1.7 },
    { name: 'Ghana', value: 30.3 },
    { name: 'Guinea', value: 1 },
    { name: 'Guinea-Bissau', value: 1 },
    { name: 'Kenya', value: 23.9 },
    { name: 'Lesotho', value: 41.1 },
    { name: 'Liberia', value: 0.4 },
    { name: 'Madagascar', value: 1.4 },
    { name: 'Malawi', value: 1.6 },
    { name: 'Mali', value: 0.900000000000001 },
    { name: 'Mauritania', value: 48.3 },
    { name: 'Morocco', value: 98.2 },
    { name: 'Mozambique', value: 5.4 },
    { name: 'Namibia', value: 47.3 },
    { name: 'Niger', value: 3 },
    { name: 'Nigeria', value: 16.8 },
    { name: 'Rwanda', value: 5.4 },
    { name: 'Senegal', value: 29.4 },
    { name: 'Sierra Leone', value: 0.800000000000001 },
    { name: 'Somalia', value: 3.8 },
    { name: 'South Africa', value: 88.4 },
    { name: 'South Sudan', value: 0 },
    { name: 'Sudan', value: 62.8 },
    { name: 'Togo', value: 11.4 },
    { name: 'Uganda', value: 0.700000000000001 },
    { name: 'Zambia', value: 10.2 },
    { name: 'Zimbabwe', value: 30.3 },
];
