name: Nx Cloud Build

on:
    workflow_dispatch: {}
    schedule:
        # Run periodically to freshen Nx Cloud cache.
        - cron: 0 4,11,13,15 * * 1-5

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: ${{ github.ref != 'refs/heads/latest' }}

env:
    NX_BRANCH: ${{ github.ref }}
    NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_ACCESS_TOKEN }}
    # Set to --batch to enable batch execution.
    NX_BATCH_FLAG: '--batch'

jobs:
    execute_blt:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 1

            - name: Setup
              id: setup
              uses: ./.github/actions/setup-nx

            - name: nx build
              id: build
              run: |
                  # Non-batched builds - some TS/JS targets will fail if run with --batch, so build them unbatched first.
                  yarn nx run-many -p tag:no-batching -t build --parallel=3
                  # Batched builds.
                  yarn nx run-many -t build --parallel=3  --exclude all ${NX_BATCH_FLAG}

            - name: nx blt
              id: blt
              run: |
                  yarn nx run blt

            - name: Tidy Nx Cache
              run: |
                  sudo du -sh .nx/cache
                  ./tools/tidy-nx-cache.sh
                  sudo du -sh .nx/cache
