name: Bump Beta Version

on:
    workflow_dispatch: {}
    schedule:
        - cron: '0 20 * * 0'

env:
    NX_REJECT_UNKNOWN_LOCAL_CACHE: 0
    NX_NO_CLOUD: true
    NX_CLOUD_ACCESS_TOKEN: x
    NX_BRANCH: ${{ github.ref }}

jobs:
    bump_version_and_tag:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v4
            - name: Fetch Refs
              run: git fetch origin latest-success latest

            - name: Setup Node.js
              id: setup_node
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'yarn'

            - name: yarn install
              id: yarn_install
              run: yarn install --ci

            - name: Calculate Next Beta Version
              id: next_version
              run: |
                  NEW_VERSION=$(node ./tools/calculate-next-version.js)
                  echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
                  echo "version=${NEW_VERSION}" >> $GITHUB_OUTPUT
                  echo "tag=b${NEW_VERSION}" >> $GITHUB_OUTPUT

            - name: Bump Beta Package Version
              run: ./tools/bump-versions.sh ${NEW_VERSION}

            - name: Commit Changes
              uses: EndBug/add-and-commit@v9
              if: success()
              with:
                  default_author: github_actions
                  message: Automated package version bump to ${{ steps.next_version.outputs.version }}.

            - name: Tag Latest Successful Commit
              uses: EndBug/latest-tag@latest
              if: success()
              with:
                  ref: ${{ steps.next_version.outputs.tag }}
                  description: Latest commit to pass GitHub Actions workflow on latest branch.

            - name: Tag Latest Successful Commit
              uses: EndBug/latest-tag@latest
              if: success()
              with:
                  ref: latest-beta-version
                  description: Latest commit to pass GitHub Actions workflow on latest branch.
