name: Sonar Scanner (Release)

env:
    NX_NO_CLOUD: true
    NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    NX_BRANCH: ${{ github.ref }}
    SONAR_PROJECT: ag-charts-community

on: workflow_dispatch

permissions:
    contents: read

concurrency:
    group: ${{ github.workflow }}-${{ github.event.number || github.event.head_commit.id }}
    cancel-in-progress: true

jobs:
    sonar_scanner:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Setup
              id: setup
              uses: ./.github/actions/setup-nx
              with:
                  cache_mode: ro
                  base_ref: ${{ github.head_ref }}
                  yarn_postinstall: false
            - uses: actions/setup-java@v4
              with:
                  distribution: 'oracle'
                  java-version: '17'

            - name: Run Scan
              run: |
                  npx sonar-scanner -Dsonar.token=${{ secrets.SONAR_LOGIN }} -Dsonar.projectKey=${SONAR_PROJECT}
