name: Sonar Scanner

env:
    NX_REJECT_UNKNOWN_LOCAL_CACHE: 0
    NX_NO_CLOUD: true
    NX_CLOUD_ACCESS_TOKEN: x
    NX_BRANCH: ${{ github.ref }}

on:
    push:
        branches: [latest]

concurrency:
    group: ${{ github.workflow }}-${{ github.event.number || github.event.head_commit.id }}
    cancel-in-progress: true

jobs:
    sonar_scanner:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v3
            - name: Setup Node.js
              id: setup_node
              uses: actions/setup-node@v3
              with:
                  node-version: '18'
                    cache: 'yarn'
            - uses: actions/setup-java@v4
              with:
                distribution: 'oracle'
                java-version: '17'
            - name: yarn install
              id: yarn_install
              run: yarn install --ci --prefer-offline

            - name: Run Scan
              run: |
                  npx sonar-scanner -Dsonar.login=${{ secrets.SONAR_LOGIN }}
