name: Sonar Scanner (Release)

env:
    NX_REJECT_UNKNOWN_LOCAL_CACHE: 0
    NX_NO_CLOUD: true
    NX_CLOUD_ACCESS_TOKEN: x
    NX_BRANCH: ${{ github.ref }}
    SONAR_PROJECT: ag-charts-community

on: workflow_dispatch

concurrency:
    group: ${{ github.workflow }}-${{ github.event.number || github.event.head_commit.id }}
    cancel-in-progress: true

jobs:
    sonar_scanner:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Setup Node.js
              id: setup_node
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'yarn'
            - uses: actions/setup-java@v4
              with:
                  distribution: 'oracle'
                  java-version: '17'
            - name: yarn install
              id: yarn_install
              run: yarn install --ci

            - name: Run Scan
              run: |
                  npx sonar-scanner -Dsonar.token=${{ secrets.SONAR_LOGIN }} -Dsonar.projectKey=${SONAR_PROJECT}
