export function getData() {
    return [
        { country: 'China', population: 1425 },
        { country: 'India', population: 1417 },
        { country: 'United States', population: 335 },
        { country: 'Indonesia', population: 277 },
        { country: 'Pakistan', population: 230 },
        { country: 'Nigeria', population: 224 },
        { country: 'Brazil', population: 216 },
        { country: 'Bangladesh', population: 173 },
        { country: 'Russia', population: 144 },
        { country: 'Mexico', population: 129 },
        { country: 'Ethiopia', population: 127 },
        { country: 'Japan', population: 124 },
        { country: 'Philippines', population: 117 },
        { country: 'Egypt', population: 112 },
        { country: 'DR Congo', population: 102 },
        { country: 'Vietnam', population: 99 },
        { country: 'Iran', population: 89 },
        { country: 'Turkey', population: 86 },
        { country: 'Germany', population: 84 },
        { country: 'Thailand', population: 72 },
        { country: 'United Kingdom', population: 68 },
        { country: 'Tanzania', population: 66 },
        { country: 'France', population: 65 },
        { country: 'South Africa', population: 60 },
        { country: 'Italy', population: 59 },
    ];
}
